name = "Madagascar"
uuid = "de1a7838-e64b-4715-8e96-f45059f9a2fe"
authors = ["mloubout <mathias.louboutin@gmail.com>"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Madagascar_jll = "aa2f55ac-b14e-51ec-b6ff-9716116fc184"

[compat]
Madagascar_jll = "1"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[targets]
test = ["Test", "TimerOutputs"]


