.TH sfaapwd1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfaapwd1 \- Amplitude-adjusted PWD - linear operator 
.SH SYNOPSIS
.B sfaapwd1 < inp.rsf dip=dip.rsf sig=sig.rsf amp=amp.rsf > out.rsf adj=n drift=n forx=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag
.TP
.I file   
.B amp
.B =
.R  	auxiliary input file name
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B drift
.B =n
.R  [y/n]	if shift filter
.TP
.I bool   
.B forx
.B =n
.R  [y/n]	for x only
.TP
.I file   
.B sig
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/pwd/Maapwd1.c
.SH VERSION
4.2-git
