.TH sfacqgeo 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfacqgeo \- generating acquisition geometry file for sfmpicfftrtm  
.SH SYNOPSIS
.B sfacqgeo > Fgeo.rsf nz= nx= ny= sou_z= sou_ox= sou_oy= sou_nx= sou_ny= sou_jx=(sou_nx>1)? (nx-sou_ox)/(sou_nx-1):0 sou_jy=(sou_ny>1)? (ny-sou_oy)/(sou_ny-1):0 rec_z= rec_nx= rec_ny= npad= noff= roll=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B noff
.B =
.R  	near offset
.TP
.I int    
.B npad
.B =
.R  	computational domain padding
.TP
.I int    
.B nx
.B =
.R  	dimension in x
.TP
.I int    
.B ny
.B =
.R  	dimension in y
.TP
.I int    
.B nz
.B =
.R  	dimension in z
.TP
.I int    
.B rec_nx
.B =
.R  	number of receivers in x
.TP
.I int    
.B rec_ny
.B =
.R  	number of receivers in y
.TP
.I int    
.B rec_z
.B =
.R  	receiver position in depth
.TP
.I int    
.B roll
.B =
.R  	acquisition pattern: 0-> fixed-spread, 1-> towed-streamer to the negative
.TP
.I int    
.B sou_jx
.B =(sou_nx>1)? (nx-sou_ox)/(sou_nx-1):0
.R  	source interval in x
.TP
.I int    
.B sou_jy
.B =(sou_ny>1)? (ny-sou_oy)/(sou_ny-1):0
.R  	source interval in y
.TP
.I int    
.B sou_nx
.B =
.R  	number of sources in x
.TP
.I int    
.B sou_ny
.B =
.R  	number of sources in y
.TP
.I int    
.B sou_ox
.B =
.R  	source starting location in x
.TP
.I int    
.B sou_oy
.B =
.R  	source starting location in y
.TP
.I int    
.B sou_z
.B =
.R  	source position in depth
.SH SOURCE
.I user/jsun/Macqgeo.c
.SH VERSION
4.2-git
