.TH sfacoustic1D 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfacoustic1D \- 1-D acoustic wave propagation with CE absorbing boundary
.SH SYNOPSIS
.B sfacoustic1D < Fsrc.rsf vel=Fvel.rsf > Frec.rsf rec_all=Frec_all.rsf verb=n sx= rx=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B rec_all
.B =
.R  	auxiliary output file name
.TP
.I int    
.B rx
.B =
.R  	reciever position
.TP
.I int    
.B sx
.B =
.R  	source position
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.SH USED IN
.TP
.I carrot/test/modeling
.SH SOURCE
.I user/carrot/Macoustic1D.c
.SH VERSION
4.2-git
