.TH sfaccumulate 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfaccumulate \- Accumulate 
.SH SYNOPSIS
.B sfaccumulate < Fin.rsf > Fou.rsf verb=n axis=3
.SH PARAMETERS
.PD 0
.TP
.I int    
.B axis
.B =3
.R  	accumulate axis
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/psava/Maccumulate.c
.SH VERSION
4.2-git
