.TH sfacoustic1D_FWI_adj 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfacoustic1D_FWI_adj \- 1-D acoustic FWI with adjoint state method
.SH SYNOPSIS
.B sfacoustic1D_FWI_adj < Frec.rsf vel=Fvel.rsf src=Fsrc.rsf gradient=Fgradient.rsf > Fvel_recover.rsf verb=n sx= rx= niter=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B gradient
.B =
.R  	auxiliary output file name
.TP
.I int    
.B niter
.B =
.R  	iteration number
.TP
.I int    
.B rx
.B =
.R  	reciever position
.TP
.I file   
.B src
.B =
.R  	auxiliary input file name
.TP
.I int    
.B sx
.B =
.R  	source position
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.SH SOURCE
.I user/carrot/Macoustic1D_FWI_adj.c
.SH VERSION
4.2-git
