.TH sfadiradon2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfadiradon2 \- direct adjoint 2to2 hyper Radon transform (single integral, nearest point interpolation)
.SH SYNOPSIS
.B sfadiradon2 < input.rsf > output.rsf nt= nx= t0= dt= x0= dx=
.SH PARAMETERS
.PD 0
.TP
.I        
.B dt
.B =
.R  
.TP
.I        
.B dx
.B =
.R  
.TP
.I        
.B nt
.B =
.R  
.TP
.I        
.B nx
.B =
.R  
.TP
.I        
.B t0
.B =
.R  
.TP
.I        
.B x0
.B =
.R  
.SH SOURCE
.I user/jingwei/Madiradon2.cc
.SH VERSION
4.2-git
