.TH sfaddtrace 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfaddtrace \- Add zero trace to original profile in order to improve lateral resolution 
.SH SYNOPSIS
.B sfaddtrace < in.rsf > out.rsf ratio=2
.SH PARAMETERS
.PD 0
.TP
.I int    
.B ratio
.B =2
.R  
.SH SOURCE
.I user/chenyk/Maddtrace.c
.SH VERSION
4.2-git
