.TH sfaddevent 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfaddevent \- Add a dispersive event to a seismic profile 
.SH SYNOPSIS
.B sfaddevent < in.rsf > out.rsf wvtype=0 w0=35.0 event=2 nfft= t0=0.3 v0=1500.0 a0=1.0 qv=-1.0 qa=qv f0=w0 a0ref=0
.SH PARAMETERS
.PD 0
.TP
.I float  
.B a0
.B =1.0
.R  	event amplitude at t=a0ref (x=0)
.TP
.I int    
.B a0ref
.B =0
.R  	reference point for a0: 0 - t0; 1 - a0
.TP
.I int    
.B event
.B =2
.R  	0: linear; 1: parabolic; 2:hyperbolic
.TP
.I float  
.B f0
.B =w0
.R  	reference frequency for velocity dispersion and amplitude attenuation
.TP
.I int    
.B nfft
.B =
.R  	fft length
.TP
.I float  
.B qa
.B =qv
.R  	Q factor for amplitude attenuation
.TP
.I float  
.B qv
.B =-1.0
.R  	Q factor for velocity dispersion
.TP
.I float  
.B t0
.B =0.3
.R  	event travel time at x=0
.TP
.I float  
.B v0
.B =1500.0
.R  	event velocity at x=0, for reference frequency f0
.TP
.I float  
.B w0
.B =35.0
.R  	central frequency of Ricker wavelet or bandwidth of sinc wavelet
.TP
.I int    
.B wvtype
.B =0
.R  	0: ricker; 1: sinc; x: not support
.SH USED IN
.TP
.I chen/test/fpca
.SH SOURCE
.I user/chen/Maddevent.c
.SH VERSION
4.2-git
