.TH sfadjgradient2d_coupled 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfadjgradient2d_coupled \- Gradient adjoint-state calculation for image-domain WET 
.SH SYNOPSIS
.B sfadjgradient2d_coupled < Fvel1.rsf xig1=Fxig1.rsf us1=Fus1.rsf ur1=Fur1.rsf > Fgr1.rsf vel2=Fvel2.rsf xig2=Fxig2.rsf us2=Fus2.rsf ur2=Fur2.rsf gr2=Fgr2.rsf nxtap=40 verbose=n
.SH PARAMETERS
.PD 0
.TP
.I file   
.B gr2
.B =
.R  	auxiliary output file name
.TP
.I int    
.B nxtap
.B =40
.R  	TAPER size
.TP
.I file   
.B ur1
.B =
.R  	auxiliary input file name
.TP
.I file   
.B ur2
.B =
.R  	auxiliary input file name
.TP
.I file   
.B us1
.B =
.R  	auxiliary input file name
.TP
.I file   
.B us2
.B =
.R  	auxiliary input file name
.TP
.I file   
.B vel2
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verbose
.B =n
.R  [y/n]	VERBOSITY flag
.TP
.I file   
.B xig1
.B =
.R  	auxiliary input file name
.TP
.I file   
.B xig2
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/jeff/Madjgradient2d_coupled.c
.SH VERSION
4.2-git
