.TH sfadd 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfadd \- Add, multiply, or divide  RSF datasets.
.SH SYNOPSIS
.B sfadd > out.rsf scale= add= sqrt= abs= log= exp= mode= [< file0.rsf] file1.rsf file2.rsf ...
.SH COMMENTS
The various operations, if selected, occur in the following order:

(1) Take absolute value, abs=
(2) Add a scalar, add=
(3) Take the natural logarithm, log=
(4) Take the square root, sqrt=
(5) Multiply by a scalar, scale=
(6) Compute the base-e exponential, exp=
(7) Add, multiply, or divide the data sets, mode=

sfadd operates on integer, float, or complex data, but all the input
and output files must be of the same data type.

An alternative to sfadd is sfmath, which is more versatile, but may be
less efficient.

.SH PARAMETERS
.PD 0
.TP
.I bools  
.B abs
.B =
.R  	If true take absolute value  [nin]
.TP
.I floats 
.B add
.B =
.R  	Scalar values to add to each dataset  [nin]
.TP
.I bools  
.B exp
.B =
.R  	If true compute exponential  [nin]
.TP
.I bools  
.B log
.B =
.R  	If true take logarithm  [nin]
.TP
.I string 
.B mode
.B =
.R  	'a' means add (default), 
	  'p' or 'm' means multiply, 
	  'd' means divide
.TP
.I floats 
.B scale
.B =
.R  	Scalar values to multiply each dataset with  [nin]
.TP
.I bools  
.B sqrt
.B =
.R  	If true take square root  [nin]
.SH USED IN
.TP
.I bei/sg/toldi
.TP
.I cup/rna2d/shot
.TP
.I cwp/geo2007StereographicImagingCondition/flat4
.TP
.I cwp/geo2007StereographicImagingCondition/gaus1
.TP
.I cwp/geo2007StereographicImagingCondition/sigsbee2
.TP
.I cwp/geo2008InterferometricImagingCondition/circle
.TP
.I cwp/geo2008InterferometricImagingCondition/sact1
.TP
.I cwp/geo2008InterferometricImagingCondition/sigs2
.TP
.I cwp/geo2008IsotropicAngleDomainElasticRTM/marm2allA
.TP
.I cwp/geo2008IsotropicAngleDomainElasticRTM/marm2oneA
.TP
.I cwp/geo2009TTIModeSeparation/fold
.TP
.I cwp/geo2009TTIModeSeparation/marmousi2
.TP
.I cwp/geo2009TTIModeSeparation/operator
.TP
.I cwp/geo2009VTIModeSeparation/aniopsize
.TP
.I cwp/geo2009VTIModeSeparation/oporder
.TP
.I cwp/geo2009VTIModeSeparation/separate2
.TP
.I cwp/geo2009VTIModeSeparation/separate3
.TP
.I cwp/geo2009VTIModeSeparation/separate5
.TP
.I cwp/geo2009VTIModeSeparation/sigsbee
.TP
.I cwp/geo2011WideAzimuthAngleDecomposition/flatEICangle
.TP
.I cwp/jse2006RWEImagingOverturningReflections/sigsbee
.TP
.I cwp/pept2011MicroearthquakeMonitoring/saf1
.TP
.I cwp/pept2011MicroearthquakeMonitoring/saf2
.TP
.I cwp/pept2011MicroearthquakeMonitoring/saf3
.TP
.I data/alaska/line31-81-m8r
.SH SOURCE
.I system/main/add.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfadd
.SH VERSION
4.2-git
