.TH sfadjgradient2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfadjgradient2d \- Gradient adjoint-state calculation for image-domain WET 
.SH SYNOPSIS
.B sfadjgradient2d < Fvel.rsf xig=Fxig.rsf swf=Fswf.rsf rwf=Frwf.rsf > Fgrd.rsf nxtap=40 verbose=n
.SH PARAMETERS
.PD 0
.TP
.I int    
.B nxtap
.B =40
.R  	TAPER size
.TP
.I file   
.B rwf
.B =
.R  	auxiliary input file name
.TP
.I file   
.B swf
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verbose
.B =n
.R  [y/n]	VERBOSITY flag
.TP
.I file   
.B xig
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/jeff/Madjgradient2d.c
.SH VERSION
4.2-git
