.TH sfafd2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfafd2d \- 2D coustic time-domain FD modeling with different boundary conditions
.SH SYNOPSIS
.B sfafd2d < Fw.rsf > Fo.rsf vel=Fv.rsf ref=Fr.rsf verb=0 free=n ifoneway=y ifsponge=y nb=5
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B free
.B =n
.R  [y/n]
.TP
.I bool   
.B ifoneway
.B =y
.R  [y/n]
.TP
.I bool   
.B ifsponge
.B =y
.R  [y/n]
.TP
.I int    
.B nb
.B =5
.R  	setup I/O files
.TP
.I file   
.B ref
.B =
.R  	auxiliary input file name
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =0
.R  [y/n]
.SH SOURCE
.I user/chenyk/Mafd2d.c
.SH VERSION
4.2-git
