.TH sfagc 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfagc \- Automatic gain control. 
.SH SYNOPSIS
.B sfagc < in.rsf > out.rsf repeat=1 rect#=(125,1,1,...)
.SH COMMENTS

October 2011 program of the month:
http://ahay.org/blog/2011/10/01/program-of-the-month-sfagc/

.SH PARAMETERS
.PD 0
.TP
.I int    
.B rect#
.B =(125,1,1,...)
.R  	smoothing radius on #-th axis
.TP
.I int    
.B repeat
.B =1
.R  	repeat filtering several times
.SH USED IN
.TP
.I bei/dpmv/krchdmo
.TP
.I bei/krch/wgkirch
.TP
.I bei/vela/vscan
.SH SOURCE
.I system/generic/Magc.c
.SH VERSION
4.2-git
