.TH sfahelicon 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfahelicon \- Apply multidimensional nonstationary filter on a helix. 
.SH SYNOPSIS
.B sfahelicon < in.rsf filt=filt.rsf > out.rsf n= dim=ndim lag=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B dim
.B =ndim
.R  	number of dimensions
.TP
.I file   
.B filt
.B =
.R  	auxiliary output file name
.TP
.I string 
.B lag
.B =
.R  	file with filter lags
.TP
.I ints   
.B n
.B =
.R  	 [dim]
.SH SOURCE
.I user/gee/Mahelicon.c
.SH VERSION
4.2-git
