.TH sfaimplfd1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfaimplfd1 \- Implicit solution of 1-D acoustic wave equation. 
.SH SYNOPSIS
.B sfaimplfd1 < vel.rsf > usol.rsf src=src.rsf niter=10
.SH PARAMETERS
.PD 0
.TP
.I int    
.B niter
.B =10
.R  	Number of solver iterations
.TP
.I string 
.B src
.B =
.R  	Source wavelet (auxiliary input file name)
.SH SOURCE
.I user/petsc/Maimplfd1.c
.SH VERSION
4.2-git
