.TH sfai2refl 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfai2refl \- Convert acoustic impedance to reflectivity. 
.SH SYNOPSIS
.B sfai2refl < ai.rsf > mod.rsf
.SH COMMENTS

August 2013 program of the month:
http://www.ahay.org/blog/2013/08/02/program-of-the-month-sfai2refl/

.SH USED IN
.TP
.I cwp/geo2006TimeShiftImagingCondition/flat
.SH SOURCE
.I system/seismic/Mai2refl.c
.SH VERSION
4.2-git
