.TH sfanisodiffuse 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfanisodiffuse \- Anisotropic diffusion by regularized inversion. 
.SH SYNOPSIS
.B sfanisodiffuse < in.rsf > out.rsf vx=fvx.rsf vy=fvy.rsf niter=10 repeat=1 eps=1.
.SH COMMENTS

Applied in 3D in a slice by slice fashion: set of
2D diffusions for a fixed time sample. 
.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =1.
.R  	regularization parameter
.TP
.I int    
.B niter
.B =10
.R  	number of conjugate-gradient iterations
.TP
.I int    
.B repeat
.B =1
.R  	number of smoothing iterations
.TP
.I file   
.B vx
.B =
.R  	auxiliary input file name
.TP
.I file   
.B vy
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/dmerzlikin/Manisodiffuse.c
.SH VERSION
4.2-git
