.TH sfangmig2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfangmig2 \- Angle-gather constant-velocity time migration. 
.SH SYNOPSIS
.B sfangmig2 < in.rsf > out.rsf semb=semb.rsf mask=mask.rsf vin=vin.rsf adj=n weighting=y na= amax= ng=na gmax=amax nxi=nx xi0=x0 dxi=dx ntau=nt tau0=t0 dtau=dt nh= h0= dh= ng=na gmax=amax nx=nxi x0=xi0 dx=dxi nt=ntau t0=tau0 dt=dtau eps=0.00001 l2=y
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	if y modeling, if n, migration
.TP
.I float  
.B amax
.B =
.R  	maximum dip angle
.TP
.I float  
.B dh
.B =
.R  	offset increment
.TP
.I float  
.B dt
.B =dtau
.R  	time increment
.TP
.I float  
.B dtau
.B =dt
.R  	output vertical sampling
.TP
.I float  
.B dx
.B =dxi
.R  	data domain spatial increment
.TP
.I float  
.B dxi
.B =dx
.R  	output sampling
.TP
.I float  
.B eps
.B =0.00001
.R  	epsilon for division in semblance calc
.TP
.I float  
.B gmax
.B =amax
.R  	maximum reflection angle
.TP
.I float  
.B h0
.B =
.R  	initial offset
.TP
.I bool   
.B l2
.B =y
.R  [y/n]	if y use l2 norm for semb, if n, use l1 norm
.TP
.I string 
.B mask
.B =
.R  	input file contining image mask locations, 0 = skip (auxiliary input file name)
.TP
.I int    
.B na
.B =
.R  	number of dip angles
.TP
.I int    
.B ng
.B =na
.R  	number of reflection angles
.TP
.I int    
.B nh
.B =
.R  	number of offsets
.TP
.I int    
.B nt
.B =ntau
.R  	number time samples
.TP
.I int    
.B ntau
.B =nt
.R  	output vertical samples
.TP
.I int    
.B nx
.B =nxi
.R  	data domain spatial samples
.TP
.I int    
.B nxi
.B =nx
.R  	output samples
.TP
.I string 
.B semb
.B =
.R  	output file containing Semblance (auxiliary output file name)
.TP
.I float  
.B t0
.B =tau0
.R  	time orgin
.TP
.I float  
.B tau0
.B =t0
.R  	output vertical orgin
.TP
.I string 
.B vin
.B =
.R  	input velocity file (auxiliary input file name)
.TP
.I bool   
.B weighting
.B =y
.R  [y/n]	kirchhoff weighting?
.TP
.I float  
.B x0
.B =xi0
.R  	data domain spatial orgin
.TP
.I float  
.B xi0
.B =x0
.R  	output orgin
.SH SOURCE
.I user/luke/Mangmig2.c
.SH VERSION
4.2-git
