.TH sfangle 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfangle \- Illustration of angle gathers.
.SH SYNOPSIS
.B sfangle > angle.rsf nw=513 nm=257 nh=257 dw=1./(2*(nw-1)*0.004) dm=1./(2*(nm-1)*0.01) dh=1./(2*(nh-1)*0.01) w0=dw vel=2.
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dh
.B =1./(2*(nh-1)*0.01)
.R  
.TP
.I float  
.B dm
.B =1./(2*(nm-1)*0.01)
.R  
.TP
.I float  
.B dw
.B =1./(2*(nw-1)*0.004)
.R  
.TP
.I int    
.B nh
.B =257
.R  
.TP
.I int    
.B nm
.B =257
.R  
.TP
.I int    
.B nw
.B =513
.R  
.TP
.I float  
.B vel
.B =2.
.R  
.TP
.I float  
.B w0
.B =dw
.R  
.SH SOURCE
.I user/fomels/Mangle.c
.SH VERSION
4.2-git
