.TH sfarrival 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfarrival \- Multiple-arrival interpolation from down-marching. 
.SH SYNOPSIS
.B sfarrival < in.rsf place=place.rsf > out.rsf depth=depth.rsf sx=0. nw=3
.SH PARAMETERS
.PD 0
.TP
.I string 
.B depth
.B =
.R  	auxiliary input file name
.TP
.I int    
.B nw
.B =3
.R  	interpolation accuracy
.TP
.I file   
.B place
.B =
.R  	auxiliary input file name
.TP
.I float  
.B sx
.B =0.
.R  	source x position
.SH SOURCE
.I user/fomels/Marrival.c
.SH VERSION
4.2-git
