.TH sfatm1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfatm1 \- 1D alpha-trimmed-mean filtering. 
.SH SYNOPSIS
.B sfatm1 < in.rsf > out.rsf nfw= alpha= boundary=n
.SH COMMENTS
median filter (alpha=0.5); mean filter (alpha=0.)

.SH PARAMETERS
.PD 0
.TP
.I float  
.B alpha
.B =
.R  	0.0 <= alpha <= 0.5: median filter (alpha=0.5); mean filter (alpha=0.)
.TP
.I bool   
.B boundary
.B =n
.R  [y/n]	if y, boundary is data, whereas zero
.TP
.I int    
.B nfw
.B =
.R  	filter-window length (positive and odd integer)
.SH SOURCE
.I user/yliu/Matm1.c
.SH VERSION
4.2-git
