.TH sfatm2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfatm2 \- 2D alpha-trimmed-mean filtering. 
.SH SYNOPSIS
.B sfatm2 < in.rsf > out.rsf nfw1= nfw2=nfw1 alpha= boundary=n verb=n type=
.SH COMMENTS
1D filter (nfw2=1); 2D filter (otherwise)
median filter (alpha=0.5); mean filter (alpha=0.)

.SH PARAMETERS
.PD 0
.TP
.I float  
.B alpha
.B =
.R  	0.0 <= alpha <= 0.5: median filter (alpha=0.5); mean filter (alpha=0.)
.TP
.I bool   
.B boundary
.B =n
.R  [y/n]	if y, boundary is data, whereas zero
.TP
.I int    
.B nfw1
.B =
.R  	filter-window length in n1 direction (positive and odd integer)
.TP
.I int    
.B nfw2
.B =nfw1
.R  	filter-window length in n2 direction (default=nfw1)
.TP
.I string 
.B type
.B =
.R  	[rectangular,cross] 2-D window type, the default is rectangular
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/yliu/Matm2.c
.SH VERSION
4.2-git
