.TH sfautocorr 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfautocorr \- Autocorrelation for helix filters. 
.SH SYNOPSIS
.B sfautocorr < in.rsf > out.rsf lag=lag0.rsf lagout=lag.rsf
.SH PARAMETERS
.PD 0
.TP
.I string 
.B lag
.B =
.R  	optional input file with filter lags (auxiliary input file name)
.TP
.I string 
.B lagout
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/gee/Mautocorr.c
.SH VERSION
4.2-git
