.TH sfavvvdwe2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfavvvdwe2d \- 2D acoustic variable-velocity variable-density time-domain FD modeling
.SH SYNOPSIS
.B sfavvvdwe2d < Fwav.rsf vel=Fvel.rsf den=Fden.rsf sou=Fsou.rsf rec=Frec.rsf > Fdat.rsf wfl=Fwfl.rsf verb=n free=n dabc=n adj=n snap=y nb=NOP jsnap=1 dpt=n
.SH COMMENTS

The code uses a standard second-order stencil in time.
The coefficients of the spatial stencil are computed 
by matching the transfer function of the 6-point discretized
first-derivative operator to the ideal response.

The code implements the linearized operator obtained from the
system of first-order PDEs parametrized in incompressibility and density

dv/dt = - 1./rho * grad(p)
dp/dt = - K * div(v)

where
rho  : density
K    : incompressibility
div  : divergence operator
grad : gradient  operator
p,v    : pressure and particle velocity wavefields

The models supplied by the user are wave speed and density, the code performs
the conversion internally to buoyancy (inverse density) and incompressibility.

Author: Francesco Perrone
Date: February 2020

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	Adjointness
.TP
.I bool   
.B dabc
.B =n
.R  [y/n]	Absorbing BC
.TP
.I file   
.B den
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B dpt
.B =n
.R  [y/n]	run dot product test
.TP
.I bool   
.B free
.B =n
.R  [y/n]	Free surface
.TP
.I int    
.B jsnap
.B =1
.R  	undersampling factor for the wavefields
.TP
.I int    
.B nb
.B =NOP
.R  	thickness of the absorbing boundary: NOP is the width of the FD stencil
.TP
.I file   
.B rec
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B snap
.B =y
.R  [y/n]	wavefield snapshots
.TP
.I file   
.B sou
.B =
.R  	auxiliary input file name
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	Verbosity
.TP
.I file   
.B wfl
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/fperrone/Mavvvdwe2d.c
.SH VERSION
4.2-git
