.TH sfawefd2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfawefd2d \- 2D acoustic time-domain FD modeling 
.SH SYNOPSIS
.B sfawefd2d < file_wav.rsf vel=file_vel.rsf sou=file_src.rsf rec=file_rec.rsf > file_dat.rsf wfl=file_wfl.rsf den=file_den.rsf verb=n snap=n expl=n dabc=n cden=n adj=n fsrf=n optfd=n fdorder=4 hybridbc=n sinc=n jsnap=nt jdata=1 nqz=sf_n(az) nqx=sf_n(ax) oqz=sf_o(az) oqx=sf_o(ax) dqz=sf_d(az) dqx=sf_d(ax)
.SH COMMENTS
2Nth order in space, 2nd order in time
with optimized FD scheme option and hybrid one-way ABC option 
adj flag indicates backwards source injection, not exact adjoint propagator

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag
.TP
.I bool   
.B cden
.B =n
.R  [y/n]	Constant density
.TP
.I bool   
.B dabc
.B =n
.R  [y/n]	Absorbing BC
.TP
.I string 
.B den
.B =
.R  	auxiliary input file name
.TP
.I float  
.B dqx
.B =sf_d(ax)
.R  	Saved wfld window dx
.TP
.I float  
.B dqz
.B =sf_d(az)
.R  	Saved wfld window dz
.TP
.I bool   
.B expl
.B =n
.R  [y/n]	Multiple sources, one wvlt
.TP
.I int    
.B fdorder
.B =4
.R  	spatial FD order
.TP
.I bool   
.B fsrf
.B =n
.R  [y/n]	Free surface flag
.TP
.I bool   
.B hybridbc
.B =n
.R  [y/n]	hybrid Absorbing BC
.TP
.I int    
.B jdata
.B =1
.R  	# of t steps at which to save receiver data
.TP
.I int    
.B jsnap
.B =nt
.R  	# of t steps at which to save wavefield
.TP
.I int    
.B nqx
.B =sf_n(ax)
.R  	Saved wfld window nx
.TP
.I int    
.B nqz
.B =sf_n(az)
.R  	Saved wfld window nz
.TP
.I bool   
.B optfd
.B =n
.R  [y/n]	optimized FD coefficients flag
.TP
.I float  
.B oqx
.B =sf_o(ax)
.R  	Saved wfld window ox
.TP
.I float  
.B oqz
.B =sf_o(az)
.R  	Saved wfld window oz
.TP
.I file   
.B rec
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B sinc
.B =n
.R  [y/n]	sinc source injection
.TP
.I bool   
.B snap
.B =n
.R  [y/n]	Wavefield snapshots flag
.TP
.I file   
.B sou
.B =
.R  	auxiliary input file name
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	Verbosity flag
.TP
.I file   
.B wfl
.B =
.R  	auxiliary output file name
.SH USED IN
.TP
.I cwp/geo2008IsotropicAngleDomainElasticRTM/marm2oneA
.TP
.I cwp/geo2011WideAzimuthAngleDecomposition/flatEICangle
.TP
.I cwp/jse2006RWEImagingOverturningReflections/sigsbee
.TP
.I cwp/pept2011MicroearthquakeMonitoring/saf1
.TP
.I cwp/pept2011MicroearthquakeMonitoring/saf2
.TP
.I cwp/pept2011MicroearthquakeMonitoring/saf3
.TP
.I data/amoco/fdmod
.SH SOURCE
.I user/cwp/Mawefd2d.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfawefd2d
.SH VERSION
4.2-git
