.TH sfawefd3dgpu 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfawefd3dgpu \- 3D acoustic wave equation finite difference time domain modeling 
.SH SYNOPSIS
.B sfawefd3dgpu < file_wav.rsf > file_dat.rsf vel=file_vel.rsf sou=file_src.rsf rec=file_rec.rsf den=file_den.rsf wfl=file_wfl.rsf verb=n nbd=20 snap=n cden=y jsnap=1
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B cden
.B =y
.R  [y/n]
.TP
.I file   
.B den
.B =
.R  	auxiliary input file name
.TP
.I int    
.B jsnap
.B =1
.R  
.TP
.I int    
.B nbd
.B =20
.R  
.TP
.I file   
.B rec
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B snap
.B =n
.R  [y/n]
.TP
.I file   
.B sou
.B =
.R  	auxiliary input file name
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]
.TP
.I file   
.B wfl
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/hwang/Mawefd3dgpu.cu
.SH VERSION
4.2-git
