.TH sfaxplusy 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfaxplusy \- Computes a*x + y, where x and y are datasets, and a is scalar
.SH SYNOPSIS
.B sfaxplusy < in.rsf y=yfile.rsf > out.rsf afile=fa.rsf a=1 verb=n
.SH COMMENTS
x and y are floats or sf_complex, single precision
x is the stdin
a is double precision
Computations are done in double precision. 
.SH PARAMETERS
.PD 0
.TP
.I double 
.B a
.B =1
.R  	Scaling factor
.TP
.I file   
.B afile
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	Verbosity flag
.TP
.I file   
.B y
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/jeff/Maxplusy.c
.SH VERSION
4.2-git
