.TH sfAzsort 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfAzsort \- None
.SH SYNOPSIS
.B sfAzsort < three.rsf > two.rsf out2=two2.rsf common=commonoffset.rsf sectio=sectionf.rsf filt=filtered.rsf dimen= win= radius=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B common
.B =
.R  	auxiliary output file name
.TP
.I        
.B dimen
.B =
.R  	command-line parameter
.TP
.I file   
.B filt
.B =
.R  	auxiliary output file name
.TP
.I file   
.B out2
.B =
.R  	auxiliary output file name
.TP
.I        
.B radius
.B =
.R  	command-line parameter
.TP
.I file   
.B sectio
.B =
.R  	auxiliary output file name
.TP
.I        
.B win
.B =
.R  	command-line parameter
.SH SOURCE
.I user/mehdi/MAzsort.f90
.SH VERSION
4.2-git
