.TH sfbackdireazi 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfbackdireazi \- Background directivity(Azimuth). 
.SH SYNOPSIS
.B sfbackdireazi < Zz.rsf > Zo.rsf verb=0
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B verb
.B =0
.R  [y/n]
.SH SOURCE
.I user/parvaneh/Mbackdireazi.c
.SH VERSION
4.2-git
