.TH sfbackus 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfbackus \- None
.SH SYNOPSIS
.B sfbackus < infile.rsf > outfile.rsf navg=201 all=n ang=30.
.SH PARAMETERS
.PD 0
.TP
.I        
.B all
.B =n
.R  	Print extra information
.TP
.I        
.B ang
.B =30.
.R  	Input angle
.TP
.I        
.B navg
.B =201
.R  	Number of samples to average over
.SH SOURCE
.I user/jeff/Mbackus.f90
.SH VERSION
4.2-git
