.TH sfbeamsteer 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfbeamsteer \- Beam steering for 2D surface array. 
.SH SYNOPSIS
.B sfbeamsteer < in.rsf > out.rsf mode=y xref= yref= npx= dpx= opx= npy= dpy= opy=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dpx
.B =
.R  	px sampling (if mode=y).
.TP
.I float  
.B dpy
.B =
.R  	py sampling (if mode=y).
.TP
.I bool   
.B mode
.B =y
.R  [y/n]	if n, beams computed as a function of apparent slowness and azimuth angle.
.TP
.I int    
.B npx
.B =
.R  	number of px values (if mode=y).
.TP
.I int    
.B npy
.B =
.R  	number of py values (if mode=y).
.TP
.I float  
.B opx
.B =
.R  	px origin (if mode=y)
.TP
.I float  
.B opy
.B =
.R  	py origin (if mode=y)
.TP
.I float  
.B xref
.B =
.R  	x coordinate where beams are computed
.TP
.I float  
.B yref
.B =
.R  	y coordinate where beams are computed
.SH SOURCE
.I user/browaeys/Mbeamsteer.c
.SH VERSION
4.2-git
