.TH sfbeamspray 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfbeamspray \- 2-D beam spraying. 
.SH SYNOPSIS
.B sfbeamspray < in.rsf dip=dip.rsf cur=cur.rsf > out.rsf rect=3 eps=1.0
.SH PARAMETERS
.PD 0
.TP
.I file   
.B cur
.B =
.R  	auxiliary input file name
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I float  
.B eps
.B =1.0
.R  	experimental
.TP
.I int    
.B rect
.B =3
.R  	smoothing radius
.SH SOURCE
.I system/seismic/Mbeamspray.c
.SH VERSION
4.2-git
