.TH sfbin2rsf 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfbin2rsf \- Binary file to RSF file 
.SH SYNOPSIS
.B sfbin2rsf > out.rsf n1= n2= d1=0.004 d2=1 o1=0 o2=0 bfile=
.SH COMMENTS
Convert a file containing a two dimensional array of binary floats to 
.rsf format.  n1*n2*sizeof(float) bytes are read from the input file
and the rsf file is written to standard output.  If you have a higher
dimension file (3d, 4d, ..) you can change n2, n3, etc using sfput.  

Example that converts and plots a binary velocity grid:

<Vp sfbin2rsf n1=400 d1=1 n2=1600 d2=1 o2=101 \
| sfgrey color=jet scalebar=y allpos=y | sfpen


.SH PARAMETERS
.PD 0
.TP
.I string 
.B bfile
.B =
.R  
.TP
.I float  
.B d1
.B =0.004
.R  
.TP
.I float  
.B d2
.B =1
.R  
.TP
.I int    
.B n1
.B =
.R  
.TP
.I int    
.B n2
.B =
.R  
.TP
.I float  
.B o1
.B =0
.R  
.TP
.I float  
.B o2
.B =0
.R  
.SH SOURCE
.I user/chenyk/Mbin2rsf.c
.SH VERSION
4.2-git
