.TH sfbigmpiencode 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfbigmpiencode \- shot encoding with arbitrary phase and amplitude weights using MPI on a distributed cluster 
.SH SYNOPSIS
.B sfbigmpiencode encode=Fencode.rsf nx= ny= dy= dx= ox= oy= verb=n dprefix= eprefix= shots=
.SH COMMENTS


Use mpiencode if your shots are on the same grid prior to encoding.

Use bigmpiencode if your shots are not on a single grid prior to encoding.
YOUR SHOTS MUST ALL FALL ONTO THE SAME REGULAR GRID.  BigMPIENCODE does not do any
shot interpolation.

Data axes - X, Y, W


.SH PARAMETERS
.PD 0
.TP
.I string 
.B dprefix
.B =
.R  	printf like statement that can be evaluated to find the data files corresponding to shot records
.TP
.I float  
.B dx
.B =
.R  	dx of output grid points
.TP
.I float  
.B dy
.B =
.R  	dy of output grid points
.TP
.I file   
.B encode
.B =
.R  	auxiliary input file name
.TP
.I string 
.B eprefix
.B =
.R  	printf like statement that can be evaluated for the output encodings
.TP
.I int    
.B nx
.B =
.R  	# of output grid x points
.TP
.I int    
.B ny
.B =
.R  	# of output grid y points
.TP
.I float  
.B ox
.B =
.R  	ox of output grid points
.TP
.I float  
.B oy
.B =
.R  	ox of output grid points
.TP
.I string 
.B shots
.B =
.R  	shot-file name, dimensions are 1xNS
.TP
.I bool   
.B verb
.B =n
.R  [y/n]
.SH SOURCE
.I user/cwp/Mbigmpiencode.c
.SH VERSION
4.2-git
