.TH sfbil1_new 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfbil1_new \- L1 regression 0 ~= d - G * m
.SH SYNOPSIS
.B sfbil1_new < inp.rsf reg=reg.rsf > out.rsf verb=n niter=10 Liter=10 perc=90.0
.SH COMMENTS
*
* adapted from sfbil1
* 
.SH PARAMETERS
.PD 0
.TP
.I int    
.B Liter
.B =10
.R  	number of CG iterations
.TP
.I int    
.B niter
.B =10
.R  	number of POCS iterations
.TP
.I float  
.B perc
.B =90.0
.R  	percentage for sharpening
.TP
.I file   
.B reg
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]
.SH SOURCE
.I user/lcasasan/Mbil1_new.c
.SH VERSION
4.2-git
