.TH sfbilstack 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfbilstack \- Bilateral stacking. 
.SH SYNOPSIS
.B sfbilstack < in.rsf > out.rsf weight=weight.rsf verb=n niter=20 bilat=n ax= bx=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B ax
.B =
.R  	Gaussian weight for the range distance
.TP
.I bool   
.B bilat
.B =n
.R  [y/n]	if y, bilateral smoothing
.TP
.I float  
.B bx
.B =
.R  	Exponential weight for the domain distance
.TP
.I int    
.B niter
.B =20
.R  	number of iterations
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.TP
.I file   
.B weight
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/yliu/Mbilstack.c
.SH VERSION
4.2-git
