.TH sfboxcascade 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfboxcascade \- Box filter cascade 
.SH SYNOPSIS
.B sfboxcascade < inp.rsf > out.rsf rect=0 inter=n
.SH PARAMETERS
.PD 0
.TP
.I int    
.B inter
.B =n
.R  	interrupt
.TP
.I int    
.B rect
.B =0
.R  	smoothing radius
.SH SOURCE
.I user/fomels/Mboxcascade.c
.SH VERSION
4.2-git
