.TH sfboolcmp 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfboolcmp \- Element-wise boolean comparison of values. For int/float/complex data-sets.
.SH SYNOPSIS
.B sfboolcmp < in.rsf > out.rsf right_f= eps=0 right= sign=
.SH COMMENTS
This program will solve the solution to this problem:
- [input] [sign] [right]
- sfboolcmp <left.rsf sign=ge right=right.rsf 
- left.rsf >= right.rsf
This will return a vector of same length as left and return 0's or 1's depending on the result of the inequality.  Optionally you can supply a right_f parameter to compare the input data to a single value.

Written by: C. Brown, UBC
Created: Nov 2007

.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =0
.R  	comparing within this range epsilon
.TP
.I string 
.B right
.B =
.R  	the rsf file you will be comparing to
.TP
.I float  
.B right_f
.B =
.R  	compare input (left) to a single float value (right)
.TP
.I string 
.B sign
.B =
.R  	'eq'(default),'gt','ge','lq','lt','ne'
        sign=   'eq' equal-to ( == )
        sign=   'gt' greater-than ( > )
        sign=   'ge' greater-than or equal-to ( >= )
        sign=   'lq' less-than or equal-to ( <= )
        sign=   'lt' less-than ( < )
        sign=   'ne' not-equal ( != )
	sign=   'and' the values are both non-zero ( && )
	sign=   'or' one value is non-zero ( !! )
.SH SOURCE
.I user/slim/Mboolcmp.c
.SH VERSION
4.2-git
