.TH sfboxfilter 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfboxfilter \- 3D convolution with arbitrary filter 
.SH SYNOPSIS
.B sfboxfilter < Fx.rsf > Fy.rsf flt=Ff.rsf verb=n stat=y
.SH PARAMETERS
.PD 0
.TP
.I file   
.B flt
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B stat
.B =y
.R  [y/n]	stationary flag
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/psava/Mboxfilter.c
.SH VERSION
4.2-git
