.TH sfbspvel3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfbspvel3 \- B-spline coefficients for a 3-D (an)isotropic velocity model. 
.SH SYNOPSIS
.B sfbspvel3 < velz.rsf > out.rsf vx=velx.rsf eta=eta.rsf theta=theta.rsf phi=phi.rsf verb=n
.SH PARAMETERS
.PD 0
.TP
.I string 
.B eta
.B =
.R  	Anellipticity (auxiliary input file name)
.TP
.I string 
.B phi
.B =
.R  	Tilt angle azimuth (auxiliary input file name)
.TP
.I string 
.B theta
.B =
.R  	Tilt angle elevation (auxiliary input file name)
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I string 
.B vx
.B =
.R  	Horizontal velocity (auxiliary input file name)
.SH SOURCE
.I user/cram/Mbspvel3.c
.SH VERSION
4.2-git
