.TH sfburg 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfburg \- Burg's method for 1-D PEF estimation 
.SH SYNOPSIS
.B sfburg < inp.rsf > out.rsf filter=filt.rsf na=10
.SH PARAMETERS
.PD 0
.TP
.I file   
.B filter
.B =
.R  	auxiliary output file name
.TP
.I int    
.B na
.B =10
.R  	filter size
.SH SOURCE
.I system/generic/Mburg.c
.SH VERSION
4.2-git
