.TH sfburstnoise 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfburstnoise \- Synthetics with bursts of noise. 
.SH SYNOPSIS
.B sfburstnoise < in.rsf > out.rsf sigma=1. thresh=0.93 thresh2=0.4
.SH PARAMETERS
.PD 0
.TP
.I float  
.B sigma
.B =1.
.R  	noise magnitude
.TP
.I float  
.B thresh
.B =0.93
.R  	noise threshold
.TP
.I float  
.B thresh2
.B =0.4
.R  	noise threshold
.SH SOURCE
.I user/gee/Mburstnoise.c
.SH VERSION
4.2-git
