.TH sfbyte2tif 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfbyte2tif \- Convert byte RSF to a TIFF image. 
.SH SYNOPSIS
.B sfbyte2tif < in.rsf color=(bool)(3==n1)
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B color
.B =(bool)(3==n1)
.R  [y/n]
.SH SOURCE
.I user/fomels/_byte2tif.c
.SH VERSION
4.2-git
