.TH sfbyte2jpg 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfbyte2jpg \- Convert byte RSF to a JPEG image. 
.SH SYNOPSIS
.B sfbyte2jpg < in.rsf color=(bool)(3==n1)
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B color
.B =(bool)(3==n1)
.R  [y/n]
.SH SOURCE
.I user/fomels/_byte2jpg.c
.SH VERSION
4.2-git
