.TH sfc1coh 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfc1coh \- C1 coherency algorithm. 
.SH SYNOPSIS
.B sfc1coh < in.rsf > out.rsf ntw=3 verb=y lag1=3 lag2=3
.SH PARAMETERS
.PD 0
.TP
.I int    
.B lag1
.B =3
.R  	Inline time lag (default=3)
.TP
.I int    
.B lag2
.B =3
.R  	Crossline time lag (default=3)
.TP
.I int    
.B ntw
.B =3
.R  	Temporal length of the correlation window (default=3)
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/yliu/Mc1coh.c
.SH VERSION
4.2-git
