.TH sfcamig3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcamig3 \- 3-D common-azimuth modeling/migration with extended SSF 
.SH SYNOPSIS
.B sfcamig3 slo=Fs.rsf < Fd.rsf > Fw.rsf < Fi.rsf ompchunk=1 ompnth=0 verb=n eps=0.01 inv=n twoway=n nrmax=1 dtmax=0.004 pmx=0 pmy=0 phx=0 tmx=0 tmy=0 thx=0 nw= dw= ow=0. mode=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dtmax
.B =0.004
.R  	time error
.TP
.I float  
.B dw
.B =
.R  
.TP
.I float  
.B eps
.B =0.01
.R  	stability parameter
.TP
.I bool   
.B inv
.B =n
.R  [y/n]	y=modeling; n=migration
.TP
.I string 
.B mode
.B =
.R  
.TP
.I int    
.B nrmax
.B =1
.R  	maximum number of refs
.TP
.I int    
.B nw
.B =
.R  
.TP
.I int    
.B ompchunk
.B =1
.R  	OpenMP data chunk size
.TP
.I int    
.B ompnth
.B =0
.R  	OpenMP available threads
.TP
.I float  
.B ow
.B =0.
.R  
.TP
.I int    
.B phx
.B =0
.R  	padding hx
.TP
.I int    
.B pmx
.B =0
.R  	padding mx
.TP
.I int    
.B pmy
.B =0
.R  	padding my
.TP
.I file   
.B slo
.B =
.R  	auxiliary input file name
.TP
.I int    
.B thx
.B =0
.R  	taper hx
.TP
.I int    
.B tmx
.B =0
.R  	taper mx
.TP
.I int    
.B tmy
.B =0
.R  	taper my
.TP
.I bool   
.B twoway
.B =n
.R  [y/n]	two-way traveltime
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/psava/Mcamig3.c
.SH VERSION
4.2-git
