.TH sfcanisolr2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcanisolr2 \- Lowrank decomposition for 2-D anisotropic wave propagation (Complex). 
.SH SYNOPSIS
.B sfcanisolr2 < velz.rsf vels=vels.rsf fft=fft.rsf left=left.rsf > right.rsf mode=0 seed=time(NULL eps=1.e-4 npk=20 dt= os=true sub=false sub=true taper=1.0 approx=2 relation=3
.SH PARAMETERS
.PD 0
.TP
.I        
.B approx
.B =2
.R  	Type of approximation (0=exact 1=zone 2=acoustic)
.TP
.I        
.B dt
.B =
.R  	time step
.TP
.I        
.B eps
.B =1.e-4
.R  	tolerance
.TP
.I file   
.B fft
.B =
.R  	auxiliary input file name
.TP
.I file   
.B left
.B =
.R  	auxiliary output file name
.TP
.I        
.B mode
.B =0
.R  	wave mode (0=p wave, 1=Sv wave)
.TP
.I        
.B npk
.B =20
.R  	maximum rank
.TP
.I        
.B os
.B =true
.R  
.TP
.I        
.B relation
.B =3
.R  	Type of q relationship (0=shale, 1=sand, 2=carbonate, default being smallest error)
.TP
.I        
.B seed
.B =time(NULL
.R  
.TP
.I        
.B sub
.B =true
.R  	for twostep, default true
.TP
.I        
.B taper
.B =1.0
.R  	wavenumber tapering flag
.TP
.I file   
.B vels
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/jsun/Mcanisolr2.cc
.SH VERSION
4.2-git
