.TH sfccrsym 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfccrsym \- determine symmetry using correlation 
.SH SYNOPSIS
.B sfccrsym < in.rsf > out.rsf size=0 pad=SF_EPS
.SH PARAMETERS
.PD 0
.TP
.I float  
.B pad
.B =SF_EPS
.R  	pad for stable devision
.TP
.I int    
.B size
.B =0
.R  	sliding window radius
.SH SOURCE
.I user/jsun/Mccrsym.c
.SH VERSION
4.2-git
