.TH sfcconst 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcconst \- Gaussian beam and exact complex eikonal for constant velocity medium 
.SH SYNOPSIS
.B sfcconst < in.rsf > out.rsf source=o2 s=0. v0=1. angle=45. what=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B angle
.B =45.
.R  	rotation angle (counter-clock wise with respect to vertically downward)
.TP
.I float  
.B s
.B =0.
.R  	complex source shift
.TP
.I float  
.B source
.B =o2
.R  	real source point (on surface)
.TP
.I float  
.B v0
.B =1.
.R  	constant velocity background
.TP
.I string 
.B what
.B =
.R  	what to compute (default exact solution)
.SH SOURCE
.I user/llisiw/Mcconst.c
.SH VERSION
4.2-git
