.TH sfcconv 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcconv \- 1-D convolution with complex numbers. 
.SH SYNOPSIS
.B sfcconv < in.rsf > out.rsf filt=filt.rsf single=y lag=1
.SH PARAMETERS
.PD 0
.TP
.I file   
.B filt
.B =
.R  	auxiliary input file name
.TP
.I int    
.B lag
.B =1
.R  	lag for internal convolution
.TP
.I bool   
.B single
.B =y
.R  [y/n]	single channel or multichannel
.SH SOURCE
.I user/gee/Mcconv.c
.SH VERSION
4.2-git Mconv.c 7107 2011-04-10 02:04:14Z ivlad
