.TH sfccausint 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfccausint \- Complex Causal integration on the first axis. 
.SH SYNOPSIS
.B sfccausint < in.rsf > out.rsf adj=n
.SH COMMENTS

December 2013 program of the month:
http://ahay.org/blog/2013/12/01/program-of-the-month-sfcausint/

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	if y, do adjoint integration
.SH SOURCE
.I user/fomels/Mccausint.c
.SH VERSION
4.2-git
