.TH sfcdottestmpi 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcdottestmpi \- Generic dot-product test for complex linear operators with adjoints 
.SH SYNOPSIS
.B sfcdottestmpi mod=mod.rsf dat=dat.rsf
.SH COMMENTS

In this version, the linear operator program uses --input and --output instead of stdin and stdout.

.SH PARAMETERS
.PD 0
.TP
.I file   
.B dat
.B =
.R  	auxiliary input file name
.TP
.I file   
.B mod
.B =
.R  	auxiliary input file name
.SH SOURCE
.I system/main/cdottestmpi.c
.SH VERSION
4.2-git
