.TH sfcdivn 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcdivn \- Smooth division for complex data. 
.SH SYNOPSIS
.B sfcdivn < fnum.rsf den=fden.rsf > frat.rsf niter=100 verb=y rect#=(1,1,...)
.SH PARAMETERS
.PD 0
.TP
.I file   
.B den
.B =
.R  	auxiliary input file name
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I int    
.B rect#
.B =(1,1,...)
.R  	smoothing radius on #-th axis
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity
.SH SOURCE
.I user/fomels/Mcdivn.c
.SH VERSION
4.2-git
