.TH sfcdivdir 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcdivdir \- Direct division for complex data. 
.SH SYNOPSIS
.B sfcdivdir < fnum.rsf den=fden.rsf > frat.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B den
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/chenyk/Mcdivdir.c
.SH VERSION
4.2-git
