.TH sfcemd1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcemd1 \- Bivariate empirical mode decomposition using first algorithm. 
.SH SYNOPSIS
.B sfcemd1 < inp.rsf > outp.rsf threshold=DEFAULT_THRESHOLD tolerance=DEFAULT_TOLERANCE miter=MAX_ITERATIONS mimf=0 nbdir=DEFAULT_NBPHASES
.SH PARAMETERS
.PD 0
.TP
.I int    
.B mimf
.B =0
.R  	Maximum number of IMFs, the default is as many as possible.
.TP
.I int    
.B miter
.B =MAX_ITERATIONS
.R  	Maximum number of iterations during sifting, the default is 1000.
.TP
.I int    
.B nbdir
.B =DEFAULT_NBPHASES
.R  	Number of directions used to compute the local mean, the default is 4.
.TP
.I float  
.B threshold
.B =DEFAULT_THRESHOLD
.R  	Sifting stoping parameter: threshold, the default is 0.05.
.TP
.I float  
.B tolerance
.B =DEFAULT_TOLERANCE
.R  	Sifting stoping parameter: tolerance, the default is 0.05.
.SH SOURCE
.I user/chenyk/Mcemd1.c
.SH VERSION
4.2-git
