.TH sfcfftwave1in 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcfftwave1in \- 1-D complex lowrank FFT wave extrapolation using complex to complex fft BY INJECTION
.SH SYNOPSIS
.B sfcfftwave1in < Fw.rsf > Fo.rsf refl=Fr.rsf left=left.rsf right=right.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B left
.B =
.R  	auxiliary input file name
.TP
.I file   
.B refl
.B =
.R  	auxiliary input file name
.TP
.I file   
.B right
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/jsun/Mcfftwave1in.c
.SH VERSION
4.2-git
