.TH sfcfftwave1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcfftwave1 \- 1-D complex lowrank FFT wave extrapolation 
.SH SYNOPSIS
.B sfcfftwave1 < inp.rsf > out.rsf left=left.rsf right=right.rsf prop=prop.rsf nt= dt=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dt
.B =
.R  
.TP
.I file   
.B left
.B =
.R  	auxiliary input file name
.TP
.I int    
.B nt
.B =
.R  
.TP
.I file   
.B prop
.B =
.R  	auxiliary input file name
.TP
.I string 
.B right
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/fomels/Mcfftwave1.c
.SH VERSION
4.2-git
