.TH sfcfftexpmig2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcfftexpmig2 \- Complex 2-D exploding reflector migration (read in initial complex wavefield in depth) 
.SH SYNOPSIS
.B sfcfftexpmig2 < wvfld.rsf > image.rsf left=left.rsf right=right.rsf verb=n nt= dt= pad1=1
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dt
.B =
.R  
.TP
.I file   
.B left
.B =
.R  	auxiliary input file name
.TP
.I int    
.B nt
.B =
.R  
.TP
.I int    
.B pad1
.B =1
.R  	padding factor on the first axis
.TP
.I file   
.B right
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.SH SOURCE
.I user/jsun/Mcfftexpmig2.c
.SH VERSION
4.2-git
