.TH sfcgconst 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcgconst \- Test Beam for constant velocity gradient 
.SH SYNOPSIS
.B sfcgconst < in.rsf > out.rsf mask=mask.rsf source=o2 w=0. v0=1. b=0. p=1/v0
.SH PARAMETERS
.PD 0
.TP
.I float  
.B b
.B =0.
.R  	velocity gradient
.TP
.I file   
.B mask
.B =
.R  	auxiliary output file name
.TP
.I float  
.B p
.B =1/v0
.R  
.TP
.I float  
.B source
.B =o2
.R  	real source point
.TP
.I float  
.B v0
.B =1.
.R  	surface velocity
.TP
.I float  
.B w
.B =0.
.R  	beam width
.SH SOURCE
.I user/llisiw/Mcgconst.c
.SH VERSION
4.2-git
