.TH sfchebvc 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfchebvc \- Post-stack 2-D velocity continuation by Chebyshev-tau method. 
.SH SYNOPSIS
.B sfchebvc < in.rsf > out.rsf nv= vel=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B nv
.B =
.R  
.TP
.I float  
.B vel
.B =
.R  
.SH SOURCE
.I user/fomels/Mchebvc.c
.SH VERSION
4.2-git
