.TH sfcic3d_ditthara 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcic3d_ditthara \- Conventional IC 3D 
.SH SYNOPSIS
.B sfcic3d_ditthara < Fs.rsf ur=Fr.rsf > Fi.rsf verb=n isreversed=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B isreversed
.B =n
.R  [y/n]	received wavefield
.TP
.I file   
.B ur
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/ditthara/Mcic3d_ditthara.c
.SH VERSION
4.2-git
