.TH sfcipcut 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcipcut \- cut at CIPs 
.SH SYNOPSIS
.B sfcipcut < Fcub.rsf cip=Fcip.rsf > Fcut.rsf verb=n
.SH PARAMETERS
.PD 0
.TP
.I file   
.B cip
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/cwp/Mcipcut.c
.SH VERSION
4.2-git
