.TH sfclfdc1frac 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfclfdc1frac \- 1D 10th-order Lowrank Onestep FD coefficient
.SH SYNOPSIS
.B sfclfdc1frac < velf.rsf > outm.rsf seed=time(NULL eps=1.e-4 npk=20 dt= SIZE= mode=0 perc=50 cpxexp=true
.SH PARAMETERS
.PD 0
.TP
.I        
.B SIZE
.B =
.R  	stencil size
.TP
.I        
.B cpxexp
.B =true
.R  	complex exponential
.TP
.I        
.B dt
.B =
.R  	time step
.TP
.I        
.B eps
.B =1.e-4
.R  	tolerance
.TP
.I        
.B mode
.B =0
.R  	symbol
.TP
.I        
.B npk
.B =20
.R  	maximum rank
.TP
.I        
.B perc
.B =50
.R  	cutoff percentage
.TP
.I        
.B seed
.B =time(NULL
.R  
.SH SOURCE
.I user/jsun/Mclfdc1frac.cc
.SH VERSION
4.2-git
