.TH sfclfdc2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfclfdc2 \- 2D nth-order Lowrank FD coefficient
.SH SYNOPSIS
.B sfclfdc2 < velf.rsf > outm.rsf seed=time(NULL eps=1.e-6 npk=50 dt= size=6
.SH PARAMETERS
.PD 0
.TP
.I        
.B dt
.B =
.R  	time step
.TP
.I        
.B eps
.B =1.e-6
.R  	tolerance
.TP
.I        
.B npk
.B =50
.R  	maximum rank
.TP
.I        
.B seed
.B =time(NULL
.R  
.TP
.I        
.B size
.B =6
.R  	stencil length
.SH SOURCE
.I user/jsun/Mclfdc2.cc
.SH VERSION
4.2-git
