.TH sfcloudmerge3d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcloudmerge3d \- 
.SH SYNOPSIS
.B sfcloudmerge3d all=Fcall.rsf > Fdall.rsf verb=n norm=y hashscale=2.0
.SH COMMENTS
3D CLoud DATA merge
Paul Sava
Copyright (C) 2022 Colorado School of Mines

.SH PARAMETERS
.PD 0
.TP
.I file   
.B all
.B =
.R  	auxiliary input file name
.TP
.I float  
.B hashscale
.B =2.0
.R  
.TP
.I bool   
.B norm
.B =y
.R  [y/n]	fold normalization
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.SH SOURCE
.I user/psava/Mcloudmerge3d.c
.SH VERSION
4.2-git
