.TH sfclfd1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfclfd1 \- 2-D Fourth-order Optimized Finite-difference wave extrapolation 
.SH SYNOPSIS
.B sfclfd1 > out.rsf < ini.rsf G=G.rsf dt= nt= mode=0 cpxexp=y
.SH PARAMETERS
.PD 0
.TP
.I file   
.B G
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B cpxexp
.B =y
.R  [y/n]
.TP
.I float  
.B dt
.B =
.R  
.TP
.I int    
.B mode
.B =0
.R  
.TP
.I int    
.B nt
.B =
.R  
.SH SOURCE
.I user/jsun/Mclfd1.c
.SH VERSION
4.2-git
