.TH sfcloudspray 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcloudspray \- 
.SH SYNOPSIS
.B sfcloudspray < Fin.rsf > Fou.rsf cc=Fcc.rsf verb=n axis=2
.SH COMMENTS
point cloud spray
Paul Sava
Copyright (C) 2022 Colorado School of Mines

.SH PARAMETERS
.PD 0
.TP
.I int    
.B axis
.B =2
.R  	spray axis
.TP
.I file   
.B cc
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.SH SOURCE
.I user/psava/Mcloudspray.c
.SH VERSION
4.2-git
