.TH sfcmplx 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcmplx \- Create a complex dataset from its real and imaginary parts.
.SH SYNOPSIS
.B sfcmplx < real.rsf > cmplx.rsf real.rsf imag.rsf
.SH COMMENTS
There has to be only two input files specified and no additional parameters.

.SH USED IN
.TP
.I cwp/geo2008NumericWEMVAoperators/flatWEMVA
.TP
.I cwp/geo2008NumericWEMVAoperators/saltWEMVA
.SH SOURCE
.I system/main/cmplx.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfcmplx
.SH VERSION
4.2-git
