.TH sfcmatmult 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcmatmult \- Simple matrix multiplication for complex matrices 
.SH SYNOPSIS
.B sfcmatmult < in.rsf > out.rsf mat=mat.rsf adj=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]
.TP
.I file   
.B mat
.B =
.R  	auxiliary input file name
.SH SOURCE
.I system/generic/Mcmatmult.c
.SH VERSION
4.2-git
