.TH sfconflict 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfconflict \- 2-D synthetic data of conflicting dips. 
.SH SYNOPSIS
.B sfconflict > mod.rsf n1=150 n2=80
.SH PARAMETERS
.PD 0
.TP
.I int    
.B n1
.B =150
.R  
.TP
.I int    
.B n2
.B =80
.R  
.SH SOURCE
.I user/gee/Mconflict.c
.SH VERSION
4.2-git
