.TH sfcomblist 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcomblist \- Create masks to remove combinations of k elements out of n 
.SH SYNOPSIS
.B sfcomblist < in.rsf > out.rsf k=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B k
.B =
.R  	combination of k elements
.SH SOURCE
.I user/browaeys/Mcomblist.c
.SH VERSION
4.2-git
