.TH sfconvolve 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfconvolve \- 
.SH SYNOPSIS
.B sfconvolve < _in.rsf > _out.rsf ker=_ker.rsf adj=n wrap=n
.SH COMMENTS
convolve input 2D image by kernel

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	if y adjoint convolution, if n, convolution
.TP
.I string 
.B ker
.B =
.R  	convolution kernel file (auxiliary input file name)
.TP
.I bool   
.B wrap
.B =n
.R  [y/n]	if y, perform doughnut wrapping.  if n, no wrapping
.SH SOURCE
.I user/luke/Mconvolve.c
.SH VERSION
4.2-git
