.TH sfconstpermh 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfconstpermh \- Constant-velocity prestack exploding reflector in offset. 
.SH SYNOPSIS
.B sfconstpermh < data.rsf > image.rsf mig=n snap=0 nz= dz= nt= dt= nh= dh= v=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dh
.B =
.R  	offset sampling (if modeling)
.TP
.I float  
.B dt
.B =
.R  	time sampling (if modeling)
.TP
.I float  
.B dz
.B =
.R  	depth sampling (if migration)
.TP
.I bool   
.B mig
.B =n
.R  [y/n]	if n, modeling; if y, migration
.TP
.I int    
.B nh
.B =
.R  	offset samples (if modeling)
.TP
.I int    
.B nt
.B =
.R  	time samples (if modeling)
.TP
.I int    
.B nz
.B =
.R  	depth samples (if migration)
.TP
.I int    
.B snap
.B =0
.R  	interval for snapshots
.TP
.I float  
.B v
.B =
.R  	velocity
.SH SOURCE
.I user/fomels/Mconstpermh.c
.SH VERSION
4.2-git
