.TH sfconvkernel 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfconvkernel \- 
.SH SYNOPSIS
.B sfconvkernel < Fin.rsf filter=Ffilter.rsf > Fout.rsf lag=Flag1.rsf lag2=Flag2.rsf lag3=Flag3.rsf adj=n n=1
.SH COMMENTS
Applies a 1,2, or 3D convolution kernel or its adjoint
The filter is composed by n coefficients.

example: 2d laplacian

1
1 -4  1
1 

filter: 1 1 -4 1 1
lag1 (vertical lag)  :  0  1  0  -1  0 
lag2 (horizontal lag): -1  0  0   0  1  


.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]
.TP
.I file   
.B filter
.B =
.R  	auxiliary input file name
.TP
.I file   
.B lag
.B =
.R  	auxiliary input file name
.TP
.I file   
.B lag2
.B =
.R  	auxiliary input file name
.TP
.I file   
.B lag3
.B =
.R  	auxiliary input file name
.TP
.I int    
.B n
.B =1
.R  	------------------------------------------------------------
.SH SOURCE
.I user/ediazp/Mconvkernel.c
.SH VERSION
4.2-git
