.TH sfcosft 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcosft \- Multi-dimensional cosine transform.
.SH SYNOPSIS
.B sfcosft < in.rsf > out.rsf sign#=0
.SH COMMENTS

The input and output are real and have the same dimensions. 
Pad the data if you need to suppress wrap-around effects.

.SH PARAMETERS
.PD 0
.TP
.I int    
.B sign#
.B =0
.R  	transform along #-th dimension 
	  [+1 forward or -1 backward]
.SH USED IN
.TP
.I bei/dwnc/phasemod
.TP
.I bei/dwnc/sigmoid
.TP
.I bei/dwnc/vofz
.SH SOURCE
.I system/generic/Mcosft.c
.SH VERSION
4.2-git
