.TH sfcorop 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcorop \- 
.SH SYNOPSIS
.B sfcorop opr=Fopr.rsf < Fcor.rsf > Fwfl.rsf verb=n adj=n ncor=100
.SH COMMENTS
Correlation operator w/ adjoint
wfl [file] : is taken from stdin
opr [file] : is taken from  "opr"
Requires both files to have the same dimensions

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag
.TP
.I int    
.B ncor
.B =100
.R  
.TP
.I file   
.B opr
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/psava/Mcorop.py
.SH VERSION
4.2-git
