.TH sfcorral 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcorral \- Cross-correlate every trace with every other in frequency domain. 
.SH SYNOPSIS
.B sfcorral < inp.rsf > out.rsf nlags=100
.SH PARAMETERS
.PD 0
.TP
.I int    
.B nlags
.B =100
.R  	number of lags
.SH SOURCE
.I user/rickettj/Mcorral.c
.SH VERSION
4.2-git
