.TH sfcomp 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcomp \- Compare 2 data set 
.SH SYNOPSIS
.B sfcomp < in.rsf > out.rsf ref=ref.rsf mode=0
.SH PARAMETERS
.PD 0
.TP
.I int    
.B mode
.B =0
.R  	compare method: 
	0 - normalized xcorrelation; 
	1 - mean square error
.TP
.I file   
.B ref
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/chen/Mcomp.c
.SH VERSION
4.2-git
