.TH sfconverted 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfconverted \- None
.SH SYNOPSIS
.B sfconverted actual_weights=aw.rsf weights=w1.rsf Rps=Refl.rsf NoisyRps=NoisyRps.rsf Wip=Winvpred.rsf phi= theta=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B NoisyRps
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Rps
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Wip
.B =
.R  	auxiliary output file name
.TP
.I file   
.B actual_weights
.B =
.R  	auxiliary output file name
.TP
.I        
.B phi
.B =
.R  	command-line parameter
.TP
.I        
.B theta
.B =
.R  	command-line parameter
.TP
.I file   
.B weights
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/mehdi/Mconverted.f90
.SH VERSION
4.2-git
