.TH sfcpef 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcpef \- 1-D prediction-error filter estimation from complex data 
.SH SYNOPSIS
.B sfcpef < in.rsf > out.rsf single=y nf=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B nf
.B =
.R  	filter length
.TP
.I bool   
.B single
.B =y
.R  [y/n]	single channel or multichannel
.SH SOURCE
.I user/fomels/Mcpef.c
.SH VERSION
4.2-git
