.TH sfcp 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcp \- Copy or move a dataset.
.SH SYNOPSIS
.B sfcp < in.rsf > out.rsf in.rsf out.rsf
.SH COMMENTS
sfcp - copy, sfmv - move.
Mimics standard Unix commands.

.SH USED IN
.TP
.I cwp/geo2008InterferometricImagingCondition/sact1
.SH SOURCE
.I system/main/cp.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfcp
.SH VERSION
4.2-git
