.TH sfcpef1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcpef1 \- Estimate complex PEF on the first axis. 
.SH SYNOPSIS
.B sfcpef1 < in.rsf > out.rsf nf= niter=2*nf
.SH PARAMETERS
.PD 0
.TP
.I int    
.B nf
.B =
.R  	filter length
.TP
.I int    
.B niter
.B =2*nf
.R  	number of iterations
.SH SOURCE
.I user/gee/Mcpef1.c
.SH VERSION
4.2-git
