.TH sfcplxloc 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcplxloc \- Local coherency and dip based on trace-by-trace complex statistical correlation. 
.SH SYNOPSIS
.B sfcplxloc < in.rsf > out.rsf nw=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B nw
.B =
.R  	half time-window size
.SH SOURCE
.I user/browaeys/Mcplxloc.c
.SH VERSION
4.2-git
