.TH sfcplxcoh 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcplxcoh \- Coherency based on complex statistical correlation. 
.SH SYNOPSIS
.B sfcplxcoh < in.rsf > out.rsf nw=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B nw
.B =
.R  	half time-window size
.SH SOURCE
.I user/browaeys/Mcplxcoh.c
.SH VERSION
4.2-git
