.TH sfcrestack 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcrestack \- Common Reflection Element (CRE) stacking
.SH SYNOPSIS
.B sfcrestack < in.rsf timeCurves=timeCurves.rsf > out.rsf verb=0 aperture=1
.SH COMMENTS

Programmer: Rodolfo A. C. Neves (Dirack) 06/10/2019

Email:  rodolfo_profissional@hotmail.com

License: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.


.SH PARAMETERS
.PD 0
.TP
.I int    
.B aperture
.B =1
.R  	Stacking aperture, number of offsets to stack
.TP
.I file   
.B timeCurves
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =0
.R  [y/n]	1: active mode; 0: quiet mode
.SH SOURCE
.I user/dirack/Mcrestack.c
.SH VERSION
4.2-git
