.TH sfcreate 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcreate \- Creates just the ascii header from parameters
.SH SYNOPSIS
.B sfcreate > out.rsf n#=
.SH COMMENTS
Wrapper for sf_fileflush (creating RSF header from params) 
.SH PARAMETERS
.PD 0
.TP
.I int    
.B n#
.B =
.R  	size of #-th axis
.SH SOURCE
.I user/ivlad/Mcreate.c
.SH VERSION
4.2-git
