.TH sfcrssemb 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcrssemb \- CRS-based semblance
.SH SYNOPSIS
.B sfcrssemb < inDags_.rsf dataSq=inDagsSq_.rsf > sembFile_.rsf xapp=1 dipapp=11 coher=11 scatnum=1 s1= s2=
.SH COMMENTS

Several CIGs are used simultaneously. Dip-angle sections corresponding to the same 
dip-angle compose a subvolume. The subvolume allows calculating semblance in the
scattering-angle direction along reflection boundaries.

Input:
inDags_.rsf   - dip-angle gathers - stack in the scattering-angle direction
InDagsSq_.rsf - stack of amplitude squares in the scattering-angle direction

Working with just dip-angle gathers use default value of "scatnum" parameter

Output:
sembFile_.rsf - crs-based semblance file; has the same dimensions as the input files

.SH PARAMETERS
.PD 0
.TP
.I int    
.B coher
.B =11
.R  	height of a vertical window for semblance calculation
.TP
.I file   
.B dataSq
.B =
.R  	auxiliary input file name
.TP
.I int    
.B dipapp
.B =11
.R  	number of traces in the x-dip direction processed simultaneously
.TP
.I float  
.B s1
.B =
.R  
.TP
.I float  
.B s2
.B =
.R  
.TP
.I int    
.B scatnum
.B =1
.R  	shows how many traces were stacked in the scattering angle direction; 
       if the stack was normalized use the default value
.TP
.I int    
.B xapp
.B =1
.R  	number of CIGs in the inline-direction processed simultaneously
.SH SOURCE
.I user/aklokov/Mcrssemb.c
.SH VERSION
4.2-git
