.TH sfcshifts2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcshifts2 \- Generate shifts for 2-D regularized autoregression in complex domain. From (x,y,f) to (x,y,s,f) 
.SH SYNOPSIS
.B sfcshifts2 < in.rsf > shifts.rsf ns1= ns2=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B ns1
.B =
.R  	number of shifts in first dim
.TP
.I int    
.B ns2
.B =
.R  	number of shifts in second dim
.SH USED IN
.TP
.I cup/rna3d/real
.TP
.I cup/rna3d/shot
.TP
.I cup/rna3d/sin
.SH SOURCE
.I user/gchliu/Mcshifts2.c
.SH VERSION
4.2-git
