.TH sfctscigder 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfctscigder \- Get the derivative of time-shift gathers 
.SH SYNOPSIS
.B sfctscigder < Ftg.rsf > Fder.rsf velocity=Fvel.rsf dt=0.001 pad=30
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dt
.B =0.001
.R  
.TP
.I int    
.B pad
.B =30
.R  
.TP
.I file   
.B velocity
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/zhiguang/Mctscigder.c
.SH VERSION
4.2-git
