.TH sfctshift 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfctshift \- Correct time-shift gathers 
.SH SYNOPSIS
.B sfctshift < tgather.rsf > cgather.rsf velocity=vel.rsf dt=0.001 pad=30
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dt
.B =0.001
.R  
.TP
.I int    
.B pad
.B =30
.R  
.TP
.I file   
.B velocity
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/zhiguang/Mctshift.c
.SH VERSION
4.2-git
