.TH sfcube 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcube \- Simple cube fault synthetic 
.SH SYNOPSIS
.B sfcube > cube.rsf n=51 p=0.5 q=0.5
.SH PARAMETERS
.PD 0
.TP
.I int    
.B n
.B =51
.R  	cube dimensions
.TP
.I float  
.B p
.B =0.5
.R  	inline slope
.TP
.I float  
.B q
.B =0.5
.R  	crossline slope
.SH SOURCE
.I user/gee/Mcube.c
.SH VERSION
4.2-git
