.TH sfcurv 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcurv \- Max/Min curvatures by azimuth curvature cube 
.SH SYNOPSIS
.B sfcurv < in.rsf > out.rsf axis=2 mode=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B axis
.B =2
.R  	azimuth dimension
.TP
.I string 
.B mode
.B =
.R  	max/min/mean/gauss/mpo/mne/dip/strike
.SH SOURCE
.I user/chen/Mcurv.c
.SH VERSION
4.2-git
