.TH sfcurv2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcurv2 \- Joint estimation of curvature and slope 
.SH SYNOPSIS
.B sfcurv2 < in.rsf > out.rsf slope=slope.rsf niter=5 m=1 n=1 interp=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B interp
.B =
.R  	interpolation method: maxflat lagrange bspline
.TP
.I int    
.B m
.B =1
.R  	b[-m, ... ,n]
.TP
.I int    
.B n
.B =1
.R  	b[-m, ... ,n]
.TP
.I int    
.B niter
.B =5
.R  	iterations
.TP
.I file   
.B slope
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/chen/Mcurv2.c
.SH VERSION
4.2-git
