.TH sfcubesrc 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfcubesrc \- Simple 2-D wave propagation with multi-threaded fftw3 
.SH SYNOPSIS
.B sfcubesrc < Fw.rsf > Fo.rsf ref=Fr.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B ref
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/jsun/Mcubesrc.c
.SH VERSION
4.2-git
