.TH sfdatasucjb2rsf2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdatasucjb2rsf2d \- Convert 2D cjb-SU data to RSF format.
.SH SYNOPSIS
.B sfdatasucjb2rsf2d > Fo.rsf fn=
.SH COMMENTS

Copyright (C) 2012 Tongji University, Shanghai, China 
Authors: Jiubing Cheng

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

.SH PARAMETERS
.PD 0
.TP
.I string 
.B fn
.B =
.R  	setup I/O files
.SH SOURCE
.I user/chengjb/Mdatasucjb2rsf2d.c
.SH VERSION
4.2-git
