.TH sfdagapex 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdagapex \- None
.SH SYNOPSIS
.B sfdagapex < gathers_in.rsf dip=dips_in.rsf > fresnel_out.rsf mask= gray=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B dip
.B =
.R  	Image Dips (deg)(auxiliary input file name)
.TP
.I float  
.B gray
.B =
.R  
.TP
.I float  
.B mask
.B =
.R  
.SH SOURCE
.I user/luke/Mdagapex.c
.SH VERSION
4.2-git
