.TH sfdagtaper 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdagtaper \- Edge tapering for dip-angle gathers
.SH SYNOPSIS
.B sfdagtaper < dataFile.rsf > outFile.rsf len=5.f
.SH PARAMETERS
.PD 0
.TP
.I float  
.B len
.B =5.f
.R  	length of the taper function (in degree)
.SH SOURCE
.I user/aklokov/Mdagtaper.c
.SH VERSION
4.2-git
