.TH sfdatshift 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdatshift \- Calculate datum shift from elevation profile for 2-D shot gathers 
.SH SYNOPSIS
.B sfdatshift < in.rsf > out.rsf elev=elev.rsf v0=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B elev
.B =
.R  	auxiliary input file name
.TP
.I float  
.B v0
.B =
.R  
.SH SOURCE
.I user/bash/Mdatshift.c
.SH VERSION
4.2-git
