.TH sfdblendseis 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdblendseis \- Blending, or Deblending using seislet domain thresholding.
.SH SYNOPSIS
.B sfdblendseis < in.rsf > out.rsf shottime=shottime.rsf dip=dip.rsf init=init.rsf niter=30 thr=10 lambda=0.5 eps=0.01 order=1 verb=0 mode= type= thrtype=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I float  
.B eps
.B =0.01
.R  	regularization
.TP
.I string 
.B init
.B =
.R  	auxiliary input file name
.TP
.I float  
.B lambda
.B =0.5
.R  	update step size
.TP
.I string 
.B mode
.B =
.R  	[b-blending,d-deblending] function mode, the default is d
.TP
.I int    
.B niter
.B =30
.R  	number of iterations
.TP
.I int    
.B order
.B =1
.R  	accuracy order for seislet transform
.TP
.I file   
.B shottime
.B =
.R  	auxiliary input file name
.TP
.I float  
.B thr
.B =10
.R  	threshold value (coefficients preserved in percentage)
.TP
.I string 
.B thrtype
.B =
.R  	[soft,hard] thresholding type, the default is soft
.TP
.I string 
.B type
.B =
.R  	[haar,linear,biorthogonal] wavelet type, the default is linear
.TP
.I int    
.B verb
.B =0
.R  	output verbosity information
.SH SOURCE
.I user/chenyk/Mdblendseis.c
.SH VERSION
4.2-git
