.TH sfdbmerge 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdbmerge \- 
.SH SYNOPSIS
.B sfdbmerge
.SH COMMENTS
A program that can be used to merge separate SCons databases together.  Typically used when an SConstruct is split
into multiple pieces (e.g. on a cluster).

args:
outdb - path of the output database

strings - names of the databases to merge together

.SH SOURCE
.I user/cwp/Mdbmerge.py
.SH VERSION
4.2-git
