.TH sfdd 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdd \- Convert between different formats. 
.SH SYNOPSIS
.B sfdd < in.rsf > out.rsf trunc=n line=8 strip=0 ibm=n form= type= format=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B form
.B =
.R  	ascii, native, xdr
.TP
.I string 
.B format
.B =
.R  	Element format (for conversion to ASCII)
.TP
.I bool   
.B ibm
.B =n
.R  [y/n]	Special case - assume integers actually represent IBM floats
.TP
.I int    
.B line
.B =8
.R  	Number of numbers per line (for conversion to ASCII)
.TP
.I int    
.B strip
.B =0
.R  	If strip characters from format at the end of the line
.TP
.I bool   
.B trunc
.B =n
.R  [y/n]	Truncate or round to nearest when converting from float to int/short
.TP
.I string 
.B type
.B =
.R  	int, float, complex, short, long
.SH USED IN
.TP
.I bei/dpmv/krchdmo
.TP
.I bei/dwnc/vofz
.TP
.I bei/fld/cube
.TP
.I bei/fld/shotmovie
.TP
.I bei/fld/yc
.TP
.I bei/ft1/brad
.TP
.I bei/ft1/plane4
.TP
.I bei/krch/wgkirch
.TP
.I bei/sg/denmark
.TP
.I bei/sg/meander
.TP
.I bei/sg/toldi
.TP
.I bei/vela/stretch
.TP
.I bei/vela/vscan
.TP
.I bei/wvs/head
.TP
.I bei/wvs/vscan
.TP
.I chen/test/wavmod
.TP
.I chen/test/xtime
.TP
.I cup/rna2d/real
.TP
.I cup/rna2d/simple
.TP
.I cup/rna3d/real
.TP
.I cup/rna3d/shot
.TP
.I cwp/geo2007StereographicImagingCondition/flat4
.TP
.I cwp/geo2007StereographicImagingCondition/gaus1
.TP
.I cwp/geo2007StereographicImagingCondition/sigsbee2
.TP
.I cwp/geo2008InterferometricImagingCondition/circle
.TP
27 more examples listed in:
.TP
/home/mlouboutin3/Research/madagascar//share/doc/madagascar/html/sfdd.html
.SH SOURCE
.I system/main/dd.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfdd
.SH VERSION
4.2-git
