.TH sfdeburst 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdeburst \- Remove bursty noise by IRLS. 
.SH SYNOPSIS
.B sfdeburst < in.rsf > out.rsf niter=10 eps=1. norm=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =1.
.R  	regularization parameter
.TP
.I int    
.B niter
.B =10
.R  	number of iterations
.TP
.I string 
.B norm
.B =
.R  	norm to use in IRLS (cauchy,l1)
.SH SOURCE
.I user/gee/Mdeburst.c
.SH VERSION
4.2-git
