.TH sfderiv3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfderiv3 \- Second order derivative along axis
.SH SYNOPSIS
.B sfderiv3 < in.rsf > out.rsf axis=1 operator=2
.SH COMMENTS

int axis=[1] axis to differentiate

int operator=[2] 1 backward, 2 centered, 3 forward



.SH PARAMETERS
.PD 0
.TP
.I int    
.B axis
.B =1
.R  
.TP
.I int    
.B operator
.B =2
.R  
.SH SOURCE
.I user/ediazp/Mderiv3.c
.SH VERSION
4.2-git
