.TH sfdensity 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdensity \- Compute density 
.SH SYNOPSIS
.B sfdensity < Fin.rsf inY=FinY.rsf inZ=FinZ.rsf inW=FinW.rsf > Fout.rsf verb=n n1=20 n2=20 n3=20 n4=20
.SH PARAMETERS
.PD 0
.TP
.I file   
.B inW
.B =
.R  	auxiliary input file name
.TP
.I file   
.B inY
.B =
.R  	auxiliary input file name
.TP
.I file   
.B inZ
.B =
.R  	auxiliary input file name
.TP
.I int    
.B n1
.B =20
.R  	verbosity flag
.TP
.I int    
.B n2
.B =20
.R  	verbosity flag
.TP
.I int    
.B n3
.B =20
.R  	verbosity flag
.TP
.I int    
.B n4
.B =20
.R  	verbosity flag
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/jyan/Mdensity.c
.SH VERSION
4.2-git
