.TH sfdespike2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdespike2 \- Remove spikes in by sliding 2-D medians. 
.SH SYNOPSIS
.B sfdespike2 < in.rsf > out.rsf wide1=5 wide2=5
.SH PARAMETERS
.PD 0
.TP
.I int    
.B wide1
.B =5
.R  
.TP
.I int    
.B wide2
.B =5
.R  	sliding window width
.SH SOURCE
.I user/gee/Mdespike2.c
.SH VERSION
4.2-git
