.TH sfdespike 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdespike \- Remove spikes in by sliding 1-D medians. 
.SH SYNOPSIS
.B sfdespike < in.rsf > out.rsf wide=7
.SH PARAMETERS
.PD 0
.TP
.I int    
.B wide
.B =7
.R  	sliding window width
.SH SOURCE
.I user/gee/Mdespike.c
.SH VERSION
4.2-git
