.TH sfdifference 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdifference \- Difference profile of two data 
.SH SYNOPSIS
.B sfdifference < in.rsf > out.rsf subtracter=sub.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B subtracter
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/yliu/Mdifference.c
.SH VERSION
4.2-git
