.TH sfdiffcxx 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdiffcxx \- Compare the difference of two rsf data sets with the same size. 
.SH SYNOPSIS
.B sfdiffcxx < inp1.rsf match=inp2.rsf > dif.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B match
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/chenyk/Mdiffcxx.cc
.SH VERSION
4.2-git
