.TH sfdivn2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdivn2d \- 2D divn 
.SH SYNOPSIS
.B sfdivn2d < inp.rsf den=den.rsf > out.rsf rect1=1 rect2=1 niter=100 verb=n
.SH PARAMETERS
.PD 0
.TP
.I file   
.B den
.B =
.R  	auxiliary input file name
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I int    
.B rect1
.B =1
.R  
.TP
.I int    
.B rect2
.B =1
.R  	smoothing radius
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.SH SOURCE
.I user/chen/Mdivn2d.c
.SH VERSION
4.2-git
