.TH sfditime2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfditime2d \- 2D Hybrid Radon transform for diffraction imaging in the time dip-angle domain 
.SH SYNOPSIS
.B sfditime2d < in.rsf > out.rsf dweight=fileDweight.rsf reflMod=fileRefl.rsf verb=n adj=n isAA=n liter=100 niter=0 eps=0. verb=n invMod=2 dip0n= dip0d= dip0o= xin= xid= xio= dipn= dipo= dipd=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag
.TP
.I float  
.B dip0d
.B =
.R  	dip0 sampling (if adj=y)
.TP
.I int    
.B dip0n
.B =
.R  	number of dip0 values (if adj=y)
.TP
.I float  
.B dip0o
.B =
.R  	dip0 origin (if adj=y)
.TP
.I float  
.B dipd
.B =
.R  	offset sampling
.TP
.I int    
.B dipn
.B =
.R  	number of offsets
.TP
.I float  
.B dipo
.B =
.R  	offset origin
.TP
.I string 
.B dweight
.B =
.R  	input file containing data weights (auxiliary input file name)
.TP
.I float  
.B eps
.B =0.
.R  	regularization parameter
.TP
.I int    
.B invMod
.B =2
.R  	number of nonlinear iterations (for inversion)
.TP
.I bool   
.B isAA
.B =n
.R  [y/n]	if y, apply anti-aliasing
.TP
.I int    
.B liter
.B =100
.R  	number of linear iterations (for inversion)
.TP
.I int    
.B niter
.B =0
.R  	number of nonlinear iterations (for inversion)
.TP
.I file   
.B reflMod
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I float  
.B xid
.B =
.R  	xi sampling (if adj=y)
.TP
.I int    
.B xin
.B =
.R  	number of xi values (if adj=y)
.TP
.I float  
.B xio
.B =
.R  	xi origin (if adj=y)
.SH SOURCE
.I user/aklokov/Mditime2d.c
.SH VERSION
4.2-git
