.TH sfdiff 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdiff \- Compare the difference of two rsf data sets with the same size. 
.SH SYNOPSIS
.B sfdiff < inp1.rsf match=inp2.rsf > dif.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B match
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/chenyk/Mdiff.c
.SH VERSION
4.2-git
