.TH sfdifferr 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdifferr \- Error by substituting numerical solution into equation 
.SH SYNOPSIS
.B sfdifferr < in.rsf > out.rsf slow=slow.rsf slowz=slowz.rsf slowx=slowx.rsf err_cutoff=0.2 iq=2
.SH PARAMETERS
.PD 0
.TP
.I float  
.B err_cutoff
.B =0.2
.R  
.TP
.I int    
.B iq
.B =2
.R  	switch for escape variable 0=x, 1=a, 2=t, 3=z
.TP
.I file   
.B slow
.B =
.R  	auxiliary input file name
.TP
.I file   
.B slowx
.B =
.R  	auxiliary input file name
.TP
.I file   
.B slowz
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/browaeys/Mdifferr.c
.SH VERSION
4.2-git
