.TH sfdiffuse2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdiffuse2 \- Diffusion by regularized inversion. 
.SH SYNOPSIS
.B sfdiffuse2 < in.rsf > out.rsf niter=10 repeat=1 eps=1.
.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =1.
.R  	regularization parameter
.TP
.I int    
.B niter
.B =10
.R  	number of conjugate-gradient iterations
.TP
.I int    
.B repeat
.B =1
.R  	number of smoothing iterations
.SH SOURCE
.I user/dmerzlikin/Mdiffuse2.c
.SH VERSION
4.2-git
