.TH sfdiphase 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdiphase \- Derivative of local frequency. 
.SH SYNOPSIS
.B sfdiphase < df.rsf sig=in.rsf > out.rsf verb=n niter=100 order=100 ref=1. hertz=n rect#=(1,1,...)
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B hertz
.B =n
.R  [y/n]	if y, convert output to Hertz
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I int    
.B order
.B =100
.R  	Hilbert transformer order
.TP
.I int    
.B rect#
.B =(1,1,...)
.R  	smoothing radius on #-th axis
.TP
.I float  
.B ref
.B =1.
.R  	Hilbert transformer reference (0.5 < ref <= 1)
.TP
.I file   
.B sig
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.SH SOURCE
.I user/fomels/Mdiphase.c
.SH VERSION
4.2-git
