.TH sfdiradon3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdiradon3 \- direct 3to3 reflection/diffraction Radon transform
.SH SYNOPSIS
.B sfdiradon3 < input.rsf > output.rsf fi= ntau= np= nq= tau0= dtau= p0= dp= q0= dq=
.SH PARAMETERS
.PD 0
.TP
.I        
.B dp
.B =
.R  
.TP
.I        
.B dq
.B =
.R  
.TP
.I        
.B dtau
.B =
.R  
.TP
.I        
.B fi
.B =
.R  
.TP
.I        
.B np
.B =
.R  
.TP
.I        
.B nq
.B =
.R  
.TP
.I        
.B ntau
.B =
.R  
.TP
.I        
.B p0
.B =
.R  
.TP
.I        
.B q0
.B =
.R  
.TP
.I        
.B tau0
.B =
.R  
.SH SOURCE
.I user/jingwei/Mdiradon3.cc
.SH VERSION
4.2-git
