.TH sfdistance 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdistance \- Computing distance function by fast marching eikonal solver (3-D). 
.SH SYNOPSIS
.B sfdistance < points.rsf > dist.rsf velocity=vel.rsf n1= n2= n3=1 d1= d2= d3=d2 o1=0. o2=0. o3=0. order=2 vel=y
.SH PARAMETERS
.PD 0
.TP
.I float  
.B d1
.B =
.R  
.TP
.I float  
.B d2
.B =
.R  
.TP
.I float  
.B d3
.B =d2
.R  	sampling
.TP
.I int    
.B n1
.B =
.R  
.TP
.I int    
.B n2
.B =
.R  
.TP
.I int    
.B n3
.B =1
.R  	dimensions
.TP
.I float  
.B o1
.B =0.
.R  
.TP
.I float  
.B o2
.B =0.
.R  
.TP
.I float  
.B o3
.B =0.
.R  	origin
.TP
.I int    
.B order
.B =2
.R  [1,2]	Accuracy order
.TP
.I bool   
.B vel
.B =y
.R  [y/n]	if y, the input is velocity; n, slowness squared
.TP
.I string 
.B velocity
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/fomels/Mdistance.c
.SH VERSION
4.2-git Meikonal.c 825 2004-10-07 08:11:17Z fomels
