.TH sfdimag 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdimag \- Diffraction imaging in the plane-wave domain. 
.SH SYNOPSIS
.B sfdimag < cmp.rsf > scan.rsf semblance=n nb=2 v0= dv= nv= extend=4 mute=12 str=0. x0=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dv
.B =
.R  
.TP
.I int    
.B extend
.B =4
.R  	trace extension
.TP
.I int    
.B mute
.B =12
.R  	mute zone
.TP
.I int    
.B nb
.B =2
.R  	semblance averaging
.TP
.I int    
.B nv
.B =
.R  
.TP
.I bool   
.B semblance
.B =n
.R  [y/n]	if y, compute semblance; if n, stack
.TP
.I float  
.B str
.B =0.
.R  	maximum stretch allowed
.TP
.I float  
.B v0
.B =
.R  
.TP
.I float  
.B x0
.B =
.R  
.SH SOURCE
.I system/seismic/Mdimag.c
.SH VERSION
4.2-git
