.TH sfdixshape 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdixshape \- Convert RMS to interval velocity using LS and shaping regularization.
.SH SYNOPSIS
.B sfdixshape < vrms.rsf > vint.rsf weight=weight.rsf dip=dip.rsf prior=prior.rsf vrmsout=vout.rsf rect1=3 rect2=3 lam=1. order=1 niter=100 rect1= rect2= ...
.SH COMMENTS
rectN defines the size of the smoothing stencil in N-th dimension.

.SH PARAMETERS
.PD 0
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I float  
.B lam
.B =1.
.R  	operator scaling for inversion
.TP
.I int    
.B niter
.B =100
.R  	maximum number of iterations
.TP
.I int    
.B order
.B =1
.R  	accuracy order
.TP
.I string 
.B prior
.B =
.R  	prior velocity model (auxiliary input file name)
.TP
.I int    
.B rect1
.B =3
.R  
.TP
.I int    
.B rect2
.B =3
.R  	smoothing radius
.TP
.I string 
.B vrmsout
.B =
.R  	optionally, output predicted vrms (auxiliary output file name)
.TP
.I file   
.B weight
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/pwd/Mdixshape.c
.SH VERSION
4.2-git Mdix.c 1131 2005-04-20 18:19:10Z fomels
