.TH sfdiradon32 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdiradon32 \- direct azimuthally isotropic 3to2 hyper Radon transform
.SH SYNOPSIS
.B sfdiradon32 < input.rsf > output.rsf ntau= np= tau0= dtau= p0= dp=
.SH PARAMETERS
.PD 0
.TP
.I        
.B dp
.B =
.R  
.TP
.I        
.B dtau
.B =
.R  
.TP
.I        
.B np
.B =
.R  
.TP
.I        
.B ntau
.B =
.R  
.TP
.I        
.B p0
.B =
.R  
.TP
.I        
.B tau0
.B =
.R  
.SH SOURCE
.I user/jingwei/Mdiradon32.cc
.SH VERSION
4.2-git
