.TH sfdispelem 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdispelem \- Display element of rsf files. 
.SH SYNOPSIS
.B sfdispelem < in.rsf > out.rsf i1= i2=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B i1
.B =
.R  	get the index of first axis
.TP
.I int    
.B i2
.B =
.R  	get the index of second axis
.SH SOURCE
.I user/chenyk/Mdispelem.c
.SH VERSION
4.2-git
