.TH sfdipln 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdipln \- large dip calculation via non-stationary regularization  
.SH SYNOPSIS
.B sfdipln < in.rsf > out.rsf m=1 n=1 niter=5 liter=20 radius=1.0 eta=0.5 dip0=0.0 verb=n slope=n eps=0.0f rect#= shift#= interp=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dip0
.B =0.0
.R  	starting dip
.TP
.I float  
.B eps
.B =0.0f
.R  	regularization
.TP
.I float  
.B eta
.B =0.5
.R  	steps for iteration
.TP
.I string 
.B interp
.B =
.R  	interpolation method: maxflat lagrange bspline
.TP
.I int    
.B liter
.B =20
.R  	number of linear iterations
.TP
.I int    
.B m
.B =1
.R  	b[-m, ... ,n]
.TP
.I int    
.B n
.B =1
.R  	b[-m, ... ,n]
.TP
.I int    
.B niter
.B =5
.R  	number of iterations
.TP
.I float  
.B radius
.B =1.0
.R  	interpolating radius for opwd
.TP
.I string 
.B rect#
.B =
.R  	size of the smoothing stencil in #-th dimension /auxiliary input file/
.TP
.I string 
.B shift#
.B =
.R  	shifting of the smoothing stencil in #-th dimension /auxiliary input file/
.TP
.I bool   
.B slope
.B =n
.R  [y/n]	slope (y) or dip (n) estimation
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/chenyk/Mdipln.c
.SH VERSION
4.2-git
