.TH sfdips 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdips \- Estimate a number of constant dips using plane-wave destruction. 
.SH SYNOPSIS
.B sfdips < in.rsf > out.rsf dips= nd= order=1 nj=1 verb=n niter=10
.SH PARAMETERS
.PD 0
.TP
.I floats 
.B dips
.B =
.R  	initial dips  [nd]
.TP
.I int    
.B nd
.B =
.R  	number of dips
.TP
.I int    
.B niter
.B =10
.R  	number of iterations
.TP
.I int    
.B nj
.B =1
.R  	antialiasing
.TP
.I int    
.B order
.B =1
.R  [1,2,3]	accuracy order
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/pwd/Mdips.c
.SH VERSION
4.2-git
