.TH sfdiparti3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdiparti3 \- diparti
.SH SYNOPSIS
.B sfdiparti3 < piFile.rsf vel=velFile.rsf > resFile.rsf semb=sembFile.rsf apert=1000 sembWindow=11 gamma=1.f xppn=dipNum_ xppo=dipStart_ xppd=dipStep_ yppn=sdipNum_ yppo=sdipStart_ yppd=sdipStep_ itn=tNum_ ixn=xNum_ iyn=yNum_ ito=tStart_ ixo=xStart_ iyo=yStart_ itd=tStep_ ixd=xStep_ iyd=yStep_
.SH PARAMETERS
.PD 0
.TP
.I float  
.B apert
.B =1000
.R  	diffraction summation aperture
.TP
.I float  
.B gamma
.B =1.f
.R  	velocity-model-accuracy parameter
.TP
.I float  
.B itd
.B =tStep_
.R  	step in time (in ms)
.TP
.I int    
.B itn
.B =tNum_
.R  	number of imaged depth samples
.TP
.I float  
.B ito
.B =tStart_
.R  	first imaged time (in ms)
.TP
.I float  
.B ixd
.B =xStep_
.R  	step in positions (in m)
.TP
.I int    
.B ixn
.B =xNum_
.R  	number of imaged positions
.TP
.I float  
.B ixo
.B =xStart_
.R  	first imaged position (in m)
.TP
.I float  
.B iyd
.B =yStep_
.R  	step in positions (in m)
.TP
.I int    
.B iyn
.B =yNum_
.R  	number of imaged positions
.TP
.I float  
.B iyo
.B =yStart_
.R  	first imaged position (in m)
.TP
.I string 
.B semb
.B =
.R  	output file containing semblance (auxiliary output file name)
.TP
.I int    
.B sembWindow
.B =11
.R  	vertical window for semblance calculation (in samples)
.TP
.I string 
.B vel
.B =
.R  	velocity model file (velocity in km/s) (auxiliary input file name)
.TP
.I float  
.B xppd
.B =dipStep_
.R  	step in processed partial images
.TP
.I int    
.B xppn
.B =dipNum_
.R  	number of processed partial images
.TP
.I float  
.B xppo
.B =dipStart_
.R  	first processed partial image
.TP
.I float  
.B yppd
.B =sdipStep_
.R  	step in processed partial images
.TP
.I int    
.B yppn
.B =sdipNum_
.R  	number of processed partial images
.TP
.I float  
.B yppo
.B =sdipStart_
.R  	first processed partial image
.SH SOURCE
.I user/aklokov/Mdiparti3.cc
.SH VERSION
4.2-git
