.TH sfdlct 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdlct \- discrete linear chirp transfrom (DLCT)
.SH SYNOPSIS
.B sfdlct < in.rsf > out.rsf inv=n verb=n C=0.005 L=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B C
.B =0.005
.R  	C=2*Lambda/L, unit slice
.TP
.I int    
.B L
.B =
.R  
.TP
.I bool   
.B inv
.B =n
.R  [y/n]	if y, do inverse transform (Here adjoint is the same as inverse!)
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/pyang/Mdlct.c
.SH VERSION
4.2-git
