.TH sfdmeig 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdmeig \- Find eigenvalues and eigenvectors of an spd matrix. 
.SH SYNOPSIS
.B sfdmeig < mat.rsf eval=evals.rsf > evecs.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B eval
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/mccowan/Mdmeig.c
.SH VERSION
4.2-git
