.TH sfdowmf 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdowmf \- 2D dip-oriented weighted median filter (DOWMF). 
.SH SYNOPSIS
.B sfdowmf < in.rsf > out.rsf dip=dip.rsf nw= rect=nw boundary=y var=n verb=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B boundary
.B =y
.R  [y/n]	if y, boundary is data, whereas zero
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I int    
.B nw
.B =
.R  	data-window length (positive and odd integer)
.TP
.I int    
.B rect
.B =nw
.R  	Correlation window
.TP
.I bool   
.B var
.B =n
.R  [y/n]	if y, variance weights, whereas correlation weights
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/yliu/Mdowmf.c
.SH VERSION
4.2-git
