.TH sfdottestmpi 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdottestmpi \- Generic dot-product test for linear operators with adjoints 
.SH SYNOPSIS
.B sfdottestmpi mod=mod.rsf dat=dat.rsf
.SH COMMENTS

In this version, the linear operator program uses --input and --output instead of stdin and stdout.

.SH PARAMETERS
.PD 0
.TP
.I file   
.B dat
.B =
.R  	auxiliary input file name
.TP
.I file   
.B mod
.B =
.R  	auxiliary input file name
.SH SOURCE
.I system/main/dottestmpi.c
.SH VERSION
4.2-git
