.TH sfdomf 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdomf \- 2D dip-oriented median/mean filter (DOMF). 
.SH SYNOPSIS
.B sfdomf < in.rsf > out.rsf dip=dip.rsf nw= boundary=y stack=n verb=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B boundary
.B =y
.R  [y/n]	if y, boundary is data, whereas zero
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I int    
.B nw
.B =
.R  	data-window length (positive and odd integer)
.TP
.I bool   
.B stack
.B =n
.R  [y/n]	if y, mean filter, whereas median filter
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/yliu/Mdomf.c
.SH VERSION
4.2-git
