.TH sfdonut 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdonut \- Donut filter 
.SH SYNOPSIS
.B sfdonut data=data.rsf < hole.rsf > filt.rsf adj=n na=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]
.TP
.I file   
.B data
.B =
.R  	auxiliary input file name
.TP
.I int    
.B na
.B =
.R  
.SH SOURCE
.I user/fomels/Mdonut.c
.SH VERSION
4.2-git
