.TH sfdpeiko 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdpeiko \- 2-D eikonal solver based on dynamic programming. 
.SH SYNOPSIS
.B sfdpeiko < vel.rsf > ttime.rsf ishot=(n1-1)/2
.SH PARAMETERS
.PD 0
.TP
.I int    
.B ishot
.B =(n1-1)/2
.R  	shot location
.SH SOURCE
.I user/fomels/Mdpeiko.c
.SH VERSION
4.2-git
