.TH sfdrays 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdrays \- 2D dynamic ray tracing by a Runge-Kutta integrator. 
.SH SYNOPSIS
.B sfdrays < vel.rsf > gbeam.rsf shotfile=shots.rsf anglefile=angles.rsf rays=rays.rsf dmat=dmat.rsf proj=proj.rsf mask=mask.rsf vel=y order=4 nt= dt= verb=y shift=0.5 zshot=0. yshot=o[1]+0.5*(n[1]-1)*d[1] nr= a0=0. amax=360.
.SH COMMENTS
Angle is 90 deg along y-axis and 180 deg along z-axis, clockwise.

.SH PARAMETERS
.PD 0
.TP
.I float  
.B a0
.B =0.
.R  	minimum angle (if no anglefile)
.TP
.I float  
.B amax
.B =360.
.R  	maximum angle (if no anglefile)
.TP
.I string 
.B anglefile
.B =
.R  	file with initial angles [nr,nshot] (auxiliary input file name)
.TP
.I string 
.B dmat
.B =
.R  	auxiliary output file name
.TP
.I float  
.B dt
.B =
.R  	Sampling in time
.TP
.I string 
.B mask
.B =
.R  	auxiliary output file name
.TP
.I int    
.B nr
.B =
.R  	number of angles (if no anglefile)
.TP
.I int    
.B nt
.B =
.R  	Number of time steps
.TP
.I int    
.B order
.B =4
.R  	Interpolation order
.TP
.I string 
.B proj
.B =
.R  	auxiliary output file name
.TP
.I string 
.B rays
.B =
.R  	auxiliary output file name
.TP
.I float  
.B shift
.B =0.5
.R  	Complex source shift
.TP
.I string 
.B shotfile
.B =
.R  	file with shot locations [zshot,yshot,nshot] (auxiliary input file name)
.TP
.I bool   
.B vel
.B =y
.R  [y/n]	If y, input is velocity; if n, slowness
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	Verbosity flag
.TP
.I float  
.B yshot
.B =o[1]+0.5*(n[1]-1)*d[1]
.R  
.TP
.I float  
.B zshot
.B =0.
.R  
.SH SOURCE
.I user/llisiw/Mdrays.c
.SH VERSION
4.2-git
