.TH sfdsrtomo0 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdsrtomo0 \- Prestack first-arrival traveltime tomography (DSR) 
.SH SYNOPSIS
.B sfdsrtomo0 < in.rsf > out.rsf reco=reco.rsf mask=mask.rsf prec=prec.rsf grad=grad.rsf velocity=y limit=n shape=n verb=n niter=5 cgiter=10 thres=5.e-5 tol=1.e-3 nloop=10 eps=0. causal=y rect#=(1,1,...)
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B causal
.B =y
.R  [y/n]	if y, neglect non-causal branches of DSR
.TP
.I int    
.B cgiter
.B =10
.R  	number of conjugate-gradient iterations
.TP
.I float  
.B eps
.B =0.
.R  	regularization parameter
.TP
.I string 
.B grad
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B limit
.B =n
.R  [y/n]	if y, limit computation within receiver coverage
.TP
.I string 
.B mask
.B =
.R  	auxiliary input file name
.TP
.I int    
.B niter
.B =5
.R  	number of inversion iterations
.TP
.I int    
.B nloop
.B =10
.R  	number of bisection root-search
.TP
.I string 
.B prec
.B =
.R  	auxiliary input file name
.TP
.I string 
.B reco
.B =
.R  	auxiliary input file name
.TP
.I int    
.B rect#
.B =(1,1,...)
.R  	smoothing radius on #-th axis
.TP
.I bool   
.B shape
.B =n
.R  [y/n]	shaping regularization (default no)
.TP
.I float  
.B thres
.B =5.e-5
.R  	threshold (percentage)
.TP
.I float  
.B tol
.B =1.e-3
.R  	tolerance for bisection root-search
.TP
.I bool   
.B velocity
.B =y
.R  [y/n]	if y, the input is velocity; n, slowness-squared
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/llisiw/Mdsrtomo0.c
.SH VERSION
4.2-git
