.TH sfdsreiko 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdsreiko \- Double square-root eikonal solver (2D) 
.SH SYNOPSIS
.B sfdsreiko < in.rsf > out.rsf mask=mask.rsf flag=flag.rsf alpha=alpha.rsf velocity=y thres=5.e-5 tol=1.e-3 nloop=10 causal=y
.SH PARAMETERS
.PD 0
.TP
.I string 
.B alpha
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B causal
.B =y
.R  [y/n]	if y, neglect non-causal branches of DSR
.TP
.I string 
.B flag
.B =
.R  	auxiliary output file name
.TP
.I string 
.B mask
.B =
.R  	auxiliary input file name
.TP
.I int    
.B nloop
.B =10
.R  	number of bisection root-search
.TP
.I float  
.B thres
.B =5.e-5
.R  	threshold (percentage)
.TP
.I float  
.B tol
.B =1.e-3
.R  	tolerance for bisection root-search
.TP
.I bool   
.B velocity
.B =y
.R  [y/n]	if y, the input is velocity; n, slowness squared
.SH SOURCE
.I user/llisiw/Mdsreiko.c
.SH VERSION
4.2-git
