.TH sfdsreiko0 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdsreiko0 \- Double square-root eikonal solver (2D + explicit) 
.SH SYNOPSIS
.B sfdsreiko0 < in.rsf > out.rsf velocity=y
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B velocity
.B =y
.R  [y/n]	if y, the input is velocity; n, slowness squared
.SH SOURCE
.I user/llisiw/Mdsreiko0.c
.SH VERSION
4.2-git
