.TH sfdtw-interp 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdtw-interp \- 
.SH SYNOPSIS
.B sfdtw-interp < _in.rsf loc=_loc.rsf > _out.rsf maxshift= exp=2 strain=1.0 n=
.SH COMMENTS
program takes traces sampled at arbitrary locations along a 1d line 
and outputs regularly sampled line.
program assumes the locations are ordered.

.SH PARAMETERS
.PD 0
.TP
.I float  
.B exp
.B =2
.R  	error exponent (g-f)^exp
.TP
.I string 
.B loc
.B =
.R  	auxiliary input file name
.TP
.I int    
.B maxshift
.B =
.R  	maximum shift to be tested
.TP
.I int    
.B n
.B =
.R  	number of traces in output
.TP
.I float  
.B strain
.B =1.0
.R  	maximum strain for dtw
.SH SOURCE
.I user/luke/Mdtw-interp.c
.SH VERSION
4.2-git
