.TH sfdtw 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdtw \- 
.SH SYNOPSIS
.B sfdtw < _in.rsf ref=_ref.rsf > _out.rsf error=_error.rsf accum=_accum.rsf shifts=_shifts.rsf maxshift= exp=2 strain=1.0
.SH COMMENTS
program calculates the shifts to warp a matching trace (input) 
to a reference trace (ref=) of equal length and applies those shifts 

.SH PARAMETERS
.PD 0
.TP
.I string 
.B accum
.B =
.R  	accumulation errors from forward and backtracking (auxiliary output file name)
.TP
.I string 
.B error
.B =
.R  	misfit error (auxiliary output file name)
.TP
.I float  
.B exp
.B =2
.R  	error exponent (g-f)^exp
.TP
.I int    
.B maxshift
.B =
.R  
.TP
.I string 
.B ref
.B =
.R  	auxiliary input file name
.TP
.I string 
.B shifts
.B =
.R  	output integer shifts as floats (auxiliary output file name)
.TP
.I float  
.B strain
.B =1.0
.R  	maximum strain
.SH SOURCE
.I user/luke/Mdtw.c
.SH VERSION
4.2-git
