.TH sfdtw-track 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdtw-track \- 
.SH SYNOPSIS
.B sfdtw-track < _in.rsf error=_miss.rsf > _out.rsf strain=1
.SH COMMENTS
problem finds the optimal trajectory 
across accumulation errors using backtracking.  
takes the same strain strain= as the accumulation step.

.SH PARAMETERS
.PD 0
.TP
.I string 
.B error
.B =
.R  	auxiliary input file name
.TP
.I float  
.B strain
.B =1
.R  	maximum strain
.SH SOURCE
.I user/luke/Mdtw-track.c
.SH VERSION
4.2-git
