.TH sfdtw-accumulate 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdtw-accumulate \- 
.SH SYNOPSIS
.B sfdtw-accumulate < _in.rsf > _out.rsf strain=1 dir=0
.SH COMMENTS
accumulates or smooths alignment errors in the 
forward direction, subject to 
strain str=float is the maximum du/di

.SH PARAMETERS
.PD 0
.TP
.I int    
.B dir
.B =0
.R  	accumulation direction: 1 is forward, -1 is backward, 0 is both
.TP
.I float  
.B strain
.B =1
.R  	maximum strain
.SH SOURCE
.I user/luke/Mdtw-accumulate.c
.SH VERSION
4.2-git
