.TH sfdtw-flatten 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdtw-flatten \- flattens a gather or similar object to its stack using dtw, optionally writes out shifts, currently set up for (time,gather,space) for 2d imaging
.SH SYNOPSIS
.B sfdtw-flatten < _in.rsf > _out.rsf shifts=_shifts.rsf exp=2 strain=1.0 maxshift=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B exp
.B =2
.R  	error exponent (g-f)^exp
.TP
.I int    
.B maxshift
.B =
.R  
.TP
.I string 
.B shifts
.B =
.R  	output gather flattening shifts (auxiliary output file name)
.TP
.I float  
.B strain
.B =1.0
.R  	maximum strain
.SH SOURCE
.I user/luke/Mdtw-flatten.c
.SH VERSION
4.2-git
