.TH sfdtw-apply 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdtw-apply \- 
.SH SYNOPSIS
.B sfdtw-apply < _in.rsf shifts=_shifts.rsf > _out.rsf
.SH COMMENTS
program applies integer shifts (stored as floats!) to warp a matching trace.  Can match 1d shifts to a 1,2, or 3d volume , or 2d shifts to a 2, or 3 d volume, or 3d shifts to a 3d volume 

.SH PARAMETERS
.PD 0
.TP
.I string 
.B shifts
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/luke/Mdtw-apply.c
.SH VERSION
4.2-git
