.TH sfdtw-errors 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdtw-errors \- 
.SH SYNOPSIS
.B sfdtw-errors < _in.rsf ref=_ref.rsf > _out.rsf maxshift= exp=2
.SH COMMENTS
program calculates the alignment errors 
between a reference and matching trace 
given a maximum shift (maxshift=) and an error exponent (exp=)

.SH PARAMETERS
.PD 0
.TP
.I float  
.B exp
.B =2
.R  	error exponent (g-f)^exp
.TP
.I int    
.B maxshift
.B =
.R  	maximum shift
.TP
.I string 
.B ref
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/luke/Mdtw-errors.c
.SH VERSION
4.2-git
