.TH sfdvscan2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfdvscan2d \- Diffraction velocity analysis
.SH SYNOPSIS
.B sfdvscan2d < dataFile_.rsf vel=velFile_.rsf > sembFile_.rsf gn=1 go=1.0 gd=1 coher=11 cigNum=1 dlim=fabs (dipStart_) isSemb=y
.SH COMMENTS

Input:
dataFile_.rsf - migrated dip-angle gathers

Output:
sembFile_.rsf - semblance spectrum

.SH PARAMETERS
.PD 0
.TP
.I int    
.B cigNum
.B =1
.R  	height of a vertical window for semblance calculation
.TP
.I int    
.B coher
.B =11
.R  	height of a vertical window for semblance calculation
.TP
.I float  
.B dlim
.B =fabs (dipStart_)
.R  	defines dip-angle-window for the analysis
.TP
.I float  
.B gd
.B =1
.R  	increment of Vm/V parameter
.TP
.I int    
.B gn
.B =1
.R  	number of scanned Vm/V values
.TP
.I float  
.B go
.B =1.0
.R  	start of Vm/V parameter
.TP
.I bool   
.B isSemb
.B =y
.R  [y/n]	y - output is semblance; n - stack power
.TP
.I string 
.B vel
.B =
.R  	velocity model file (velocity in km/s) (auxiliary input file name)
.SH SOURCE
.I user/aklokov/Mdvscan2d.c
.SH VERSION
4.2-git
