.TH sfederiv3dfilters 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfederiv3dfilters \- 
.SH SYNOPSIS
.B sfederiv3dfilters ccc=Fccc.rsf < Fspk.rsf pzdel=Fpzdel.rsf pxdel=Fpxdel.rsf pydel=Fpydel.rsf hzdel=Fhzdel.rsf hxdel=Fhxdel.rsf hydel=Fhydel.rsf vzdel=Fvzdel.rsf vxdel=Fvxdel.rsf vydel=Fvydel.rsf verb=n stat=y domain=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B ccc
.B =
.R  	auxiliary input file name
.TP
.I string 
.B domain
.B =
.R  
.TP
.I file   
.B hxdel
.B =
.R  	auxiliary output file name
.TP
.I file   
.B hydel
.B =
.R  	auxiliary output file name
.TP
.I file   
.B hzdel
.B =
.R  	auxiliary output file name
.TP
.I file   
.B pxdel
.B =
.R  	auxiliary output file name
.TP
.I file   
.B pydel
.B =
.R  	auxiliary output file name
.TP
.I file   
.B pzdel
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B stat
.B =y
.R  [y/n]	stationary operator
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I file   
.B vxdel
.B =
.R  	auxiliary output file name
.TP
.I file   
.B vydel
.B =
.R  	auxiliary output file name
.TP
.I file   
.B vzdel
.B =
.R  	auxiliary output file name
.SH USED IN
.TP
.I cwp/geo2009TTIModeSeparation/vti3
.SH SOURCE
.I user/jyan/Mederiv3dfilters.c
.SH VERSION
4.2-git
