.TH sfederiv2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfederiv2d \- 
.SH SYNOPSIS
.B sfederiv2d ccc=Fccc.rsf < Fspk.rsf zdel=Fzdel.rsf xdel=Fxdel.rsf verb=n stat=y sig=1.5 order=8 domain= tapertype=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B ccc
.B =
.R  	auxiliary input file name
.TP
.I string 
.B domain
.B =
.R  
.TP
.I int    
.B order
.B =8
.R  	order
.TP
.I float  
.B sig
.B =1.5
.R  	sigma
.TP
.I bool   
.B stat
.B =y
.R  [y/n]	stationary operator
.TP
.I string 
.B tapertype
.B =
.R  
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I file   
.B xdel
.B =
.R  	auxiliary output file name
.TP
.I file   
.B zdel
.B =
.R  	auxiliary output file name
.SH USED IN
.TP
.I cwp/geo2009TTIModeSeparation/fold
.TP
.I cwp/geo2009TTIModeSeparation/marmousi2
.TP
.I cwp/geo2009TTIModeSeparation/operator
.TP
.I cwp/geo2009VTIModeSeparation/aniopsize
.TP
.I cwp/geo2009VTIModeSeparation/oporder
.TP
.I cwp/geo2009VTIModeSeparation/separate2
.TP
.I cwp/geo2009VTIModeSeparation/separate3
.TP
.I cwp/geo2009VTIModeSeparation/separate5
.TP
.I cwp/geo2009VTIModeSeparation/sigsbee
.SH SOURCE
.I user/jyan/Mederiv2d.c
.SH VERSION
4.2-git
