.TH sfemfdm3d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfemfdm3d \- 3D Electromagnetic time-domain FD modeling
.SH SYNOPSIS
.B sfemfdm3d < Fwav.rsf sou=Fsou.rsf rec=Frec.rsf wfl=Fwfl.rsf > Fdat.rsf mag=Fmag.rsf ele=Fele.rsf cdt=Fcdt.rsf verb=n snap=n free=n expl=n dabc=n jdata=1 jsnap=nt nqz=sf_n(az) nqx=sf_n(ax) nqy=sf_n(ay) oqz=sf_o(az) oqx=sf_o(ax) oqy=sf_o(ay) dqz=sf_d(az) dqx=sf_d(ax) dqy=sf_d(ay) nb=2
.SH COMMENTS

4th order in space, 2nd order in time. Absorbing boundary conditions. 
.SH PARAMETERS
.PD 0
.TP
.I file   
.B cdt
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B dabc
.B =n
.R  [y/n]	Absorbing BC
.TP
.I float  
.B dqx
.B =sf_d(ax)
.R  	Saved wfld window dx
.TP
.I float  
.B dqy
.B =sf_d(ay)
.R  	Saved wfld window dy
.TP
.I float  
.B dqz
.B =sf_d(az)
.R  	Saved wfld window dz
.TP
.I file   
.B ele
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B expl
.B =n
.R  [y/n]	Multiple sources, one wvlt
.TP
.I bool   
.B free
.B =n
.R  [y/n]	Free surface flag
.TP
.I int    
.B jdata
.B =1
.R  	# of t steps at which to save receiver data
.TP
.I int    
.B jsnap
.B =nt
.R  	# of t steps at which to save wavefield
.TP
.I file   
.B mag
.B =
.R  	auxiliary input file name
.TP
.I int    
.B nb
.B =2
.R  	boundary padding in grid points
.TP
.I int    
.B nqx
.B =sf_n(ax)
.R  	Saved wfld window nx
.TP
.I int    
.B nqy
.B =sf_n(ay)
.R  	Saved wfld window ny
.TP
.I int    
.B nqz
.B =sf_n(az)
.R  	Saved wfld window nz
.TP
.I float  
.B oqx
.B =sf_o(ax)
.R  	Saved wfld window ox
.TP
.I float  
.B oqy
.B =sf_o(ay)
.R  	Saved wfld window oy
.TP
.I float  
.B oqz
.B =sf_o(az)
.R  	Saved wfld window oz
.TP
.I file   
.B rec
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B snap
.B =n
.R  [y/n]	Wavefield snapshots flag
.TP
.I file   
.B sou
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	Verbosity flag
.TP
.I file   
.B wfl
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/ditthara/Memfdm3d.c
.SH VERSION
4.2-git
