.TH sfeno2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfeno2 \- Convert velocity to slowness and compute gradient using ENO interpolation 
.SH SYNOPSIS
.B sfeno2 < vel.rsf > out.rsf order=3 is_inverse=1
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B is_inverse
.B =1
.R  [y/n]	make vel to slowness
.TP
.I int    
.B order
.B =3
.R  	interpolation order
.SH SOURCE
.I user/fomels/Meno2.c
.SH VERSION
4.2-git
