.TH sfencode 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfencode \- shot encoding with arbitrary delays 
.SH SYNOPSIS
.B sfencode < Fi.rsf del=Fd.rsf > Fo.rsf ompchunk=1 ompnth=0 verb=n
.SH PARAMETERS
.PD 0
.TP
.I file   
.B del
.B =
.R  	auxiliary input file name
.TP
.I int    
.B ompchunk
.B =1
.R  	OpenMP data chunk size
.TP
.I int    
.B ompnth
.B =0
.R  	OpenMP available threads
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/psava/Mencode.c
.SH VERSION
4.2-git
