.TH sfepfad 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfepfad \- ADaptive Eage Preserving Filter 
.SH SYNOPSIS
.B sfepfad < in.rsf > out.rsf rect1=0 rect2=0 rect3=0
.SH PARAMETERS
.PD 0
.TP
.I int    
.B rect1
.B =0
.R  
.TP
.I int    
.B rect2
.B =0
.R  
.TP
.I int    
.B rect3
.B =0
.R  	smoothing half window on the #-th dimension
.SH SOURCE
.I user/chen/Mepfad.c
.SH VERSION
4.2-git
