.TH sfepfbil 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfepfbil \- Bilateral filter 
.SH SYNOPSIS
.B sfepfbil < in.rsf > out.rsf twod=n sigmar=1.0 sigmad=1.0
.SH PARAMETERS
.PD 0
.TP
.I float  
.B sigmad
.B =1.0
.R  	sigma for domain filter
.TP
.I float  
.B sigmar
.B =1.0
.R  	sigma for range filter
.TP
.I bool   
.B twod
.B =n
.R  [y/n]	y, 2D smoothing
.SH SOURCE
.I user/chen/Mepfbil.c
.SH VERSION
4.2-git
