.TH sferf 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sferf \- Bandpass filtering using erf function. 
.SH SYNOPSIS
.B sferf < in.rsf > out.rsf flo=-1. fhi=-1. rect=1 spline=n der=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B der
.B =n
.R  [y/n]	compute derivative
.TP
.I float  
.B fhi
.B =-1.
.R  	high frequency in band
.TP
.I float  
.B flo
.B =-1.
.R  	low frequency in band
.TP
.I float  
.B rect
.B =1
.R  	filter sharpness
.TP
.I bool   
.B spline
.B =n
.R  [y/n]	if use B-spline erf
.SH SOURCE
.I user/fomels/Merf.c
.SH VERSION
4.2-git
