.TH sfesou 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfesou \- source for quasistatic electric potential 
.SH SYNOPSIS
.B sfesou < Fpre.rsf > Feso.rsf ske=Fske.rsf qke=Fqke.rsf verb=n zbnd=n
.SH PARAMETERS
.PD 0
.TP
.I file   
.B qke
.B =
.R  	auxiliary input file name
.TP
.I file   
.B ske
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I bool   
.B zbnd
.B =n
.R  [y/n]	boundary flag
.SH SOURCE
.I user/psava/Mesou.c
.SH VERSION
4.2-git
