.TH sfescst3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfescst3 \- Escape tables by stitching of escape solutions in supercells in 3-D. 
.SH SYNOPSIS
.B sfescst3 < spdom.rsf > out.rsf vspl=vspline.rsf scgrid=scgrid.rsf scdaemon=scdaemon.rsf na=360 nb=180 mp=1 nc=0 aper=SF_HUGE parab=y mmaped=y rfail=y verb=n morder=1 inet=1 tdel=0
.SH PARAMETERS
.PD 0
.TP
.I float  
.B aper
.B =SF_HUGE
.R  	Maximum aperture in x and y directions from current point (default - up to grid boundaries)
.TP
.I int    
.B inet
.B =1
.R  	Network interface index
.TP
.I bool   
.B mmaped
.B =y
.R  [y/n]	n - do not use memory mapping for local data access
.TP
.I int    
.B morder
.B =1
.R  	Order of interpolation accuracy in the angular domain (1-3)
.TP
.I int    
.B mp
.B =1
.R  	Bufferization factor for multicore processing (number of points in buffer = mp*nc)
.TP
.I int    
.B na
.B =360
.R  	Number of azimuth phase angles
.TP
.I int    
.B nb
.B =180
.R  	Number of inclination phase angles
.TP
.I int    
.B nc
.B =0
.R  	Number of threads to use for ray tracing (OMP_NUM_THREADS by default)
.TP
.I bool   
.B parab
.B =y
.R  [y/n]	y - use parabolic approximation of trajectories, n - straight line
.TP
.I bool   
.B rfail
.B =y
.R  [y/n]	n - do not quit if remote processing fails, try local processing
.TP
.I string 
.B scdaemon
.B =
.R  	Daemon for distributed computation (auxiliary input file name)
.TP
.I string 
.B scgrid
.B =
.R  	Grid of supercells of local escape solutions (auxiliary input file name)
.TP
.I int    
.B tdel
.B =0
.R  	Optional delay time before connecting (seconds)
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I string 
.B vspl
.B =
.R  	Spline coefficients for velocity model (auxiliary input file name)
.SH SOURCE
.I user/cram/Mescst3.c
.SH VERSION
4.2-git
