.TH sfescbsc3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfescbsc3 \- Prepare supercells for stitching escape tables in 3-D. 
.SH SYNOPSIS
.B sfescbsc3 < adom.rsf > out.rsf vspl=vspline.rsf verb=n nz= oz= dz= nx= ox= dx= ny= oy= dy= na= nb= df=0.1 nc=0 parab=y md=dz
.SH PARAMETERS
.PD 0
.TP
.I float  
.B df
.B =0.1
.R  	< Maximum distance to travel per step (fraction of the cell size) >
.TP
.I float  
.B dx
.B =
.R  	Sampling of x axis
.TP
.I float  
.B dy
.B =
.R  	Sampling of y axis
.TP
.I float  
.B dz
.B =
.R  	Sampling of z axis
.TP
.I float  
.B md
.B =dz
.R  	Half-width of a supercell
.TP
.I int    
.B na
.B =
.R  	Number of samples in azimuth dimension
.TP
.I int    
.B nb
.B =
.R  	Number of samples in inclination dimension
.TP
.I int    
.B nc
.B =0
.R  	Number of threads to use for ray tracing (OMP_NUM_THREADS by default)
.TP
.I int    
.B nx
.B =
.R  	Number of samples in x axis
.TP
.I int    
.B ny
.B =
.R  	Number of samples in y axis
.TP
.I int    
.B nz
.B =
.R  	Number of samples in z axis
.TP
.I float  
.B ox
.B =
.R  	Beginning of x axis
.TP
.I float  
.B oy
.B =
.R  	Beginning of y axis
.TP
.I float  
.B oz
.B =
.R  	Beginning of z axis
.TP
.I bool   
.B parab
.B =y
.R  [y/n]	y - use parabolic approximation of trajectories, n - straight line
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I string 
.B vspl
.B =
.R  	Spline coefficients for velocity model (auxiliary input file name)
.SH SOURCE
.I user/cram/Mescbsc3.c
.SH VERSION
4.2-git
