.TH sfescscd3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfescscd3 \- Daemon for distributed computation of stitched escape solutions in supercells in 3-D. 
.SH SYNOPSIS
.B sfescscd3 < in.rsf > out.rsf scgrid=scgrid.rsf nab=1 port=29542 ith=0 inet=1 ma=20 mb=20 nthreads=2*ncpu timeout=10 tdelay=0
.SH PARAMETERS
.PD 0
.TP
.I int    
.B inet
.B =1
.R  	Network interface index
.TP
.I int    
.B ith
.B =0
.R  	Make every ith process a daemon
.TP
.I int    
.B ma
.B =20
.R  	How many azimuth angles to expect per request
.TP
.I int    
.B mb
.B =20
.R  	How many inclination angles to expect per request
.TP
.I int    
.B nab
.B =1
.R  	Number of angular blocks to keep in memory per daemon
.TP
.I int    
.B nthreads
.B =2*ncpu
.R  	Number of threads (connections) per daemon
.TP
.I int    
.B port
.B =29542
.R  	TCP port for listening
.TP
.I string 
.B scgrid
.B =
.R  	Grid of supercells of local escape solutions (auxiliary input file name)
.TP
.I int    
.B tdelay
.B =0
.R  	Time delay before accessing data, tdel*icpu (secs)
.TP
.I int    
.B timeout
.B =10
.R  	Inactivity time before shutdown (mins)
.SH SOURCE
.I user/cram/Mescscd3.c
.SH VERSION
4.2-git
