.TH sfesctbl2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfesctbl2 \- Esctape tables from solution of escape equations by the hybrid solver with narrow band. 
.SH SYNOPSIS
.B sfesctbl2 < in.rsf > out.rsf verb=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/cram/Mesctbl2.c
.SH VERSION
4.2-git
