.TH sfewefd2d_gpu_dev 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfewefd2d_gpu_dev \- 2D elastic time-domain FD modeling with GPU (with experimental functionalities)
.SH SYNOPSIS
.B sfewefd2d_gpu_dev < Fwav.rsf ccc=Fccc.rsf den=Fden.rsf sou=Fsou.rsf rec=Frec.rsf wfl=Fwfl.rsf > Fdat.rsf um=Fum.rsf uo=Fuo.rsf verb=n snap=n free=n ssou=n dabc=n wavSrc=y gpu=0 nbell=5 jdata=1 jsnap=nt
.SH PARAMETERS
.PD 0
.TP
.I file   
.B ccc
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B dabc
.B =n
.R  [y/n]	absorbing BC
.TP
.I file   
.B den
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B free
.B =n
.R  [y/n]	free surface flag
.TP
.I int    
.B gpu
.B =0
.R  	ID of the GPU to be used
.TP
.I int    
.B jdata
.B =1
.R  	extract receiver data every jdata time steps
.TP
.I int    
.B jsnap
.B =nt
.R  	save wavefield every jsnap time steps
.TP
.I int    
.B nbell
.B =5
.R  	bell size
.TP
.I file   
.B rec
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B snap
.B =n
.R  [y/n]	wavefield snapshots flag
.TP
.I file   
.B sou
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B ssou
.B =n
.R  [y/n]	stress source
.TP
.I file   
.B um
.B =
.R  	auxiliary input file name
.TP
.I file   
.B uo
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I bool   
.B wavSrc
.B =y
.R  [y/n]	if yes, look for a source wavelet.  if no, look for initial displacement fields (uo and um)
.TP
.I file   
.B wfl
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/rweiss/Mewefd2d_gpu_dev.cu
.SH VERSION
4.2-git
