.TH sfewefd2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfewefd2d \- 2D elastic time-domain FD modeling 
.SH SYNOPSIS
.B sfewefd2d < Fwav.rsf ccc=Fccc.rsf den=Fden.rsf sou=Fsou.rsf rec=Frec.rsf > Fdat.rsf wfl=Fwfl.rsf verb=n snap=n free=n ssou=n dabc=n opot=n nbell=5 jdata=1 jsnap=nt nqz=sf_n(az) nqx=sf_n(ax) oqz=sf_o(az) oqx=sf_o(ax)
.SH PARAMETERS
.PD 0
.TP
.I file   
.B ccc
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B dabc
.B =n
.R  [y/n]	absorbing BC
.TP
.I file   
.B den
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B free
.B =n
.R  [y/n]	free surface flag
.TP
.I int    
.B jdata
.B =1
.R  
.TP
.I int    
.B jsnap
.B =nt
.R  
.TP
.I int    
.B nbell
.B =5
.R  	bell size
.TP
.I int    
.B nqx
.B =sf_n(ax)
.R  
.TP
.I int    
.B nqz
.B =sf_n(az)
.R  
.TP
.I bool   
.B opot
.B =n
.R  [y/n]	output potentials
.TP
.I float  
.B oqx
.B =sf_o(ax)
.R  
.TP
.I float  
.B oqz
.B =sf_o(az)
.R  
.TP
.I file   
.B rec
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B snap
.B =n
.R  [y/n]	wavefield snapshots flag
.TP
.I file   
.B sou
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B ssou
.B =n
.R  [y/n]	stress source
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I file   
.B wfl
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/psava/Mewefd2d.c
.SH VERSION
4.2-git
