.TH sfeweks3d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfeweks3d \- 3D elastic time-domain pseudo-spectral (k-space) modeling using shared-memory parallel FFT
.SH SYNOPSIS
.B sfeweks3d < Fwav.rsf ccc=Fccc.rsf den=Fden.rsf sou=Fsou.rsf rec=Frec.rsf wfl=Fwfl.rsf > Fdat.rsf verb=n snap=n free=n ssou=0 dabc=n opot=n back=n kspace=n nbell=5 jdata=1 jsnap=nt nqz=sf_n(az) nqx=sf_n(ax) nqy=sf_n(ay) oqz=sf_o(az) oqx=sf_o(ax) oqy=sf_o(ay)
.SH COMMENTS
sou wavelet  (nx,ny,nc,nt)
rec data     (nx,ny,nc,nt)
sou geometry (nc,nx,ny)
rec geometry (nc,nx,ny)

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B back
.B =n
.R  [y/n]	backward extrapolation flag (for rtm)
.TP
.I file   
.B ccc
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B dabc
.B =n
.R  [y/n]	absorbing BC
.TP
.I file   
.B den
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B free
.B =n
.R  [y/n]	free surface flag
.TP
.I int    
.B jdata
.B =1
.R  
.TP
.I int    
.B jsnap
.B =nt
.R  
.TP
.I bool   
.B kspace
.B =n
.R  [y/n]	k-space method (ps) flag
.TP
.I int    
.B nbell
.B =5
.R  	bell size
.TP
.I int    
.B nqx
.B =sf_n(ax)
.R  
.TP
.I int    
.B nqy
.B =sf_n(ay)
.R  
.TP
.I int    
.B nqz
.B =sf_n(az)
.R  
.TP
.I bool   
.B opot
.B =n
.R  [y/n]	output potentials -> 1*scalar, 3*vector potentials
.TP
.I float  
.B oqx
.B =sf_o(ax)
.R  
.TP
.I float  
.B oqy
.B =sf_o(ay)
.R  
.TP
.I float  
.B oqz
.B =sf_o(az)
.R  
.TP
.I file   
.B rec
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B snap
.B =n
.R  [y/n]	wavefield snapshots flag
.TP
.I file   
.B sou
.B =
.R  	auxiliary input file name
.TP
.I int    
.B ssou
.B =0
.R  	0 -> acceleration source; 1 -> stress source; 2 -> displacement source
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I file   
.B wfl
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/jsun/Meweks3d.c
.SH VERSION
4.2-git
