.TH sfewedc3dgrad 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfewedc3dgrad \- 3D elastic recursive integral time extrapolation of decomposed wave modes using KISS-FFT
.SH SYNOPSIS
.B sfewedc3dgrad < Fwav.rsf > Fdat.rsf sou=Fsou.rsf rec=Frec.rsf ccc=Fccc.rsf rkp=Frkp.rsf ltp=Fltp.rsf rtp=Frtp.rsf wfp=Fwfp.rsf rks=Frks.rsf lts=Flts.rsf rts=Frts.rsf wfs=Fwfs.rsf verb=n snap=n free=n back=n esou=n nbell=NOP jdata=1 jsnap=nt nb=NOP nqz=sf_n(az) nqx=sf_n(ax) nqy=sf_n(ay) oqz=sf_o(az) oqx=sf_o(ax) oqy=sf_o(ay)
.SH COMMENTS
sou wavelet  (nx,ny,nc,nt)
rec data     (nx,ny,nc,nt)
sou geometry (nc,nx,ny)
rec geometry (nc,nx,ny)

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B back
.B =n
.R  [y/n]	backward extrapolation flag (for rtm)
.TP
.I file   
.B ccc
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B esou
.B =n
.R  [y/n]	explosive force source
.TP
.I bool   
.B free
.B =n
.R  [y/n]	free surface flag
.TP
.I int    
.B jdata
.B =1
.R  
.TP
.I int    
.B jsnap
.B =nt
.R  
.TP
.I file   
.B ltp
.B =
.R  	auxiliary input file name
.TP
.I file   
.B lts
.B =
.R  	auxiliary input file name
.TP
.I int    
.B nb
.B =NOP
.R  
.TP
.I int    
.B nbell
.B =NOP
.R  	bell size
.TP
.I int    
.B nqx
.B =sf_n(ax)
.R  
.TP
.I int    
.B nqy
.B =sf_n(ay)
.R  
.TP
.I int    
.B nqz
.B =sf_n(az)
.R  
.TP
.I float  
.B oqx
.B =sf_o(ax)
.R  
.TP
.I float  
.B oqy
.B =sf_o(ay)
.R  
.TP
.I float  
.B oqz
.B =sf_o(az)
.R  
.TP
.I file   
.B rec
.B =
.R  	auxiliary input file name
.TP
.I file   
.B rkp
.B =
.R  	auxiliary input file name
.TP
.I file   
.B rks
.B =
.R  	auxiliary input file name
.TP
.I file   
.B rtp
.B =
.R  	auxiliary input file name
.TP
.I file   
.B rts
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B snap
.B =n
.R  [y/n]	wavefield snapshots flag
.TP
.I file   
.B sou
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I file   
.B wfp
.B =
.R  	auxiliary output file name
.TP
.I file   
.B wfs
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/jsun/Mewedc3dgrad.c
.SH VERSION
4.2-git
