.TH sfexpand 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfexpand \- Expand 2D data  
.SH SYNOPSIS
.B sfexpand > out.rsf < in.rsf left=0.5*nx right=0.5*nx top=0 bottom=0
.SH PARAMETERS
.PD 0
.TP
.I int    
.B bottom
.B =0
.R  
.TP
.I int    
.B left
.B =0.5*nx
.R  
.TP
.I int    
.B right
.B =0.5*nx
.R  
.TP
.I int    
.B top
.B =0
.R  
.SH SOURCE
.I user/fangg/Mexpand.c
.SH VERSION
4.2-git
