.TH sfexgr 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfexgr \- Exact group velocity in VTI media 
.SH SYNOPSIS
.B sfexgr > out.rsf aq=14.47 bq=2.28 cq=9.57 dq=4.51
.SH PARAMETERS
.PD 0
.TP
.I float  
.B aq
.B =14.47
.R  
.TP
.I float  
.B bq
.B =2.28
.R  
.TP
.I float  
.B cq
.B =9.57
.R  
.TP
.I float  
.B dq
.B =4.51
.R  
.SH SOURCE
.I user/fomels/Mexgr.c
.SH VERSION
4.2-git
