.TH sfexcitationic 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfexcitationic \- Demo for excitation imaging condition
.SH SYNOPSIS
.B sfexcitationic < Fv.rsf > Fout.rsf nb=20 nt= dt= fm=20.0 kt=300 jsx= jsz=0 jgx=1 jgz=0 sxbeg= szbeg= gxbeg= gzbeg= csdgather=y ns=1 ng=nx
.SH COMMENTS
Note that excitation imaging condition has some multipathing artifacts.
The significance of this imaging condition is the cheap computation and
low memory requirement. (1) Cheap computation: only 2 times of simulation,
one for source wavefield the other for receiver wavefield, are needed for 
single shot imaging before stacking. (2) Low memory request: this imaging 
condition only asks for the excitation time and the amplitude. Therefore,
it differs from cross-correlation imaging condition which needs storing 
or reconstructing the source wavefield to cross-correlate with receiver
wavefield at each time step.

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B csdgather
.B =y
.R  [y/n]
.TP
.I float  
.B dt
.B =
.R  	time sampling interval
.TP
.I float  
.B fm
.B =20.0
.R  	dominant freq of Ricker wavelet
.TP
.I int    
.B gxbeg
.B =
.R  	x-begining index of receivers, starting from 0
.TP
.I int    
.B gzbeg
.B =
.R  	z-begining index of receivers, starting from 0
.TP
.I int    
.B jgx
.B =1
.R  	receiver x-axis jump interval
.TP
.I int    
.B jgz
.B =0
.R  	receiver z-axis jump interval
.TP
.I int    
.B jsx
.B =
.R  	source x-axis  jump interval
.TP
.I int    
.B jsz
.B =0
.R  	source z-axis jump interval
.TP
.I int    
.B kt
.B =300
.R  	output wavefield at time kt
.TP
.I int    
.B nb
.B =20
.R  	thickness of sponge ABC
.TP
.I int    
.B ng
.B =nx
.R  	number of receivers
.TP
.I int    
.B ns
.B =1
.R  	number of shots
.TP
.I int    
.B nt
.B =
.R  	number of time steps
.TP
.I int    
.B sxbeg
.B =
.R  	x-begining index of sources, starting from 0
.TP
.I int    
.B szbeg
.B =
.R  	z-begining index of sources, starting from 0
.SH SOURCE
.I user/pyang/Mexcitationic.c
.SH VERSION
4.2-git
