.TH sfexpsignoi 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfexpsignoi \- Signal and noise separation using frequency components. 
.SH SYNOPSIS
.B sfexpsignoi < in.rsf freq=freq.rsf > out.rsf niter=50 eps=1. verb=n
.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =1.
.R  	regularization parameter
.TP
.I file   
.B freq
.B =
.R  	auxiliary input file name
.TP
.I int    
.B niter
.B =50
.R  	maximum number of iterations
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/pwd/Mexpsignoi.c
.SH VERSION
4.2-git
