.TH sfextend 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfextend \- 
.SH SYNOPSIS
.B sfextend < loga.rsf > log_eo.rsf < refa.rsf switch= val= reflog=
.SH COMMENTS
Dataset padding/clipping

Built for log data manipulation - Before and after LSIM alignments to deal with edge-effects and extraneous values introduced from LSIM shifting

.SH PARAMETERS
.PD 0
.TP
.I string 
.B reflog
.B =
.R  	Reference log (switch=3)
.TP
.I int    
.B switch
.B =
.R  	(0 = Two-sided axis extension by first and last non-zero sample in dataset); (2 = Two-sided axis reduction); (3 = Matches starting value and number of samples between input and reference well log); (else = pad data to dataset size by first and last nonzero sample); (4 = Testing)
.TP
.I int    
.B val
.B =
.R  	Sample manipulation (switch=0/2)
.SH SOURCE
.I user/sbader/Mextend.py
.SH VERSION
4.2-git
