.TH sffatomo 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffatomo \- First-arrival Traveltime Tomography 
.SH SYNOPSIS
.B sffatomo < sinp.rsf > sout.rsf time=time.rsf shot=shot.rsf receiver=rece.rsf record=reco.rsf topo=topo.rsf gradient=grad.rsf misnorm=norm.rsf adj=n velocity=y l1norm=n verb=n order=2 niter=10 stiter=200 eps=0. perc=90. nfreq=1 nmem=1 what=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag (for what=linear)
.TP
.I float  
.B eps
.B =0.
.R  	regularization parameter
.TP
.I string 
.B gradient
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B l1norm
.B =n
.R  [y/n]	norm for minimization (default L2 norm)
.TP
.I string 
.B misnorm
.B =
.R  	auxiliary output file name
.TP
.I int    
.B nfreq
.B =1
.R  	l1-norm weighting nfreq
.TP
.I int    
.B niter
.B =10
.R  	number of slowness inversion iterations
.TP
.I int    
.B nmem
.B =1
.R  	l1-norm weighting nmem
.TP
.I int    
.B order
.B =2
.R  	fast marching accuracy order
.TP
.I float  
.B perc
.B =90.
.R  
.TP
.I string 
.B receiver
.B =
.R  	auxiliary input file name
.TP
.I string 
.B record
.B =
.R  	auxiliary input file name
.TP
.I string 
.B shot
.B =
.R  	auxiliary input file name
.TP
.I int    
.B stiter
.B =200
.R  	number of step iterations
.TP
.I string 
.B time
.B =
.R  	auxiliary input file name
.TP
.I string 
.B topo
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B velocity
.B =y
.R  [y/n]	if y, the input is velocity; n, slowness squared
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I string 
.B what
.B =
.R  	what to compute (default tomography)
.SH SOURCE
.I user/llisiw/Mfatomo.c
.SH VERSION
4.2-git
