.TH sffastft 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffastft \- Fast Fourier Transform. 
.SH SYNOPSIS
.B sffastft < in.rsf > out.rsf inv=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B inv
.B =n
.R  [y/n]	if y, perform inverse transform
.SH SOURCE
.I user/mccowan/Mfastft.c
.SH VERSION
4.2-git
