.TH sffault 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffault \- fault detection  
.SH SYNOPSIS
.B sffault < in.rsf > out.rsf lamda=0.9 sigma=1.0
.SH PARAMETERS
.PD 0
.TP
.I float  
.B lamda
.B =0.9
.R  
.TP
.I float  
.B sigma
.B =1.0
.R  
.SH SOURCE
.I user/chen/Mfault.c
.SH VERSION
4.2-git
