.TH sffagrad 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffagrad \- Calculating frequency attenuation gradient. 
.SH SYNOPSIS
.B sffagrad < in.rsf > out.rsf grad=y lperc=65. hperc=85. freq= type=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B freq
.B =
.R  	Frequency corresponding to energy ratio, valid when type=ratio
.TP
.I bool   
.B grad
.B =y
.R  [y/n]	If y, output attenuation gradient; if n, output absorption factor
.TP
.I float  
.B hperc
.B =85.
.R  	High percentage of total energy
.TP
.I float  
.B lperc
.B =65.
.R  	Low percentage of total energy
.TP
.I string 
.B type
.B =
.R  	[low,full,ratio,attenuation] attribute type, the default is attenuation
.SH SOURCE
.I user/yliu/Mfagrad.c
.SH VERSION
4.2-git
