.TH sffbfreq 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffbfreq \- frequency response of linear phase filter bank 
.SH SYNOPSIS
.B sffbfreq > out.rsf m=1 n=1 n1=50 nd=1 interp=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B interp
.B =
.R  	interpolation method: maxflat lagrange bspline
.TP
.I int    
.B m
.B =1
.R  	b[-m, ... ,n]
.TP
.I int    
.B n
.B =1
.R  	b[-m, ... ,n]
.TP
.I int    
.B n1
.B =50
.R  	samples in frequency domain is 2*n1+1
.TP
.I int    
.B nd
.B =1
.R  	nd dimensional filter bank, nd should not be large, or you will need to buy a new disk array
.SH SOURCE
.I user/chen/Mfbfreq.c
.SH VERSION
4.2-git
