.TH sffbank1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffbank1 \- 1d filter bank  
.SH SYNOPSIS
.B sffbank1 < in.rsf > out.rsf m=1 n=1 interp=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B interp
.B =
.R  	interpolation method: maxflat lagrange bspline
.TP
.I int    
.B m
.B =1
.R  	b[-m, ... ,n]
.TP
.I int    
.B n
.B =1
.R  	b[-m, ... ,n]
.SH SOURCE
.I user/chen/Mfbank1.c
.SH VERSION
4.2-git
