.TH sffbpick 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffbpick \- First break picking from instantaneous traveltime attribute. 
.SH SYNOPSIS
.B sffbpick < in.rsf > out.rsf type=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B type
.B =
.R  	[traveltime,position] type, the default is traveltime
.SH SOURCE
.I user/yliu/Mfbpick.c
.SH VERSION
4.2-git
