.TH sffbrec2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffbrec2d \- 2-D forward modeling to generate shot records 
.SH SYNOPSIS
.B sffbrec2d < vinit.rsf > shots.rsf check1=check1.rsf check2=check2.rsf kt=100 amp=1. fm=10 dt= nt= ns= ng= jsx= jsz=0 jgx=1 jgz=0 sxbeg= szbeg= gxbeg= gzbeg= csdgather=n
.SH COMMENTS
Note: 	Clayton-Enquist absorbing boundary condition is applied!

.SH PARAMETERS
.PD 0
.TP
.I float  
.B amp
.B =1.
.R  	maximum amplitude of ricker
.TP
.I file   
.B check1
.B =
.R  	auxiliary output file name
.TP
.I file   
.B check2
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B csdgather
.B =n
.R  [y/n]	default, common shot-gather; if n, record at every point
.TP
.I float  
.B dt
.B =
.R  	time interval
.TP
.I float  
.B fm
.B =10
.R  	dominant freq of ricker
.TP
.I int    
.B gxbeg
.B =
.R  	x-begining index of receivers, starting from 0
.TP
.I int    
.B gzbeg
.B =
.R  	z-begining index of receivers, starting from 0
.TP
.I int    
.B jgx
.B =1
.R  	receiver x-axis jump interval
.TP
.I int    
.B jgz
.B =0
.R  	receiver z-axis jump interval
.TP
.I int    
.B jsx
.B =
.R  	source x-axis  jump interval
.TP
.I int    
.B jsz
.B =0
.R  	source z-axis jump interval
.TP
.I int    
.B kt
.B =100
.R  	check it at it=100
.TP
.I int    
.B ng
.B =
.R  	total receivers in each shot
.TP
.I int    
.B ns
.B =
.R  	total shots
.TP
.I int    
.B nt
.B =
.R  	total modeling time steps
.TP
.I int    
.B sxbeg
.B =
.R  	x-begining index of sources, starting from 0
.TP
.I int    
.B szbeg
.B =
.R  	z-begining index of sources, starting from 0
.SH SOURCE
.I user/pyang/Mfbrec2d.c
.SH VERSION
4.2-git
