.TH sffbpwd 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffbpwd \- omnidirectional plane-wave destruction  
.SH SYNOPSIS
.B sffbpwd < in.rsf > out.rsf dip=fp.rsf radius=1.0
.SH PARAMETERS
.PD 0
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I float  
.B radius
.B =1.0
.R  	interpolating radius for opwd
.SH SOURCE
.I user/chen/Mfbpwd.c
.SH VERSION
4.2-git
