.TH sffcoh1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffcoh1 \- Fast C1 Coherence 
.SH SYNOPSIS
.B sffcoh1 < in.rsf > out.rsf idip=idip.rsf xdip=xdip.rsf ntw=5 twod=y verb=y min1=-2 max1=2 min2=-2 max2=2
.SH PARAMETERS
.PD 0
.TP
.I string 
.B idip
.B =
.R  	inline dip (auxiliary output file name)
.TP
.I int    
.B max1
.B =2
.R  	inline slope
.TP
.I int    
.B max2
.B =2
.R  	xline slope
.TP
.I int    
.B min1
.B =-2
.R  
.TP
.I int    
.B min2
.B =-2
.R  
.TP
.I int    
.B ntw
.B =5
.R  	half window size for coherence
.TP
.I bool   
.B twod
.B =y
.R  [y/n]	y: only twod coherence
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity
.TP
.I string 
.B xdip
.B =
.R  	crossline dip (auxiliary output file name)
.SH SOURCE
.I user/chen/Mfcoh1.c
.SH VERSION
4.2-git
