.TH sffcoh2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffcoh2 \- Fast C2 Coherence 
.SH SYNOPSIS
.B sffcoh2 < in.rsf > out.rsf idip=idip.rsf ntw=5 nxw=5 twod=y verb=y min1=-2 max1=2 min2=-2 max2=2
.SH PARAMETERS
.PD 0
.TP
.I string 
.B idip
.B =
.R  	inline dip (auxiliary output file name)
.TP
.I int    
.B max1
.B =2
.R  	inline slope
.TP
.I int    
.B max2
.B =2
.R  	xline slope
.TP
.I int    
.B min1
.B =-2
.R  
.TP
.I int    
.B min2
.B =-2
.R  
.TP
.I int    
.B ntw
.B =5
.R  	half window size for time direction
.TP
.I int    
.B nxw
.B =5
.R  	half window size for x2
.TP
.I bool   
.B twod
.B =y
.R  [y/n]	y: only twod coherence
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity
.SH SOURCE
.I user/chen/Mfcoh2.c
.SH VERSION
4.2-git
