.TH sffdip 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffdip \- 3D fast dip estimation by plane wave destruction 
.SH SYNOPSIS
.B sffdip < in.rsf > out.rsf mask=mask.rsf n4=2 liter=20 rect1=1 rect2=1 rect3=1 verb=n
.SH PARAMETERS
.PD 0
.TP
.I int    
.B liter
.B =20
.R  	number of linear iterations
.TP
.I string 
.B mask
.B =
.R  	auxiliary input file name
.TP
.I int    
.B n4
.B =2
.R  	what to compute in 3-D. 0: in-line, 1: cross-line, 2: both
.TP
.I int    
.B rect1
.B =1
.R  	dip smoothness on 1st axis
.TP
.I int    
.B rect2
.B =1
.R  	dip smoothness on 2nd axis
.TP
.I int    
.B rect3
.B =1
.R  	dip smoothness on 3rd axuis
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH USED IN
.TP
.I data/alaska/line31-81-m8r
.SH SOURCE
.I user/pwd/Mfdip.c
.SH VERSION
4.2-git
