.TH sffd1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffd1 \- 1-D Optimized finite-difference wave extrapolation 
.SH SYNOPSIS
.B sffd1 < in.rsf vel=vel.rsf > out.rsf isx=(int)(nx/2) nt= dt=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dt
.B =
.R  
.TP
.I int    
.B isx
.B =(int)(nx/2)
.R  
.TP
.I int    
.B nt
.B =
.R  
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/songxl/Mfd1.c
.SH VERSION
4.2-git
