.TH sffd2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffd2d \- 2-D Fourth-order Finite-difference wave extrapolation with ABC 
.SH SYNOPSIS
.B sffd2d < Fw.rsf vel=Fv.rsf ref=Fr.rsf > Fo.rsf verb=0 nb=30 c=0.01
.SH PARAMETERS
.PD 0
.TP
.I float  
.B c
.B =0.01
.R  	decaying parameter
.TP
.I int    
.B nb
.B =30
.R  	boundary length
.TP
.I file   
.B ref
.B =
.R  	auxiliary input file name
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =0
.R  [y/n]	setup I/O files
.SH SOURCE
.I user/jsun/Mfd2d.c
.SH VERSION
4.2-git
