.TH sffdct 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffdct \- 
.SH SYNOPSIS
.B sffdct nbs=4 nba=8 ac=1 adj=n
.SH COMMENTS
Madagascar wrapper to the Fast Discrete Curvelet Transform (FDCT)

Requirements:
- Python API enable in Madagascar
- PyCurveLab (https://wave.eos.ubc.ca/Software/Licenced/)
- CurveLab (http://www.curvelet.org/)

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B ac
.B =1
.R  [y/n]	curvelets at finest scale
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint transform
.TP
.I int    
.B nba
.B =8
.R  	number of angle at the 2nd coarsest scale
.TP
.I int    
.B nbs
.B =4
.R  	number of scale for the decomposition
.SH SOURCE
.I user/slim/Mfdct.py
.SH VERSION
4.2-git
