.TH sffdb1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffdb1 \- 1-D Finite-difference wave extrapolation 
.SH SYNOPSIS
.B sffdb1 < in.rsf vel=vel.rsf > out.rsf dt= nt= nb=20 abc=0 order=2
.SH PARAMETERS
.PD 0
.TP
.I int    
.B abc
.B =0
.R  	absorbing boundary condition 1: cos 0: exp
.TP
.I float  
.B dt
.B =
.R  
.TP
.I int    
.B nb
.B =20
.R  
.TP
.I int    
.B nt
.B =
.R  
.TP
.I int    
.B order
.B =2
.R  	FD order: 2,4
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/songxl/Mfdb1.c
.SH VERSION
4.2-git
