.TH sffdac2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffdac2d \- None
.SH SYNOPSIS
.B sffdac2d slo=Fslo.rsf glo=Fglo.rsf vel=Fvel.rsf wavelet=Fwav.rsf frec=Frec.rsf verb=y npml= nthreads=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B frec
.B =
.R  	auxiliary output file name
.TP
.I file   
.B glo
.B =
.R  	auxiliary input file name
.TP
.I        
.B npml
.B =
.R  	Grid points for PML
.TP
.I        
.B nthreads
.B =
.R  	Threads for OMP
.TP
.I file   
.B slo
.B =
.R  	auxiliary input file name
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I        
.B verb
.B =y
.R  
.TP
.I file   
.B wavelet
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/zdzhang/Mfdac2d.f90
.SH VERSION
4.2-git
