.TH sffedchain2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffedchain2 \- Fast explicit diffusion as a chain (2-D) 
.SH SYNOPSIS
.B sffedchain2 < inp.rsf smooth=smo.rsf w=wht.rsf > out.rsf nc=1 rect=1 verb=y niter=0 liter=50
.SH PARAMETERS
.PD 0
.TP
.I int    
.B liter
.B =50
.R  	number of linear iterations
.TP
.I int    
.B nc
.B =1
.R  	number of components
.TP
.I int    
.B niter
.B =0
.R  	number of iterations
.TP
.I int    
.B rect
.B =1
.R  	smoothing radius
.TP
.I file   
.B smooth
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity flag
.TP
.I file   
.B w
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/fomels/Mfedchain2.c
.SH VERSION
4.2-git
