.TH sffedchain1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffedchain1 \- Fast explicit diffusion using chains - linear operator 
.SH SYNOPSIS
.B sffedchain1 < inp.rsf weight=wht.rsf sig=sig.rsf > out.rsf adj=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag
.TP
.I file   
.B sig
.B =
.R  	auxiliary input file name
.TP
.I file   
.B weight
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/fomels/Mfedchain1.c
.SH VERSION
4.2-git
