.TH sffftwave2omp 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffftwave2omp \- Simple 2-D wave propagation with multi-threaded Kiss-FFT 
.SH SYNOPSIS
.B sffftwave2omp < Fw.rsf > Fo.rsf ref=Fr.rsf snaps=snaps.rsf left=left.rsf right=right.rsf verb=n abc=n nbt= nbb=nbt nbl=nbt nbr=nbt ct= cb=ct cl=ct cr=ct snap=0 pad1=1
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B abc
.B =n
.R  [y/n]	absorbing flag
.TP
.I float  
.B cb
.B =ct
.R  
.TP
.I float  
.B cl
.B =ct
.R  
.TP
.I float  
.B cr
.B =ct
.R  
.TP
.I float  
.B ct
.B =
.R  
.TP
.I file   
.B left
.B =
.R  	auxiliary input file name
.TP
.I int    
.B nbb
.B =nbt
.R  
.TP
.I int    
.B nbl
.B =nbt
.R  
.TP
.I int    
.B nbr
.B =nbt
.R  
.TP
.I int    
.B nbt
.B =
.R  
.TP
.I int    
.B pad1
.B =1
.R  	padding factor on the first axis
.TP
.I file   
.B ref
.B =
.R  	auxiliary input file name
.TP
.I file   
.B right
.B =
.R  	auxiliary input file name
.TP
.I int    
.B snap
.B =0
.R  	interval for snapshots
.TP
.I file   
.B snaps
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.SH SOURCE
.I user/jsun/Mfftwave2omp.c
.SH VERSION
4.2-git
