.TH sffftone 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffftone \- Test 1-D Fourier transform. 
.SH SYNOPSIS
.B sffftone < freq.rsf > space.rsf inv=n n1=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B inv
.B =n
.R  [y/n]	inverse flag
.TP
.I int    
.B n1
.B =
.R  	dimension (for inv=y)
.SH SOURCE
.I user/fomels/Mfftone.c
.SH VERSION
4.2-git
