.TH sffftexp1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffftexp1 \- 2-D FFT-based prestack exploding reflector modeling/migration  
.SH SYNOPSIS
.B sffftexp1 < data.rsf > image.rsf left=left.rsf right=right.rsf mig=n snap=0 nz= dz= nt= dt= nh= dh= cmplx=n sub=y
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B cmplx
.B =n
.R  [y/n]	use complex FFT
.TP
.I float  
.B dh
.B =
.R  	offset sampling (if modeling)
.TP
.I float  
.B dt
.B =
.R  	time sampling (if modeling)
.TP
.I float  
.B dz
.B =
.R  	time sampling (if migration)
.TP
.I file   
.B left
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B mig
.B =n
.R  [y/n]	if n, modeling; if y, migration
.TP
.I int    
.B nh
.B =
.R  	offset samples (if modeling)
.TP
.I int    
.B nt
.B =
.R  	time samples (if modeling)
.TP
.I int    
.B nz
.B =
.R  	time samples (if migration)
.TP
.I file   
.B right
.B =
.R  	auxiliary input file name
.TP
.I int    
.B snap
.B =0
.R  	interval for snapshots
.TP
.I bool   
.B sub
.B =y
.R  [y/n]	if -1 is included in the matrix
.SH SOURCE
.I user/fomels/Mfftexp1.c
.SH VERSION
4.2-git
