.TH sffftexp0test 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffftexp0test \- 2-D FFT-based zero-offset exploding reflector modeling/migration (outputs time volume; can be used to generate movies) 
.SH SYNOPSIS
.B sffftexp0test movie=movie.rsf < data.rsf > image.rsf left=left.rsf right=right.rsf mig=n cmplx=n pad1=1 nz= dz= nt= dt= jt=1
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B cmplx
.B =n
.R  [y/n]	use complex FFT
.TP
.I float  
.B dt
.B =
.R  	time sampling (if modeling)
.TP
.I float  
.B dz
.B =
.R  	time sampling (if migration)
.TP
.I int    
.B jt
.B =1
.R  	time interval
.TP
.I file   
.B left
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B mig
.B =n
.R  [y/n]	if n, modeling; if y, migration
.TP
.I file   
.B movie
.B =
.R  	auxiliary output file name
.TP
.I int    
.B nt
.B =
.R  	time samples (if modeling)
.TP
.I int    
.B nz
.B =
.R  	time samples (if migration)
.TP
.I int    
.B pad1
.B =1
.R  	padding factor on the first axis
.TP
.I file   
.B right
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/jsun/Mfftexp0test.c
.SH VERSION
4.2-git
