.TH sfffdrtms 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfffdrtms \- 2-D FFD isotropic RTM: MPI + OMP
.SH SYNOPSIS
.B sfffdrtms geo=geo.rsf vel=vel.rsf source=source.rsf opt=y dt= nt= isz= irz=isz jr=1 jm=20 nr= nbt=44 nbb=44 nbl=44 nbr=44 ct=0.01 cb=0.01 cl=0.01 cr=0.01 sht=0 tskip=0 left=2400 right=800
.SH PARAMETERS
.PD 0
.TP
.I float  
.B cb
.B =0.01
.R  	decaying parameter
.TP
.I float  
.B cl
.B =0.01
.R  	decaying parameter
.TP
.I float  
.B cr
.B =0.01
.R  	decaying parameter
.TP
.I float  
.B ct
.B =0.01
.R  	decaying parameter
.TP
.I float  
.B dt
.B =
.R  	time step size
.TP
.I file   
.B geo
.B =
.R  	auxiliary input file name
.TP
.I int    
.B irz
.B =isz
.R  	receiver depth
.TP
.I int    
.B isz
.B =
.R  	source depth
.TP
.I int    
.B jm
.B =20
.R  	snap sampling
.TP
.I int    
.B jr
.B =1
.R  	receiver sampling
.TP
.I int    
.B left
.B =2400
.R  	left
.TP
.I int    
.B nbb
.B =44
.R  	boundary nodes
.TP
.I int    
.B nbl
.B =44
.R  	boundary nodes
.TP
.I int    
.B nbr
.B =44
.R  	boundary nodes
.TP
.I int    
.B nbt
.B =44
.R  	boundary nodes
.TP
.I int    
.B nr
.B =
.R  	streamer total length
.TP
.I int    
.B nt
.B =
.R  	total time length
.TP
.I bool   
.B opt
.B =y
.R  [y/n]	optimal padding
.TP
.I int    
.B right
.B =800
.R  	right
.TP
.I int    
.B sht
.B =0
.R  	Time shift parameter
.TP
.I file   
.B source
.B =
.R  	auxiliary input file name
.TP
.I int    
.B tskip
.B =0
.R  	Time shift parameter
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/songxl/Mffdrtms.c
.SH VERSION
4.2-git
