.TH sffftexp0 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffftexp0 \- 2-D FFT-based zero-offset exploding reflector modeling/migration  
.SH SYNOPSIS
.B sffftexp0 < data.rsf > image.rsf snaps=snaps.rsf left=left.rsf right=right.rsf mig=n cmplx=n pad1=1 trm=n nz= dz= nt= dt= t0=0.0f snap=0
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B cmplx
.B =n
.R  [y/n]	use complex FFT
.TP
.I float  
.B dt
.B =
.R  	time sampling (if modeling)
.TP
.I float  
.B dz
.B =
.R  	time sampling (if migration)
.TP
.I file   
.B left
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B mig
.B =n
.R  [y/n]	if n, modeling; if y, migration
.TP
.I int    
.B nt
.B =
.R  	time samples (if modeling)
.TP
.I int    
.B nz
.B =
.R  	time samples (if migration)
.TP
.I int    
.B pad1
.B =1
.R  	padding factor on the first axis
.TP
.I file   
.B right
.B =
.R  	auxiliary input file name
.TP
.I int    
.B snap
.B =0
.R  	interval for snapshots
.TP
.I file   
.B snaps
.B =
.R  	auxiliary output file name
.TP
.I float  
.B t0
.B =0.0f
.R  	time origin (if modeling)
.TP
.I bool   
.B trm
.B =n
.R  [y/n]	time-reversal imaging
.SH SOURCE
.I user/fomels/Mfftexp0.c
.SH VERSION
4.2-git
