.TH sffftexp3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffftexp3 \- 3-D FFT-based zero-offset exploding reflector modeling/migration  
.SH SYNOPSIS
.B sffftexp3 < data.rsf > image.rsf left=left.rsf right=right.rsf mig=n ompchunk=1 nz= dz= nt= dt=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dt
.B =
.R  	time sampling (if modeling)
.TP
.I float  
.B dz
.B =
.R  	time sampling (if migration)
.TP
.I file   
.B left
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B mig
.B =n
.R  [y/n]	if n, modeling; if y, migration
.TP
.I int    
.B nt
.B =
.R  	time samples (if modeling)
.TP
.I int    
.B nz
.B =
.R  	time samples (if migration)
.TP
.I int    
.B ompchunk
.B =1
.R  	OpenMP data chunk size
.TP
.I file   
.B right
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/fomels/Mfftexp3.c
.SH VERSION
4.2-git
