.TH sffftfwi_sparse_2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffftfwi_sparse_2d \- 2D frequency domain full waveform inversion with sparsity regularization. 
.SH SYNOPSIS
.B sffftfwi_sparse_2d < in.rsf > out.rsf receiver=receiver.rsf source=source.rsf record=record.rsf dip=dip.rsf vout=vout.rsf misfit=misfit.rsf sparsity=y niter=10 npml=20 par=1 pclip=8. uts=0 order= type=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B dip
.B =
.R  	auxiliary input file name
.TP
.I string 
.B misfit
.B =
.R  	auxiliary output file name
.TP
.I int    
.B niter
.B =10
.R  	number of iteration
.TP
.I int    
.B npml
.B =20
.R  	PML width
.TP
.I string 
.B order
.B =
.R  	discretization scheme (default optimal 9-point)
.TP
.I int    
.B par
.B =1
.R  	seislet transform accuracy order
.TP
.I float  
.B pclip
.B =8.
.R  	soft thresholding parameter
.TP
.I string 
.B receiver
.B =
.R  	auxiliary input file name
.TP
.I string 
.B record
.B =
.R  	auxiliary input file name
.TP
.I string 
.B source
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B sparsity
.B =y
.R  [y/n]	if true, sparsity constriant; if false, normal FWI
.TP
.I string 
.B type
.B =
.R  	[haar,linear,biorthogonal] wavelet type, the default is biorthogonal
.TP
.I int    
.B uts
.B =0
.R  
.TP
.I string 
.B vout
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/zhiguang/Mfftfwi_sparse_2d.c
.SH VERSION
4.2-git
