.TH sffftwave1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffftwave1 \- 1-D FFT wave extrapolation 
.SH SYNOPSIS
.B sffftwave1 < inp.rsf > out.rsf prop=prop.rsf right=right.rsf nt= dt= sub=y step=y nsps=n
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dt
.B =
.R  
.TP
.I bool   
.B nsps
.B =n
.R  [y/n]	if using NSPS
.TP
.I int    
.B nt
.B =
.R  
.TP
.I file   
.B prop
.B =
.R  	auxiliary input file name
.TP
.I string 
.B right
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B step
.B =y
.R  [y/n]	if two-step propagation
.TP
.I bool   
.B sub
.B =y
.R  [y/n]	if -1 is included in the matrix
.SH SOURCE
.I user/fomels/Mfftwave1.c
.SH VERSION
4.2-git
