.TH sffindmax 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffindmax \- 
.SH SYNOPSIS
.B sffindmax < Fin.rsf > Fou.rsf verb=n
.SH COMMENTS
find max value in a file

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/psava/Mfindmax.py
.SH VERSION
4.2-git
