.TH sffindmin2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffindmin2 \- Find minimum in 2-D 
.SH SYNOPSIS
.B sffindmin2 < inp.rsf > out.rsf gate1=3 gate2=3
.SH PARAMETERS
.PD 0
.TP
.I int    
.B gate1
.B =3
.R  
.TP
.I int    
.B gate2
.B =3
.R  	picking gate
.SH SOURCE
.I user/fomels/Mfindmin2.c
.SH VERSION
4.2-git
