.TH sffindwellcoord 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffindwellcoord \- Find well location by using well coordinates. 
.SH SYNOPSIS
.B sffindwellcoord xcoord=xcoord.rsf ycoord=ycoord.rsf wellx= welly=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B wellx
.B =
.R  	X coordinate for well
.TP
.I float  
.B welly
.B =
.R  	Y coordinate for well
.TP
.I file   
.B xcoord
.B =
.R  	auxiliary input file name
.TP
.I file   
.B ycoord
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/yliu/Mfindwellcoord.c
.SH VERSION
4.2-git
