.TH sffileflush 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffileflush \- Creates just the ascii header from parameters
.SH SYNOPSIS
.B sffileflush < in.rsf > out.rsf
.SH COMMENTS
Wrapper for sf_fileflush (copy RSF header of a file to another) 
.SH SOURCE
.I user/ivlad/Mfileflush.c
.SH VERSION
4.2-git
