.TH sffindrefmax1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffindrefmax1 \- Find the sampled position of max value after reference point along fast dimension. 
.SH SYNOPSIS
.B sffindrefmax1 < inp.rsf > out.rsf max_val=max_val.rsf zeropo=zeropo.rsf verb=n
.SH PARAMETERS
.PD 0
.TP
.I string 
.B max_val
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]
.TP
.I string 
.B zeropo
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/yliu/Mfindrefmax1.c
.SH VERSION
4.2-git
