.TH sffileheader 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffileheader \- dumps header information to the standard output.
.SH SYNOPSIS
.B sffileheader < in.rsf large=n parform=y all=n
.SH COMMENTS
Extended sffiledims.
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B all
.B =n
.R  [y/n]	If y, print all values, icluding singleton dimensions.
       If n, drop trailing singleteon dimensions.
.TP
.I bool   
.B large
.B =n
.R  [y/n]	if y, file with large dimensions.
.TP
.I bool   
.B parform
.B =y
.R  [y/n]	If y, print out parameter=value. If n, print out value.
.SH SOURCE
.I user/slim/Mfileheader.c
.SH VERSION
4.2-git
