.TH sffindintval 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffindintval \- Find a certain integer value position in an array [n1]
.SH SYNOPSIS
.B sffindintval < in.rsf > out.rsf val= val2=val type=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B type
.B =
.R  	type of comparison eq (=) leq (<=) geq(>=)
.TP
.I int    
.B val
.B =
.R  
.TP
.I int    
.B val2
.B =val
.R  
.SH SOURCE
.I user/lcasasan/Mfindintval.c
.SH VERSION
4.2-git
