.TH sffir 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffir \- FIR filter 
.SH SYNOPSIS
.B sffir < in.rsf > out.rsf fir=fir.rsf axis=1
.SH PARAMETERS
.PD 0
.TP
.I int    
.B axis
.B =1
.R  	apply fir filter on which dimension
.TP
.I file   
.B fir
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/chen/Mfir.c
.SH VERSION
4.2-git
