.TH sffindzeroendt 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffindzeroendt \- Find the position of first non-zero value along time axis. 
.SH SYNOPSIS
.B sffindzeroendt < inp.rsf > out.rsf verb=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B verb
.B =n
.R  [y/n]
.SH SOURCE
.I user/yliu/Mfindzeroendt.c
.SH VERSION
4.2-git
