.TH sffindmax1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffindmax1 \- Find max value and its sampled position along fast dimension 
.SH SYNOPSIS
.B sffindmax1 < in.rsf > out.rsf max_val=max_val.rsf shift=0 verb=n
.SH PARAMETERS
.PD 0
.TP
.I string 
.B max_val
.B =
.R  	auxiliary output file name
.TP
.I int    
.B shift
.B =0
.R  	shift
.TP
.I bool   
.B verb
.B =n
.R  [y/n]
.SH SOURCE
.I user/lcasasan/Mfindmax1.c
.SH VERSION
4.2-git
