.TH sffkoclet 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffkoclet \- 1-D seislet transform using omega-wavenumber offset continuation 
.SH SYNOPSIS
.B sffkoclet < in.rsf > out.rsf inv=n adj=n dwt=n verb=y eps=0.01 type=
.SH COMMENTS
Forward transform (adj=n inv=y/n) m=T[d]
Inverse transform (adj=y inv=y)   d=T^(-1)[d]
Adjoint transform (adj=y inv=n)   d=T'[d]

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	if y, do adjoint transform
.TP
.I bool   
.B dwt
.B =n
.R  [y/n]	if y, do wavelet transform
.TP
.I float  
.B eps
.B =0.01
.R  	regularization
.TP
.I bool   
.B inv
.B =n
.R  [y/n]	if y, do inverse transform
.TP
.I string 
.B type
.B =
.R  	[haar,linear,biorthogonal] wavelet type, the default is biorthogonal
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/yliu/Mfkoclet.c
.SH VERSION
4.2-git
