.TH sffourmis2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffourmis2 \- Missing data interpolation in 2-D using Fourier transform and compressive sensing. 
.SH SYNOPSIS
.B sffourmis2 < in.rsf > out.rsf mask=mask.rsf res=res.rsf ref=ref.rsf niter=20 verb=n error=n cut=n f0=0. k0=0. parf=0. parw=0. orderf=1. orderw=1. perc=99. ordert=1. ordert=1. oper=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B cut
.B =n
.R  [y/n]	cutting verbosity flag, the default is soft-thresholding
.TP
.I bool   
.B error
.B =n
.R  [y/n]	error verbosity flag
.TP
.I float  
.B f0
.B =0.
.R  	initial cutting frequency
.TP
.I float  
.B k0
.B =0.
.R  	initial cutting wavenumber
.TP
.I string 
.B mask
.B =
.R  	auxiliary input file name
.TP
.I int    
.B niter
.B =20
.R  	number of iterations
.TP
.I string 
.B oper
.B =
.R  	[shaping,pocs,bregman] method, the default is shaping
.TP
.I float  
.B orderf
.B =1.
.R  	Curve order for frequency window, default is linear
.TP
.I float  
.B ordert
.B =1.
.R  	Curve order for thresholding parameter, default is linear
.TP
.I float  
.B orderw
.B =1.
.R  	Curve order for frequency window, default is linear
.TP
.I float  
.B parf
.B =0.
.R  	Ajustable parameter for frequency window, default is fixed window
.TP
.I float  
.B parw
.B =0.
.R  	Ajustable parameter for wavenumber window, default is fixed window
.TP
.I float  
.B perc
.B =99.
.R  	percentage for soft-thresholding
.TP
.I file   
.B ref
.B =
.R  	auxiliary input file name
.TP
.I string 
.B res
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/yliu/Mfourmis2.c
.SH VERSION
4.2-git
