.TH sffoldmap3D 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffoldmap3D \- 
.SH SYNOPSIS
.B sffoldmap3D < fIn.rsf > Fou.rsf verb=n topo= topoWl=
.SH COMMENTS
Create a foldmap from multiple orbit swaths
Created by: Dylan Hickson, Colorado School of Mines
Created on: Mar 9, 2022

.SH PARAMETERS
.PD 0
.TP
.I string 
.B topo
.B =
.R  
.TP
.I string 
.B topoWl
.B =
.R  
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/cwp/Mfoldmap3D.py
.SH VERSION
4.2-git
