.TH sffocus 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffocus \- Focusing indicator. 
.SH SYNOPSIS
.B sffocus < in.rsf > out.rsf dim= niter=100 verb=y rect#=(1,1,...)
.SH PARAMETERS
.PD 0
.TP
.I int    
.B dim
.B =
.R  	dimensionality
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I int    
.B rect#
.B =(1,1,...)
.R  	smoothing radius on #-th axis
.TP
.I bool   
.B verb
.B =y
.R  [y/n]
.SH SOURCE
.I user/fomels/Mfocus.c
.SH VERSION
4.2-git
