.TH sffpow 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffpow \- Time/frequency power estimation 
.SH SYNOPSIS
.B sffpow < inp.rsf > out.rsf beta=beta.rsf niter=10 fmin=o1 fmax=o1+(n1-1)*d1 bmin=-1.0 bmax=1.0 nb=10 tol=SF_EPS verb=y time=n
.SH PARAMETERS
.PD 0
.TP
.I file   
.B beta
.B =
.R  	auxiliary output file name
.TP
.I float  
.B bmax
.B =1.0
.R  	maximum value of beta
.TP
.I float  
.B bmin
.B =-1.0
.R  	minimum value of beta
.TP
.I float  
.B fmax
.B =o1+(n1-1)*d1
.R  	maximum frequency
.TP
.I float  
.B fmin
.B =o1
.R  	minimum frequency
.TP
.I int    
.B nb
.B =10
.R  
.TP
.I int    
.B niter
.B =10
.R  	number of Newton iterations
.TP
.I bool   
.B time
.B =n
.R  [y/n]	time axis
.TP
.I float  
.B tol
.B =SF_EPS
.R  	accuracy tolerance for beta
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/fomels/Mfpow.c
.SH VERSION
4.2-git
