.TH sffpca 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffpca \- Fast PCA by iterative algorithm
.SH SYNOPSIS
.B sffpca < pin.rsf > pout.rsf nc=1 niter=1 seed=2012
.SH PARAMETERS
.PD 0
.TP
.I int    
.B nc
.B =1
.R  	component number
.TP
.I int    
.B niter
.B =1
.R  	iterations for each component
.TP
.I int    
.B seed
.B =2012
.R  	seed for random number
.SH SOURCE
.I user/chen/Mfpca.py
.SH VERSION
4.2-git
