.TH sffreqest 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffreqest \- Local frequency estimation 
.SH SYNOPSIS
.B sffreqest < in.rsf > out.rsf niter=100 hertz=n rect1=1 rect2=1 ... 
.SH COMMENTS
rectN defines the size of the smoothing stencil in N-th dimension.

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B hertz
.B =n
.R  [y/n]	if y, convert output to Hertz
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.SH SOURCE
.I user/fomels/Mfreqest.c
.SH VERSION
4.2-git Menvelope.c 696 2004-07-06 23:17:31Z fomels
