.TH sfframe 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfframe \- Create a frame for binning.
.SH SYNOPSIS
.B sfframe < in.rsf > out.rsf xyz=xyzs.rsf base=0.
.SH PARAMETERS
.PD 0
.TP
.I float  
.B base
.B =0.
.R  	base to be subtracted from z
.TP
.I file   
.B xyz
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/gee/Mframe.c
.SH VERSION
4.2-git
