.TH sffshift 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffshift \- 
.SH SYNOPSIS
.B sffshift < Fin.rsf > Fou.rsf tt=Ftt.rsf verb=n
.SH COMMENTS
time shift in the frequency domain

.SH PARAMETERS
.PD 0
.TP
.I file   
.B tt
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/psava/Mfshift.py
.SH VERSION
4.2-git
