.TH sffwiupdate 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffwiupdate \- Update model with search direction and step length in FWI
.SH SYNOPSIS
.B sffwiupdate < in.rsf > out.rsf direction=dir.rsf alpha=alpha.rsf alpha0= max=0.
.SH PARAMETERS
.PD 0
.TP
.I string 
.B alpha
.B =
.R  	auxiliary input file name
.TP
.I float  
.B alpha0
.B =
.R  
.TP
.I file   
.B direction
.B =
.R  	auxiliary input file name
.TP
.I float  
.B max
.B =0.
.R  	if max=0, no normalization; if max!=0, normalization by alpha*max/dmax
.SH SOURCE
.I user/zhiguang/Mfwiupdate.c
.SH VERSION
4.2-git
