.TH sffwipe 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffwipe \- Phase encoding 
.SH SYNOPSIS
.B sffwipe < in.rsf > out.rsf oldrec=oldrec.rsf newrec=newrec.rsf encoding=y nsim=ns nsource=1 seed=time(NULL)
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B encoding
.B =y
.R  [y/n]
.TP
.I file   
.B newrec
.B =
.R  	auxiliary output file name
.TP
.I int    
.B nsim
.B =ns
.R  
.TP
.I int    
.B nsource
.B =1
.R  	check
.TP
.I file   
.B oldrec
.B =
.R  	auxiliary input file name
.TP
.I int    
.B seed
.B =time(NULL)
.R  
.SH SOURCE
.I user/zhiguang/Mfwipe.c
.SH VERSION
4.2-git
