.TH sffxyspfint3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffxyspfint3 \- 3D missing data interpolation using f-x-y streaming prediction filter. 
.SH SYNOPSIS
.B sffxyspfint3 < inp.rsf > out.rsf mask=msk.rsf verb=n ftype=1 lambdax= na1= na2=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B ftype
.B =1
.R  	default = 1,
       1 : causal filter design
       2 : noncausal filter design
.TP
.I float  
.B lambdax
.B =
.R  	lambdax.r
.TP
.I file   
.B mask
.B =
.R  	auxiliary input file name
.TP
.I int    
.B na1
.B =
.R  
.TP
.I int    
.B na2
.B =
.R  
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	default=false, verbosity flag
.SH SOURCE
.I user/yliu/Mfxyspfint3.c
.SH VERSION
4.2-git
