.TH sffxspfint2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffxspfint2 \- 2D missing data interpolation using f-x streaming prediction filter. 
.SH SYNOPSIS
.B sffxspfint2 < inp.rsf > out.rsf mask=msk.rsf verb=n ftype=1 lambda1= na=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B ftype
.B =1
.R  	default = 1,
       1 : causal filter design
       2 : noncausal filter design
.TP
.I float  
.B lambda1
.B =
.R  	lambda1.r
.TP
.I file   
.B mask
.B =
.R  	auxiliary input file name
.TP
.I int    
.B na
.B =
.R  
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	default=false, verbosity flag
.SH SOURCE
.I user/yliu/Mfxspfint2.c
.SH VERSION
4.2-git
