.TH sffxynpre2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffxynpre2 \- FXY non-stationary predictive filtering (with the option of local processing windows). 
.SH SYNOPSIS
.B sffxynpre2 < Fin.rsf > Fou.rsf verb=n sym=n opt=y fs=n Nfrac=6.0 Ntimes=5.0 pow=0.5 niter=100 n1win=n1 n2win=nx n3win=ny r1=0.5 r2=0.5 r3=0.5 mode=0 nsx=2 nsy=2 rect#= shift#=
.SH COMMENTS
with frequency-axis smoothness constraint
with frequency-dependent smoothing
with arbitrarily designed smoothing strategies (to enforce the a priori constraint)
Enhanced version of sffxynpre
Reference: Huang et al. (2021).

.SH PARAMETERS
.PD 0
.TP
.I float  
.B Nfrac
.B =6.0
.R  
.TP
.I float  
.B Ntimes
.B =5.0
.R  
.TP
.I bool   
.B fs
.B =n
.R  [y/n]	y, determine frequency-dependent smoothing
.TP
.I int    
.B mode
.B =0
.R  	predictive filtering mode; default: non-stationary
.TP
.I int    
.B n1win
.B =n1
.R  	first window length
.TP
.I int    
.B n2win
.B =nx
.R  	second window length
.TP
.I int    
.B n3win
.B =ny
.R  	second window length
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I int    
.B nsx
.B =2
.R  	number of shifts in non-causal prediction filtering
.TP
.I int    
.B nsy
.B =2
.R  	number of shifts in non-causal prediction filtering
.TP
.I bool   
.B opt
.B =y
.R  [y/n]	y, determine optimal size for efficiency
.TP
.I float  
.B pow
.B =0.5
.R  
.TP
.I float  
.B r1
.B =0.5
.R  	first overlapping ratio
.TP
.I float  
.B r2
.B =0.5
.R  	second overlapping ratio
.TP
.I float  
.B r3
.B =0.5
.R  	third overlapping ratio
.TP
.I string 
.B rect#
.B =
.R  	size of the smoothing stencil in #-th dimension /auxiliary input file/
.TP
.I string 
.B shift#
.B =
.R  	shifting of the smoothing stencil in #-th dimension /auxiliary input file/
.TP
.I bool   
.B sym
.B =n
.R  [y/n]	y, symmetric scaling for Hermitian FFT
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	Verbosity flag
.SH SOURCE
.I user/chenyk/Mfxynpre2.c
.SH VERSION
4.2-git
