.TH sffxspfdenoise2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sffxspfdenoise2 \- Random noise attenuation using 2D f-x streaming prediction filter. 
.SH SYNOPSIS
.B sffxspfdenoise2 < inp.rsf > out.rsf verb=n lambda1= lambda3= na1=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B lambda1
.B =
.R  	Regularization in x direction
.TP
.I float  
.B lambda3
.B =
.R  	Regularization in f direction
.TP
.I int    
.B na1
.B =
.R  	filter size in x direction
.TP
.I bool   
.B verb
.B =n
.R  [y/n]
.SH SOURCE
.I user/yliu/Mfxspfdenoise2.c
.SH VERSION
4.2-git
