.TH sfgettype 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfgettype \- Displays numerical type of a dataset
.SH SYNOPSIS
.B sfgettype < in.rsf
.SH COMMENTS
Output can be be: SF_CHAR, SF_COMPLEX, SF_FLOAT, SF_INT, SF_SHORT, SF_UCHAR
Shell/tester for sf_gettype
.SH SOURCE
.I user/ivlad/Mgettype.c
.SH VERSION
4.2-git
