.TH sfgenshots 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfgenshots \- Generate shots for FWI using Enquist absorbing boundary condition
.SH SYNOPSIS
.B sfgenshots < vinit.rsf > shots.rsf time=time.rsf check=check.rsf amp=1000 fm=10 dt= nt= ns= ng= jsx= jsz=0 jgx=1 jgz=0 sxbeg= szbeg= gxbeg= gzbeg= csdgather=n chk=n kt=100
.SH COMMENTS

Note: You can try other complex boundary condition but we do not
recommend to do so. The main reason is that FWI is to recover
the low-frequency information of the earth model. Low-freq 
means that exact absorbing is not necessarilly needed. The 
result will be improved with the optimization procedure. 
Furthermore, complex boundary condition (such as sponge ABC or
PML) implies more computational cost, which will degrade the
efficiency of FWI. 

.SH PARAMETERS
.PD 0
.TP
.I float  
.B amp
.B =1000
.R  	maximum amplitude of ricker
.TP
.I file   
.B check
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B chk
.B =n
.R  [y/n]	check whether GPU-CPU implementation coincide with each other or not
.TP
.I bool   
.B csdgather
.B =n
.R  [y/n]	default, common shot-gather; if n, record at every point
.TP
.I float  
.B dt
.B =
.R  	time interval
.TP
.I float  
.B fm
.B =10
.R  	dominant freq of ricker
.TP
.I int    
.B gxbeg
.B =
.R  	x-begining index of receivers, starting from 0
.TP
.I int    
.B gzbeg
.B =
.R  	z-begining index of receivers, starting from 0
.TP
.I int    
.B jgx
.B =1
.R  	receiver x-axis jump interval
.TP
.I int    
.B jgz
.B =0
.R  	receiver z-axis jump interval
.TP
.I int    
.B jsx
.B =
.R  	source x-axis  jump interval
.TP
.I int    
.B jsz
.B =0
.R  	source z-axis jump interval
.TP
.I int    
.B kt
.B =100
.R  	check it at it=100
.TP
.I int    
.B ng
.B =
.R  	total receivers in each shot
.TP
.I int    
.B ns
.B =
.R  	total shots
.TP
.I int    
.B nt
.B =
.R  	total modeling time steps
.TP
.I int    
.B sxbeg
.B =
.R  	x-begining index of sources, starting from 0
.TP
.I int    
.B szbeg
.B =
.R  	z-begining index of sources, starting from 0
.TP
.I file   
.B time
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/pyang/Mgenshots.cu
.SH VERSION
4.2-git
