.TH sfgeoconvert 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfgeoconvert \- 2-D regular geometry conversion 
.SH SYNOPSIS
.B sfgeoconvert < in.rsf > out.rsf ns= nr= ds=0.05 dr=0.025 os=0. or=0.
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dr
.B =0.025
.R  	receiver interval
.TP
.I float  
.B ds
.B =0.05
.R  	shot interval
.TP
.I int    
.B nr
.B =
.R  	receiver number per shot
.TP
.I int    
.B ns
.B =
.R  	shot number
.TP
.I float  
.B or
.B =0.
.R  	receiver origin
.TP
.I float  
.B os
.B =0.
.R  	shot origin
.SH SOURCE
.I user/yliu/Mgeoconvert.c
.SH VERSION
4.2-git
