.TH sfgpi3dzo 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfgpi3dzo \- Gaussian weighting for ZO 3D case
.SH SYNOPSIS
.B sfgpi3dzo < inp.rsf > out.rsf v_a= v_b= beta=0.0 eps=0.001
.SH PARAMETERS
.PD 0
.TP
.I float  
.B beta
.B =0.0
.R  
.TP
.I float  
.B eps
.B =0.001
.R  
.TP
.I float  
.B v_a
.B =
.R  
.TP
.I float  
.B v_b
.B =
.R  
.SH SOURCE
.I user/dmerzlikin/Mgpi3dzo.c
.SH VERSION
4.2-git
