.TH sfgpuktmig 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfgpuktmig \- Prestack time migration (2-D/3-D) with CUDA. 
.SH SYNOPSIS
.B sfgpuktmig < data.rsf > image.rsf vrms=vrms.rsf sxsy=sxsy.rsf gxgy=gxgy.rsf cxcy=cxcy.rsf verb=n time=n aa=y diff=y dbtr=-1 apx=onx/2 apy=ony/2 maxtri=13 trfact=4.0*(0.5*(odx + ody)/dt)
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B aa
.B =y
.R  [y/n]	Antialiaing flag
.TP
.I int    
.B apx
.B =onx/2
.R  	Apperture half-width in x direction
.TP
.I int    
.B apy
.B =ony/2
.R  	Apperture half-width in y direction
.TP
.I string 
.B cxcy
.B =
.R  	File with midpoint coordinates (auxiliary input file name)
.TP
.I int    
.B dbtr
.B =-1
.R  	Desired number of traces per block of threads
.TP
.I bool   
.B diff
.B =y
.R  [y/n]	Differentiation flag
.TP
.I string 
.B gxgy
.B =
.R  	File with receiver coordinates (auxiliary input file name)
.TP
.I int    
.B maxtri
.B =13
.R  	Maximum half-length of the antialias filter
.TP
.I string 
.B sxsy
.B =
.R  	File with shot coordinates (auxiliary input file name)
.TP
.I bool   
.B time
.B =n
.R  [y/n]	Total time measurement time
.TP
.I float  
.B trfact
.B =4.0*(0.5*(odx + ody)/dt)
.R  	Trace factor for antialias filter length calculation
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	Verbosity flag
.TP
.I string 
.B vrms
.B =
.R  	File with RMS velocities (auxiliary input file name)
.SH SOURCE
.I user/cuda/Mgpuktmig.cu
.SH VERSION
4.2-git
