.TH sfgrad3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfgrad3 \- 3-D smooth gradient. 
.SH SYNOPSIS
.B sfgrad3 < in.rsf > out.rsf dim=0
.SH PARAMETERS
.PD 0
.TP
.I int    
.B dim
.B =0
.R  	dimension of the gradient, 0 for gradient squared
.SH SOURCE
.I system/generic/Mgrad3.c
.SH VERSION
4.2-git
