.TH sfgradient 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfgradient \- Linearized complex eikonal equation 
.SH SYNOPSIS
.B sfgradient < vel.rsf > time.rsf s1=o[0] s2=o[1] s3=o[2] v0=1. b=0. s=0.
.SH PARAMETERS
.PD 0
.TP
.I float  
.B b
.B =0.
.R  
.TP
.I float  
.B s
.B =0.
.R  
.TP
.I float  
.B s1
.B =o[0]
.R  
.TP
.I float  
.B s2
.B =o[1]
.R  
.TP
.I float  
.B s3
.B =o[2]
.R  
.TP
.I float  
.B v0
.B =1.
.R  
.SH SOURCE
.I user/llisiw/Mgradient.c
.SH VERSION
4.2-git
