.TH sfgsray2rays2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfgsray2rays2d \- Oriented zero-offset migration. 
.SH SYNOPSIS
.B sfgsray2rays2d < time.rsf dept=dept.rsf ang=angl.rsf slow=slow.rsf slowz=slowz.rsf slowx=slowx.rsf ref3=fref3.rsf > imagt.rsf stride=1 tolz= tolx= tola= ref1= ref2=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B ang
.B =
.R  	auxiliary input file name
.TP
.I file   
.B dept
.B =
.R  	auxiliary input file name
.TP
.I string 
.B ref1
.B =
.R  
.TP
.I string 
.B ref2
.B =
.R  
.TP
.I string 
.B ref3
.B =
.R  	auxiliary input file name
.TP
.I file   
.B slow
.B =
.R  	auxiliary input file name
.TP
.I file   
.B slowx
.B =
.R  	auxiliary input file name
.TP
.I file   
.B slowz
.B =
.R  	auxiliary input file name
.TP
.I int    
.B stride
.B =1
.R  
.TP
.I float  
.B tola
.B =
.R  
.TP
.I float  
.B tolx
.B =
.R  
.TP
.I float  
.B tolz
.B =
.R  
.SH SOURCE
.I user/roman/Mgsray2rays2d.c
.SH VERSION
4.2-git
