.TH sfgsrayvti 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfgsrayvti \- Gauss Seidel iterative solver for phase space escape positions, angle and traveltime 
.SH SYNOPSIS
.B sfgsrayvti < in.rsf > out.rsf vel=slow.rsf velz=slowz.rsf velx=slowx.rsf iq= niter=50 tol=0.000002*nx*nz vti_eps=0.0 vti_gamma=0.0 vti_delta=0.0 vti=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B iq
.B =
.R  	switch for escape variable 0=x, 1=a, 2=t, 3=z, 4=l
.TP
.I int    
.B niter
.B =50
.R  	number of Gauss-Seidel iterations
.TP
.I float  
.B tol
.B =0.000002*nx*nz
.R  	accuracy tolerance
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I file   
.B velx
.B =
.R  	auxiliary input file name
.TP
.I file   
.B velz
.B =
.R  	auxiliary input file name
.TP
.I string 
.B vti
.B =
.R  	what to compute (p=qP, v=qSV, h=SH)
.TP
.I float  
.B vti_delta
.B =0.0
.R  	VTI constants Thomsen
.TP
.I float  
.B vti_eps
.B =0.0
.R  
.TP
.I float  
.B vti_gamma
.B =0.0
.R  
.SH SOURCE
.I user/roman/Mgsrayvti.c
.SH VERSION
4.2-git
