.TH sfgsray 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfgsray \- Gauss Seidel iterative solver for phase space escape positions, angle and traveltime 
.SH SYNOPSIS
.B sfgsray < in.rsf > out.rsf slow=slow.rsf slowz=slowz.rsf slowx=slowx.rsf dslow=dslow.rsf dtout=dtout.rsf iq= niter=50 liter=0 tol=0.000002*nx*nz order=1 verb=n sph=n
.SH PARAMETERS
.PD 0
.TP
.I string 
.B dslow
.B =
.R  	auxiliary input file name
.TP
.I file   
.B dtout
.B =
.R  	auxiliary output file name
.TP
.I int    
.B iq
.B =
.R  	switch for escape variable 0=x, 1=a, 2=t, 3=z, 4=l, 5=i
.TP
.I int    
.B liter
.B =0
.R  	number of first iterations with low-order scheme
.TP
.I int    
.B niter
.B =50
.R  	number of Gauss-Seidel iterations
.TP
.I int    
.B order
.B =1
.R  	order of upwind
.TP
.I file   
.B slow
.B =
.R  	auxiliary input file name
.TP
.I file   
.B slowx
.B =
.R  	auxiliary input file name
.TP
.I file   
.B slowz
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B sph
.B =n
.R  [y/n]	true - half-sphere, false - flat B.C. on left/right
.TP
.I float  
.B tol
.B =0.000002*nx*nz
.R  	accuracy tolerance
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/browaeys/Mgsray.c
.SH VERSION
4.2-git
