.TH sfhcascade 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfhcascade \- Multidimensional convolution cascade.
.SH SYNOPSIS
.B sfhcascade < in.rsf filt=filt.rsf > out.rsf n= rect=0 lag=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B filt
.B =
.R  	auxiliary input file name
.TP
.I string 
.B lag
.B =
.R  	file with filter lags
.TP
.I ints   
.B n
.B =
.R  	 [dim]
.TP
.I int    
.B rect
.B =0
.R  	smoothing radius
.SH SOURCE
.I user/gee/Mhcascade.c
.SH VERSION
4.2-git
