.TH sfhelmlu 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfhelmlu \- 2D Helmholtz solver by LU factorization. 
.SH SYNOPSIS
.B sfhelmlu < in.rsf > out.rsf source=source.rsf verb=n save=n load=n uts=0 hermite=n npml=10 order=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B hermite
.B =n
.R  [y/n]	Hermite operator
.TP
.I bool   
.B load
.B =n
.R  [y/n]	load LU
.TP
.I int    
.B npml
.B =10
.R  	PML width
.TP
.I string 
.B order
.B =
.R  	discretization scheme (default optimal 9-point)
.TP
.I bool   
.B save
.B =n
.R  [y/n]	save LU
.TP
.I string 
.B source
.B =
.R  	auxiliary input file name
.TP
.I int    
.B uts
.B =0
.R  	number of OMP threads
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/sparse/Mhelmlu.c
.SH VERSION
4.2-git
