.TH sfhelm2D_genrec 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfhelm2D_genrec \- Generate receiver file for Helmholtz solver. 
.SH SYNOPSIS
.B sfhelm2D_genrec > out.rsf n1=1 n2=1 d1=0.1 d2=0.1 recz= recx0= recdx=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B d1
.B =0.1
.R  
.TP
.I float  
.B d2
.B =0.1
.R  
.TP
.I int    
.B n1
.B =1
.R  
.TP
.I int    
.B n2
.B =1
.R  
.TP
.I int    
.B recdx
.B =
.R  
.TP
.I int    
.B recx0
.B =
.R  
.TP
.I int    
.B recz
.B =
.R  
.SH SOURCE
.I user/hzhu/Mhelm2D_genrec.c
.SH VERSION
4.2-git
