.TH sfheaderwindow 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfheaderwindow \- Window a dataset based on a header mask.
.SH SYNOPSIS
.B sfheaderwindow mask=head.rsf < in.rsf > out.rsf inv=n
.SH COMMENTS

The input data is a collection of traces n1xn2,
mask is an integer array os size n2, windowed is n1xm2,
where m2 is the number of nonzero elements in mask.

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B inv
.B =n
.R  [y/n]	inversion flag
.TP
.I file   
.B mask
.B =
.R  	auxiliary input file name
.SH USED IN
.TP
.I cwp/jse2006RWEImagingOverturningReflections/sigsbee
.TP
.I data/alaska/line31-81-m8r
.SH SOURCE
.I system/main/headerwindow.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfheaderwindow
.SH VERSION
4.2-git
