.TH sfheaderattr 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfheaderattr \- Display header attributes. 
.SH SYNOPSIS
.B sfheaderattr < head.rsf segy=y desc=n
.SH COMMENTS

Only nonzero values are reported.

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B desc
.B =n
.R  [y/n]	if describe keys
.TP
.I bool   
.B segy
.B =y
.R  [y/n]	if SEGY headers
.SH USED IN
.TP
.I data/boem-g3d1206-002a/displayin
.TP
.I data/bpmodel94/firstlook
.SH SOURCE
.I system/seismic/Mheaderattr.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfheaderattr
.SH VERSION
4.2-git
