.TH sfhelmmig 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfhelmmig \- 2D frequency-domain migration with space-lag imaging condition. 
.SH SYNOPSIS
.B sfhelmmig < in.rsf > out.rsf source=source.rsf data=data.rsf us=us.rsf ur=ur.rsf timg=timg.rsf verb=n save=n load=n uts=0 nh=0 npml=10 order=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B data
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B load
.B =n
.R  [y/n]	load LU
.TP
.I int    
.B nh
.B =0
.R  	horizontal space-lag
.TP
.I int    
.B npml
.B =10
.R  	PML width
.TP
.I string 
.B order
.B =
.R  	discretization scheme (default optimal 9-point)
.TP
.I bool   
.B save
.B =n
.R  [y/n]	save LU
.TP
.I string 
.B source
.B =
.R  	auxiliary input file name
.TP
.I string 
.B timg
.B =
.R  	auxiliary output file name
.TP
.I string 
.B ur
.B =
.R  	auxiliary output file name
.TP
.I string 
.B us
.B =
.R  	auxiliary output file name
.TP
.I int    
.B uts
.B =0
.R  	number of OMP threads
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/sparse/Mhelmmig.c
.SH VERSION
4.2-git
