.TH sfheadersort 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfheadersort \- Sort a dataset according to a header key. 
.SH SYNOPSIS
.B sfheadersort < in.rsf > out.rsf head=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B head
.B =
.R  	header file
.SH USED IN
.TP
.I bei/ft1/autocor
.SH SOURCE
.I system/main/headersort.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfheadersort
.SH VERSION
4.2-git
