.TH sfheat3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfheat3 \- Finite-difference 3-D heat-flow equation using helix 
.SH SYNOPSIS
.B sfheat3 > out.rsf n3=10 nh=5
.SH PARAMETERS
.PD 0
.TP
.I int    
.B n3
.B =10
.R  
.TP
.I int    
.B nh
.B =5
.R  
.SH SOURCE
.I user/gee/Mheat3.c
.SH VERSION
4.2-git
