.TH sfhilbert 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfhilbert \- Compute hilbert transform using different methods. 
.SH SYNOPSIS
.B sfhilbert < in.rsf > out.rsf order=100 ref=1. phase=90. type=
.SH COMMENTS
type=t -> time domain convolution
type=f -> frequency domain multiplication and use FFT
type=m -> closed-form design of maximally flat FIR hilbert transformer

.SH PARAMETERS
.PD 0
.TP
.I int    
.B order
.B =100
.R  	Hilbert transformer order if type=m
.TP
.I float  
.B phase
.B =90.
.R  	phase shift (in degrees)
.TP
.I float  
.B ref
.B =1.
.R  	Hilbert transformer reference (0.5 < ref <= 1) if type=m
.TP
.I string 
.B type
.B =
.R  	Choosing hilbert transform method, type=t means time domain, 
       type=f means freqency domain, type=m means using more robust algorithm
       the default is type=m
.SH SOURCE
.I user/chenyk/Mhilbert.c
.SH VERSION
4.2-git
