.TH sfhole 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfhole \- Cut an elliptic hole in data (for interpolation tests).
.SH SYNOPSIS
.B sfhole < in.rsf > out.rsf maskout=mask.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B maskout
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/gee/Mhole.c
.SH VERSION
4.2-git
