.TH sfhorwrite 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfhorwrite \- save rsf data into horizon ASCII format, eq to dd form=ascii 
.SH SYNOPSIS
.B sfhorwrite < in.rsf head= tail= fromat=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B fromat
.B =
.R  	format
.TP
.I string 
.B head
.B =
.R  	header
.TP
.I string 
.B tail
.B =
.R  	tail
.SH SOURCE
.I user/chen/Mhorwrite.c
.SH VERSION
4.2-git
