.TH sfhorizon 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfhorizon \- horizon extraction  
.SH SYNOPSIS
.B sfhorizon < in.rsf horizon=hor.rsf > out.rsf interp=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B horizon
.B =
.R  	auxiliary input file name
.TP
.I string 
.B interp
.B =
.R  	< interpolation method: nearest, linear >
.SH SOURCE
.I user/chen/Mhorizon.c
.SH VERSION
4.2-git
