.TH sfhv2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfhv2d \- Velocity with heterogeneity convert to dip. 
.SH SYNOPSIS
.B sfhv2d < in.rsf > out.rsf heterog=heterog.rsf n=32 d=12.5 o=0. mute=n half=n tp=0.150 t0=0. v0=10000 x0=0. abs=y inner=n hyper=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B abs
.B =y
.R  [y/n]	if y, use absolute value |x-x0| (available when mute=y)
.TP
.I float  
.B d
.B =12.5
.R  	offset interval
.TP
.I bool   
.B half
.B =n
.R  [y/n]	if y, half-offset instead of full offset
.TP
.I file   
.B heterog
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B hyper
.B =n
.R  [y/n]	if y, do hyperbolic mute (available when mute=y)
.TP
.I bool   
.B inner
.B =n
.R  [y/n]	if y, do inner muter (available when mute=y)
.TP
.I bool   
.B mute
.B =n
.R  [y/n]	if y, use mutter
.TP
.I int    
.B n
.B =32
.R  	offset number
.TP
.I float  
.B o
.B =0.
.R  	offset origin
.TP
.I float  
.B t0
.B =0.
.R  	starting time (available when mute=y)
.TP
.I float  
.B tp
.B =0.150
.R  	end time (available when mute=y)
.TP
.I float  
.B v0
.B =10000
.R  	velocity (available when mute=y)
.TP
.I float  
.B x0
.B =0.
.R  	starting space (available when mute=y)
.SH SOURCE
.I user/yliu/Mhv2d.c
.SH VERSION
4.2-git
