.TH sfic 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfic \- Imaging condition 
.SH SYNOPSIS
.B sfic < Fs.rsf ur=Fr.rsf > Fi.rsf ompchunk=1 verb=n nbuf=1 version=0 eps=1e-6
.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =1e-6
.R  	epsilon
.TP
.I int    
.B nbuf
.B =1
.R  	buffer size
.TP
.I int    
.B ompchunk
.B =1
.R  	OpenMP data chunk size
.TP
.I file   
.B ur
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I int    
.B version
.B =0
.R  	I.C. version (see paper)
.SH USED IN
.TP
.I cwp/geo2007StereographicImagingCondition/flat4
.TP
.I cwp/geo2007StereographicImagingCondition/gaus1
.SH SOURCE
.I user/psava/Mic.c
.SH VERSION
4.2-git
