.TH sfimray 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfimray \- 2-D image ray tracing using HWT 
.SH SYNOPSIS
.B sfimray < vel.rsf > dix.rsf nt= dt= order=3
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dt
.B =
.R  
.TP
.I int    
.B nt
.B =
.R  
.TP
.I int    
.B order
.B =3
.R  	interpolation order
.SH SOURCE
.I user/fomels/Mimray.c
.SH VERSION
4.2-git
