.TH sfimagsrc 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfimagsrc \- Convolution with a Ricker wavelet. 
.SH SYNOPSIS
.B sfimagsrc < in.rsf > out.rsf frequency= freq=0.2
.SH PARAMETERS
.PD 0
.TP
.I float  
.B freq
.B =0.2
.R  	peak frequency for Ricker wavelet (as fraction of Nyquist)
.TP
.I float  
.B frequency
.B =
.R  	peak frequency for Ricker wavelet (in Hz)
.SH SOURCE
.I user/jsun/Mimagsrc.c
.SH VERSION
4.2-git
