.TH sfinterpt 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfinterpt \- Multiple-arrival interpolation (yet another).
.SH SYNOPSIS
.B sfinterpt < in.rsf > out.rsf sx=0. sz=0. nw=4
.SH PARAMETERS
.PD 0
.TP
.I int    
.B nw
.B =4
.R  	Interpolation accuracy
.TP
.I float  
.B sx
.B =0.
.R  
.TP
.I float  
.B sz
.B =0.
.R  	Shot coordinate
.SH SOURCE
.I user/fomels/Minterpt.c
.SH VERSION
4.2-git
