.TH sfinvbin 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfinvbin \- Data interpolation in 2-D slices using helix preconditioning. 
.SH SYNOPSIS
.B sfinvbin < in.rsf > out.rsf filt=flt.rsf pch=pch.rsf n= xkey= ykey= xmax= xmin= ymax= ymin= x0=xmin y0=ymin nx=(int) (xmax - xmin + 1.) ny=(int) (ymax - ymin + 1.) dx= dy= interp=2 der=n stat=y niter=20 eps=0.01 head= lag= nh=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B der
.B =n
.R  [y/n]	if y, apply derivative filter on the residual
.TP
.I float  
.B dx
.B =
.R  	bin size in x
.TP
.I float  
.B dy
.B =
.R  	bin size in y
.TP
.I float  
.B eps
.B =0.01
.R  	regularization parameter
.TP
.I file   
.B filt
.B =
.R  	auxiliary input file name
.TP
.I string 
.B head
.B =
.R  
.TP
.I int    
.B interp
.B =2
.R  	interpolation length
.TP
.I string 
.B lag
.B =
.R  
.TP
.I ints   
.B n
.B =
.R  	 [2]
.TP
.I string 
.B nh
.B =
.R  
.TP
.I int    
.B niter
.B =20
.R  	number of iterations
.TP
.I int    
.B nx
.B =(int) (xmax - xmin + 1.)
.R  	Number of bins in x
.TP
.I int    
.B ny
.B =(int) (ymax - ymin + 1.)
.R  	Number of bins in y
.TP
.I file   
.B pch
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B stat
.B =y
.R  [y/n]	stationary or nonstationary filter
.TP
.I float  
.B x0
.B =xmin
.R  
.TP
.I int    
.B xkey
.B =
.R  	x key number
.TP
.I float  
.B xmax
.B =
.R  
.TP
.I float  
.B xmin
.B =
.R  
.TP
.I float  
.B y0
.B =ymin
.R  	grid origin
.TP
.I int    
.B ykey
.B =
.R  	y key number
.TP
.I float  
.B ymax
.B =
.R  
.TP
.I float  
.B ymin
.B =
.R  	Grid dimensions
.SH SOURCE
.I user/gee/Minvbin.c
.SH VERSION
4.2-git Mbin.c 991 2005-02-10 11:42:19Z fomels
