.TH sfinitial 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfinitial \- Initialize a data 
.SH SYNOPSIS
.B sfinitial < in.rsf > out.rsf sign=y
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B sign
.B =y
.R  [y/n]	if y, initialize data with "1", or with "0"
.SH SOURCE
.I user/yliu/Minitial.c
.SH VERSION
4.2-git
