.TH sfinmo3_ort 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfinmo3_ort \- 3-D Inverse normal moveout using orthogonal parametrization
.SH SYNOPSIS
.B sfinmo3_ort < cmp.rsf > nmod.rsf velocity=vel.rsf half=y eps=0.01 extend=8
.SH COMMENTS

velocity file contains slowness squared with n2=3 (Wavg,Wcos,Wsin)

.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =0.01
.R  	stretch regularization
.TP
.I int    
.B extend
.B =8
.R  	trace extension
.TP
.I bool   
.B half
.B =y
.R  [y/n]	if y, the second and third axes are half-offset instead of full offset
.TP
.I file   
.B velocity
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/jingwei/Minmo3_ort.c
.SH VERSION
4.2-git
