.TH sfinstsnr 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfinstsnr \- Instantaneous signal-to-noise ratio (SNR) estimation. 
.SH SYNOPSIS
.B sfinstsnr < in.rsf > out.rsf en=en.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B en
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/yliu/Minstsnr.c
.SH VERSION
4.2-git
