.TH sfinterp 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfinterp \- 
.SH SYNOPSIS
.B sfinterp < logrefa.rsf > logref_co.rsf
.SH COMMENTS
1D linear missing data interpolation

Linear interpolation of missing data (0 values) based on nearest nonzero samples

.SH SOURCE
.I user/sbader/Minterp.py
.SH VERSION
4.2-git
