.TH sfinitwave2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfinitwave2 \- Complex 2-D wave propagation using initial condition 
.SH SYNOPSIS
.B sfinitwave2 < Fi.rsf > Fo.rsf snaps=Fs.rsf left=left.rsf right=right.rsf verb=y nt= dt= snap=0 correct=n pad1=1 mode=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B correct
.B =n
.R  [y/n]	correction
.TP
.I float  
.B dt
.B =
.R  
.TP
.I file   
.B left
.B =
.R  	auxiliary input file name
.TP
.I string 
.B mode
.B =
.R  	default mode is pspi
.TP
.I int    
.B nt
.B =
.R  
.TP
.I int    
.B pad1
.B =1
.R  	padding factor on the first axis
.TP
.I file   
.B right
.B =
.R  	auxiliary input file name
.TP
.I int    
.B snap
.B =0
.R  	interval for snapshots
.TP
.I file   
.B snaps
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity
.SH SOURCE
.I user/jsun/Minitwave2.c
.SH VERSION
4.2-git
