.TH sfintbin4 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfintbin4 \- 5-D data binning. 
.SH SYNOPSIS
.B sfintbin4 < in.rsf > out.rsf xkey= ykey= skey= rkey= xmin= xmax= ymin= ymax= smin= smax= rmin= rmax= dx=1 dy=1 ds=1 dr=1 head= xk= yk= sk= rk= fold=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B dr
.B =1
.R  
.TP
.I int    
.B ds
.B =1
.R  
.TP
.I int    
.B dx
.B =1
.R  
.TP
.I int    
.B dy
.B =1
.R  
.TP
.I string 
.B fold
.B =
.R  	output fold file
.TP
.I string 
.B head
.B =
.R  	header file
.TP
.I string 
.B rk
.B =
.R  	r key name
.TP
.I int    
.B rkey
.B =
.R  	r key number (if no rk), default is gwdep
.TP
.I int    
.B rmax
.B =
.R  	r maximum
.TP
.I int    
.B rmin
.B =
.R  	r minimum
.TP
.I string 
.B sk
.B =
.R  	s key name
.TP
.I int    
.B skey
.B =
.R  	s key number (if no sk), default is swdep
.TP
.I int    
.B smax
.B =
.R  	s maximum
.TP
.I int    
.B smin
.B =
.R  	s minimum
.TP
.I string 
.B xk
.B =
.R  	x key name
.TP
.I int    
.B xkey
.B =
.R  	x key number (if no xk), default is fldr
.TP
.I int    
.B xmax
.B =
.R  	x maximum
.TP
.I int    
.B xmin
.B =
.R  	x minimum
.TP
.I string 
.B yk
.B =
.R  	y key name
.TP
.I int    
.B ykey
.B =
.R  	y key number (if no yk), default is tracf
.TP
.I int    
.B ymax
.B =
.R  	y maximum
.TP
.I int    
.B ymin
.B =
.R  	y minimum
.SH SOURCE
.I user/yliu/Mintbin4.c
.SH VERSION
4.2-git
