.TH sfisaac0 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfisaac0 \- Zero-offset bending ray tracing in one-layered media
.SH SYNOPSIS
.B sfisaac0 < refl.rsf > ttime.rsf xrefl=xrefl.rsf ns=nr ds=dr s0=r0 order=3 velocity=2.0 tol=0.0001/velocity
.SH PARAMETERS
.PD 0
.TP
.I float  
.B ds
.B =dr
.R  	source sampling
.TP
.I int    
.B ns
.B =nr
.R  	Number of sources
.TP
.I int    
.B order
.B =3
.R  	interpolation order
.TP
.I float  
.B s0
.B =r0
.R  	source origin
.TP
.I float  
.B tol
.B =0.0001/velocity
.R  	assign a default value for tolerance
.TP
.I float  
.B velocity
.B =2.0
.R  	assign velocity km/s
.TP
.I file   
.B xrefl
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/zone/Misaac0.c
.SH VERSION
4.2-git
