.TH sfistseislet 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfistseislet \- Analysis-based IST interpolation using seislet (2d validation)
.SH SYNOPSIS
.B sfistseislet < Fin.rsf mask=Fmask.rsf > Fout.rsf dip=Fdip.rsf eps=0.01 order=1 pscale=25 verb=n niter=10 pclip=99 p=0.35 type= mode=
.SH COMMENTS
IST=iterative shrinkage-thresholding

.SH PARAMETERS
.PD 0
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I float  
.B eps
.B =0.01
.R  	regularization
.TP
.I string 
.B mask
.B =
.R  	auxiliary input file name
.TP
.I string 
.B mode
.B =
.R  	thresholding mode: 'hard', 'soft','pthresh','exp';
       'hard', hard thresholding;	'soft', soft thresholding; 
       'pthresh', generalized quasi-p; 'exp', exponential shrinkage
.TP
.I int    
.B niter
.B =10
.R  	total number iterations
.TP
.I int    
.B order
.B =1
.R  	accuracy order for seislet transform
.TP
.I float  
.B p
.B =0.35
.R  	norm=p, where 0<p<=1
.TP
.I float  
.B pclip
.B =99
.R  	starting data clip percentile (default is 99)
.TP
.I float  
.B pscale
.B =25
.R  	percentile of small scale to be preserved (default is 25)
.TP
.I string 
.B type
.B =
.R  	[haar,linear,biorthogonal] wavelet type, the default is linear
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.SH SOURCE
.I user/pyang/Mistseislet.c
.SH VERSION
4.2-git
