.TH sfisin2ang 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfisin2ang \- inverse sin to angle transformation 
.SH SYNOPSIS
.B sfisin2ang < Fstk.rsf > Fang.rsf velocity=velocity.rsf na=nt da=90/(nt-1) a0=0. extend=4 top=n
.SH PARAMETERS
.PD 0
.TP
.I float  
.B a0
.B =0.
.R  	angle origin
.TP
.I float  
.B da
.B =90/(nt-1)
.R  	angle sampling
.TP
.I int    
.B extend
.B =4
.R  	tmp extension
.TP
.I int    
.B na
.B =nt
.R  	number of angles
.TP
.I bool   
.B top
.B =n
.R  [y/n]	velocity scaling option
.TP
.I file   
.B velocity
.B =
.R  	auxiliary input file name
.SH SOURCE
.I system/seismic/Misin2ang.c
.SH VERSION
4.2-git
