.TH sfistinterp 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfistinterp \- n-D IST interpolation using a generalized shrinkage operator
.SH SYNOPSIS
.B sfistinterp < in.rsf > out.rsf mask=Fmask.rsf verb=n niter=100 pclip=10. normp=0.9 n#= mode=
.SH COMMENTS
Note: Acquistion geometry specified by mask operator

.SH PARAMETERS
.PD 0
.TP
.I string 
.B mask
.B =
.R  	auxiliary input file name
.TP
.I string 
.B mode
.B =
.R  	thresholding mode: 'hard', 'soft','pthresh','exp';
       'hard', hard thresholding;	'soft', soft thresholding; 
       'pthresh', generalized quasi-p; 'exp', exponential shrinkage
.TP
.I int    
.B n#
.B =
.R  	size of #-th axis
.TP
.I int    
.B niter
.B =100
.R  	total number of iterations
.TP
.I float  
.B normp
.B =0.9
.R  	quasi-norm: normp<2
.TP
.I float  
.B pclip
.B =10.
.R  	starting data clip percentile (default is 10)
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.SH SOURCE
.I user/pyang/Mistinterp.c
.SH VERSION
4.2-git
