.TH sfisoimpulse 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfisoimpulse \- Impulse response for plane-wave migration in tilted coordinates 
.SH SYNOPSIS
.B sfisoimpulse wave=wave.rsf t=0.8 ep=0.4 dl=0.2 vti=y
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dl
.B =0.2
.R  
.TP
.I float  
.B ep
.B =0.4
.R  
.TP
.I float  
.B t
.B =0.8
.R  
.TP
.I bool   
.B vti
.B =y
.R  [y/n]
.TP
.I file   
.B wave
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/guojian/Misoimpulse.c
.SH VERSION
4.2-git
