.TH sfisaac3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfisaac3 \- 3D Bending ray tracing in Multi-layered media
.SH SYNOPSIS
.B sfisaac3 < refl.rsf > xrefl.rsf aniso=vti.rsf layer= velocity= xgradient= ygradient= zgradient= xref= yref= zref= xinitial= yinitial= xinitial= number= xs= ys= xr= yr= vstatus= order=3 xmin= ymin= xmax= ymax= niter= debug=n tol=0.000001/v_inp[0] ns=3  ns2=nr3+2 ds=1 s0=0 order=3
.SH PARAMETERS
.PD 0
.TP
.I file   
.B aniso
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B debug
.B =n
.R  [y/n]	Debug flag
.TP
.I float  
.B ds
.B =1
.R  	Step increment
.TP
.I floats 
.B layer
.B =
.R  	Layer sequence [nr3+1]
.TP
.I int    
.B niter
.B =
.R  	The number of iterations
.TP
.I int    
.B ns
.B =3 
.R  	Dimension of output reflection points (x,y,z)
.TP
.I int    
.B ns2
.B =nr3+2
.R  	Dimension of output reflection points (the number of points)
.TP
.I int    
.B number
.B =
.R  	Number of reflectors
.TP
.I int    
.B order
.B =3
.R  	Interpolation order
.TP
.I float  
.B s0
.B =0
.R  	Staring position
.TP
.I double 
.B tol
.B =0.000001/v_inp[0]
.R  	Assign a default value for tolerance
.TP
.I floats 
.B velocity
.B =
.R  	Assign velocity km/s [N-1]
.TP
.I int    
.B vstatus
.B =
.R  	Velocity status (0 for constant v, 1 for gradient v, and 2 for VTI)
.TP
.I floats 
.B xgradient
.B =
.R  	Assign x-gradient [N-1]
.TP
.I floats 
.B xinitial
.B =
.R  	 [nr3]
.TP
.I float  
.B xmax
.B =
.R  
.TP
.I float  
.B xmin
.B =
.R  
.TP
.I float  
.B xr
.B =
.R  	x-Receiver
.TP
.I floats 
.B xref
.B =
.R  	Assign x-reference point [N-1]
.TP
.I float  
.B xs
.B =
.R  	x-Source
.TP
.I floats 
.B ygradient
.B =
.R  	Assign y-gradient [N-1]
.TP
.I floats 
.B yinitial
.B =
.R  	 [nr3]
.TP
.I float  
.B ymax
.B =
.R  
.TP
.I float  
.B ymin
.B =
.R  
.TP
.I float  
.B yr
.B =
.R  	y-Receiver
.TP
.I floats 
.B yref
.B =
.R  	Assign y-reference point [N-1]
.TP
.I float  
.B ys
.B =
.R  	y-Source
.TP
.I floats 
.B zgradient
.B =
.R  	Assign z-gradient  [N-1]
.TP
.I floats 
.B zref
.B =
.R  	Assign z-reference point [N-1]
.SH SOURCE
.I user/zone/Misaac3.c
.SH VERSION
4.2-git
