.TH sfistpad 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfistpad \- n-D IST interpolation using a generalized shrinkage operator and zero-padding
.SH SYNOPSIS
.B sfistpad < in.rsf > out.rsf mask=Fmask.rsf pad= verb=n pow2=n niter=100 pclip=10. normp=1. n#= mode=
.SH COMMENTS
Note: Acquistion geometry specified by mask operator

.SH PARAMETERS
.PD 0
.TP
.I string 
.B mask
.B =
.R  	auxiliary input file name
.TP
.I string 
.B mode
.B =
.R  	thresholding mode: 'hard', 'soft','pthresh','exp';
       'hard', hard thresholding;	   'soft', soft thresholding; 
       'pthresh', generalized quasi-p;  'exp', exponential shrinkage
.TP
.I int    
.B n#
.B =
.R  	size of #-th axis
.TP
.I int    
.B niter
.B =100
.R  	total number of iterations
.TP
.I float  
.B normp
.B =1.
.R  	quasi-norm: normp<2
.TP
.I ints   
.B pad
.B =
.R  	number of zeros to be padded for each axis  [dim]
.TP
.I float  
.B pclip
.B =10.
.R  	starting data clip percentile (default is 10)
.TP
.I bool   
.B pow2
.B =n
.R  [y/n]	round up the length of each axis to be power of 2
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.SH SOURCE
.I user/pyang/Mistpad.c
.SH VERSION
4.2-git
