.TH sfisaac1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfisaac1 \- Pre-stack bending ray tracing in one-layered media
.SH SYNOPSIS
.B sfisaac1 < refl.rsf > ttime.rsf xrefl=xrefl.rsf ns=nr ns2=nr ds=dr ds2=dr s0=r0 s02=r0 type=1 order=4 velocity=2.0 tol=1/(1000000*velocity) break=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B break
.B =n
.R  [y/n]	Go beyond zero or not
.TP
.I float  
.B ds
.B =dr
.R  	source sampling for midpoint
.TP
.I float  
.B ds2
.B =dr
.R  	source sampling for offset
.TP
.I int    
.B ns
.B =nr
.R  	number of sources for midpoint
.TP
.I int    
.B ns2
.B =nr
.R  	number of sources for offset
.TP
.I int    
.B order
.B =4
.R  	Interpolation order if choose to use sf_eno
.TP
.I float  
.B s0
.B =r0
.R  	origin for midpoint
.TP
.I float  
.B s02
.B =r0
.R  	origin for offset
.TP
.I float  
.B tol
.B =1/(1000000*velocity)
.R  	Assign a default value for tolerance
.TP
.I int    
.B type
.B =1
.R  	Interpolation type 0=sf_eno and 1=central finite difference
.TP
.I float  
.B velocity
.B =2.0
.R  	Assign velocity km/s
.TP
.I file   
.B xrefl
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/zone/Misaac1.c
.SH VERSION
4.2-git
