.TH sfitaupmo2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfitaupmo2 \- Inverse normal moveout in tau-p-x domain. 
.SH SYNOPSIS
.B sfitaupmo2 < cmp.rsf velocity=velocity.rsf > nmod.rsf nx= dx= x0=0.0 nw=4
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dx
.B =
.R  	offset sampling
.TP
.I int    
.B nw
.B =4
.R  	interpolator size (2,3,4,6,8)
.TP
.I int    
.B nx
.B =
.R  	number of offsets
.TP
.I file   
.B velocity
.B =
.R  	auxiliary input file name
.TP
.I float  
.B x0
.B =0.0
.R  	first offset
.SH SOURCE
.I system/seismic/Mitaupmo2.c
.SH VERSION
4.2-git
