.TH sfitaupmo3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfitaupmo3 \- 3-D Inverse taup normal moveout.
.SH SYNOPSIS
.B sfitaupmo3 < cmp.rsf > nmod.rsf velocity=vel.rsf eps=0.01 slow=n interval=y extend=8
.SH COMMENTS

velocity file contains velocity squared with n2=3 (vx,vy,vxy)

.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =0.01
.R  	stretch regularization
.TP
.I int    
.B extend
.B =8
.R  	trace extension
.TP
.I bool   
.B interval
.B =y
.R  [y/n]	use interval velocity
.TP
.I bool   
.B slow
.B =n
.R  [y/n]	slowness [y] or velocity [n] squared
.TP
.I file   
.B velocity
.B =
.R  	auxiliary input file name
.SH SOURCE
.I system/seismic/Mitaupmo3.c
.SH VERSION
4.2-git
