.TH sfitrace 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfitrace \- 
.SH SYNOPSIS
.B sfitrace < xEscFile.rsf esct=tEscFile.rsf > xResFile.rsf zres=zResFile.rsf x0=0.f z0=0.f p0=0.f sa0=0.f dx=5*xStep dt=0.02f
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dt
.B =0.02f
.R  	time-range for point detection
.TP
.I float  
.B dx
.B =5*xStep
.R  	x-range for point detection
.TP
.I string 
.B esct
.B =
.R  	escape-time file (auxiliary input file name)
.TP
.I float  
.B p0
.B =0.f
.R  	migration angle
.TP
.I float  
.B sa0
.B =0.f
.R  	scattering-angle
.TP
.I float  
.B x0
.B =0.f
.R  	x-coordinate of the diffraction point
.TP
.I float  
.B z0
.B =0.f
.R  	z-coordinate of the diffraction point
.TP
.I string 
.B zres
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/aklokov/Mitrace.cc
.SH VERSION
4.2-git
