.TH sfiwiiter0 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfiwiiter0 \- Image-domain waveform tomography. 
.SH SYNOPSIS
.B sfiwiiter0 < in.rsf > out.rsf model=model.rsf us=us.rsf ur=ur.rsf weight=weight.rsf precon=precon.rsf miter=miter.rsf riter=riter.rsf verb=n nh=0 uts=0 npml=10 mass=n cgiter=10 shape=n reg=0. tol=1.e-6 rect1=1 rect2=1 order=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B cgiter
.B =10
.R  	number of conjugate-gradient iterations
.TP
.I bool   
.B mass
.B =n
.R  [y/n]	if y, use discretization-based mass term
.TP
.I string 
.B miter
.B =
.R  	auxiliary output file name
.TP
.I string 
.B model
.B =
.R  	auxiliary input file name
.TP
.I int    
.B nh
.B =0
.R  	horizontal space-lag
.TP
.I int    
.B npml
.B =10
.R  	PML width
.TP
.I string 
.B order
.B =
.R  	discretization scheme (default optimal 9-point)
.TP
.I string 
.B precon
.B =
.R  	auxiliary input file name
.TP
.I int    
.B rect1
.B =1
.R  	smoothing radius on axis 1
.TP
.I int    
.B rect2
.B =1
.R  	smoothing radius on axis 2
.TP
.I float  
.B reg
.B =0.
.R  	regularization parameter
.TP
.I file   
.B riter
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B shape
.B =n
.R  [y/n]	regularization (default Tikhnov)
.TP
.I float  
.B tol
.B =1.e-6
.R  	tolerance for shaping regularization
.TP
.I string 
.B ur
.B =
.R  	auxiliary input file name
.TP
.I string 
.B us
.B =
.R  	auxiliary input file name
.TP
.I int    
.B uts
.B =0
.R  	number of OMP threads
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I string 
.B weight
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/sparse/Miwiiter0.c
.SH VERSION
4.2-git
