.TH sfiwigrad 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfiwigrad \- Image-domain waveform tomography (gradient). 
.SH SYNOPSIS
.B sfiwigrad < in.rsf > out.rsf source=source.rsf data=data.rsf imask=imask.rsf weight=weight.rsf precon=precon.rsf verb=n nh=0 load=n update=y uts=0 npml=10 prect1=5 prect2=1 prect3=5 pliter=20 plower=0.1 pupper=3. dorder=6 grect1=5 grect2=5 gliter=1 geps=0. gscale=0.5 miter=10 lower=1.5 upper=7.5 order= cost=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B cost
.B =
.R  	cost functional type (default classic DSO)
.TP
.I string 
.B data
.B =
.R  	auxiliary input file name
.TP
.I int    
.B dorder
.B =6
.R  	image derivative accuracy order
.TP
.I float  
.B geps
.B =0.
.R  	regularization parameter for Gauss-Newton
.TP
.I int    
.B gliter
.B =1
.R  	# of Gauss-Newton iterations
.TP
.I int    
.B grect1
.B =5
.R  	gradient smoothing radius on axis 1
.TP
.I int    
.B grect2
.B =5
.R  	gradient smoothing radius on axis 2
.TP
.I float  
.B gscale
.B =0.5
.R  	gradient re-scale
.TP
.I string 
.B imask
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B load
.B =n
.R  [y/n]	load LU
.TP
.I float  
.B lower
.B =1.5
.R  	lower bound of feasible set
.TP
.I int    
.B miter
.B =10
.R  	Nonlinear-CG maximum # of iterations
.TP
.I int    
.B nh
.B =0
.R  	horizontal space-lag
.TP
.I int    
.B npml
.B =10
.R  	PML width
.TP
.I string 
.B order
.B =
.R  	discretization scheme (default optimal 9-point)
.TP
.I int    
.B pliter
.B =20
.R  	slope estimation # of linear iterations
.TP
.I float  
.B plower
.B =0.1
.R  	slope thresholding lower limit
.TP
.I string 
.B precon
.B =
.R  	auxiliary input file name
.TP
.I int    
.B prect1
.B =5
.R  	slope smoothing radius on axis 1
.TP
.I int    
.B prect2
.B =1
.R  	slope smoothing radius on axis 2
.TP
.I int    
.B prect3
.B =5
.R  	slope smoothing radius on axis 3
.TP
.I float  
.B pupper
.B =3.
.R  	slope thresholding upper limit
.TP
.I string 
.B source
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B update
.B =y
.R  [y/n]	Non-linear CG update
.TP
.I float  
.B upper
.B =7.5
.R  	upper bound of feasible set
.TP
.I int    
.B uts
.B =0
.R  	number of OMP threads
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I string 
.B weight
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/sparse/Miwigrad.c
.SH VERSION
4.2-git
