.TH sfjacobi2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfjacobi2 \- Find eigenvalues of a general complex matrix by Jacobi-like iteration. 
.SH SYNOPSIS
.B sfjacobi2 < mat.rsf > val.rsf niter=10 verb=n
.SH PARAMETERS
.PD 0
.TP
.I int    
.B niter
.B =10
.R  
.TP
.I bool   
.B verb
.B =n
.R  [y/n]
.SH SOURCE
.I system/generic/Mjacobi2.c
.SH VERSION
4.2-git
