.TH sfjitter 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfjitter \- 
.SH SYNOPSIS
.B sfjitter perc=.75 jit=1/(1-perc seed=np.random.randn(
.SH COMMENTS
Return mask to remove random traces in 2D using jittered sampling

.SH PARAMETERS
.PD 0
.TP
.I float  
.B jit
.B =1/(1-perc
.R  
.TP
.I float  
.B perc
.B =.75
.R  	percentage of traces to remove
.TP
.I int    
.B seed
.B =np.random.randn(
.R  
.SH SOURCE
.I user/slim/Mjitter.py
.SH VERSION
4.2-git
