.TH sfjoiner 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfjoiner \- Join two selected points along the first dimension 
.SH SYNOPSIS
.B sfjoiner < in.rsf index=index_FILE.rsf > out.rsf nw=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B index
.B =
.R  	auxiliary input file name
.TP
.I int    
.B nw
.B =
.R  	length of joining window
.SH SOURCE
.I user/lcasasan/Mjoiner.c
.SH VERSION
4.2-git
