.TH sfkarman 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfkarman \- Estimation of von Karman autocorrelation 1D spectrum. 
.SH SYNOPSIS
.B sfkarman < in.rsf > out.rsf x0=1. niter=100 nliter=1 verb=n
.SH PARAMETERS
.PD 0
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I int    
.B nliter
.B =1
.R  	number of reweighting iterations
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I float  
.B x0
.B =1.
.R  	initial squared length scale
.SH SOURCE
.I user/browaeys/Mkarman.c
.SH VERSION
4.2-git
