.TH sfkarmans 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfkarmans \- Inversion for von Karman autocorrelation 1D spectrum. 
.SH SYNOPSIS
.B sfkarmans < in.rsf > out.rsf prm=prm.rsf niter=100 x10=6. x20=-0.5 x30=200. verb=n
.SH PARAMETERS
.PD 0
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I file   
.B prm
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I float  
.B x10
.B =6.
.R  	initial nonlinear parameter x1 value
.TP
.I float  
.B x20
.B =-0.5
.R  	initial nonlinear parameter x2 value
.TP
.I float  
.B x30
.B =200.
.R  	initial nonlinear parameter x3 value
.SH SOURCE
.I user/browaeys/Mkarmans.c
.SH VERSION
4.2-git
