.TH sfkine2dvti 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfkine2dvti \- 2-D two-components wavefield modeling using pseudo-pure mode P-wave equation in VTI media.
.SH SYNOPSIS
.B sfkine2dvti > Fo1.rsf WFp=Fo2.rsf WFs=Fo3.rsf nx=201 nz=201 dx=0.008 dz=0.008 time=0.2 da=0.05 vp0=3000.0 vs0=1200.0 eps=0.2 del=0.1 the=0.0 t0=0.04 f0=20.0
.SH COMMENTS
Copyright (C) 2012 Tongji University, Shanghai, China 
Authors: Jiubing Cheng and Wei Kang

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

.SH PARAMETERS
.PD 0
.TP
.I file   
.B WFp
.B =
.R  	auxiliary output file name
.TP
.I file   
.B WFs
.B =
.R  	auxiliary output file name
.TP
.I float  
.B da
.B =0.05
.R  
.TP
.I float  
.B del
.B =0.1
.R  
.TP
.I float  
.B dx
.B =0.008
.R  
.TP
.I float  
.B dz
.B =0.008
.R  
.TP
.I float  
.B eps
.B =0.2
.R  
.TP
.I float  
.B f0
.B =20.0
.R  
.TP
.I int    
.B nx
.B =201
.R  
.TP
.I int    
.B nz
.B =201
.R  
.TP
.I float  
.B t0
.B =0.04
.R  
.TP
.I float  
.B the
.B =0.0
.R  
.TP
.I float  
.B time
.B =0.2
.R  	unit: SECOND
.TP
.I float  
.B vp0
.B =3000.0
.R  
.TP
.I float  
.B vs0
.B =1200.0
.R  
.SH SOURCE
.I user/chengjb/Mkine2dvti.c
.SH VERSION
4.2-git
