.TH sfkirmod_newton 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfkirmod_newton \- Kirchhoff 2-D/2.5-D modeling in layered media with bending ray tracing.  
.SH SYNOPSIS
.B sfkirmod_newton < modl.rsf > data.rsf curv=curv.rsf refl=refl.rsf picks=picks.rsf slopes=slopes.rsf aniso=vti.rsf velocity= xgradient= zgradient= xref= zref= lin=n adj=n absoff=n nt= dt=0.004 t0=0. ns=nx s0=x0 ds=dx nh=nx h0=0. dh=dx verb=n r0=1. r0=1. debug=n fwdxini=n vstatus= niter=500 tol=0.00001 order=3 cmp=n freq=0.2/dt rgrad= dip=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B absoff
.B =n
.R  [y/n]	y - h0 is not in shot coordinate system
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag
.TP
.I file   
.B aniso
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B cmp
.B =n
.R  [y/n]	compute CMP instead of shot gathers
.TP
.I file   
.B curv
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B debug
.B =n
.R  [y/n]	debug flag
.TP
.I float  
.B dh
.B =dx
.R  	offset increment
.TP
.I string 
.B dip
.B =
.R  	reflector dip file
.TP
.I float  
.B ds
.B =dx
.R  	shot/midpoint increment
.TP
.I float  
.B dt
.B =0.004
.R  	time sampling
.TP
.I float  
.B freq
.B =0.2/dt
.R  	peak frequency for Ricker wavelet
.TP
.I bool   
.B fwdxini
.B =n
.R  [y/n]	use the result of previous iteration to be the xinitial of the next one
.TP
.I float  
.B h0
.B =0.
.R  	first offset
.TP
.I bool   
.B lin
.B =n
.R  [y/n]	if linear operator
.TP
.I int    
.B nh
.B =nx
.R  	number of offsets
.TP
.I int    
.B niter
.B =500
.R  	The number of iterations
.TP
.I int    
.B ns
.B =nx
.R  	number of shots (midpoints if cmp=y)
.TP
.I int    
.B nt
.B =
.R  	time samples
.TP
.I int    
.B order
.B =3
.R  	Interpolation order
.TP
.I string 
.B picks
.B =
.R  	auxiliary output file name
.TP
.I float  
.B r0
.B =1.
.R  	normal reflectivity (if constant)
.TP
.I string 
.B refl
.B =
.R  	auxiliary input file name
.TP
.I string 
.B rgrad
.B =
.R  	AVO gradient file (B/A)
.TP
.I float  
.B s0
.B =x0
.R  	first shot (midpoint if cmp=y)
.TP
.I string 
.B slopes
.B =
.R  	auxiliary output file name
.TP
.I float  
.B t0
.B =0.
.R  	time origin
.TP
.I double 
.B tol
.B =0.00001
.R  	Assign a default value for tolerance
.TP
.I floats 
.B velocity
.B =
.R  	Assign velocity km/s [nc]
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I int    
.B vstatus
.B =
.R  	Velocity status (0 for constant v,1 for gradient v, and 2 for vti)
.TP
.I floats 
.B xgradient
.B =
.R  	 [nc]
.TP
.I floats 
.B xref
.B =
.R  	Assign x-reference point [nc]
.TP
.I floats 
.B zgradient
.B =
.R  	 [nc]
.TP
.I floats 
.B zref
.B =
.R  	Assign z-reference point [nc]
.SH SOURCE
.I user/zone/Mkirmod_newton.c
.SH VERSION
4.2-git
