.TH sfkirmig0 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfkirmig0 \- 2-D Post-stack Kirchhoff depth migration. 
.SH SYNOPSIS
.B sfkirmig0 < dat.rsf > mig.rsf table=tbl.rsf deriv=der.rsf adj=y nt= ns= t0=0.0 dt= s0=0.0 ds= aperture=90. antialias=1.0 type=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =y
.R  [y/n]	y for migration, n for modeling
.TP
.I float  
.B antialias
.B =1.0
.R  	antialiasing
.TP
.I float  
.B aperture
.B =90.
.R  	migration aperture (in degree)
.TP
.I file   
.B deriv
.B =
.R  	auxiliary input file name
.TP
.I float  
.B ds
.B =
.R  	midpoint sampling
.TP
.I float  
.B dt
.B =
.R  	time sampling
.TP
.I int    
.B ns
.B =
.R  	midpoint samples
.TP
.I int    
.B nt
.B =
.R  	time samples
.TP
.I float  
.B s0
.B =0.0
.R  	midpoint origin
.TP
.I float  
.B t0
.B =0.0
.R  	time origin
.TP
.I file   
.B table
.B =
.R  	auxiliary input file name
.TP
.I string 
.B type
.B =
.R  	type of interpolation (default Hermit)
.SH SOURCE
.I user/llisiw/Mkirmig0.c
.SH VERSION
4.2-git
