.TH sfkirdatsr 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfkirdatsr \- 2-D Pre-stack Kirchhoff redatuming. 
.SH SYNOPSIS
.B sfkirdatsr < in.rsf > out.rsf sgreen=sgreen.rsf rgreen=rgreen.rsf interm=interm.rsf verb=n sdatum= rdatum= aperture=50 taper=10 length=0.025
.SH PARAMETERS
.PD 0
.TP
.I int    
.B aperture
.B =50
.R  	aperture (number of traces)
.TP
.I string 
.B interm
.B =
.R  	auxiliary output file name
.TP
.I float  
.B length
.B =0.025
.R  	filter length (in seconds)
.TP
.I float  
.B rdatum
.B =
.R  	receiver datum depth
.TP
.I file   
.B rgreen
.B =
.R  	auxiliary input file name
.TP
.I float  
.B sdatum
.B =
.R  	source datum depth
.TP
.I file   
.B sgreen
.B =
.R  	auxiliary input file name
.TP
.I int    
.B taper
.B =10
.R  	taper (number of traces)
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/llisiw/Mkirdatsr.c
.SH VERSION
4.2-git
