.TH sfkirchinvs 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfkirchinvs \- Kirchhoff 2-D post-stack least-squares time migration with sparse constrains. 
.SH SYNOPSIS
.B sfkirchinvs < in.rsf > out.rsf velocity=vel.rsf hd=y ps=y verb=n sw=0 niter=5 liter=5 eps=0. err=
.SH COMMENTS

Antialiasing by reparameterization. 
.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =0.
.R  	regularization parameters
.TP
.I string 
.B err
.B =
.R  	output file for error
.TP
.I bool   
.B hd
.B =y
.R  [y/n]	if y, apply half-derivative filter
.TP
.I int    
.B liter
.B =5
.R  	number of linear iterations
.TP
.I int    
.B niter
.B =5
.R  	number of non-linear iterations, when niter=1, it's linear
.TP
.I bool   
.B ps
.B =y
.R  [y/n]	if y, apply pseudo-unitary weighting
.TP
.I int    
.B sw
.B =0
.R  	if > 0, select a branch of the antialiasing operation
.TP
.I file   
.B velocity
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/seisinv/Mkirchinvs.c
.SH VERSION
4.2-git
