.TH sfkolmog 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfkolmog \- Kolmogoroff spectral factorization. 
.SH SYNOPSIS
.B sfkolmog < in.rsf > out.rsf spec=n lag=0 shift=0
.SH PARAMETERS
.PD 0
.TP
.I int    
.B lag
.B =0
.R  	lag for asymmetric part
.TP
.I int    
.B shift
.B =0
.R  	time shift
.TP
.I bool   
.B spec
.B =n
.R  [y/n]	if y, the input is spectrum squared; n, time-domain signal
.SH SOURCE
.I user/gee/Mkolmog.c
.SH VERSION
4.2-git
