.TH sflaps2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflaps2d \- OpenMP lagged-products in the time-domain 
.SH SYNOPSIS
.B sflaps2d < Fs.rsf ur=Fr.rsf cc=Fc.rsf > Fi.rsf verb=n buf=n nhz=0 nhx=0 nht=0
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B buf
.B =n
.R  [y/n]
.TP
.I file   
.B cc
.B =
.R  	auxiliary input file name
.TP
.I int    
.B nht
.B =0
.R  	number of lags on the t axis
.TP
.I int    
.B nhx
.B =0
.R  	number of lags on the x axis
.TP
.I int    
.B nhz
.B =0
.R  	number of lags on the z axis
.TP
.I file   
.B ur
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH USED IN
.TP
.I cwp/geo2008IsotropicAngleDomainElasticRTM/marm2allA
.SH SOURCE
.I user/psava/Mlaps2d.c
.SH VERSION
4.2-git
