.TH sflagrange 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflagrange \- A forward interpolation using Lagrange method. 
.SH SYNOPSIS
.B sflagrange < in.rsf > out.rsf ox=o1 dx=d1 nx=n1
.SH COMMENTS
Specify ox= dx= nx=

.SH PARAMETERS
.PD 0
.TP
.I float  
.B dx
.B =d1
.R  
.TP
.I int    
.B nx
.B =n1
.R  
.TP
.I float  
.B ox
.B =o1
.R  
.SH SOURCE
.I user/chenyk/Mlagrange.c
.SH VERSION
4.2-git
