.TH sfleftsize 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfleftsize \- Computes Ni+1 x Ni+2 x ...
.SH SYNOPSIS
.B sfleftsize < in.rsf i=0
.SH COMMENTS
Wrapper for sf_leftsize
.SH PARAMETERS
.PD 0
.TP
.I int    
.B i
.B =0
.R  	What size to start counting from. i=0 gets total number of elements
.SH SOURCE
.I user/ivlad/Mleftsize.c
.SH VERSION
4.2-git
