.TH sflesolver 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflesolver \- Linear equations solver using Gauss Elimination 
.SH SYNOPSIS
.B sflesolver < in.rsf d=d.rsf > out.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B d
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/chenyk/Mlesolver.c
.SH VERSION
4.2-git
