.TH sflegacy 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflegacy \- Merging legacy and hires datasets 
.SH SYNOPSIS
.B sflegacy < in.rsf > out.rsf rect=rect.rsf hweight=hweight.rsf lweight=lweight.rsf adj=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag
.TP
.I file   
.B hweight
.B =
.R  	auxiliary input file name
.TP
.I file   
.B lweight
.B =
.R  	auxiliary input file name
.TP
.I file   
.B rect
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/fomels/Mlegacy.c
.SH VERSION
4.2-git
