.TH sflffd2_an_25 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflffd2_an_25 \- 2-D Fourier finite-difference wave extrapolation 
.SH SYNOPSIS
.B sflffd2_an_25 > out.rsf < source.rsf velz=velz.rsf velx=velx.rsf yita=yita.rsf seta=seta.rsf G=G.rsf paras=paras.rsf s1=files1.rsf s2=files2.rsf dt= nt= isx= isz= ax=2.0 az=2.0 factor=1.0 err=0.0001 de=y
.SH PARAMETERS
.PD 0
.TP
.I file   
.B G
.B =
.R  	auxiliary input file name
.TP
.I float  
.B ax
.B =2.0
.R  	suppress HF parameter
.TP
.I float  
.B az
.B =2.0
.R  	suppress HF parameter
.TP
.I bool   
.B de
.B =y
.R  [y/n]
.TP
.I float  
.B dt
.B =
.R  
.TP
.I float  
.B err
.B =0.0001
.R  	suppress HF parameter
.TP
.I float  
.B factor
.B =1.0
.R  	suppress HF parameter
.TP
.I int    
.B isx
.B =
.R  
.TP
.I int    
.B isz
.B =
.R  
.TP
.I int    
.B nt
.B =
.R  
.TP
.I file   
.B paras
.B =
.R  	auxiliary input file name
.TP
.I file   
.B s1
.B =
.R  	auxiliary input file name
.TP
.I file   
.B s2
.B =
.R  	auxiliary input file name
.TP
.I file   
.B seta
.B =
.R  	auxiliary input file name
.TP
.I file   
.B velx
.B =
.R  	auxiliary input file name
.TP
.I file   
.B velz
.B =
.R  	auxiliary input file name
.TP
.I file   
.B yita
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/songxl/Mlffd2_an_25.c
.SH VERSION
4.2-git
