.TH sflint1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflint1 \- Linear interpolation 
.SH SYNOPSIS
.B sflint1 coord=coord.rsf < dat.rsf > mod.rsf adj=n n1= o1= d1=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag
.TP
.I file   
.B coord
.B =
.R  	auxiliary input file name
.TP
.I float  
.B d1
.B =
.R  	regular axis sampling (for adj=y)
.TP
.I int    
.B n1
.B =
.R  	regular axis size (for adj=y)
.TP
.I float  
.B o1
.B =
.R  	regular axis origin (for adj=y)
.SH SOURCE
.I user/gee/Mlint1.c
.SH VERSION
4.2-git
