.TH sflinmig3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflinmig3 \- 3-D Kirchhoff time migration with antialiasing with adjoint flag. 
.SH SYNOPSIS
.B sflinmig3 < in.rsf > mig.rsf vel=velFile.rsf n1= adj=y doomp=n rho=1.-1./nt apt=nx angle=90.0 vel= antialias=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =y
.R  [y/n]	adjoint flag
.TP
.I float  
.B angle
.B =90.0
.R  	angle aperture
.TP
.I string 
.B antialias
.B =
.R  	antialiasing type [triangle,flat,steep,none]
.TP
.I int    
.B apt
.B =nx
.R  	integral aperture
.TP
.I bool   
.B doomp
.B =n
.R  [y/n]	perform OpenMP optimization
.TP
.I int    
.B n1
.B =
.R  
.TP
.I float  
.B rho
.B =1.-1./nt
.R  	Leaky integration constant
.TP
.I float  
.B vel
.B =
.R  	migration velocity
.SH SOURCE
.I user/dmerzlikin/Mlinmig3.c
.SH VERSION
4.2-git
