.TH sflinsincos 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflinsincos \- Solve for angle in equation vx*sin(d) + vy*cos(d) = 1/s0. 
.SH SYNOPSIS
.B sflinsincos < in.rsf > out.rsf s0= na= da= oa= nt=180 dt=2. ot=0. nr=nvx/2 dr=dvx extend=4
.SH PARAMETERS
.PD 0
.TP
.I float  
.B da
.B =
.R  	angle sampling.
.TP
.I float  
.B dr
.B =dvx
.R  	radius sampling.
.TP
.I float  
.B dt
.B =2.
.R  	polar angle sampling.
.TP
.I int    
.B extend
.B =4
.R  	tmp extension
.TP
.I int    
.B na
.B =
.R  	number of angle values.
.TP
.I int    
.B nr
.B =nvx/2
.R  	number of radius on radial lines
.TP
.I int    
.B nt
.B =180
.R  	number of polar angle for integration.
.TP
.I float  
.B oa
.B =
.R  	angle origin
.TP
.I float  
.B ot
.B =0.
.R  	polar angle origin
.TP
.I float  
.B s0
.B =
.R  	reference slowness
.SH SOURCE
.I system/seismic/Mlinsincos.c
.SH VERSION
4.2-git
