.TH sflinmig2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflinmig2 \- 2-D Kirchhoff time migration with antialiasing with adjoint flag. 
.SH SYNOPSIS
.B sflinmig2 < in.rsf > mig.rsf vel=fvel.rsf n1= adj=y ps=y doomp=y rho=1.-1./nt hd=y apt=nx angle=90.0 dd=y antialias=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =y
.R  [y/n]	adjoint flag
.TP
.I float  
.B angle
.B =90.0
.R  	angle aperture
.TP
.I string 
.B antialias
.B =
.R  	antialiasing type [triangle,flat,steep,none]
.TP
.I int    
.B apt
.B =nx
.R  	integral aperture
.TP
.I bool   
.B dd
.B =y
.R  [y/n]	differentiation in the data domain
.TP
.I bool   
.B doomp
.B =y
.R  [y/n]	perform OpenMP optimization
.TP
.I bool   
.B hd
.B =y
.R  [y/n]	half derivative
.TP
.I int    
.B n1
.B =
.R  
.TP
.I bool   
.B ps
.B =y
.R  [y/n]	spherical divergence
.TP
.I float  
.B rho
.B =1.-1./nt
.R  	Leaky integration constant
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/dmerzlikin/Mlinmig2.c
.SH VERSION
4.2-git
