.TH sflinpi 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflinpi \- 3D Path-Summation Integral Operator as a Linear Filter
.SH SYNOPSIS
.B sflinpi < inp.rsf > out.rsf adj=n v_1= v_2= v_3= v_4= passthr=0.001 eps=0.001 epst2=0.001 pad=nt
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag
.TP
.I float  
.B eps
.B =0.001
.R  
.TP
.I float  
.B epst2
.B =0.001
.R  
.TP
.I int    
.B pad
.B =nt
.R  	output time samples
.TP
.I float  
.B passthr
.B =0.001
.R  
.TP
.I float  
.B v_1
.B =
.R  	path-integral range
.TP
.I float  
.B v_2
.B =
.R  
.TP
.I float  
.B v_3
.B =
.R  
.TP
.I float  
.B v_4
.B =
.R  
.SH SOURCE
.I user/dmerzlikin/Mlinpi.c
.SH VERSION
4.2-git
