.TH sflinpipwd2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflinpipwd2d \- pi operator building wrapping test function flat gaussian weighting smoothing after pi
.SH SYNOPSIS
.B sflinpipwd2d < inp.rsf > out.rsf vel=vel.rsf dip=dip.rsf adj=n sm=y domod=y doomp=y dopi=y ps=y dd=y apt=nx angle=90.0 hd=y verb=y rho=1.-1./nt v_1= v_2= v_3= v_4= passthr=0.001 eps=0.001 epst2=0.001 pad=nt order=1 nj1=1 antialias=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag
.TP
.I float  
.B angle
.B =90.0
.R  	angle aperture
.TP
.I string 
.B antialias
.B =
.R  	antialiasing type [triangle,flat,steep,none]
.TP
.I int    
.B apt
.B =nx
.R  	integral aperture
.TP
.I bool   
.B dd
.B =y
.R  [y/n]	differentiation in the data domain
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B domod
.B =y
.R  [y/n]	if perform modeling via Kirchhoff
.TP
.I bool   
.B doomp
.B =y
.R  [y/n]	OMP is forced currently
.TP
.I bool   
.B dopi
.B =y
.R  [y/n]	if do pi
.TP
.I float  
.B eps
.B =0.001
.R  	damper for pi
.TP
.I float  
.B epst2
.B =0.001
.R  	damper for t2warp
.TP
.I bool   
.B hd
.B =y
.R  [y/n]	half differentiation
.TP
.I int    
.B nj1
.B =1
.R  	antialiasing
.TP
.I int    
.B order
.B =1
.R  [1,2,3]	accuracy order
.TP
.I int    
.B pad
.B =nt
.R  	output time samples
.TP
.I float  
.B passthr
.B =0.001
.R  	threshold for tail elimination
.TP
.I bool   
.B ps
.B =y
.R  [y/n]	spherical divergence
.TP
.I float  
.B rho
.B =1.-1./nt
.R  	Leaky integration constant
.TP
.I bool   
.B sm
.B =y
.R  [y/n]	if perform derivative filtering = PWD
.TP
.I float  
.B v_1
.B =
.R  
.TP
.I float  
.B v_2
.B =
.R  
.TP
.I float  
.B v_3
.B =
.R  
.TP
.I float  
.B v_4
.B =
.R  
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/dmerzlikin/Mlinpipwd2d.c
.SH VERSION
4.2-git
