.TH sfllpf 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfllpf \- Local prediction filter (n-dimensional) with an adjoint flag. 
.SH SYNOPSIS
.B sfllpf basis=dat.rsf < mat.rsf > flt.rsf adj=n niter=100 verb=y
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]
.TP
.I file   
.B basis
.B =
.R  	auxiliary input file name
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/fomels/Mllpf.c
.SH VERSION
4.2-git
