.TH sflocalsnr 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflocalsnr \- Local signal-to-noise ratio (SNR) estimation. 
.SH SYNOPSIS
.B sflocalsnr < in.rsf en=en.rsf > out.rsf nw= niter=100 verb=y eps=0.0f stack=y rect#=(1,1,...)
.SH PARAMETERS
.PD 0
.TP
.I file   
.B en
.B =
.R  	auxiliary input file name
.TP
.I float  
.B eps
.B =0.0f
.R  	regularization
.TP
.I int    
.B niter
.B =100
.R  	number of inversion iterations
.TP
.I int    
.B nw
.B =
.R  	window length
.TP
.I int    
.B rect#
.B =(1,1,...)
.R  	smoothing radius on #-th axis
.TP
.I bool   
.B stack
.B =y
.R  [y/n]	if y, window centre point, whereas window average
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/yliu/Mlocalsnr.c
.SH VERSION
4.2-git
