.TH sflogzero 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflogzero \- 
.SH SYNOPSIS
.B sflogzero < loga.rsf > log_eo.rsf switch=
.SH COMMENTS
1D dataset windowing

Built for log data manipulation - Clips padded values at the beginning and end of well log data to zero

.SH PARAMETERS
.PD 0
.TP
.I int    
.B switch
.B =
.R  
.SH SOURCE
.I user/sbader/Mlogzero.py
.SH VERSION
4.2-git
