.TH sflomatch 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflomatch \- Local Matched filter for coherent noise removal (1-D, 2-D, and 3-D). 
.SH SYNOPSIS
.B sflomatch < dat.rsf > mcf.rsf match=mat.rsf mask=known.rsf w= a= k= gap= center= niter=1 perc=90.0 eps=0.01 verb=n dim=dim liter=aa->nh lag=
.SH PARAMETERS
.PD 0
.TP
.I ints   
.B a
.B =
.R  	filter size  [dim1]
.TP
.I ints   
.B center
.B =
.R  	filter center  [dim1]
.TP
.I int    
.B dim
.B =dim
.R  	matched filter  dimensionality
.TP
.I float  
.B eps
.B =0.01
.R  	dumping parameter x=(M'M+eps*I)M'd
.TP
.I ints   
.B gap
.B =
.R  	filter gap  [dim1]
.TP
.I ints   
.B k
.B =
.R  	number of windows  [dim1]
.TP
.I string 
.B lag
.B =
.R  	output file for filter lags
.TP
.I int    
.B liter
.B =aa->nh
.R  	number of linear iteration
.TP
.I string 
.B mask
.B =
.R  	auxiliary input file name
.TP
.I string 
.B match
.B =
.R  	auxiliary input file name
.TP
.I int    
.B niter
.B =1
.R  	number of POCS iterations: =1 L2 norm ; >1 L1 norm
.TP
.I float  
.B perc
.B =90.0
.R  	percentage for sharpening [L1 norm]
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I ints   
.B w
.B =
.R  	window size  [dim1]
.SH SOURCE
.I user/lcasasan/Mlomatch.c
.SH VERSION
4.2-git
