.TH sflosignoi 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflosignoi \- Local signal and noise separation (N-dimensional).
.SH SYNOPSIS
.B sflosignoi < dat.rsf > signal.rsf sfilt=spef.rsf nfilt=npef.rsf eps= niter=20 slag= nlag=
.SH COMMENTS

Signal and noise separation by inversion (super-deconvolution).
Uses the helix and patching technologies.

.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =
.R  	regularization parameter
.TP
.I file   
.B nfilt
.B =
.R  	auxiliary input file name
.TP
.I int    
.B niter
.B =20
.R  	number of iterations
.TP
.I string 
.B nlag
.B =
.R  
.TP
.I file   
.B sfilt
.B =
.R  	auxiliary input file name
.TP
.I string 
.B slag
.B =
.R  
.SH SOURCE
.I user/gee/Mlosignoi.c
.SH VERSION
4.2-git
