.TH sflpfdenoise2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflpfdenoise2 \- 2D denoising using edge-preserving local polynomial fitting (ELPF). 
.SH SYNOPSIS
.B sflpfdenoise2 < in.rsf > out.rsf dip=dip.rsf nfw= nw= rect= boundary=y niter=100 verb=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B boundary
.B =y
.R  [y/n]	if y, boundary is data, whereas zero
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I int    
.B nfw
.B =
.R  	filter-window length (positive and odd integer)
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I int    
.B nw
.B =
.R  	data-window length (positive and odd integer)
.TP
.I int    
.B rect
.B =
.R  	local smoothing radius
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/yliu/Mlpfdenoise2.c
.SH VERSION
4.2-git
