.TH sflrosrtm2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflrosrtm2 \- 2-D Low-rank One-step Pre-stack Reverse-Time-Migration
.SH SYNOPSIS
.B sflrosrtm2 refl=Frefl.rsf vel=Fvel.rsf < Fsrc.rsf rec=Frcd.rsf > Fimg1.rsf img2=Fimg2.rsf tmpwf=Ftmpwf.rsf tmpbwf=Ftmpbwf.rsf left=left.rsf right=right.rsf leftb=leftb.rsf rightb=rightb.rsf verb=n wantwf=n wantrecord=y dbg=n srcill=y srctrunc=0.4 rectz=1 rectx=1 repeat=0 pad1=1 top=40 bot=40 lft=40 rht=40 slx=-1.0 spx=-1 slz=-1.0 spz=-1 gdep=-1.0 gpz=0 gpx= gpl= snapinter=10
.SH COMMENTS
img1 :  crosscorrelation
img2 :  crosscorrelation with source/receiver normalization


.SH PARAMETERS
.PD 0
.TP
.I int    
.B bot
.B =40
.R  
.TP
.I bool   
.B dbg
.B =n
.R  [y/n]	debug mode - doesn't propagate receiver wavefield
.TP
.I float  
.B gdep
.B =-1.0
.R  	recorder depth on grid
.TP
.I int    
.B gpl
.B =
.R  	recorder length on index
.TP
.I int    
.B gpx
.B =
.R  	recorder starting location on index
.TP
.I int    
.B gpz
.B =0
.R  	recorder depth on index
.TP
.I file   
.B img2
.B =
.R  	auxiliary output file name
.TP
.I file   
.B left
.B =
.R  	auxiliary input file name
.TP
.I file   
.B leftb
.B =
.R  	auxiliary input file name
.TP
.I int    
.B lft
.B =40
.R  
.TP
.I int    
.B pad1
.B =1
.R  	padding factor on the first axis
.TP
.I file   
.B rec
.B =
.R  	auxiliary input file name
.TP
.I int    
.B rectx
.B =1
.R  
.TP
.I int    
.B rectz
.B =1
.R  
.TP
.I file   
.B refl
.B =
.R  	auxiliary output file name
.TP
.I int    
.B repeat
.B =0
.R  
.TP
.I int    
.B rht
.B =40
.R  	Width of abc layer
.TP
.I file   
.B right
.B =
.R  	auxiliary input file name
.TP
.I file   
.B rightb
.B =
.R  	auxiliary input file name
.TP
.I float  
.B slx
.B =-1.0
.R  	source location x
.TP
.I float  
.B slz
.B =-1.0
.R  	source location z
.TP
.I int    
.B snapinter
.B =10
.R  	snap interval
.TP
.I int    
.B spx
.B =-1
.R  	source location x (index)
.TP
.I int    
.B spz
.B =-1
.R  	source location z (index)
.TP
.I bool   
.B srcill
.B =y
.R  [y/n]	true - source illumination; false - receiver illumination
.TP
.I float  
.B srctrunc
.B =0.4
.R  
.TP
.I file   
.B tmpbwf
.B =
.R  	auxiliary output file name
.TP
.I file   
.B tmpwf
.B =
.R  	auxiliary output file name
.TP
.I int    
.B top
.B =40
.R  
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.TP
.I bool   
.B wantrecord
.B =y
.R  [y/n]	if n, using record data generated by this program
.TP
.I bool   
.B wantwf
.B =n
.R  [y/n]	output forward and backward wavefield
.SH SOURCE
.I user/jsun/Mlrosrtm2.c
.SH VERSION
4.2-git
