.TH sflrmatrix 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflrmatrix \- Lowrank matrix decomposition
.SH SYNOPSIS
.B sflrmatrix name=mfile.rsf < in.rsf > out.rsf seed=time(NULL eps=1.e-4 npk=20 outputs=2
.SH PARAMETERS
.PD 0
.TP
.I        
.B eps
.B =1.e-4
.R  	tolerance
.TP
.I file   
.B name
.B =
.R  	auxiliary output file name
.TP
.I        
.B npk
.B =20
.R  	maximum rank
.TP
.I        
.B outputs
.B =2
.R  	number of outputs (2 or 3)
.TP
.I        
.B seed
.B =time(NULL
.R  
.SH SOURCE
.I user/lexing/Mlrmatrix.cc
.SH VERSION
4.2-git
