.TH sflsrtm2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflsrtm2d \- 2-D zero-offset least-squares reverse time migration (LSRTM)
.SH SYNOPSIS
.B sflsrtm2d < data.rsf > imag.rsf vel=modl.rsf n0=0 verb=n niter=10 tol=1.e-12
.SH PARAMETERS
.PD 0
.TP
.I int    
.B n0
.B =0
.R  	shot depth in the grid
.TP
.I int    
.B niter
.B =10
.R  	totol number of least-squares iteration
.TP
.I float  
.B tol
.B =1.e-12
.R  	tolerance of inversion
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.SH SOURCE
.I user/pyang/Mlsrtm2d.c
.SH VERSION
4.2-git
