.TH sflsinterp2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflsinterp2d \- Least-squares interpolation for 2D validition
.SH SYNOPSIS
.B sflsinterp2d < Fin.rsf mask=Fmask.rsf > Fout.rsf verb=n niter=100 nouter=5 eps=1.e-2
.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =1.e-2
.R  	regularization parameter
.TP
.I string 
.B mask
.B =
.R  	auxiliary input file name
.TP
.I int    
.B niter
.B =100
.R  	inner iterations
.TP
.I int    
.B nouter
.B =5
.R  	outer iterations
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.SH SOURCE
.I user/pyang/Mlsinterp2d.c
.SH VERSION
4.2-git
