.TH sflsprtm2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflsprtm2d \- least-squares prestack RTM in 2-D 
.SH SYNOPSIS
.B sflsprtm2d < shots.rsf vel=velo.rsf > imglsm.rsf imgrtm=imgrtm.rsf verb=y niter=10 nb=20 fromBoundary=y testadj=0
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B fromBoundary
.B =y
.R  [y/n]	if fromBoundary=true, reconstruct source wavefield from stored boundary
.TP
.I file   
.B imgrtm
.B =
.R  	auxiliary output file name
.TP
.I int    
.B nb
.B =20
.R  	number (thickness) of ABC on each side
.TP
.I int    
.B niter
.B =10
.R  	totol number of least-squares iteration
.TP
.I int    
.B testadj
.B =0
.R  	if testadj = 1 then program only testadj without calculating
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity
.SH SOURCE
.I user/pyang/Mlsprtm2d.c
.SH VERSION
4.2-git
