.TH sflstri2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflstri2d \- 2-D passive seismic RTM and its adjoint 
.SH SYNOPSIS
.B sflstri2d < in.rsf > out.rsf velocity=vel.rsf geop=geop.rsf weight=weight.rsf verb=n adj=n abc=n inv=n prec=n sw=n ctr=n depth=0 niter=0 ngrp=1 size=0 rectz=1 rectx=1 rectt=1 repeat=1 stack=1 perc=SF_EPS hard=0.0f cb=0.0f
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B abc
.B =n
.R  [y/n]	absorbing boundary condition
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag, 0: modeling, 1: migration
.TP
.I float  
.B cb
.B =0.0f
.R  	allocate arrays
.TP
.I bool   
.B ctr
.B =n
.R  [y/n]	CTR IC flag
.TP
.I int    
.B depth
.B =0
.R  	acquisition surface
.TP
.I string 
.B geop
.B =
.R  	auxiliary input file name
.TP
.I float  
.B hard
.B =0.0f
.R  	hard thresholding
.TP
.I bool   
.B inv
.B =n
.R  [y/n]	inversion flag
.TP
.I int    
.B ngrp
.B =1
.R  	number of groups of receivers
.TP
.I int    
.B niter
.B =0
.R  	number of iterations
.TP
.I float  
.B perc
.B =SF_EPS
.R  	stable division padding percentage (of max)
.TP
.I bool   
.B prec
.B =n
.R  [y/n]	use ctr as precondioner
.TP
.I int    
.B rectt
.B =1
.R  	smoothing radius in t
.TP
.I int    
.B rectx
.B =1
.R  	smoothing radius in x
.TP
.I int    
.B rectz
.B =1
.R  	smoothing radius in z
.TP
.I int    
.B repeat
.B =1
.R  	smoothing repeatation
.TP
.I int    
.B size
.B =0
.R  	sliding window size
.TP
.I int    
.B stack
.B =1
.R  	local stacking length
.TP
.I bool   
.B sw
.B =n
.R  [y/n]	inversion flag
.TP
.I file   
.B velocity
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I string 
.B weight
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/jsun/Mlstri2d.c
.SH VERSION
4.2-git
