.TH sflsm_dsr2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflsm_dsr2d \- 2-D prestack least-squares migration with split-step DSR. 
.SH SYNOPSIS
.B sflsm_dsr2d < in.rsf > out.rsf slowness=vel.rsf error=error.rsf verb=n eps=0.01 niter=10 nt=1 nr=1 dt=0.004 npad=0
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dt
.B =0.004
.R  	time error
.TP
.I float  
.B eps
.B =0.01
.R  	stability parameter
.TP
.I file   
.B error
.B =
.R  	auxiliary output file name
.TP
.I int    
.B niter
.B =10
.R  	number of iterations
.TP
.I int    
.B npad
.B =0
.R  	padding on offset wavenumber
.TP
.I int    
.B nr
.B =1
.R  	maximum number of references
.TP
.I int    
.B nt
.B =1
.R  	taper size
.TP
.I file   
.B slowness
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/seisinv/Mlsm_dsr2d.c
.SH VERSION
4.2-git
