.TH sflum 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflum \- 1D LUM filter
.SH SYNOPSIS
.B sflum < in.rsf > out.rsf nfw= smnclip=(nfw+1)/2 shnclip=(nfw+1)/2 boundary=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B boundary
.B =n
.R  [y/n]	if y, boundary is data, whereas zero
.TP
.I int    
.B nfw
.B =
.R  	filter-window length (positive and odd integer)
.TP
.I int    
.B shnclip
.B =(nfw+1)/2
.R  	sharpener tuning parameter (1 <= shnclip <= (nfw+1)/2, the default is (nfw+1)/2)
.TP
.I int    
.B smnclip
.B =(nfw+1)/2
.R  	smoother tuning parameter (1 <= smnclip <= (nfw+1)/2, the default is (nfw+1)/2)
.SH SOURCE
.I user/yliu/Mlum.c
.SH VERSION
4.2-git
