.TH sflwefd2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sflwefd2d \- linearized acoustic time-domain FD modeling 
.SH SYNOPSIS
.B sflwefd2d < Fwav.rsf sou=Fsou.rsf rec=Frec.rsf vel=Fvel.rsf den=Fden.rsf ref=Fref.rsf wfl=Fwfl.rsf > Fdat.rsf liw=Fliw.rsf lid=Flid.rsf ompchunk=1 ompnth=0 verb=n snap=n free=n expl=n jdata=1 jsnap=nt nqz=sf_n(a1) nqx=sf_n(a2) oqz=sf_o(a1) oqx=sf_o(a2)
.SH PARAMETERS
.PD 0
.TP
.I file   
.B den
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B expl
.B =n
.R  [y/n]	"exploding reflector"
.TP
.I bool   
.B free
.B =n
.R  [y/n]	free surface flag
.TP
.I int    
.B jdata
.B =1
.R  
.TP
.I int    
.B jsnap
.B =nt
.R  
.TP
.I file   
.B lid
.B =
.R  	auxiliary output file name
.TP
.I file   
.B liw
.B =
.R  	auxiliary output file name
.TP
.I int    
.B nqx
.B =sf_n(a2)
.R  
.TP
.I int    
.B nqz
.B =sf_n(a1)
.R  
.TP
.I int    
.B ompchunk
.B =1
.R  	OpenMP data chunk size
.TP
.I int    
.B ompnth
.B =0
.R  	OpenMP available threads
.TP
.I float  
.B oqx
.B =sf_o(a2)
.R  
.TP
.I float  
.B oqz
.B =sf_o(a1)
.R  
.TP
.I file   
.B rec
.B =
.R  	auxiliary input file name
.TP
.I file   
.B ref
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B snap
.B =n
.R  [y/n]	wavefield snapshots flag
.TP
.I file   
.B sou
.B =
.R  	auxiliary input file name
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I file   
.B wfl
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/psava/Mlwefd2d.c
.SH VERSION
4.2-git
