.TH sfmatchoper 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmatchoper \- Local matching-radon operator. 
.SH SYNOPSIS
.B sfmatchoper < in.rsf > out.rsf weight=weight.rsf np= dp= p0= shift= verb=n freq=y parab=n x0=1. rho=y anti=1. p1=0. niter=100 pclip=100.
.SH PARAMETERS
.PD 0
.TP
.I float  
.B anti
.B =1.
.R  	antialiasing, only when freq=n
.TP
.I float  
.B dp
.B =
.R  	p sampling
.TP
.I bool   
.B freq
.B =y
.R  [y/n]	if y, parabolic Radon transform
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I int    
.B np
.B =
.R  	number of p values
.TP
.I float  
.B p0
.B =
.R  	p origin
.TP
.I float  
.B p1
.B =0.
.R  	reference slope, only when freq=n
.TP
.I bool   
.B parab
.B =n
.R  [y/n]	if y, parabolic Radon transform, only when freq=y
.TP
.I float  
.B pclip
.B =100.
.R  
.TP
.I bool   
.B rho
.B =y
.R  [y/n]	rho filtering, only when freq=n
.TP
.I int    
.B shift
.B =
.R  
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I string 
.B weight
.B =
.R  	auxiliary output file name
.TP
.I float  
.B x0
.B =1.
.R  	reference offset
.SH SOURCE
.I user/yliu/Mmatchoper.c
.SH VERSION
4.2-git
