.TH sfmarchenko 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmarchenko \- Marchenko-Wapenaar-Broggini iterative scheme
.SH SYNOPSIS
.B sfmarchenko < Fplus.rsf refl=FRefl.rsf > FGp.rsf Gm=FGm.rsf G=FG.rsf H=FH.rsf p=Fp.rsf q=Fq.rsf window=Ftwin.rsf verb=n conj=n twin=n pandq=n Gtot=n Htot=n niter=1 ntaper=101 scale=1.0 eps=1e-4 shift=5
.SH COMMENTS

sfmarchenko < downgoing.rsf refl=REFL_000.rsf conj=y verb=n Gtot=y niter=21 nshots=401 scale=1 eps=1e-4 shift=5 Gm=Gm.rsf G=G.rsf> Gp.rsf

======= INPUTS ============

p0plus.rsf: initial downgoing wave field

REFL_000.rsf: Fourier transform of the reflection response

======= PARAMETERS ========

conj  = [y]/n	- complex-conjugation of the first input (corresponds to time-reversal in time)
verb = y/[n]	- verbosity flag
twin  = y/[n]	- returns the timewindow as one of the outputs (window=window.rsf)
pandq  = y/[n]	- pandq=true: returns p and q, pandq=false returns Gp and Gm
Gtot  = y/[n]	- Gtot=true returns G=Gp+Gm
Htot  = y/[n]	- Htot=true returns H=Gp-Gm
niter  = 1		- number of iterations
ntaper  = 101	- tapering width for each side
scale  = 1.0	- scale factor (often due to resampling)
eps  = 1e-4		- threshold for the timewindow
shift  = 5		- shift in samples for the timewindow

.SH PARAMETERS
.PD 0
.TP
.I file   
.B G
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Gm
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B Gtot
.B =n
.R  [y/n]	Gtot=true: returns G=Gp+Gm
.TP
.I file   
.B H
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B Htot
.B =n
.R  [y/n]	Htot=true: returns H=Gp-Gm
.TP
.I bool   
.B conj
.B =n
.R  [y/n]	complex conjugation (time-reversal) flag
.TP
.I float  
.B eps
.B =1e-4
.R  	threshold for the timewindow
.TP
.I int    
.B niter
.B =1
.R  	number of iterations
.TP
.I int    
.B ntaper
.B =101
.R  	tapering widht
.TP
.I file   
.B p
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B pandq
.B =n
.R  [y/n]	pandq=true: returns p and q
.TP
.I file   
.B q
.B =
.R  	auxiliary output file name
.TP
.I file   
.B refl
.B =
.R  	auxiliary input file name
.TP
.I float  
.B scale
.B =1.0
.R  	scale factor
.TP
.I int    
.B shift
.B =5
.R  	shift in samples for the timewindow
.TP
.I bool   
.B twin
.B =n
.R  [y/n]	returns the timewindow as one of the outputs
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I file   
.B window
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/fbroggin/Mmarchenko.c
.SH VERSION
4.2-git
