.TH sfmaskval 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmaskval \- Mask values inside or outside of a range.
.SH SYNOPSIS
.B sfmaskval < in.rsf > out.rsf upper=+FLT_MAX lower=-FLT_MAX upperval=+FLT_MAX lowerval=-FLT_MAX
.SH COMMENTS

sfmaskval < in.rsf > out.rsf upper=ul lower=ll upperval=uv lowerval=lv

If upper > lower, then values larger than ul will be changed to uv and
values belowe ll will be changed to lv.
If upper < lower, then values inside [ul;ll] will be changed to lv.


.SH PARAMETERS
.PD 0
.TP
.I float  
.B lower
.B =-FLT_MAX
.R  	lower range limit
.TP
.I float  
.B lowerval
.B =-FLT_MAX
.R  	lower range value
.TP
.I float  
.B upper
.B =+FLT_MAX
.R  	upper range limit
.TP
.I float  
.B upperval
.B =+FLT_MAX
.R  	upper range value
.SH SOURCE
.I user/bash/Mmaskval.c
.SH VERSION
4.2-git
