.TH sfmap2cloud3D 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmap2cloud3D \- 
.SH SYNOPSIS
.B sfmap2cloud3D < Fin.rsf > Fou.rsf msk=Fmk.rsf verb=n sphc=n
.SH COMMENTS
reformat gridded maps to point clouds
Paul Sava
Copyright (C) 2022 Colorado School of Mines

.SH PARAMETERS
.PD 0
.TP
.I string 
.B msk
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B sphc
.B =n
.R  [y/n]	spherical coordinates
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.SH SOURCE
.I user/psava/Mmap2cloud3D.c
.SH VERSION
4.2-git
