.TH sfmatoper 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmatoper \- Matrix algebra operation
.SH SYNOPSIS
.B sfmatoper < in.rsf mat=mat.rsf > out.rsf type=
.SH COMMENTS
Implement C=Oper(A,B).
Specially, when "Oper" stands for multiplication, C=AB,  where: 
C is a m*k matrix, m corresponds to dimension 2 while k corrsponds to dimension 1.
A is a m*n matrix, m corresponds to dimension 2 while n corrsponds to dimension 1.
B is a n*k matrix, n corresponds to dimension 2 while k corrsponds to dimension 1.
Like matlab matrix operation.
.SH PARAMETERS
.PD 0
.TP
.I file   
.B mat
.B =
.R  	auxiliary input file name
.TP
.I string 
.B type
.B =
.R  	[mul, add, sub, dotmul] operation type, the default is mul
.SH SOURCE
.I user/chenyk/Mmatoper.c
.SH VERSION
4.2-git
