.TH sfmatch 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmatch \- Simple matching filtering 
.SH SYNOPSIS
.B sfmatch < inp.rsf > out.rsf other=oth.rsf adj=n nf=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag
.TP
.I int    
.B nf
.B =
.R  	filter size
.TP
.I file   
.B other
.B =
.R  	auxiliary input file name
.SH SOURCE
.I system/generic/Mmatch.c
.SH VERSION
4.2-git
