.TH sfmarsiswav 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmarsiswav \- 
.SH SYNOPSIS
.B sfmarsiswav > wavTout.rsf verb=n window= delay= cmplxBB= zpad=
.SH COMMENTS
Create the time domain range compressed waveform for MARSIS
Created by: Dylan Hickson, Colorado School of Mines
Created on: Feb 16, 2022
Edited May 4, 2022:
- add option to zero-pad

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B cmplxBB
.B =
.R  [y/n]	complex baseband chirp
.TP
.I float  
.B delay
.B =
.R  	latency delay in transmitted signal in microseconds
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I bool   
.B window
.B =
.R  [y/n]	spectral Hann window flag
.TP
.I bool   
.B zpad
.B =
.R  [y/n]	zero pad to closest 2^n
.SH SOURCE
.I user/cwp/Mmarsiswav.py
.SH VERSION
4.2-git
