.TH sfmask 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmask \- Create a mask.
.SH SYNOPSIS
.B sfmask < in.rsf > out.rsf min= max= min= max=
.SH COMMENTS

Mask is an integer data with ones and zeros. 
Ones correspond to input values between min and max.

The output can be used with sfheaderwindow.

.SH PARAMETERS
.PD 0
.TP
.I int    
.B max
.B =
.R  	maximum header value
.TP
.I int    
.B min
.B =
.R  	minimum header value
.SH USED IN
.TP
.I cup/rna2d/real
.TP
.I cup/rna2d/simple
.TP
.I cwp/geo2008InterferometricImagingCondition/sact1
.TP
.I cwp/geo2008InterferometricImagingCondition/sigs2
.TP
.I cwp/geo2008IsotropicAngleDomainElasticRTM/marm2allA
.TP
.I cwp/geo2008IsotropicAngleDomainElasticRTM/marm2oneA
.TP
.I cwp/geo2009TTIModeSeparation/marmousi2
.TP
.I cwp/geo2009VTIModeSeparation/sigsbee
.TP
.I cwp/jse2006RWEImagingOverturningReflections/sigsbee
.TP
.I data/alaska/line31-81-m8r
.SH SOURCE
.I system/main/mask.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfmask
.SH VERSION
4.2-git
