.TH sfmcaseislet 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmcaseislet \- Morphological component analysis using 2-D Seislet transform 
.SH SYNOPSIS
.B sfmcaseislet < Fin.rsf > Fout.rsf dips=Fdips.rsf mask=Fmask.rsf eps=0.01 order=1 pscale=25 verb=n decr=y niter=10 pclip=10 p=0.5 type= mode=
.SH COMMENTS
Note:  Here, nc components with nc seislet transforms build a seislet 
frame to do the simultineous multicomponent separation and interpolation.	

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B decr
.B =y
.R  [y/n]	decrease threshold in iterations or not
.TP
.I file   
.B dips
.B =
.R  	auxiliary input file name
.TP
.I float  
.B eps
.B =0.01
.R  	regularization
.TP
.I string 
.B mask
.B =
.R  	auxiliary input file name
.TP
.I string 
.B mode
.B =
.R  	thresholding mode: 'hard', 'soft','pthresh','exp';
       'hard', hard thresholding;	'soft', soft thresholding; 
       'pthresh', generalized quasi-p; 'exp', exponential shrinkage
.TP
.I int    
.B niter
.B =10
.R  	total number iterations
.TP
.I int    
.B order
.B =1
.R  	accuracy order for seislet transform
.TP
.I float  
.B p
.B =0.5
.R  	norm=p, where 0<p<=1
.TP
.I float  
.B pclip
.B =10
.R  	starting data clip percentile (default is 10)
.TP
.I float  
.B pscale
.B =25
.R  	percentile of small scale to be preserved (default is 100)
.TP
.I string 
.B type
.B =
.R  	[haar,linear,biorthogonal] wavelet type, the default is linear
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity or not
.SH SOURCE
.I user/pyang/Mmcaseislet.c
.SH VERSION
4.2-git
