.TH sfmdfd4 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmdfd4 \- 2D finite difference modeling	
.SH SYNOPSIS
.B sfmdfd4 < modl.rsf > data.rsf wave=wave.rsf div=div.rsf nt=1000 dt=0.004 jt=40 wvlt=0 w0=35.0 sx=0 sz=0 rx0=0 nr=1 dr=1 rz=0
.SH PARAMETERS
.PD 0
.TP
.I file   
.B div
.B =
.R  	auxiliary output file name
.TP
.I int    
.B dr
.B =1
.R  	receiver interval of unit "dx"
.TP
.I float  
.B dt
.B =0.004
.R  	time interval
.TP
.I int    
.B jt
.B =40
.R  	wave movie time interval
.TP
.I int    
.B nr
.B =1
.R  	receiver numbers
.TP
.I int    
.B nt
.B =1000
.R  	time samples
.TP
.I int    
.B rx0
.B =0
.R  	x position index of first receiver
.TP
.I int    
.B rz
.B =0
.R  	z position index of receivers
.TP
.I int    
.B sx
.B =0
.R  	x position index of the source
.TP
.I int    
.B sz
.B =0
.R  	z position index of the source
.TP
.I float  
.B w0
.B =35.0
.R  	central frequency for ricker/harmonic wavelet
.TP
.I string 
.B wave
.B =
.R  	wavefield movie file (auxiliary output file name)
.TP
.I int    
.B wvlt
.B =0
.R  	wavelet type "ricker/harmonic/other"
.SH SOURCE
.I user/chen/Mmdfd4.c
.SH VERSION
4.2-git
