.TH sfmedianbalance 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmedianbalance \- Do median balancing.
.SH SYNOPSIS
.B sfmedianbalance inp= out= inp= out= verb=n pclip=99
.SH PARAMETERS
.PD 0
.TP
.I string 
.B inp
.B =
.R  	input file
.TP
.I string 
.B out
.B =
.R  	output file
.TP
.I float  
.B pclip
.B =99
.R  	percentile clip
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	if y, print system commands, outputs
.SH SOURCE
.I user/mlai/Mmedianbalance.py
.SH VERSION
4.2-git
