.TH sfmean 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmean \- 1-D sliding-window mean filtering 
.SH SYNOPSIS
.B sfmean < in.rsf > out.rsf nfw= boundary=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B boundary
.B =n
.R  [y/n]	if y, boundary is data, whereas zero
.TP
.I int    
.B nfw
.B =
.R  	filter-window length (positive integer)
.SH SOURCE
.I user/yliu/Mmean.c
.SH VERSION
4.2-git
