.TH sfmig2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmig2 \- 2-D prestack Kirchhoff time migration with antialiasing. 
.SH SYNOPSIS
.B sfmig2 < inp.rsf vel=vel.rsf > out.rsf gather=gather.rsf offset=offset.rsf adj=y normalize=y nh= antialias=1.0 apt=nx angle=90.0 half=y verb=y rho=1.-1./nt dh= h0=
.SH COMMENTS
The axes in the input are {time,midpoint,offset}
The axes in the offset are {1,midpoint,offset}
The axes in the output are {time,midpoint}
The axes in the "image gather" are {time,midpoint,offset}

February 2016 program of the month:
http://ahay.org/blog/2016/02/18/program-of-the-month-sfmig2/

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =y
.R  [y/n]	adjoint flag (y for migration, n for modeling)
.TP
.I float  
.B angle
.B =90.0
.R  	angle aperture
.TP
.I float  
.B antialias
.B =1.0
.R  	antialiasing
.TP
.I int    
.B apt
.B =nx
.R  	integral aperture
.TP
.I float  
.B dh
.B =
.R  	offset sampling (for modeling)
.TP
.I string 
.B gather
.B =
.R  	auxiliary output file name
.TP
.I float  
.B h0
.B =
.R  	first offset (for modeling)
.TP
.I bool   
.B half
.B =y
.R  [y/n]	if y, the third axis is half-offset instead of full offset
.TP
.I int    
.B nh
.B =
.R  	number of offsets (for modeling)
.TP
.I bool   
.B normalize
.B =y
.R  [y/n]	normalize for the fold
.TP
.I string 
.B offset
.B =
.R  	auxiliary input file name
.TP
.I float  
.B rho
.B =1.-1./nt
.R  	Leaky integration constant
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/yliu/Mmig2.c
.SH VERSION
4.2-git
