.TH sfminmax 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfminmax \- Element by element minimum or maximum of two RSF files.
.SH SYNOPSIS
.B sfminmax file1=file1.rsf file2=file2.rsf > out.rsf mode=
.SH COMMENTS

file1 and file2 must have the same number of elements.

See also: sflistminmax, sfstack.

.SH PARAMETERS
.PD 0
.TP
.I string 
.B file1
.B =
.R  	RSF filename required, data type must be float (auxiliary input file name)
.TP
.I string 
.B file2
.B =
.R  	RSF filename required, data type must be float (auxiliary input file name)
.TP
.I string 
.B mode
.B =
.R  	'min' (default) or 'max'
.SH SOURCE
.I user/jennings/Mminmax.c
.SH VERSION
4.2-git
