.TH sfmiss2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmiss2 \- 2-D missing data interpolation. 
.SH SYNOPSIS
.B sfmiss2 < in.rsf > out.rsf mask=mask.rsf niter=100 nliter=1 filt1=3. filt2=filt1 eps=0.0001 shape=n force=y
.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =0.0001
.R  	regularization parameter
.TP
.I float  
.B filt1
.B =3.
.R  
.TP
.I float  
.B filt2
.B =filt1
.R  	smoothing radius
.TP
.I bool   
.B force
.B =y
.R  [y/n]	if y, keep known values
.TP
.I string 
.B mask
.B =
.R  	optional input mask file for known data (auxiliary input file name)
.TP
.I int    
.B niter
.B =100
.R  	Number of iterations
.TP
.I int    
.B nliter
.B =1
.R  	Number of reweighting iterations
.TP
.I bool   
.B shape
.B =n
.R  [y/n]	if y, estimate shaping
.SH SOURCE
.I system/generic/Mmiss2.c
.SH VERSION
4.2-git
