.TH sfmlm 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmlm \- 2D Multistage median filtering. 
.SH SYNOPSIS
.B sfmlm < in.rsf > out.rsf nfw= boundary=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B boundary
.B =n
.R  [y/n]	if y, boundary is data, whereas zero
.TP
.I int    
.B nfw
.B =
.R  	filter-window length (positive and odd integer)
.SH SOURCE
.I user/yliu/Mmlm.c
.SH VERSION
4.2-git
