.TH sfmms1dexp 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmms1dexp \- 1D method of manufactured solution using Gaussian pulsa
.SH SYNOPSIS
.B sfmms1dexp < Fvel.rsf dvel=Fdvel.rsf den=Fden.rsf velhf=Fvelhf.rsf dvelhf=Fdvelhf.rsf denhf=Fdenhf.rsf presrc=Fpsrc.rsf velsrc=Fvsrc.rsf preinit=Fpint.rsf velinit=Fvint.rsf > Fmms.rsf nt= dt= slx=nx*dx*0.5 alpha=1.0e-2
.SH PARAMETERS
.PD 0
.TP
.I float  
.B alpha
.B =1.0e-2
.R  	source parameter
.TP
.I file   
.B den
.B =
.R  	auxiliary input file name
.TP
.I file   
.B denhf
.B =
.R  	auxiliary input file name
.TP
.I float  
.B dt
.B =
.R  	time step
.TP
.I file   
.B dvel
.B =
.R  	auxiliary input file name
.TP
.I file   
.B dvelhf
.B =
.R  	auxiliary input file name
.TP
.I int    
.B nt
.B =
.R  	number of time step
.TP
.I file   
.B preinit
.B =
.R  	auxiliary output file name
.TP
.I file   
.B presrc
.B =
.R  	auxiliary output file name
.TP
.I float  
.B slx
.B =nx*dx*0.5
.R  	center of source location: x
.TP
.I file   
.B velhf
.B =
.R  	auxiliary input file name
.TP
.I file   
.B velinit
.B =
.R  	auxiliary output file name
.TP
.I file   
.B velsrc
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/fangg/Mmms1dexp.c
.SH VERSION
4.2-git
