.TH sfmodrefl3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmodrefl3 \- Normal reflectivity modeling. 
.SH SYNOPSIS
.B sfmodrefl3 < in.rsf > out.rsf sparse=10 moveout=y nt= dt= np= dp= p0= eps=0.01
.SH COMMENTS

In this version, the input contains Vp, Vs, and density into one file. 
The output contains PP and PS tau-p seismograms.


.SH PARAMETERS
.PD 0
.TP
.I float  
.B dp
.B =
.R  	slope sampling
.TP
.I float  
.B dt
.B =
.R  	time sampling
.TP
.I float  
.B eps
.B =0.01
.R  	stretch regularization
.TP
.I bool   
.B moveout
.B =y
.R  [y/n]	if apply moveout
.TP
.I int    
.B np
.B =
.R  	slope samples
.TP
.I int    
.B nt
.B =
.R  	time samples
.TP
.I float  
.B p0
.B =
.R  	slope origin
.TP
.I int    
.B sparse
.B =10
.R  	sparseness of reflectivity
.SH SOURCE
.I system/seismic/Mmodrefl3.c
.SH VERSION
4.2-git
