.TH sfmodatten1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmodatten1 \- 1D attenuation modeling according to modified Kolsky model. 
.SH SYNOPSIS
.B sfmodatten1 > out.rsf at= q= n1=1000 d1=0.001 o1=0. nc=1 fm=40 mag=1.
.SH PARAMETERS
.PD 0
.TP
.I ints   
.B at
.B =
.R  	(at=[at1,at2,...] layer quality factor)  [nc]
.TP
.I float  
.B d1
.B =0.001
.R  	sampling on time axis
.TP
.I int    
.B fm
.B =40
.R  	dominant frequency of Ricker wavelet
.TP
.I float  
.B mag
.B =1.
.R  	min-phase
.TP
.I int    
.B n1
.B =1000
.R  	size of time axis
.TP
.I int    
.B nc
.B =1
.R  	number of layer
.TP
.I float  
.B o1
.B =0.
.R  	origin on time axis
.TP
.I floats 
.B q
.B =
.R  	(q=[q1,q2,...] layer quality factor)  [nc]
.SH SOURCE
.I user/yliu/Mmodatten1.c
.SH VERSION
4.2-git
