.TH sfmonof2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmonof2 \- Gaussian wavelet estimation in 2-D. 
.SH SYNOPSIS
.B sfmonof2 < in.rsf > out.rsf ma=ma.rsf a0=1. b0=0. c0=1. niter=100 nliter=1 verb=n
.SH PARAMETERS
.PD 0
.TP
.I float  
.B a0
.B =1.
.R  	starting sharpness in xx
.TP
.I float  
.B b0
.B =0.
.R  	starting sharpness in xy
.TP
.I float  
.B c0
.B =1.
.R  	starting sharpness in yy
.TP
.I file   
.B ma
.B =
.R  	auxiliary output file name
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I int    
.B nliter
.B =1
.R  	number of reweighting iterations
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I system/generic/Mmonof2.c
.SH VERSION
4.2-git
