.TH sfmorph 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmorph \- Morphological operations on binary images 
.SH SYNOPSIS
.B sfmorph < inp.rsf > out.rsf what=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B what
.B =
.R  	what operation to perform (dilation,closing,erosion,opening,skeleton)
.SH SOURCE
.I user/fomels/Mmorph.c
.SH VERSION
4.2-git
