.TH sfmpigpufwi 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmpigpufwi \- CUDA based FWI using Enquist absorbing boundary condition
.SH SYNOPSIS
.B sfmpigpufwi < vinit.rsf shots=shots.rsf > vupdates.rsf grads=grads.rsf objs=objs.rsf illums=illums.rsf verb=y precon=n niter=100 rbell=2
.SH COMMENTS

Note: You can try other complex boundary condition but we do not
recommend to do so. The main reason is that FWI is to recover
the low-frequency information of the earth model. Low-freq 
means that exact absorbing is not necessarilly needed. The 
result will be improved with the optimization precedure. 
Furthermore, complex boundary condition (such as sponge ABC or
PML) implies more computational cost, which will degrade the
efficiency of FWI. 

.SH PARAMETERS
.PD 0
.TP
.I file   
.B grads
.B =
.R  	auxiliary output file name
.TP
.I file   
.B illums
.B =
.R  	auxiliary output file name
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I file   
.B objs
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B precon
.B =n
.R  [y/n]	precondition or not
.TP
.I int    
.B rbell
.B =2
.R  	radius of bell smooth
.TP
.I file   
.B shots
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	vebosity
.SH SOURCE
.I user/pyang/Mmpigpufwi.cu
.SH VERSION
4.2-git
