.TH sfmpirtmiso 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmpirtmiso \- isotropic reverse-time migration 
.SH SYNOPSIS
.B sfmpirtmiso velo=fvelo.rsf sour=fsour.rsf nz= nz= tz= dz= dz= dt= z0= x0= bzl= bzh= bxl= bxh= czl= czh= cxl= cxh= j3= nh= ns= dh= ds= h0= s0= zr= zs= nH= nC= dH= dC= C0= mode= tau=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B C0
.B =
.R  
.TP
.I int    
.B bxh
.B =
.R  
.TP
.I int    
.B bxl
.B =
.R  
.TP
.I int    
.B bzh
.B =
.R  
.TP
.I int    
.B bzl
.B =
.R  
.TP
.I float  
.B cxh
.B =
.R  
.TP
.I float  
.B cxl
.B =
.R  
.TP
.I float  
.B czh
.B =
.R  
.TP
.I float  
.B czl
.B =
.R  
.TP
.I int    
.B dC
.B =
.R  
.TP
.I int    
.B dH
.B =
.R  
.TP
.I float  
.B dh
.B =
.R  
.TP
.I float  
.B ds
.B =
.R  
.TP
.I float  
.B dt
.B =
.R  
.TP
.I float  
.B dz
.B =
.R  
.TP
.I float  
.B h0
.B =
.R  
.TP
.I int    
.B j3
.B =
.R  
.TP
.I int    
.B mode
.B =
.R  
.TP
.I int    
.B nC
.B =
.R  
.TP
.I int    
.B nH
.B =
.R  
.TP
.I int    
.B nh
.B =
.R  
.TP
.I int    
.B ns
.B =
.R  
.TP
.I int    
.B nz
.B =
.R  
.TP
.I float  
.B s0
.B =
.R  
.TP
.I file   
.B sour
.B =
.R  	auxiliary input file name
.TP
.I int    
.B tau
.B =
.R  
.TP
.I int    
.B tz
.B =
.R  
.TP
.I file   
.B velo
.B =
.R  	auxiliary input file name
.TP
.I float  
.B x0
.B =
.R  
.TP
.I float  
.B z0
.B =
.R  
.TP
.I float  
.B zr
.B =
.R  
.TP
.I float  
.B zs
.B =
.R  
.SH SOURCE
.I user/xuxin/Mmpirtmiso.c
.SH VERSION
4.2-git
