.TH sfmpirfwigrad 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmpirfwigrad \- Calculate acoustic Reflection FWI gradient with the prepared adjoint source (velocity-impedance scale separation) 
.SH SYNOPSIS
.B sfmpirfwigrad Fvel=Fv.rsf Fd=Fd.rsf Fd0=Fd0.rsf Fwavelet=Fw.rsf Fadj=Fadj.rsf Fgrad=Fgrad.rsf ns= ds= s0= sz=3 nr=nx dr=dx r0=x0 rz=3 verb=n frectx=2 frectz=2 nb=20 coef=5. interval=1 acqui_type=1
.SH PARAMETERS
.PD 0
.TP
.I file   
.B Fadj
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Fd
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Fd0
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Fgrad
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Fvel
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Fwavelet
.B =
.R  	auxiliary input file name
.TP
.I int    
.B acqui_type
.B =1
.R  	acquisition type
.TP
.I float  
.B coef
.B =5.
.R  	maximum velocity of the medium
.TP
.I float  
.B dr
.B =dx
.R  	receiver interval
.TP
.I float  
.B ds
.B =
.R  	shot interval
.TP
.I int    
.B frectx
.B =2
.R  	source smoothing in x
.TP
.I int    
.B frectz
.B =2
.R  	source smoothing in z
.TP
.I int    
.B interval
.B =1
.R  	wavefield storing interval
.TP
.I int    
.B nb
.B =20
.R  	PML boundary width
.TP
.I int    
.B nr
.B =nx
.R  	number of receiver
.TP
.I int    
.B ns
.B =
.R  	shot number
.TP
.I float  
.B r0
.B =x0
.R  	receiver origin
.TP
.I int    
.B rz
.B =3
.R  	receiver depth
.TP
.I float  
.B s0
.B =
.R  	shot origin
.TP
.I int    
.B sz
.B =3
.R  	source depth
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/zhiguang/Mmpirfwigrad.c
.SH VERSION
4.2-git
