.TH sfmpifdlsrtm 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmpifdlsrtm \- 2-D prestack reverse time migration and its adjoint with MPI for full coverage
.SH SYNOPSIS
.B sfmpifdlsrtm input=in.rsf velocity=vel.rsf wavelet=wavelet.rsf output=out.rsf snapshot=snapshot.rsf adj=y verb=n snap=n nr= dr= r0= ns= ds= s0= zr=0.0 zs=0.0 jt=100 padz=nz padx=nz
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =y
.R  [y/n]
.TP
.I float  
.B dr
.B =
.R  
.TP
.I float  
.B ds
.B =
.R  
.TP
.I file   
.B input
.B =
.R  	auxiliary input file name
.TP
.I int    
.B jt
.B =100
.R  
.TP
.I int    
.B nr
.B =
.R  
.TP
.I int    
.B ns
.B =
.R  
.TP
.I file   
.B output
.B =
.R  	auxiliary output file name
.TP
.I int    
.B padx
.B =nz
.R  
.TP
.I int    
.B padz
.B =nz
.R  
.TP
.I float  
.B r0
.B =
.R  
.TP
.I float  
.B s0
.B =
.R  
.TP
.I bool   
.B snap
.B =n
.R  [y/n]
.TP
.I file   
.B snapshot
.B =
.R  	auxiliary output file name
.TP
.I file   
.B velocity
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]
.TP
.I file   
.B wavelet
.B =
.R  	auxiliary input file name
.TP
.I float  
.B zr
.B =0.0
.R  
.TP
.I float  
.B zs
.B =0.0
.R  
.SH SOURCE
.I user/zhiguang/Mmpifdlsrtm.c
.SH VERSION
4.2-git
