.TH sfmpilrrtm 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmpilrrtm \- 2-D Low-rank One-step Reverse-Time-Migration (simultaneous sources data and incomplete data) 
.SH SYNOPSIS
.B sfmpilrrtm src=Fsrc.rsf rec=Frcd.rsf left=left.rsf right=right.rsf leftb=leftb.rsf rightb=rightb.rsf vel=Fvel.rsf tmpwf=Ftmpwf.rsf mask=mask.rsf verb=n adj=y wantwf=n wantrecord=y illum=n roll=y fm=n incom=n shtbgn= sht0=shtbgn shtend= shtint= spz= gpz= gpl= snapinter=1 wfint=50 srctrunc=0.4 rectz=2 rectx=2 repeat=2 top=40 bot=40 lft=40 rht=40 nsource=1 dsource=0 tdelay=0 choose=nsource pad1=1
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =y
.R  [y/n]	migration
.TP
.I int    
.B bot
.B =40
.R  
.TP
.I int    
.B choose
.B =nsource
.R  	Set I/O file
.TP
.I int    
.B dsource
.B =0
.R  
.TP
.I bool   
.B fm
.B =n
.R  [y/n]	if n, Born modelling
.TP
.I int    
.B gpl
.B =
.R  
.TP
.I int    
.B gpz
.B =
.R  
.TP
.I bool   
.B illum
.B =n
.R  [y/n]	if n, no source illumination applied
.TP
.I bool   
.B incom
.B =n
.R  [y/n]	if n, use complete data
.TP
.I file   
.B left
.B =
.R  	auxiliary input file name
.TP
.I file   
.B leftb
.B =
.R  	auxiliary input file name
.TP
.I int    
.B lft
.B =40
.R  
.TP
.I file   
.B mask
.B =
.R  	auxiliary input file name
.TP
.I int    
.B nsource
.B =1
.R  
.TP
.I int    
.B pad1
.B =1
.R  	padding factor on the first axis
.TP
.I file   
.B rec
.B =
.R  	auxiliary output file name
.TP
.I int    
.B rectx
.B =2
.R  
.TP
.I int    
.B rectz
.B =2
.R  
.TP
.I int    
.B repeat
.B =2
.R  	abc parameters
.TP
.I int    
.B rht
.B =40
.R  	simultaneous sources parameter
.TP
.I file   
.B right
.B =
.R  	auxiliary input file name
.TP
.I file   
.B rightb
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B roll
.B =y
.R  [y/n]	if n, receiver is independent of source location and gpl=nx
.TP
.I int    
.B sht0
.B =shtbgn
.R  	actual shot origin on grid
.TP
.I int    
.B shtbgn
.B =
.R  
.TP
.I int    
.B shtend
.B =
.R  
.TP
.I int    
.B shtint
.B =
.R  
.TP
.I int    
.B snapinter
.B =1
.R  	snap interval
.TP
.I int    
.B spz
.B =
.R  
.TP
.I file   
.B src
.B =
.R  	auxiliary input file name
.TP
.I float  
.B srctrunc
.B =0.4
.R  
.TP
.I float  
.B tdelay
.B =0
.R  
.TP
.I file   
.B tmpwf
.B =
.R  	auxiliary output file name
.TP
.I int    
.B top
.B =40
.R  
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.TP
.I bool   
.B wantrecord
.B =y
.R  [y/n]	if n, using record data generated by this program
.TP
.I bool   
.B wantwf
.B =n
.R  [y/n]	output forward and backward wavefield
.TP
.I int    
.B wfint
.B =50
.R  	snap interval
.SH SOURCE
.I user/zhiguang/Mmpilrrtm.c
.SH VERSION
4.2-git
