.TH sfmpictshiftlr 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmpictshiftlr \- Correct time-shift gathers with two-step lowrank propagator 
.SH SYNOPSIS
.B sfmpictshiftlr left=left.rsf right=right.rsf dt=0.001 nb=60 par=0.01 cmplx=n abc=y pad1=1 taper=y thresh=0.92
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B abc
.B =y
.R  [y/n]	absorbing boundary condition
.TP
.I bool   
.B cmplx
.B =n
.R  [y/n]	use complex FFT
.TP
.I float  
.B dt
.B =0.001
.R  	time interval
.TP
.I file   
.B left
.B =
.R  	auxiliary input file name
.TP
.I int    
.B nb
.B =60
.R  	boundary width
.TP
.I int    
.B pad1
.B =1
.R  	padding factor on the first axis
.TP
.I float  
.B par
.B =0.01
.R  	absorbing boundary coefficient
.TP
.I file   
.B right
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B taper
.B =y
.R  [y/n]	tapering
.TP
.I float  
.B thresh
.B =0.92
.R  	thresholding
.SH SOURCE
.I user/zhiguang/Mmpictshiftlr.c
.SH VERSION
4.2-git
