.TH sfmpircvrtm 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmpircvrtm \- 2-D Low-rank One-step Least Pre-stack Reverse-Time-Migration in the complex domain (both img and data are complex valued)
.SH SYNOPSIS
.B sfmpircvrtm input=Frcd.rsf src=Fsrc.rsf output=Fimg.rsf left=left.rsf right=right.rsf leftb=leftb.rsf rightb=rightb.rsf vel=Fvel.rsf tmpwf=Ftmpwf.rsf rec2=Frcd2.rsf spx= verb=n adj=y rmig=n rcvint=1 rcvbgn=0 rcvend=-1 wantwf=n wantrecord=y illum=n roll=n stack=y shtbgn= sht0=shtbgn shtend= shtint= spz= gpz= gpl= snapinter=1 srctrunc=0.4 rectz=1 rectx=1 repeat=0 top=40 bot=40 lft=40 rht=40 mute=n vref=1500 wd=5 depth=gpz pad1=1
.SH COMMENTS
img :  crosscorrelation with source normalization (stdout)

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =y
.R  [y/n]	migration
.TP
.I int    
.B bot
.B =40
.R  
.TP
.I int    
.B depth
.B =gpz
.R  	muting source depth -> receiver depth according reciprocity
.TP
.I int    
.B gpl
.B =
.R  
.TP
.I int    
.B gpz
.B =
.R  
.TP
.I bool   
.B illum
.B =n
.R  [y/n]	if n, no source illumination applied
.TP
.I file   
.B input
.B =
.R  	auxiliary input file name
.TP
.I file   
.B left
.B =
.R  	auxiliary input file name
.TP
.I file   
.B leftb
.B =
.R  	auxiliary input file name
.TP
.I int    
.B lft
.B =40
.R  
.TP
.I bool   
.B mute
.B =n
.R  [y/n]	muting in the receiver gather
.TP
.I file   
.B output
.B =
.R  	auxiliary output file name
.TP
.I int    
.B pad1
.B =1
.R  	padding factor on the first axis
.TP
.I int    
.B rcvbgn
.B =0
.R  
.TP
.I int    
.B rcvend
.B =-1
.R  
.TP
.I int    
.B rcvint
.B =1
.R  
.TP
.I file   
.B rec2
.B =
.R  	auxiliary output file name
.TP
.I int    
.B rectx
.B =1
.R  
.TP
.I int    
.B rectz
.B =1
.R  
.TP
.I int    
.B repeat
.B =0
.R  	abc parameters
.TP
.I int    
.B rht
.B =40
.R  
.TP
.I file   
.B right
.B =
.R  	auxiliary input file name
.TP
.I file   
.B rightb
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B rmig
.B =n
.R  [y/n]	receiver domain migration
.TP
.I bool   
.B roll
.B =n
.R  [y/n]	if n, receiver is independent of source location and gpl=nx
.TP
.I int    
.B sht0
.B =shtbgn
.R  	actual shot origin on grid
.TP
.I int    
.B shtbgn
.B =
.R  
.TP
.I int    
.B shtend
.B =
.R  
.TP
.I int    
.B shtint
.B =
.R  
.TP
.I int    
.B snapinter
.B =1
.R  	snap interval
.TP
.I ints   
.B spx
.B =
.R  	 [num_of_shots]
.TP
.I int    
.B spz
.B =
.R  
.TP
.I file   
.B src
.B =
.R  	auxiliary input file name
.TP
.I float  
.B srctrunc
.B =0.4
.R  
.TP
.I bool   
.B stack
.B =y
.R  [y/n]	if y, outputs stacked image
.TP
.I file   
.B tmpwf
.B =
.R  	auxiliary output file name
.TP
.I int    
.B top
.B =40
.R  
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.TP
.I float  
.B vref
.B =1500
.R  
.TP
.I bool   
.B wantrecord
.B =y
.R  [y/n]	if n, using record data generated by this program
.TP
.I bool   
.B wantwf
.B =n
.R  [y/n]	output forward and backward wavefield
.TP
.I int    
.B wd
.B =5
.R  
.SH SOURCE
.I user/jsun/Mmpircvrtm.c
.SH VERSION
4.2-git
