.TH sfmpifd2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmpifd2d \- Acoustic wave equation forward modeling with MPI and OpenMP 
.SH SYNOPSIS
.B sfmpifd2d rho=Frho.rsf wavelet=Fw.rsf verb=n ns= ds= s0= sz=5 nr= dr= r0= rz=sz nb=80 coef=0.003 rectx=2 rectz=2
.SH PARAMETERS
.PD 0
.TP
.I float  
.B coef
.B =0.003
.R  	absorbing boundary coefficient
.TP
.I float  
.B dr
.B =
.R  	receiver interval
.TP
.I float  
.B ds
.B =
.R  	shot interval
.TP
.I int    
.B nb
.B =80
.R  	boundary width
.TP
.I int    
.B nr
.B =
.R  	number of receiver
.TP
.I int    
.B ns
.B =
.R  	shot number
.TP
.I float  
.B r0
.B =
.R  	receiver origin
.TP
.I int    
.B rectx
.B =2
.R  	source smooothing parameter
.TP
.I int    
.B rectz
.B =2
.R  	source smooothing parameter
.TP
.I file   
.B rho
.B =
.R  	auxiliary input file name
.TP
.I int    
.B rz
.B =sz
.R  	receiver depth
.TP
.I float  
.B s0
.B =
.R  	shot origin
.TP
.I int    
.B sz
.B =5
.R  	source depth
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I file   
.B wavelet
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/zhiguang/Mmpifd2d.c
.SH VERSION
4.2-git
