.TH sfmpitransp 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmpitransp \- Large rectangular matrix in-place transpose with MPI 
.SH SYNOPSIS
.B sfmpitransp indat=Fin.rsf transp=Fout.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B indat
.B =
.R  	auxiliary input file name
.TP
.I file   
.B transp
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/hwang/Mmpitransp.c
.SH VERSION
4.2-git
