.TH sfmpilrrtm_ts 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmpilrrtm_ts \- One-step lowrank RTM with time-shift imaging condition 
.SH SYNOPSIS
.B sfmpilrrtm_ts Fimg2=Fimg2.rsf Fsrc=Fsrc.rsf Fpadvel=Fvel.rsf Ffwf=Ffwf.rsf Fbwf=Fbwf.rsf taper=0 thresh=0.92 wantwf=n verb=n pad1=1 nb= srctrunc=0.4 rectx=2 rectz=2 repeat=2 scalet=1 snap=100 snapshot=0 nds= gpz= spx= spz= rnx= ndr=1 nr0=0 ntau= dtau= tau0= ncut=0 path1= path2=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B Fbwf
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Ffwf
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Fimg2
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Fpadvel
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Fsrc
.B =
.R  	auxiliary input file name
.TP
.I float  
.B dtau
.B =
.R  	interval of time-shift
.TP
.I int    
.B gpz
.B =
.R  	depth of geophone
.TP
.I int    
.B nb
.B =
.R  	padded boundary width
.TP
.I int    
.B ncut
.B =0
.R  	number of cutting samples for generating non-negative source wavelet
.TP
.I int    
.B ndr
.B =1
.R  	receiver interval
.TP
.I int    
.B nds
.B =
.R  	source interval in number of dx
.TP
.I int    
.B nr0
.B =0
.R  	receiver starting point in rnx
.TP
.I int    
.B ntau
.B =
.R  	number of time-shift
.TP
.I int    
.B pad1
.B =1
.R  	padding factor on the first axis
.TP
.I string 
.B path1
.B =
.R  	path of left matrices './mat/left'
.TP
.I string 
.B path2
.B =
.R  	path of right matrices './mat/left'
.TP
.I int    
.B rectx
.B =2
.R  	source smoothing in x-direction
.TP
.I int    
.B rectz
.B =2
.R  	source smoothing in z-direction
.TP
.I int    
.B repeat
.B =2
.R  	repeat numbers of source smoothing
.TP
.I int    
.B rnx
.B =
.R  	coverage area of one shot
.TP
.I int    
.B scalet
.B =1
.R  	wavefield storage interval
.TP
.I int    
.B snap
.B =100
.R  	wavefield output interval when wantwf=y
.TP
.I int    
.B snapshot
.B =0
.R  	print out the wavefield snapshots of this shot
.TP
.I int    
.B spx
.B =
.R  	horizontal location of source
.TP
.I int    
.B spz
.B =
.R  	depth of source
.TP
.I float  
.B srctrunc
.B =0.4
.R  	source truncation
.TP
.I int    
.B taper
.B =0
.R  	if not 0, tapering in the frequency domain
.TP
.I float  
.B tau0
.B =
.R  	origin of time-shift
.TP
.I float  
.B thresh
.B =0.92
.R  	tapering threshold
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I bool   
.B wantwf
.B =n
.R  [y/n]	if true, output wavefield of a certain (snapshot=) shot
.SH SOURCE
.I user/zhiguang/Mmpilrrtm_ts.c
.SH VERSION
4.2-git
