.TH sfmpihello 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmpihello \- MPI example, summation of vectors c = a + b 
.SH SYNOPSIS
.B sfmpihello b=bin.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B b
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/bash/Mmpihello.c
.SH VERSION
4.2-git
