.TH sfmpifwigrad 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmpifwigrad \- Calculate acoustic FWI gradient with the prepared adjoint source 
.SH SYNOPSIS
.B sfmpifwigrad Fvel=Fv.rsf Fwavelet=Fw.rsf Fadj=Fadj.rsf Fgrad=Fgrad.rsf Fwfl1=Fwfl1.rsf Fwfl2=Fwfl2.rsf ns= ds= s0= sz=5 nr=nx dr=dx r0=x0 rz=5 frectx=2 frectz=2 nb=100 coef=0.002
.SH PARAMETERS
.PD 0
.TP
.I file   
.B Fadj
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Fgrad
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Fvel
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Fwavelet
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Fwfl1
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Fwfl2
.B =
.R  	auxiliary output file name
.TP
.I float  
.B coef
.B =0.002
.R  	absorbing boundary coefficient
.TP
.I float  
.B dr
.B =dx
.R  	receiver interval
.TP
.I float  
.B ds
.B =
.R  	shot interval
.TP
.I int    
.B frectx
.B =2
.R  	source smoothing in x
.TP
.I int    
.B frectz
.B =2
.R  	source smoothing in z
.TP
.I int    
.B nb
.B =100
.R  	boundary width
.TP
.I int    
.B nr
.B =nx
.R  	number of receiver
.TP
.I int    
.B ns
.B =
.R  	shot number
.TP
.I float  
.B r0
.B =x0
.R  	receiver origin
.TP
.I int    
.B rz
.B =5
.R  	receiver depth
.TP
.I float  
.B s0
.B =
.R  	shot origin
.TP
.I int    
.B sz
.B =5
.R  	source depth
.SH SOURCE
.I user/zhiguang/Mmpifwigrad.c
.SH VERSION
4.2-git
