.TH sfmqrbf 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmqrbf \- 
.SH SYNOPSIS
.B sfmqrbf < cubea.rsf > rbf_out.rsf < othera.rsf xl= il= eps= boundary= other=
.SH COMMENTS
Inverse Multiquadratic Radial Basis Function

1/sqrt(1 + (eps*r)^2) where r is distance from source

.SH PARAMETERS
.PD 0
.TP
.I int    
.B boundary
.B =
.R  	Scalar factor
.TP
.I float  
.B eps
.B =
.R  	Scalar factor
.TP
.I int    
.B il
.B =
.R  	n3 location of source
.TP
.I string 
.B other
.B =
.R  	Boundary map
.TP
.I int    
.B xl
.B =
.R  	n2 location of source
.SH SOURCE
.I user/sbader/Mmqrbf.py
.SH VERSION
4.2-git
