.TH sfmshots 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmshots \- 2-D prestack forward modeling using sponge ABC using 4-th order FD
.SH SYNOPSIS
.B sfmshots < vinit.rsf > shots.rsf amp=1000 fm=10 nb=30 dt= nt= ns= ng= jsx= jsz=0 jgx=1 jgz=0 sxbeg= szbeg= gxbeg= gzbeg= csdgather=n mute=n vmute=1500 tdmute=2.0/(fm*dt)
.SH COMMENTS
NB: prepare high quality prestack seismic data for LSRTM and FWI
Top boundary is free surface (no ABC applied)!

.SH PARAMETERS
.PD 0
.TP
.I float  
.B amp
.B =1000
.R  	maximum amplitude of ricker
.TP
.I bool   
.B csdgather
.B =n
.R  [y/n]	default, common shot-gather; if n, record at every point
.TP
.I float  
.B dt
.B =
.R  	time interval
.TP
.I float  
.B fm
.B =10
.R  	dominant freq of ricker
.TP
.I int    
.B gxbeg
.B =
.R  	x-begining index of receivers, starting from 0
.TP
.I int    
.B gzbeg
.B =
.R  	z-begining index of receivers, starting from 0
.TP
.I int    
.B jgx
.B =1
.R  	receiver x-axis jump interval
.TP
.I int    
.B jgz
.B =0
.R  	receiver z-axis jump interval
.TP
.I int    
.B jsx
.B =
.R  	source x-axis  jump interval
.TP
.I int    
.B jsz
.B =0
.R  	source z-axis jump interval
.TP
.I bool   
.B mute
.B =n
.R  [y/n]	if yes, muting the direct arrivals
.TP
.I int    
.B nb
.B =30
.R  	thickness of sponge ABC
.TP
.I int    
.B ng
.B =
.R  	total receivers in each shot
.TP
.I int    
.B ns
.B =
.R  	total shots
.TP
.I int    
.B nt
.B =
.R  	total modeling time steps
.TP
.I int    
.B sxbeg
.B =
.R  	x-begining index of sources, starting from 0
.TP
.I int    
.B szbeg
.B =
.R  	z-begining index of sources, starting from 0
.TP
.I int    
.B tdmute
.B =2.0/(fm*dt)
.R  	number of deleyed time samples to mute
.TP
.I float  
.B vmute
.B =1500
.R  	muting velocity to remove the low-freq artifacts, unit=m/s
.SH SOURCE
.I user/pyang/Mmshots.c
.SH VERSION
4.2-git
