.TH sfmtm 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmtm \- 1-D and 2-D modified-trimmed-mean (MTM) filtering. 
.SH SYNOPSIS
.B sfmtm < in.rsf > out.rsf nfw1= nfw2=1 pclip= boundary=n verb=n type=
.SH COMMENTS
Also called range-trimmed-mean filter
1D filter (nfw2=1); 2D filter (otherwise)
median filter (pclip=0.); mean filter (pclip=100.)

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B boundary
.B =n
.R  [y/n]	if y, boundary is data, whereas zero
.TP
.I int    
.B nfw1
.B =
.R  	filter-window length in n1 direction (positive and odd integer)
.TP
.I int    
.B nfw2
.B =1
.R  	filter-window length in n2 direction (default=1, 1D case)
.TP
.I float  
.B pclip
.B =
.R  	0.0 <= pclip <= 100.0: median filter (pclip=0.); mean filter (pclip=100.)
.TP
.I string 
.B type
.B =
.R  	[rectangular,cross] 2-D window type, the default is rectangular
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/yliu/Mmtm.c
.SH VERSION
4.2-git
