.TH sfmulawefd2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmulawefd2d \- 2D multisource acoustic time-domain FD modeling for testing
.SH SYNOPSIS
.B sfmulawefd2d < Fwav.rsf vel=Fvel.rsf sou1=Fsou1.rsf sou2=Fsou2.rsf rec=Frec.rsf > Fdat.rsf wfl=Fwfl.rsf den=Fden.rsf verb=n snap=n free=n dabc=n cden=n jdata=1 jsnap=nt nqz=sf_n(az) nqx=sf_n(ax) oqz=sf_o(az) oqx=sf_o(ax)
.SH COMMENTS
4th order in space, 2nd order in time. Absorbing boundary conditions.
Invisible parameter due to self-doc parsing bug: 
nb=[2] Boundary padding in grid points 
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B cden
.B =n
.R  [y/n]	Constant density
.TP
.I bool   
.B dabc
.B =n
.R  [y/n]	Absorbing BC
.TP
.I file   
.B den
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B free
.B =n
.R  [y/n]	Free surface flag
.TP
.I int    
.B jdata
.B =1
.R  	# of t steps at which to save receiver data
.TP
.I int    
.B jsnap
.B =nt
.R  	# of t steps at which to save wavefield
.TP
.I int    
.B nqx
.B =sf_n(ax)
.R  	Saved wfld window nx
.TP
.I int    
.B nqz
.B =sf_n(az)
.R  	Saved wfld window nz
.TP
.I float  
.B oqx
.B =sf_o(ax)
.R  	Saved wfld window ox
.TP
.I float  
.B oqz
.B =sf_o(az)
.R  	Saved wfld window oz
.TP
.I file   
.B rec
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B snap
.B =n
.R  [y/n]	Wavefield snapshots flag
.TP
.I file   
.B sou1
.B =
.R  	auxiliary input file name
.TP
.I file   
.B sou2
.B =
.R  	auxiliary input file name
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	Verbosity flag
.TP
.I file   
.B wfl
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/chenyk/Mmulawefd2d.c
.SH VERSION
4.2-git
