.TH sfmulticheck 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmulticheck \- Check whether all values in a dataset are a multiple of a factor or not 
.SH SYNOPSIS
.B sfmulticheck < in.rsf i_fac=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B i_fac
.B =
.R  
.SH SOURCE
.I user/ivlad/Mmulticheck.c
.SH VERSION
4.2-git
