.TH sfmvo1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmvo1 \- Calculate MVO and PVO curve of CSEM data (another version). 
.SH SYNOPSIS
.B sfmvo1 < in.rsf > out.rsf opt=y log=y mvo=y f=0.08 nnw=1600 n=1
.SH PARAMETERS
.PD 0
.TP
.I float  
.B f
.B =0.08
.R  	calculate frequency
.TP
.I bool   
.B log
.B =y
.R  [y/n]	if y, calculate logarithm of MVO
.TP
.I bool   
.B mvo
.B =y
.R  [y/n]	if y, MVO curve; otherwise, PVO curve
.TP
.I int    
.B n
.B =1
.R  	number of window period
.TP
.I int    
.B nnw
.B =1600
.R  	sample window
.TP
.I bool   
.B opt
.B =y
.R  [y/n]	if y, determine optimal size for efficiency
.SH SOURCE
.I user/yliu/Mmvo1.c
.SH VERSION
4.2-git
