.TH sfmythresh 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfmythresh \- Generalized thresholding operator
.SH SYNOPSIS
.B sfmythresh < in.rsf > out.rsf pclip=99. p=0.35 mode=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B mode
.B =
.R  	thresholding mode='hard', 'soft','pthresh' or 'exp';
       'hard', hard thresholding;	'soft', soft thresholding; 
       'pthresh', generalized quasi-p; 'exp', exponential shrinkage
.TP
.I float  
.B p
.B =0.35
.R  	norm=p, where 0<p<=1
.TP
.I float  
.B pclip
.B =99.
.R  	percentage to clip
.SH SOURCE
.I user/pyang/Mmythresh.c
.SH VERSION
4.2-git
