.TH sfndsmooth 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfndsmooth \- N-D non-stationary triangle smoothing derivative. 
.SH SYNOPSIS
.B sfndsmooth < in.rsf > out.rsf ider=1 repeat=1 nderiv=6 rect#= shift#=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B ider
.B =1
.R  	direction of the derivative (0 means no derivative)
.TP
.I int    
.B nderiv
.B =6
.R  	derivative filter accuracy
.TP
.I string 
.B rect#
.B =
.R  	size of the smoothing stencil in #-th dimension /auxiliary input file/
.TP
.I int    
.B repeat
.B =1
.R  	repeat smoothing several times
.TP
.I string 
.B shift#
.B =
.R  	shifting of the smoothing stencil in #-th dimension /auxiliary input file/
.SH SOURCE
.I user/reem/Mndsmooth.c
.SH VERSION
4.2-git
