.TH sfndecon 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfndecon \- Random noise removal by nonstationary deconvolution 
.SH SYNOPSIS
.B sfndecon < inp.rsf > out.rsf filt=fil.rsf weight=wht.rsf eps=1.0f niter=10
.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =1.0f
.R  	regularization parameter
.TP
.I file   
.B filt
.B =
.R  	auxiliary input file name
.TP
.I int    
.B niter
.B =10
.R  	number of iterations
.TP
.I string 
.B weight
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/yliu/Mndecon.c
.SH VERSION
4.2-git
