.TH sfndix 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfndix \- Convert RMS to interval velocity using LS and shaping regularization with non-stationary smoothing 
.SH SYNOPSIS
.B sfndix < vrms.rsf > vint.rsf weight=weight.rsf vrmsout=vout.rsf niter=100 rect#= shift#=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B niter
.B =100
.R  	maximum number of iterations
.TP
.I string 
.B rect#
.B =
.R  	size of the smoothing stencil in #-th dimension /auxiliary input file/
.TP
.I string 
.B shift#
.B =
.R  	shifting of the smoothing stencil in #-th dimension /auxiliary input file/
.TP
.I string 
.B vrmsout
.B =
.R  	optionally, output predicted vrms (auxiliary output file name)
.TP
.I string 
.B weight
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/reem/Mndix.c
.SH VERSION
4.2-git
