.TH sfnderiv 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfnderiv \- 
.SH SYNOPSIS
.B sfnderiv < Fin.rsf > Fout.rsf order=1 length=5 scale=y axis=1
.SH COMMENTS
This program implements Fornberg, 1988
paper for digital differentiators
of arbitrary order.

So, it computes first, second, n derivative along axis 1,2 or 3.

.SH PARAMETERS
.PD 0
.TP
.I int    
.B axis
.B =1
.R  	apply differentiator along axis, default is fast axis
.TP
.I int    
.B length
.B =5
.R  	filter length, the lengthier the accurate, but also gets costlier
.TP
.I int    
.B order
.B =1
.R  	order of the derivative, default first derivative
.TP
.I bool   
.B scale
.B =y
.R  [y/n]	scales by 1/d^order
.SH SOURCE
.I user/ediazp/Mnderiv.py
.SH VERSION
4.2-git
