.TH sfnfmiss 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfnfmiss \- Missing data interpolation in freq domain. 
.SH SYNOPSIS
.B sfnfmiss < in.rsf > out.rsf filt=filt.rsf mask=mask.rsf exact=y verb=n niter=n1 ty=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B exact
.B =y
.R  [y/n]	If y, preserve the known data values
.TP
.I file   
.B filt
.B =
.R  	auxiliary input file name
.TP
.I string 
.B mask
.B =
.R  	optional input mask file for known data (auxiliary input file name)
.TP
.I int    
.B niter
.B =n1
.R  	number of iterations
.TP
.I string 
.B ty
.B =
.R  	Prediction type: all=backward+forward
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/gchliu/Mnfmiss.c
.SH VERSION
4.2-git Mmiss1.c 7107 2011-04-10 02:04:14Z ivlad
