.TH sfnmo3gma_adj 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfnmo3gma_adj \- Fwd-Adj of 3D NMO GMA for iterative LS coefficient solve 
.SH SYNOPSIS
.B sfnmo3gma_adj < inp.rsf > out.rsf gather=gather.rsf mod=inicoef.rsf t0sq=t0sqf.rsf adj=y nw=16
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =y
.R  [y/n]
.TP
.I file   
.B gather
.B =
.R  	auxiliary input file name
.TP
.I file   
.B mod
.B =
.R  	auxiliary input file name
.TP
.I int    
.B nw
.B =16
.R  	16 parameters of 3D GMA
.TP
.I file   
.B t0sq
.B =
.R  	auxiliary input file name
.SH SOURCE
.I system/seismic/Mnmo3gma_adj.c
.SH VERSION
4.2-git
