.TH sfnmo3gmaprep 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfnmo3gmaprep \- 3D NMO GMA  linearized operator preparation for lsfit
.SH SYNOPSIS
.B sfnmo3gmaprep < inp.rsf coef=inicoef.rsf > out.rsf fit=fit.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B coef
.B =
.R  	auxiliary input file name
.TP
.I file   
.B fit
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/zone/Mnmo3gmaprep.c
.SH VERSION
4.2-git
