.TH sfnmo3gmafit 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfnmo3gmafit \- 3D NMO GMA  linearized operator preparation for lsfit
.SH SYNOPSIS
.B sfnmo3gmafit < inp.rsf coef=inicoef.rsf > out.rsf fit=fit.rsf offsetx=offsx.rsf offsety=offsy.rsf verb=n gather=n
.SH PARAMETERS
.PD 0
.TP
.I file   
.B coef
.B =
.R  	auxiliary input file name
.TP
.I file   
.B fit
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B gather
.B =n
.R  [y/n]	Memory allocation
.TP
.I file   
.B offsetx
.B =
.R  	auxiliary input file name
.TP
.I file   
.B offsety
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]
.SH SOURCE
.I user/zone/Mnmo3gmafit.c
.SH VERSION
4.2-git
