.TH sfnmo3mcmc 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfnmo3mcmc \- 3D NMO GMA MCMC inversion with Metropolis rule (Mosegaard and Tarantola, 1995) 
.SH SYNOPSIS
.B sfnmo3mcmc < inp.rsf t0sq=t0sqf.rsf rangecoef=rangecoeff.rsf > out.rsf seed=time(NULL) sigma=1.0 saveiter=20 prior=n nmodel=1000
.SH PARAMETERS
.PD 0
.TP
.I int    
.B nmodel
.B =1000
.R  	Get the number of MC models
.TP
.I bool   
.B prior
.B =n
.R  [y/n]	generate prior or posterior
.TP
.I file   
.B rangecoef
.B =
.R  	auxiliary input file name
.TP
.I int    
.B saveiter
.B =20
.R  	save state every iter
.TP
.I int    
.B seed
.B =time(NULL)
.R  	random seed
.TP
.I float  
.B sigma
.B =1.0
.R  	noise variance
.TP
.I file   
.B t0sq
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/zone/Mnmo3mcmc.c
.SH VERSION
4.2-git
