.TH sfnonloc 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfnonloc \- Non-local (Bilateral) smoothing. 
.SH SYNOPSIS
.B sfnonloc < inp.rsf > out.rsf ns= bx= gauss=n repeat=1 ax=
.SH COMMENTS
Tomasi, C., and R. Manduchi, 1998, Bilateral filtering 
for gray and color images: Proceedings of the 1998 
IEEE International Conference on Computer Vision, 
IEEE, 836-846
.SH PARAMETERS
.PD 0
.TP
.I float  
.B ax
.B =
.R  	Gaussian weight for the range distance
.TP
.I float  
.B bx
.B =
.R  	exponential weight for the domain distance (different if gaussian)
.TP
.I bool   
.B gauss
.B =n
.R  [y/n]	if y, Gaussian weight, whereas Triangle weight
.TP
.I int    
.B ns
.B =
.R  	spray radius
.TP
.I int    
.B repeat
.B =1
.R  	repeat filtering several times
.SH SOURCE
.I user/yliu/Mnonloc.c
.SH VERSION
4.2-git
