.TH sfnorsar 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfnorsar \- Traveltime and amplitude estimation using wavefront construction. 
.SH SYNOPSIS
.B sfnorsar < inp.rsf ampl=ampl.rsf time=time.rsf dirx=dirx.rsf dirz=dirz.rsf srcx=srcx.rsf srcz=srcz.rsf invgeo=invgeo.rsf nang=10 rays=0 wfront=0 gap=1 inter=1 DSmax=5 dt=0.0005 nt=5 nrmax=2000 lomx=1 first=1 nou=6 gnx=nx gnz=nz gdx=dx gdz=dz gox=ox goz=oz N=3 TETAMAX=1.5 alpha2=4.0 freq=100. prcube=0 pr=0 ds=1. os=0. depth=dz
.SH PARAMETERS
.PD 0
.TP
.I float  
.B DSmax
.B =5
.R  	Maximum distance between contiguos points of a wavefront
.TP
.I int    
.B N
.B =3
.R  	Number of control points
.TP
.I float  
.B TETAMAX
.B =1.5
.R  	Truncation parameter
.TP
.I float  
.B alpha2
.B =4.0
.R  	Width of gaussian weighting function
.TP
.I file   
.B ampl
.B =
.R  	auxiliary output file name
.TP
.I float  
.B depth
.B =dz
.R  	Depth location of sources
.TP
.I file   
.B dirx
.B =
.R  	auxiliary output file name
.TP
.I file   
.B dirz
.B =
.R  	auxiliary output file name
.TP
.I float  
.B ds
.B =1.
.R  	interval between sources
.TP
.I float  
.B dt
.B =0.0005
.R  	time step
.TP
.I int    
.B first
.B =1
.R  	Obtain first arrivals only
.TP
.I float  
.B freq
.B =100.
.R  	Pseudo-frequency of waverays
.TP
.I int    
.B gap
.B =1
.R  	Draw wavefronts every gap intervals
.TP
.I float  
.B gdx
.B =dx
.R  
.TP
.I float  
.B gdz
.B =dz
.R  
.TP
.I int    
.B gnx
.B =nx
.R  	Coordinates of output grid
.TP
.I int    
.B gnz
.B =nz
.R  
.TP
.I float  
.B gox
.B =ox
.R  
.TP
.I float  
.B goz
.B =oz
.R  	GET LOMAX SPECIFIC PARAMETERS
.TP
.I int    
.B inter
.B =1
.R  	If use linear interpolation
.TP
.I file   
.B invgeo
.B =
.R  	auxiliary output file name
.TP
.I int    
.B lomx
.B =1
.R  	Use Lomax's waveray method
.TP
.I int    
.B nang
.B =10
.R  	Number of take-off angles
.TP
.I int    
.B nou
.B =6
.R  	GET GRIDDING PARAMETERS
.TP
.I int    
.B nrmax
.B =2000
.R  	Maximum number of points that define a wavefront
.TP
.I int    
.B nt
.B =5
.R  	Number of time steps between wavefronts
.TP
.I float  
.B os
.B =0.
.R  	first source location
.TP
.I int    
.B pr
.B =0
.R  	For debugging porpouses
.TP
.I int    
.B prcube
.B =0
.R  	For debugging porpouses
.TP
.I int    
.B rays
.B =0
.R  	If draw rays
.TP
.I file   
.B srcx
.B =
.R  	auxiliary output file name
.TP
.I file   
.B srcz
.B =
.R  	auxiliary output file name
.TP
.I file   
.B time
.B =
.R  	auxiliary output file name
.TP
.I int    
.B wfront
.B =0
.R  	If draw wavefronts
.SH SOURCE
.I user/urdaneta/Mnorsar.c
.SH VERSION
4.2-git
