.TH sfnormalize 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfnormalize \- Normalization of data batches up to a given axis.
.SH SYNOPSIS
.B sfnormalize < in.rsf > out.rsf axis=1 type=
.SH COMMENTS
Can either normalize to be between [0,1] with type=m
or have mean=0, std dev = 1 with type=s 
.SH PARAMETERS
.PD 0
.TP
.I int    
.B axis
.B =1
.R  	normalize so axes groups up to this dimension have mean 0, std deviation 1
.TP
.I string 
.B type
.B =
.R  	'm' means data are biased and scaled to be between 0 and 1 
       's' means data are biased and scaled to have mean=0, std dev = 1
.SH SOURCE
.I user/luke/Mnormalize.c
.SH VERSION
4.2-git
