.TH sfnorm 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfnorm \- Normalize the data. 
.SH SYNOPSIS
.B sfnorm > outp.rsf < inp.rsf apply=apply.rsf max=
.SH COMMENTS
Normalize by dividing the data set by its absolute maximum value. 
.SH PARAMETERS
.PD 0
.TP
.I file   
.B apply
.B =
.R  	auxiliary input file name
.TP
.I float  
.B max
.B =
.R  
.SH SOURCE
.I user/chenyk/Mnorm.c
.SH VERSION
4.2-git
