.TH sfnpef5_recon 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfnpef5_recon \- 5-D missing data interpolation with non-stationary PEFs. 
.SH SYNOPSIS
.B sfnpef5_recon < in.rsf filt=fil.rsf > out.rsf mask=mask.rsf niter=100 exact=y eps=0. verb=n
.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =0.
.R  	regularization parameter
.TP
.I bool   
.B exact
.B =y
.R  [y/n]	If y, preserve the known data values
.TP
.I file   
.B filt
.B =
.R  	auxiliary input file name
.TP
.I string 
.B mask
.B =
.R  	optional input mask file for known data (auxiliary input file name)
.TP
.I int    
.B niter
.B =100
.R  	Number of iterations
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/chenyk/Mnpef5_recon.c
.SH VERSION
4.2-git
