.TH sfnpyConv 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfnpyConv \- 
.SH SYNOPSIS
.B sfnpyConv < Fa.rsf flt=Fb.rsf > Fc.rsf norm=n mode=same
.SH COMMENTS
Implements conv(a,b) along the fast axis 
a [file] : is taken from stdin
b [file] : is taken from  "flt"
Requires both files to have the same sampling interval

mode [string]:
'full': returns an M+N-1 array, boundary effects are visible.
'same': returns a max(M,N) array, boundary effects are visible.

.SH PARAMETERS
.PD 0
.TP
.I file   
.B flt
.B =
.R  	auxiliary input file name
.TP
.I string 
.B mode
.B =same
.R  
.TP
.I bool   
.B norm
.B =n
.R  [y/n]	normalize output
.SH SOURCE
.I user/ediazp/MnpyConv.py
.SH VERSION
4.2-git
