.TH sfnshape 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfnshape \- Nonstationary autoregressive shaping 
.SH SYNOPSIS
.B sfnshape < inp.rsf > out.rsf filt=fil.rsf eps=1.0f rect=1
.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =1.0f
.R  	regularization parameter
.TP
.I file   
.B filt
.B =
.R  	auxiliary input file name
.TP
.I int    
.B rect
.B =1
.R  	shaping radius
.SH SOURCE
.I user/yliu/Mnshape.c
.SH VERSION
4.2-git
