.TH sfnsmooth 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfnsmooth \- N-D non-stationary smoothing. 
.SH SYNOPSIS
.B sfnsmooth < in.rsf > out.rsf repeat=1 rect#= shift#=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B rect#
.B =
.R  	size of the smoothing stencil in #-th dimension /auxiliary input file/
.TP
.I int    
.B repeat
.B =1
.R  	repeat filtering several times
.TP
.I string 
.B shift#
.B =
.R  	shifting of the smoothing stencil in #-th dimension /auxiliary input file/
.SH SOURCE
.I user/fomels/Mnsmooth.c
.SH VERSION
4.2-git Msmooth.c 691 2004-07-04 19:28:08Z fomels
