.TH sfocparcel 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfocparcel \- Patching test for out-of-core patching. 
.SH SYNOPSIS
.B sfocparcel < in.rsf > out.rsf w= k=
.SH PARAMETERS
.PD 0
.TP
.I ints   
.B k
.B =
.R  	 [dim]
.TP
.I ints   
.B w
.B =
.R  	 [dim]
.SH SOURCE
.I user/fomels/Mocparcel.c
.SH VERSION
4.2-git Mparcel.c 691 2004-07-04 19:28:08Z fomels
