.TH sfoclet 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfoclet \- Seislet transform in log-stretched frequency-offset-midpoint domain 
.SH SYNOPSIS
.B sfoclet < in.rsf > out.rsf inv=y adj=y unit=n verb=n type=
.SH COMMENTS
Forward transform (adj=y inv=y)   m=T[d]
Adjoint transform (adj=y inv=n)   m=T^(-1)'[d]
Inverse transform (adj=n inv=y/n) d=T^(-1)[m]

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =y
.R  [y/n]	if y, do adjoint transform
.TP
.I bool   
.B inv
.B =y
.R  [y/n]	if y, do inverse transform
.TP
.I string 
.B type
.B =
.R  	[haar,linear,biorthogonal] wavelet type, the default is linear
.TP
.I bool   
.B unit
.B =n
.R  [y/n]	if y, use unitary scaling
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/yliu/Moclet.c
.SH VERSION
4.2-git
