.TH sfocor3d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfocor3d \- 
.SH SYNOPSIS
.B sfocor3d < Fwfl.rsf opr=Fopr.rsf > Fcor.rsf verb=n adj=n ocox=0.0 ocoy=0.0 ocoz=0.0 ntlag=100 nxlag=0 nylag=0 nzlag=0
.SH COMMENTS
Oriented correlation
wfl [file] : is taken from stdin
opr [file] : is taken from  "opr"
requires both files to have the same dimensions
correlation is computed at coordinates (ocox,ocoy,ocoz)
the (half) lags are: ntlag, nxlag, nylag, nzlag

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag
.TP
.I int    
.B ntlag
.B =100
.R  
.TP
.I int    
.B nxlag
.B =0
.R  
.TP
.I int    
.B nylag
.B =0
.R  
.TP
.I int    
.B nzlag
.B =0
.R  
.TP
.I float  
.B ocox
.B =0.0
.R  
.TP
.I float  
.B ocoy
.B =0.0
.R  
.TP
.I float  
.B ocoz
.B =0.0
.R  
.TP
.I file   
.B opr
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/psava/Mocor3d.py
.SH VERSION
4.2-git
