.TH sfoctentwt 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfoctentwt \- Tent-like weight for out-of-core patching. 
.SH SYNOPSIS
.B sfoctentwt > wallwt.rsf windwt=windwt.rsf w= k= a= center= dim=2
.SH PARAMETERS
.PD 0
.TP
.I ints   
.B a
.B =
.R  	filter size  [dim]
.TP
.I ints   
.B center
.B =
.R  	 [dim]
.TP
.I int    
.B dim
.B =2
.R  	number of dimensions
.TP
.I ints   
.B k
.B =
.R  	number of windows  [dim]
.TP
.I ints   
.B w
.B =
.R  	window size  [dim]
.TP
.I file   
.B windwt
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/fomels/Moctentwt.c
.SH VERSION
4.2-git Mtentwt.c 691 2004-07-04 19:28:08Z fomels
