.TH sfodip 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfodip \- omnidirectional dip estimation  
.SH SYNOPSIS
.B sfodip < in.rsf > out.rsf m=1 n=1 rect1=0 rect2=0 niter=5 liter=20 radius=1.0 eta=0.5 dip0=0.0 verb=n slope=n interp=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dip0
.B =0.0
.R  	starting dip
.TP
.I float  
.B eta
.B =0.5
.R  	steps for iteration
.TP
.I string 
.B interp
.B =
.R  	interpolation method: maxflat lagrange bspline
.TP
.I int    
.B liter
.B =20
.R  	number of linear iterations
.TP
.I int    
.B m
.B =1
.R  	b[-m, ... ,n]
.TP
.I int    
.B n
.B =1
.R  	b[-m, ... ,n]
.TP
.I int    
.B niter
.B =5
.R  	number of iterations
.TP
.I float  
.B radius
.B =1.0
.R  	interpolating radius for opwd
.TP
.I int    
.B rect1
.B =0
.R  	dip smoothness on 1st axis
.TP
.I int    
.B rect2
.B =0
.R  	dip smoothness on 2nd axis
.TP
.I bool   
.B slope
.B =n
.R  [y/n]	slope (y) or dip (n) estimation
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/chen/Modip.c
.SH VERSION
4.2-git
