.TH sfofilp 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfofilp \- 2-D missing data interpolation by differential offset continuation. 
.SH SYNOPSIS
.B sfofilp < in.rsf > out.rsf known=known.rsf niter=10 simple=n
.SH PARAMETERS
.PD 0
.TP
.I file   
.B known
.B =
.R  	auxiliary input file name
.TP
.I int    
.B niter
.B =10
.R  	number of iterations
.TP
.I bool   
.B simple
.B =n
.R  [y/n]	if y, use simple h derivative for regularization
.SH SOURCE
.I user/fomels/Mofilp.c
.SH VERSION
4.2-git
