.TH sfofd2_5 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfofd2_5 \- 2-D Fourth-order Optimized Finite-difference wave extrapolation 
.SH SYNOPSIS
.B sfofd2_5 > out.rsf vel=vel.rsf < source.rsf G=G.rsf dt= nt= isx= isz=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B G
.B =
.R  	auxiliary input file name
.TP
.I float  
.B dt
.B =
.R  
.TP
.I int    
.B isx
.B =
.R  
.TP
.I int    
.B isz
.B =
.R  
.TP
.I int    
.B nt
.B =
.R  
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/songxl/Mofd2_5.c
.SH VERSION
4.2-git
