.TH sfofsemb 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfofsemb \- Objective function of dip estimation with semblance. 
.SH SYNOPSIS
.B sfofsemb < in.rsf > of.rsf np=100 p0= dp=2*p0/(1.-np)
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dp
.B =2*p0/(1.-np)
.R  	dip sampling
.TP
.I int    
.B np
.B =100
.R  	number of dips
.TP
.I float  
.B p0
.B =
.R  	dip origin
.SH SOURCE
.I user/fomels/Mofsemb.c
.SH VERSION
4.2-git
