.TH sfoff2abs3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfoff2abs3 \- Transform vector-offset to absolute-offset 
.SH SYNOPSIS
.B sfoff2abs3 < Fm.rsf > Fd.rsf verb=n nw=4 nh=nhx + ohx/dhx oh=0 dh=dhx na=180 oa=0. da=2. nb=180 ob=0. db=2.
.SH COMMENTS
h = sqrt(hx^2+hy^2+hz^2)
pcs 2005 

.SH PARAMETERS
.PD 0
.TP
.I float  
.B da
.B =2.
.R  
.TP
.I float  
.B db
.B =2.
.R  
.TP
.I float  
.B dh
.B =dhx
.R  
.TP
.I int    
.B na
.B =180
.R  
.TP
.I int    
.B nb
.B =180
.R  
.TP
.I int    
.B nh
.B =nhx + ohx/dhx
.R  
.TP
.I int    
.B nw
.B =4
.R  	spline order
.TP
.I float  
.B oa
.B =0.
.R  
.TP
.I float  
.B ob
.B =0.
.R  
.TP
.I float  
.B oh
.B =0
.R  
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/psava/Moff2abs3.c
.SH VERSION
4.2-git
