.TH sfoff2abs 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfoff2abs \- Transform vector-offset to absolute-offset 
.SH SYNOPSIS
.B sfoff2abs < Fd.rsf > Fm.rsf verb=n nw=4 nh=nhx + ohx/dhx oh=0 dh=dhx
.SH COMMENTS
h = sqrt(hx^2+hy^2+hz^2)
pcs 2005 

.SH PARAMETERS
.PD 0
.TP
.I float  
.B dh
.B =dhx
.R  
.TP
.I int    
.B nh
.B =nhx + ohx/dhx
.R  
.TP
.I int    
.B nw
.B =4
.R  	spline order
.TP
.I float  
.B oh
.B =0
.R  
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/psava/Moff2abs.c
.SH VERSION
4.2-git
