.TH sfofpwd 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfofpwd \- Objective function of dip estimation with PWD filters. 
.SH SYNOPSIS
.B sfofpwd < in.rsf > of.rsf np=100 p0= dp=2*p0/(1.-np) drift=n order=1 nj=1
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dp
.B =2*p0/(1.-np)
.R  	dip sampling
.TP
.I bool   
.B drift
.B =n
.R  [y/n]	if shift filter
.TP
.I int    
.B nj
.B =1
.R  	antialiasing
.TP
.I int    
.B np
.B =100
.R  	number of dips
.TP
.I int    
.B order
.B =1
.R  [1,2,3]	accuracy order
.TP
.I float  
.B p0
.B =
.R  	dip origin
.SH SOURCE
.I user/pwd/Mofpwd.c
.SH VERSION
4.2-git
