.TH sfopwd2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfopwd2 \- 2-D omnidirectional plane wave destruction. 
.SH SYNOPSIS
.B sfopwd2 < in.rsf dip=ang.rsf > out.rsf order=1
.SH PARAMETERS
.PD 0
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I int    
.B order
.B =1
.R  	accuracy
.SH SOURCE
.I user/pwd/Mopwd2.c
.SH VERSION
4.2-git
