.TH sfopsmigrk 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfopsmigrk \- Shot-recorder Oriented prestack migration data is (shots x recs x time). 
.SH SYNOPSIS
.B sfopsmigrk < dist.rsf time=time.rsf dept=dept.rsf > imag.rsf data=data.rsf tolz=2.0 is_offset=n
.SH PARAMETERS
.PD 0
.TP
.I file   
.B data
.B =
.R  	auxiliary input file name
.TP
.I file   
.B dept
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B is_offset
.B =n
.R  [y/n]
.TP
.I file   
.B time
.B =
.R  	auxiliary input file name
.TP
.I float  
.B tolz
.B =2.0
.R  
.SH SOURCE
.I user/roman/Mopsmigrk.c
.SH VERSION
4.2-git
