.TH sfopame2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfopame2d \- 2-D opam for elastic wave modeling and vector field decompostion 
.SH SYNOPSIS
.B sfopame2d vp=fvelp.rsf vs=fvels.rsf < fsource.rsf > fwavup.rsf wavwp=fwavwp.rsf wavus=fwavus.rsf wavws=fwavws.rsf wavu=fwavu.rsf wavw=fwavw.rsf Guxxl=Guxxl.rsf Guxxr=Guxxr.rsf Gwxzpl=Gwxzpl.rsf Gwxzpr=Gwxzpr.rsf Guxzpl=Guxzpl.rsf Guxzpr=Guxzpr.rsf Gwzzl=Gwzzl.rsf Gwzzr=Gwzzr.rsf Guzzl=Guzzl.rsf Guzzr=Guzzr.rsf Gwxzsl=Gwxzsl.rsf Gwxzsr=Gwxzsr.rsf Gwxxl=Gwxxl.rsf Gwxxr=Gwxxr.rsf Guxzsl=Guxzsl.rsf Guxzsr=Guxzsr.rsf opt=0 dt= nt= isx= isz= nbt=44 nbb=44 nxl=44 nxr=44 czt=0.01 czb=0.01 cxl=0.01 cxr=0.01 cmplx=n pad1=1 snap=1
.SH PARAMETERS
.PD 0
.TP
.I file   
.B Guxxl
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Guxxr
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Guxzpl
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Guxzpr
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Guxzsl
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Guxzsr
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Guzzl
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Guzzr
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Gwxxl
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Gwxxr
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Gwxzpl
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Gwxzpr
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Gwxzsl
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Gwxzsr
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Gwzzl
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Gwzzr
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B cmplx
.B =n
.R  [y/n]	use complex FFT
.TP
.I float  
.B cxl
.B =0.01
.R  	decaying parameter
.TP
.I float  
.B cxr
.B =0.01
.R  	decaying parameter
.TP
.I float  
.B czb
.B =0.01
.R  	decaying parameter
.TP
.I float  
.B czt
.B =0.01
.R  	decaying parameter
.TP
.I float  
.B dt
.B =
.R  
.TP
.I int    
.B isx
.B =
.R  
.TP
.I int    
.B isz
.B =
.R  
.TP
.I int    
.B nbb
.B =44
.R  
.TP
.I int    
.B nbt
.B =44
.R  
.TP
.I int    
.B nt
.B =
.R  
.TP
.I int    
.B nxl
.B =44
.R  
.TP
.I int    
.B nxr
.B =44
.R  	assume ABC pars are the same
.TP
.I int    
.B opt
.B =0
.R  	if y, determine optimal size for efficiency
.TP
.I int    
.B pad1
.B =1
.R  	padding factor on the first axis
.TP
.I int    
.B snap
.B =1
.R  
.TP
.I file   
.B vp
.B =
.R  	auxiliary input file name
.TP
.I file   
.B vs
.B =
.R  	auxiliary input file name
.TP
.I file   
.B wavu
.B =
.R  	auxiliary output file name
.TP
.I file   
.B wavus
.B =
.R  	auxiliary output file name
.TP
.I file   
.B wavw
.B =
.R  	auxiliary output file name
.TP
.I file   
.B wavwp
.B =
.R  	auxiliary output file name
.TP
.I file   
.B wavws
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/junyan/Mopame2d.c
.SH VERSION
4.2-git
