.TH sfort3de 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfort3de \- 3-D three-components wavefield modeling using elastic wave equation in tilted ORT media.
.SH SYNOPSIS
.B sfort3de < Fvp0.rsf vs0=Fvs0.rsf epsi1=Fep1.rsf epsi2=Fep2.rsf del1=Fde1.rsf del2=Fde2.rsf del3=Fde3.rsf gam1=Fga1.rsf gam2=Fga2.rsf the=Falpha.rsf the=Fthe.rsf phi=Fphi.rsf > Fo1.rsf FDElasticy=Fo2.rsf FDElasticz=Fo3.rsf ns=301 dt=0.001
.SH COMMENTS

Copyright (C) 2012 Tongji University, Shanghai, China 

Authors: Jiubing Cheng and Tengfei Wang

This code is first written by Tengfei Wang at Tongji University,
and then optimzied by Jiubing Cheng for Madagascar version at BEG,
University of Texas at Austin.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

.SH PARAMETERS
.PD 0
.TP
.I file   
.B FDElasticy
.B =
.R  	auxiliary output file name
.TP
.I file   
.B FDElasticz
.B =
.R  	auxiliary output file name
.TP
.I file   
.B del1
.B =
.R  	auxiliary input file name
.TP
.I file   
.B del2
.B =
.R  	auxiliary input file name
.TP
.I file   
.B del3
.B =
.R  	auxiliary input file name
.TP
.I float  
.B dt
.B =0.001
.R  
.TP
.I file   
.B epsi1
.B =
.R  	auxiliary input file name
.TP
.I file   
.B epsi2
.B =
.R  	auxiliary input file name
.TP
.I file   
.B gam1
.B =
.R  	auxiliary input file name
.TP
.I file   
.B gam2
.B =
.R  	auxiliary input file name
.TP
.I int    
.B ns
.B =301
.R  
.TP
.I file   
.B phi
.B =
.R  	auxiliary input file name
.TP
.I file   
.B the
.B =
.R  	auxiliary input file name
.TP
.I file   
.B vs0
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/chengjb/Mort3de.c
.SH VERSION
4.2-git
