.TH sforthowave 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sforthowave \- Simple 3-D wave propagation 
.SH SYNOPSIS
.B sforthowave < Fw.rsf > Fo.rsf ref=Fr.rsf snaps=snaps.rsf left=left.rsf right=right.rsf mid=mid.rsf verb=y cmplx=n pad1=1 snap=0
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B cmplx
.B =n
.R  [y/n]	use complex FFT
.TP
.I file   
.B left
.B =
.R  	auxiliary input file name
.TP
.I file   
.B mid
.B =
.R  	auxiliary input file name
.TP
.I int    
.B pad1
.B =1
.R  	padding factor on the first axis
.TP
.I file   
.B ref
.B =
.R  	auxiliary input file name
.TP
.I file   
.B right
.B =
.R  	auxiliary input file name
.TP
.I int    
.B snap
.B =0
.R  	interval for snapshots
.TP
.I file   
.B snaps
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity
.SH SOURCE
.I user/songxl/Morthowave.c
.SH VERSION
4.2-git
