.TH sforientation 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sforientation \- orientation estimation by structural gradient tensor 
.SH SYNOPSIS
.B sforientation < in.rsf > out.rsf weight=wgt.rsf azimuth=az.rsf rect1=0 rect2=0 rect3=0 order=2 interp= filt=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B azimuth
.B =
.R  	auxiliary output file name
.TP
.I string 
.B filt
.B =
.R  	filter type : ls, tls, tensor
.TP
.I string 
.B interp
.B =
.R  	interpolation method: maxflat lagrange bspline
.TP
.I int    
.B order
.B =2
.R  	approximating order of finite difference
.TP
.I int    
.B rect1
.B =0
.R  	smoothness on 1st axis
.TP
.I int    
.B rect2
.B =0
.R  	smoothness on 2nd axis
.TP
.I int    
.B rect3
.B =0
.R  	smoothness on 3rd axis
.TP
.I string 
.B weight
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/chen/Morientation.c
.SH VERSION
4.2-git
