.TH sforp 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sforp \- 2-D 10th-order Finite-difference dispersion
.SH SYNOPSIS
.B sforp > out.rsf < vel.rsf vx=2.1 vy=2.05 vz=2.0 e1=0.3 e2=0.1 e3=1.0 phi=45.0
.SH PARAMETERS
.PD 0
.TP
.I float  
.B e1
.B =0.3
.R  
.TP
.I float  
.B e2
.B =0.1
.R  
.TP
.I float  
.B e3
.B =1.0
.R  
.TP
.I float  
.B phi
.B =45.0
.R  
.TP
.I float  
.B vx
.B =2.1
.R  
.TP
.I float  
.B vy
.B =2.05
.R  
.TP
.I float  
.B vz
.B =2.0
.R  
.SH SOURCE
.I user/songxl/Morp.c
.SH VERSION
4.2-git
