.TH sfoshift1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfoshift1 \- Generate shifts with offset for 1-D regularized autoregression. 
.SH SYNOPSIS
.B sfoshift1 < in.rsf > shift.rsf ns= nf=1
.SH PARAMETERS
.PD 0
.TP
.I int    
.B nf
.B =1
.R  	offset of first shift
.TP
.I int    
.B ns
.B =
.R  	number of shifts
.SH SOURCE
.I user/yliu/Moshift1.c
.SH VERSION
4.2-git
