.TH sfpad2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpad2 \- Pad boundary 
.SH SYNOPSIS
.B sfpad2 < Fin.rsf > Fout.rsf top=0 bottom=0 left=0 right=0
.SH PARAMETERS
.PD 0
.TP
.I int    
.B bottom
.B =0
.R  
.TP
.I int    
.B left
.B =0
.R  
.TP
.I int    
.B right
.B =0
.R  
.TP
.I int    
.B top
.B =0
.R  
.SH SOURCE
.I user/zhiguang/Mpad2.c
.SH VERSION
4.2-git
