.TH sfpatch 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpatch \- Patching (N-dimensional). 
.SH SYNOPSIS
.B sfpatch < in.rsf > out.rsf n0= w= p= inv=n verb=n weight=n dim=dim0
.SH COMMENTS

w is window size (defaults to n1,n2,...)
p is number of patches in different dimensions (defaults to 1,1,...)

If inv=n, the number of output dimensions is twice the number of input dimensions.
If inv=y, the number of output dimensions is half the number of input dimensions.

September 2013 program of the month:
http://ahay.org/blog/2013/09/14/program-of-the-month-sfpatch/

.SH PARAMETERS
.PD 0
.TP
.I int    
.B dim
.B =dim0
.R  
.TP
.I bool   
.B inv
.B =n
.R  [y/n]	inverse or forward operation
.TP
.I ints   
.B n0
.B =
.R  	data dimensions (for inv=y)  [dim]
.TP
.I ints   
.B p
.B =
.R  	number of windows  [dim]
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I ints   
.B w
.B =
.R  	window size  [dim]
.TP
.I bool   
.B weight
.B =n
.R  [y/n]	if y, apply weighting to each patch
.SH USED IN
.TP
.I cup/rna2d/real
.TP
.I cup/rna2d/shot
.TP
.I cup/rna2d/simple
.TP
.I cup/rna3d/real
.SH SOURCE
.I user/fomels/Mpatch.c
.SH VERSION
4.2-git
