.TH sfpadzero 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpadzero \- Interpolation from a coarser grid to finer grid with zero padded 
.SH SYNOPSIS
.B sfpadzero < in.rsf > out.rsf scalex= scalez=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B scalex
.B =
.R  
.TP
.I int    
.B scalez
.B =
.R  
.SH SOURCE
.I user/zhiguang/Mpadzero.c
.SH VERSION
4.2-git
