.TH sfpadpt3D 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpadpt3D \- 
.SH SYNOPSIS
.B sfpadpt3D < Fin.rsf > Fou.rsf verb=n modTin= topoW= topo=
.SH COMMENTS
Write data datumed to windowed point cloud to original point cloud
Created by: Dylan Hickson, Colorado School of Mines
Created on: Mar 9, 2022

.SH PARAMETERS
.PD 0
.TP
.I string 
.B modTin
.B =
.R  
.TP
.I string 
.B topo
.B =
.R  	Local functions
.TP
.I string 
.B topoW
.B =
.R  
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/cwp/Mpadpt3D.py
.SH VERSION
4.2-git
