.TH sfpad2nextfastsize 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpad2nextfastsize \- How much to pad to get to next fast c2c FFT size (factors: 2,3 and 5)
.SH SYNOPSIS
.B sfpad2nextfastsize n=
.SH COMMENTS
Wrapper for kiss_fft_next_fast_size. 
.SH PARAMETERS
.PD 0
.TP
.I int    
.B n
.B =
.R  
.SH SOURCE
.I user/ivlad/Mpad2nextfastsize.c
.SH VERSION
4.2-git
