.TH sfpadfault 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpadfault \- Horizontally pad fault  
.SH SYNOPSIS
.B sfpadfault < in.rsf slip=slip.rsf > out.rsf mask=mask.rsf bound=bound.rsf dip=dip.rsf shift=shift.rsf newdip=newdip.rsf ppbig=ppbig.rsf extend=y mode=y conf=1 order=2
.SH PARAMETERS
.PD 0
.TP
.I file   
.B bound
.B =
.R  	auxiliary output file name
.TP
.I int    
.B conf
.B =1
.R  
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B extend
.B =y
.R  [y/n]
.TP
.I file   
.B mask
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B mode
.B =y
.R  [y/n]
.TP
.I file   
.B newdip
.B =
.R  	auxiliary output file name
.TP
.I int    
.B order
.B =2
.R  
.TP
.I file   
.B ppbig
.B =
.R  	auxiliary output file name
.TP
.I file   
.B shift
.B =
.R  	auxiliary input file name
.TP
.I file   
.B slip
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/zhiguang/Mpadfault.c
.SH VERSION
4.2-git
