.TH sfpchain 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpchain \- Nonstationary Prony by chain of PEFs 
.SH SYNOPSIS
.B sfpchain < inp.rsf pef=pef.rsf > out.rsf nc=1 verb=(bool) (1 == nt) niter=0 liter=50 rect=1
.SH PARAMETERS
.PD 0
.TP
.I int    
.B liter
.B =50
.R  	number of linear iterations
.TP
.I int    
.B nc
.B =1
.R  	number of components
.TP
.I int    
.B niter
.B =0
.R  	number of iterations
.TP
.I file   
.B pef
.B =
.R  	auxiliary output file name
.TP
.I int    
.B rect
.B =1
.R  	smoothing in time
.TP
.I bool   
.B verb
.B =(bool) (1 == nt)
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/fomels/Mpchain.c
.SH VERSION
4.2-git
