.TH sfpcrsurv3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpcrsurv3 \- Prepare survey info for 3-D angle-domain migration. 
.SH SYNOPSIS
.B sfpcrsurv3 < data.rsf > survey.rsf sxsy=sxsy.rsf gxgy=gxgy.rsf verb=n tri=n esmax=0.2 ehmax=0.1
.SH PARAMETERS
.PD 0
.TP
.I float  
.B ehmax
.B =0.1
.R  	Maximum edge length in the receiver triangulation
.TP
.I float  
.B esmax
.B =0.2
.R  	Maximum edge length in the shot triangulation
.TP
.I string 
.B gxgy
.B =
.R  	File with receiver coordinates (auxiliary input file name)
.TP
.I string 
.B sxsy
.B =
.R  	File with shot coordinates (auxiliary input file name)
.TP
.I bool   
.B tri
.B =n
.R  [y/n]	triangulation flag
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/cram/Mpcrsurv3.c
.SH VERSION
4.2-git
