.TH sfpcrdata2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpcrdata2 \- Prepare data for 2-D angle-domain migration. 
.SH SYNOPSIS
.B sfpcrdata2 < data.rsf > out.rsf verb=n absoff=n filter=y KMAH=y diff=y
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B KMAH
.B =y
.R  [y/n]	y - account for phase shifts due to KMAH index
.TP
.I bool   
.B absoff
.B =n
.R  [y/n]	y - absolute offset (default - relative to shot axis)
.TP
.I bool   
.B diff
.B =y
.R  [y/n]	y - apply half-order differentiation
.TP
.I bool   
.B filter
.B =y
.R  [y/n]	y - antialiasing filter for data
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/cram/Mpcrdata2.c
.SH VERSION
4.2-git
