.TH sfpdrscan2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpdrscan2d \- Velocity Scan by 2D Parametric Development of Reflections 
.SH SYNOPSIS
.B sfpdrscan2d < dataFile.rsf > outFile.rsf aux=auxFile.rsf po=shotStart_ pn=recNum_ pd=recStep_ vn=1 vo=1500 vd=50 wh=11
.SH PARAMETERS
.PD 0
.TP
.I string 
.B aux
.B =
.R  	output file containing semblance measure of CIGs stacking (auxiliary output file name)
.TP
.I float  
.B pd
.B =recStep_
.R  	increment of positions in stack section
.TP
.I int    
.B pn
.B =recNum_
.R  	number of positions in stack section
.TP
.I float  
.B po
.B =shotStart_
.R  	start position in stack section
.TP
.I float  
.B vd
.B =50
.R  	increment of velocities
.TP
.I int    
.B vn
.B =1
.R  	number of scanned velocities
.TP
.I float  
.B vo
.B =1500
.R  	start velocity
.TP
.I int    
.B wh
.B =11
.R  	height of a vertical window for semblance calculation
.SH SOURCE
.I user/aklokov/Mpdrscan2d.c
.SH VERSION
4.2-git
