.TH sfpdr2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpdr2d \- 2D Parametric Development of Reflections 
.SH SYNOPSIS
.B sfpdr2d < dataFile.rsf > outFile.rsf aux=auxFile.rsf vel=velFile.rsf po=shotStart_ pn=recNum_ pd=recStep_ wh=11
.SH PARAMETERS
.PD 0
.TP
.I string 
.B aux
.B =
.R  	output file containing semblance measure of CIGs stacking (auxiliary output file name)
.TP
.I float  
.B pd
.B =recStep_
.R  	increment of positions in stack section
.TP
.I int    
.B pn
.B =recNum_
.R  	number of positions in stack section
.TP
.I float  
.B po
.B =shotStart_
.R  	start position in stack section
.TP
.I string 
.B vel
.B =
.R  	velocity model file (velocity in m/s) (auxiliary input file name)
.TP
.I int    
.B wh
.B =11
.R  	height of a vertical window for semblance calculation
.SH SOURCE
.I user/aklokov/Mpdr2d.c
.SH VERSION
4.2-git
