.TH sfpefdeburst 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpefdeburst \- Burst noise removal using PEF. 
.SH SYNOPSIS
.B sfpefdeburst < in.rsf > out.rsf na=3 niter=10
.SH PARAMETERS
.PD 0
.TP
.I int    
.B na
.B =3
.R  	PEF length
.TP
.I int    
.B niter
.B =10
.R  	number of iterations
.SH SOURCE
.I user/gee/Mpefdeburst.c
.SH VERSION
4.2-git
