.TH sfpfactor2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpfactor2 \- Plane prediction filter on a helix. 
.SH SYNOPSIS
.B sfpfactor2 > filt.rsf nt= nx= p= q= niter=20 na=25 eps=FLT_EPSILON fixed=y lag=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =FLT_EPSILON
.R  	compression tolerance
.TP
.I bool   
.B fixed
.B =y
.R  [y/n]	if fixed size
.TP
.I string 
.B lag
.B =
.R  
.TP
.I int    
.B na
.B =25
.R  	filter size
.TP
.I int    
.B niter
.B =20
.R  	number of factorization iterations
.TP
.I int    
.B nt
.B =
.R  
.TP
.I int    
.B nx
.B =
.R  
.TP
.I float  
.B p
.B =
.R  
.TP
.I float  
.B q
.B =
.R  
.SH SOURCE
.I user/gee/Mpfactor2.c
.SH VERSION
4.2-git
