.TH sfpgreywfl 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpgreywfl \- Plot wavefields over a background image
.SH SYNOPSIS
.B sfpgreywfl bg=None savefile= title= pclip=100 absclip=n scalebar=y barlabel= timetext=y bgcmap=viridis wflcmap=gray jsnap=1 aspect=1 tmin=None tmax=None figx=10 figy=8 xints=None yints=None fps=15 speedup=10 dpi=90 fontsize=16 verb=n
.SH COMMENTS
Common usage examples
	* Plot to screen using default parameters
		sfpgreywfl < wavefield.rsf bg=velocity.rsf
	* Save to file using custom parameters
		sfpgreywfl < wavefield.rsf bg=velocity.rsf jsnap=10 bgcmap=gray wflcmap=seismic fps=10 verb=y savefile=output.mp4

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B absclip
.B =n
.R  [y/n]	Clipping is done for all gathers rather than per frame (y/n)
.TP
.I int    
.B aspect
.B =1
.R  	Aspect ratio
.TP
.I string 
.B barlabel
.B =
.R  	Colorbar label
.TP
.I string 
.B bg
.B =None
.R  	Background for animation. Zero if not supplied
.TP
.I string 
.B bgcmap
.B =viridis
.R  	Background colormap. See https://matplotlib.org/users/colormaps.html
.TP
.I float  
.B dpi
.B =90
.R  	DPI
.TP
.I float  
.B figx
.B =10
.R  	Figure x size in inches
.TP
.I float  
.B figy
.B =8
.R  	Figure y size in inches
.TP
.I float  
.B fontsize
.B =16
.R  	Font size
.TP
.I float  
.B fps
.B =15
.R  	Frames per second (when saving file)
.TP
.I int    
.B jsnap
.B =1
.R  	Number of timesteps at which to plot wavefield
.TP
.I float  
.B pclip
.B =100
.R  	Clip amplitude percentage from (0-100)
.TP
.I string 
.B savefile
.B =
.R  	Save animation to file. If not present, display animation.
.TP
.I bool   
.B scalebar
.B =y
.R  [y/n]	Colorbar
.TP
.I float  
.B speedup
.B =10
.R  	Delay between frames (in milliseconds) will be speedup*dt
.TP
.I bool   
.B timetext
.B =y
.R  [y/n]	Time text
.TP
.I string 
.B title
.B =
.R  	Plot title
.TP
.I float  
.B tmax
.B =None
.R  	Maximum time
.TP
.I float  
.B tmin
.B =None
.R  	Minimum time
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	Verbosity flag
.TP
.I string 
.B wflcmap
.B =gray
.R  	Wavefield colormap (should be sequential)
.TP
.I int    
.B xints
.B =None
.R  	Max number of x intervals
.TP
.I int    
.B yints
.B =None
.R  	Max number of y intervals
.SH SOURCE
.I user/cdacosta/Mpgreywfl.py
.SH VERSION
4.2-git
