.TH sfphaserot 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfphaserot \- Non-stationary phase rotation. 
.SH SYNOPSIS
.B sfphaserot < inp.rsf phase=pha.rsf > out.rsf na=721 da=1.0 a0=-360. order=100 ref=1.
.SH PARAMETERS
.PD 0
.TP
.I float  
.B a0
.B =-360.
.R  	first angle
.TP
.I float  
.B da
.B =1.0
.R  	angle increment
.TP
.I int    
.B na
.B =721
.R  	number of angles
.TP
.I int    
.B order
.B =100
.R  	Hilbert transformer order
.TP
.I file   
.B phase
.B =
.R  	auxiliary input file name
.TP
.I float  
.B ref
.B =1.
.R  	Hilbert transformer reference (0.5 < ref <= 1)
.SH SOURCE
.I user/fomels/Mphaserot.c
.SH VERSION
4.2-git
