.TH sfpickprint 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpickprint \- Write predictive painting result into a txt file 
.SH SYNOPSIS
.B sfpickprint < in.rsf pick=pick.rsf npick=npick.rsf semblance=semblance.rsf verb=y cut=0.
.SH PARAMETERS
.PD 0
.TP
.I float  
.B cut
.B =0.
.R  	muting value in boundary
.TP
.I file   
.B npick
.B =
.R  	auxiliary input file name
.TP
.I file   
.B pick
.B =
.R  	auxiliary input file name
.TP
.I file   
.B semblance
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	if y, print icdp/ncdp during operation
.SH SOURCE
.I user/zhiguang/Mpickprint.c
.SH VERSION
4.2-git
