.TH sfpickmaxima 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpickmaxima \- Picking local maxima on the first axis with evenly spaced windows. 
.SH SYNOPSIS
.B sfpickmaxima < in.rsf > out.rsf semblance=semblance.rsf npicks=npicks.rsf min=o1 max=o1+(n1-1)*d1 np=n1 nw=1 space=100. parab=n removal=y
.SH PARAMETERS
.PD 0
.TP
.I float  
.B max
.B =o1+(n1-1)*d1
.R  	maximum value of time
.TP
.I float  
.B min
.B =o1
.R  	minimum value of time
.TP
.I int    
.B np
.B =n1
.R  	maximum number of picks
.TP
.I file   
.B npicks
.B =
.R  	auxiliary output file name
.TP
.I int    
.B nw
.B =1
.R  	number of windows
.TP
.I bool   
.B parab
.B =n
.R  [y/n]	if y, parabolic interpolation
.TP
.I bool   
.B removal
.B =y
.R  [y/n]	if y, remove adjacent events based on semblance
.TP
.I file   
.B semblance
.B =
.R  	auxiliary input file name
.TP
.I float  
.B space
.B =100.
.R  	minimum distance bewteen picked events
.SH SOURCE
.I user/zhiguang/Mpickmaxima.c
.SH VERSION
4.2-git
