.TH sfpick 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpick \- Automatic picking from semblance-like panels.
.SH SYNOPSIS
.B sfpick < scn.rsf > pik.rsf vel0=o2 niter=100 an=1. gate=3 smooth=y norm=n back=n rect#=(1,1,...) rect1=1 rect2=1 ...
.SH COMMENTS
rectN defines the size of the smoothing stencil in N-th dimension.

Theory in Appendix B of:
S. Fomel, 2009,
Velocity analysis using AB semblance: Geophysical Prospecting, v. 57, 311-321.
Reproducible version in RSFSRC/book/tccs/avo
http://ahay.org/RSF/book/tccs/avo/paper_html/

August 2012 program of the month:
http://ahay.org/blog/2012/08/01/program-of-the-month-sfpick/

.SH PARAMETERS
.PD 0
.TP
.I float  
.B an
.B =1.
.R  	axes anisotropy
.TP
.I bool   
.B back
.B =n
.R  [y/n]	if run backward
.TP
.I int    
.B gate
.B =3
.R  	picking gate
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I bool   
.B norm
.B =n
.R  [y/n]	if apply normalization (0.~1.)
.TP
.I int    
.B rect#
.B =(1,1,...)
.R  	smoothing radius on #-th axis
.TP
.I bool   
.B smooth
.B =y
.R  [y/n]	if apply smoothing
.TP
.I float  
.B vel0
.B =o2
.R  	surface velocity
.SH USED IN
.TP
.I bei/vela/vscan
.TP
.I bei/wvs/vscan
.TP
.I data/alaska/line31-81-m8r
.SH SOURCE
.I user/fomels/Mpick.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfpick
.SH VERSION
4.2-git
