.TH sfpick3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpick3 \- Automatic picking  from 3-D semblance-like panels. 
.SH SYNOPSIS
.B sfpick3 < scn.rsf > pik.rsf vel1=o2 vel2=o3 rect1=1 niter=100 an1=1. an2=1. gate1=3 gate2=3 smooth=y
.SH PARAMETERS
.PD 0
.TP
.I float  
.B an1
.B =1.
.R  
.TP
.I float  
.B an2
.B =1.
.R  	axes anisotropy
.TP
.I int    
.B gate1
.B =3
.R  
.TP
.I int    
.B gate2
.B =3
.R  	picking gate
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I int    
.B rect1
.B =1
.R  	smoothing radius
.TP
.I bool   
.B smooth
.B =y
.R  [y/n]	if apply smoothing
.TP
.I float  
.B vel1
.B =o2
.R  
.TP
.I float  
.B vel2
.B =o3
.R  	surface velocity
.SH SOURCE
.I user/fomels/Mpick3.c
.SH VERSION
4.2-git
