.TH sfpicks2rsf 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpicks2rsf \- Creates a mask from horizons:
.SH SYNOPSIS
.B sfpicks2rsf < in.rsf > out.rsf ntic=5 tmask=y extend=n above=n picks=
.SH COMMENTS

horizon format:

x1 h1
x2 h2
x3 h3
x4 h4
.
.
.
xn hn



xn> ... >x4 >x3 >x2>x1

picks (file)  ascii file with two columns (x and h(x))
the x values must be increasing order,
you can easily achieve that by doing:

sort -k 1  unsorted_picks.txt > sorted_picks.txt

stdin             2D file from which the axes will be read
extend [false]    Extends picks to the boundaries of the axis
n Do not extend
y Extend to boundary

tmask [true]     write a mask (1 if z>h(x))
false     put a tic on the horizon

above [false] put 1 above the horizon
true   put 1 below the horizon

ntic [1]     works with tmask=false; put 1 around ntic grid points
above and below the horizon.   

stdout       It writes a file with the same dimensions as stdin 
with a mask function, 1 below the horizon 0 above 

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B above
.B =n
.R  [y/n]
.TP
.I bool   
.B extend
.B =n
.R  [y/n]
.TP
.I int    
.B ntic
.B =5
.R  
.TP
.I string 
.B picks
.B =
.R  	parameters from input file
.TP
.I bool   
.B tmask
.B =y
.R  [y/n]
.SH SOURCE
.I user/ediazp/Mpicks2rsf.c
.SH VERSION
4.2-git
