.TH sfplanemis3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfplanemis3 \- Missing data interpolation in 3-D using plane-wave destruction. 
.SH SYNOPSIS
.B sfplanemis3 < in.rsf > out.rsf dip=dip.rsf mask=mask.rsf niter=100 order=1 nj1=1 nj2=1 drift=n verb=n seed=time(NULL) var=0.
.SH PARAMETERS
.PD 0
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B drift
.B =n
.R  [y/n]	if shift filter
.TP
.I string 
.B mask
.B =
.R  	auxiliary input file name
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I int    
.B nj1
.B =1
.R  
.TP
.I int    
.B nj2
.B =1
.R  	antialiasing
.TP
.I int    
.B order
.B =1
.R  [1,2,3]	accuracy order
.TP
.I int    
.B seed
.B =time(NULL)
.R  	random seed
.TP
.I float  
.B var
.B =0.
.R  	noise variance
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/pwd/Mplanemis3.c
.SH VERSION
4.2-git
