.TH sfpmig1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpmig1 \- Slope-based prestack (t,xs,h) time migration . 
.SH SYNOPSIS
.B sfpmig1 < csg.rsf sdip=sdip.rsf hdip=hdip.rsf > mig.rsf half=y nw=4 mzo=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B half
.B =y
.R  [y/n]	if y, the second axis is half-offset instead of full offset
.TP
.I file   
.B hdip
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B mzo
.B =n
.R  [y/n]	do migration to zero offset
.TP
.I int    
.B nw
.B =4
.R  	interpolator size (2,3,4,6,8)
.TP
.I file   
.B sdip
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/lcasasan/Mpmig1.c
.SH VERSION
4.2-git Mpmig.c 4796 2009-09-29 19:39:07Z ivlad
