.TH sfpmshape2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpmshape2 \- Missing data interpolation in 2-D using plane-wave destruction and shaping regularization. 
.SH SYNOPSIS
.B sfpmshape2 < in.rsf > out.rsf dip=dip.rsf mask=mask.rsf niter=100 order=1 rect1=3 rect2=3
.SH PARAMETERS
.PD 0
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I string 
.B mask
.B =
.R  	auxiliary input file name
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I int    
.B order
.B =1
.R  	accuracy order
.TP
.I int    
.B rect1
.B =3
.R  
.TP
.I int    
.B rect2
.B =3
.R  	smoothing radius
.SH SOURCE
.I user/pwd/Mpmshape2.c
.SH VERSION
4.2-git
