.TH sfpow 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpow \- Apply power gain. 
.SH SYNOPSIS
.B sfpow < in.rsf > out.rsf tpow= pow#=(0,0,...)
.SH COMMENTS

March 2013 program of the month:
http://www.ahay.org/blog/2013/03/10/program-of-the-month-sfpow/

.SH PARAMETERS
.PD 0
.TP
.I float  
.B pow#
.B =(0,0,...)
.R  	power on #-th axis
.TP
.I float  
.B tpow
.B =
.R  
.SH USED IN
.TP
.I bei/dpmv/matt
.TP
.I bei/dwnc/vofz
.TP
.I bei/fld/yc
.TP
.I bei/ft1/brad
.TP
.I bei/krch/sep73
.TP
.I bei/sg/denmark
.TP
.I bei/vela/stretch
.TP
.I bei/wvs/head
.TP
.I data/alaska/line31-81-m8r
.TP
.I data/bpmodel94/firstlook
.SH SOURCE
.I system/generic/Mpow.c
.SH VERSION
4.2-git
