.TH sfpocssemb 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpocssemb \- POCS using semblance thresholding or amplitude thresholding.
.SH SYNOPSIS
.B sfpocssemb < inp.rsf mask=m.rsf > outp.rsf spec2=spec2.rsf spec1=spec1.rsf snr=snr.rsf true=trued.rsf niter=10 ifsnr=0 pmin=-2 pmax=2 np=nx type=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B ifsnr
.B =0
.R  	If compute SNR during iteration
.TP
.I file   
.B mask
.B =
.R  	auxiliary input file name
.TP
.I int    
.B niter
.B =10
.R  	Get the number of iterations
.TP
.I int    
.B np
.B =nx
.R  	number of p
.TP
.I float  
.B pmax
.B =2
.R  	maximum p
.TP
.I float  
.B pmin
.B =-2
.R  	minimum p
.TP
.I file   
.B snr
.B =
.R  	auxiliary output file name
.TP
.I string 
.B spec1
.B =
.R  	auxiliary output file name
.TP
.I string 
.B spec2
.B =
.R  	auxiliary output file name
.TP
.I string 
.B true
.B =
.R  	auxiliary input file name
.TP
.I string 
.B type
.B =
.R  	[amplitude, semblance] thresholding type, the default is amplitude thresholding
.SH SOURCE
.I user/chenyk/Mpocssemb.c
.SH VERSION
4.2-git
