.TH sfpolymask 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpolymask \- Mask a polygon. 
.SH SYNOPSIS
.B sfpolymask < inp.rsf > out.rsf poly=poly.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B poly
.B =
.R  	auxiliary input file name
.SH SOURCE
.I system/generic/Mpolymask.c
.SH VERSION
4.2-git
