.TH sfpoly 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpoly \- From roots to polynomials 
.SH SYNOPSIS
.B sfpoly < inp.rsf > out.rsf coef=coef.rsf n1= d1= o1=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B coef
.B =
.R  	(optional) coefficients (auxiliary output file name)
.TP
.I float  
.B d1
.B =
.R  	sampling
.TP
.I int    
.B n1
.B =
.R  	number of samples
.TP
.I float  
.B o1
.B =
.R  	origin
.SH SOURCE
.I user/fomels/Mpoly.c
.SH VERSION
4.2-git
