.TH sfpolyfit 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpolyfit \- Fitting a polynomial by least-squares. 
.SH SYNOPSIS
.B sfpolyfit < inp.rsf > out.rsf coef=coef.rsf coord=coord.rsf reg=reg.rsf eps=0.0f np=1 n1= d1= o1=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B coef
.B =
.R  	(optional) coefficients (auxiliary output file name)
.TP
.I string 
.B coord
.B =
.R  	coordinates (auxiliary input file name)
.TP
.I float  
.B d1
.B =
.R  	sampling for regularly sampled
.TP
.I float  
.B eps
.B =0.0f
.R  	regularization parameter
.TP
.I int    
.B n1
.B =
.R  	number of samples for regularly sampled
.TP
.I int    
.B np
.B =1
.R  	polynomial order
.TP
.I float  
.B o1
.B =
.R  	origin for regularly sampled
.TP
.I string 
.B reg
.B =
.R  	(optional) regularly sampled (auxiliary output file name)
.SH SOURCE
.I user/fomels/Mpolyfit.c
.SH VERSION
4.2-git
