.TH sfpostrtm2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpostrtm2d \- 2-D exploding-reflector RTM and its adjoint 
.SH SYNOPSIS
.B sfpostrtm2d < in.rsf > out.rsf velocity=vel.rsf wave=wave.rsf adj=y snap=n n0=0 jt=50 nt= dt= padx=nz/2 padz=nz/2
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =y
.R  [y/n]	adjoint flag, 0: modeling, 1: migration
.TP
.I float  
.B dt
.B =
.R  
.TP
.I int    
.B jt
.B =50
.R  	time interval of wavefield snapshot
.TP
.I int    
.B n0
.B =0
.R  	surface
.TP
.I int    
.B nt
.B =
.R  
.TP
.I int    
.B padx
.B =nz/2
.R  
.TP
.I int    
.B padz
.B =nz/2
.R  
.TP
.I bool   
.B snap
.B =n
.R  [y/n]	wavefield snapshot flag
.TP
.I file   
.B velocity
.B =
.R  	auxiliary input file name
.TP
.I file   
.B wave
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/zhiguang/Mpostrtm2d.c
.SH VERSION
4.2-git
