.TH sfpp2pstsic 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpp2pstsic \- Compute angle gathers for time-shift imaging condition 
.SH SYNOPSIS
.B sfpp2pstsic < Fstk.rsf velocity=Fvel.rsf vpvs=Fgam.rsf dip=Fdip.rsf > Fang.rsf na=nv da=1./(nv-1) a0=0. extend=4
.SH PARAMETERS
.PD 0
.TP
.I float  
.B a0
.B =0.
.R  
.TP
.I float  
.B da
.B =1./(nv-1)
.R  
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I int    
.B extend
.B =4
.R  	tmp extension
.TP
.I int    
.B na
.B =nv
.R  
.TP
.I file   
.B velocity
.B =
.R  	auxiliary input file name
.TP
.I file   
.B vpvs
.B =
.R  	auxiliary input file name
.SH SOURCE
.I system/seismic/Mpp2pstsic.c
.SH VERSION
4.2-git
