.TH sfpresum 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpresum \- 
.SH SYNOPSIS
.B sfpresum < Fin.rsf > Fou.rsf verb=n nsum=1
.SH COMMENTS
presum traces
Paul Sava
Copyright (C) 2022 Colorado School of Mines

.SH PARAMETERS
.PD 0
.TP
.I int    
.B nsum
.B =1
.R  	number of traces to sum
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.SH SOURCE
.I user/psava/Mpresum.c
.SH VERSION
4.2-git
