.TH sfproj 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfproj \- Projection filter. 
.SH SYNOPSIS
.B sfproj < in.rsf > out.rsf filt=filt.rsf single=y lag=1 eps=1.0f niter=100 verb=n
.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =1.0f
.R  	regularizion parameter
.TP
.I file   
.B filt
.B =
.R  	auxiliary input file name
.TP
.I int    
.B lag
.B =1
.R  	lag for internal convolution
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I bool   
.B single
.B =y
.R  [y/n]	single channel or multichannel
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/gee/Mproj.c
.SH VERSION
4.2-git Mconv.c 7107 2011-04-10 02:04:14Z ivlad
