.TH sfpreerror 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpreerror \- Prediction error 
.SH SYNOPSIS
.B sfpreerror < in.rsf predict=pre.rsf > out.rsf type=1
.SH PARAMETERS
.PD 0
.TP
.I file   
.B predict
.B =
.R  	auxiliary input file name
.TP
.I int    
.B type
.B =1
.R  	if compute relative error, 1: yes, 0: no, default is yes.
.SH SOURCE
.I user/chenyk/Mpreerror.c
.SH VERSION
4.2-git
