.TH sfprekirchsr 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfprekirchsr \- 2-D Prestack Kirchhoff time migration with antialiasing in source-receiver domain. 
.SH SYNOPSIS
.B sfprekirchsr vel=vel.rsf < inp.rsf > outp.rsf nz=nt dz=dt z0=t0 adj=n antialias=1.0
.SH COMMENTS
The axes in the input are {time,receiver,source}
The axes in the output are {time,receiver}
I(t0,x0)=\int (W(t0,y0,s,r) * u(s,r,T(s,t0,x0)+T(r,t0,x0)) dsdr

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]
.TP
.I float  
.B antialias
.B =1.0
.R  	antialiasing
.TP
.I float  
.B dz
.B =dt
.R  
.TP
.I int    
.B nz
.B =nt
.R  
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I float  
.B z0
.B =t0
.R  
.SH SOURCE
.I user/chenyk/Mprekirchsr.c
.SH VERSION
4.2-git
