.TH sfprefilt 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfprefilt \- prefilter bank of pwd
.SH SYNOPSIS
.B sfprefilt < input.rsf > dip.rsf coef=coef.rsf pf=pf.rsf nf=1 iter=5 eta=0.05
.SH PARAMETERS
.PD 0
.TP
.I file   
.B coef
.B =
.R  	auxiliary output file name
.TP
.I float  
.B eta
.B =0.05
.R  
.TP
.I int    
.B iter
.B =5
.R  
.TP
.I int    
.B nf
.B =1
.R  
.TP
.I file   
.B pf
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/chen/Mprefilt.py
.SH VERSION
4.2-git
