.TH sfprestolt 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfprestolt \- Prestack Stolt modeling/migration. 
.SH SYNOPSIS
.B sfprestolt < in.rsf > out.rsf inv=n depth=n stack=y nh= dh= vel= pad=nt extend=4
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B depth
.B =n
.R  [y/n]	y: depth migration, n: time migration
.TP
.I float  
.B dh
.B =
.R  	offset sampling
.TP
.I int    
.B extend
.B =4
.R  	trace extension
.TP
.I bool   
.B inv
.B =n
.R  [y/n]	y: modeling, n: migration
.TP
.I int    
.B nh
.B =
.R  	number of offsets
.TP
.I int    
.B pad
.B =nt
.R  	padding on the time axis
.TP
.I bool   
.B stack
.B =y
.R  [y/n]	if y: stack migrated image
.TP
.I float  
.B vel
.B =
.R  	constant velocity
.SH SOURCE
.I system/seismic/Mprestolt.c
.SH VERSION
4.2-git
