.TH sfpremig 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpremig \- Pseudo-spectral pre-stack source-receiver source independent diffraction imaging 
.SH SYNOPSIS
.B sfpremig < Fi.rsf > Fo.rsf vel=Fv.rsf dat_v=Fd_v.rsf dat_2=Fi1.rsf snaps=snaps.rsf spx= spz= f0= t0= A= snap=0 cmplx=y pad1=1 abc=n roll=n born=n diff=n justrec=n nbt= nbb=nbt nbl=nbt nbr=nbt ct= cb=ct cl=ct cr=ct verb=n ps=n adj=n vref=1500 nt= dt= gpl=-1 gpl_v=-1 src=0 n_srcs=1 shtbgn= shtend= shtint= which=0 gpx=-1 gpz=-1 gpx_v=-1 gpz_v=-1 offset=0 split=1
.SH PARAMETERS
.PD 0
.TP
.I floats 
.B A
.B =
.R  	wavelet amplitude  [n_srcs]
.TP
.I bool   
.B abc
.B =n
.R  [y/n]	absorbing flag
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	use pseudo-spectral
.TP
.I bool   
.B born
.B =n
.R  [y/n]	born modeling flag
.TP
.I float  
.B cb
.B =ct
.R  
.TP
.I float  
.B cl
.B =ct
.R  
.TP
.I bool   
.B cmplx
.B =y
.R  [y/n]	use complex fft
.TP
.I float  
.B cr
.B =ct
.R  
.TP
.I float  
.B ct
.B =
.R  
.TP
.I file   
.B dat_2
.B =
.R  	auxiliary input file name
.TP
.I string 
.B dat_v
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B diff
.B =n
.R  [y/n]	diffraction imaging flag
.TP
.I float  
.B dt
.B =
.R  
.TP
.I floats 
.B f0
.B =
.R  	wavelet peak freq  [n_srcs]
.TP
.I int    
.B gpl
.B =-1
.R  	geophone length
.TP
.I int    
.B gpl_v
.B =-1
.R  	geophone height
.TP
.I int    
.B gpx
.B =-1
.R  	geophone position x
.TP
.I int    
.B gpx_v
.B =-1
.R  	geophone position x
.TP
.I int    
.B gpz
.B =-1
.R  	geophone position z
.TP
.I int    
.B gpz_v
.B =-1
.R  	geophone position z
.TP
.I bool   
.B justrec
.B =n
.R  [y/n]	just need full waveform record (no born or rtdm)
.TP
.I int    
.B n_srcs
.B =1
.R  	source type
.TP
.I int    
.B nbb
.B =nbt
.R  
.TP
.I int    
.B nbl
.B =nbt
.R  
.TP
.I int    
.B nbr
.B =nbt
.R  
.TP
.I int    
.B nbt
.B =
.R  
.TP
.I int    
.B nt
.B =
.R  
.TP
.I int    
.B offset
.B =0
.R  	nearest offset
.TP
.I int    
.B pad1
.B =1
.R  	padding factor on the first axis
.TP
.I bool   
.B ps
.B =n
.R  [y/n]	use pseudo-spectral
.TP
.I bool   
.B roll
.B =n
.R  [y/n]	if n, receiver is independent of source location and gpl=nx
.TP
.I int    
.B shtbgn
.B =
.R  
.TP
.I int    
.B shtend
.B =
.R  
.TP
.I int    
.B shtint
.B =
.R  
.TP
.I int    
.B snap
.B =0
.R  	interval for snapshots
.TP
.I file   
.B snaps
.B =
.R  	auxiliary output file name
.TP
.I int    
.B split
.B =1
.R  	receiver split
.TP
.I ints   
.B spx
.B =
.R  	shot position x  [n_srcs]
.TP
.I ints   
.B spz
.B =
.R  	shot position z  [n_srcs]
.TP
.I int    
.B src
.B =0
.R  	source type
.TP
.I floats 
.B t0
.B =
.R  	wavelet time lag  [n_srcs]
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.TP
.I float  
.B vref
.B =1500
.R  	reference velocity (default using water)
.TP
.I int    
.B which
.B =0
.R  
.SH SOURCE
.I user/jsun/Mpremig.c
.SH VERSION
4.2-git
