.TH sfpseudo 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpseudo \- Generate rank-1 approximation for lowrank wave propagation: prop1, prop2, prop3, prop4
.SH SYNOPSIS
.B sfpseudo < fft.rsf > alpha.rsf flag= reg= nz= dz= z0= nx= dx= x0= seed= eps= npk=
.SH PARAMETERS
.PD 0
.TP
.I        
.B dx
.B =
.R  
.TP
.I        
.B dz
.B =
.R  
.TP
.I        
.B eps
.B =
.R  	tolerance
.TP
.I        
.B flag
.B =
.R  
.TP
.I        
.B npk
.B =
.R  	maximum sample rows/columns
.TP
.I        
.B nx
.B =
.R  
.TP
.I        
.B nz
.B =
.R  
.TP
.I        
.B reg
.B =
.R  
.TP
.I        
.B seed
.B =
.R  	seed for random number generator
.TP
.I        
.B x0
.B =
.R  	Get lowrank parameters
.TP
.I        
.B z0
.B =
.R  
.SH SOURCE
.I user/jingwei/Mpseudo.cc
.SH VERSION
4.2-git
