.TH sfpseudodepth 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpseudodepth \- depth to vertical-time interpolation
.SH SYNOPSIS
.B sfpseudodepth < Fin.rsf tau=Ftau.rsf > Fout.rsf inv=n linear=y n= o=0. d=
.SH COMMENTS
z to tau : pseudodepth < FZ.rsf inv=n tau=tau.rsf n=ntau o=otau d=dtau > FT.rsf
tau to z : pseudodepth < FT.rsf inv=y tau=tau.rsf > FZ.rsf 
.SH PARAMETERS
.PD 0
.TP
.I float  
.B d
.B =
.R  	tau d (>0)
.TP
.I bool   
.B inv
.B =n
.R  [y/n]	if y, tau to z; if n, tau to z
.TP
.I bool   
.B linear
.B =y
.R  [y/n]	if y, linear spline; if n, cubic spline (buggy)
.TP
.I int    
.B n
.B =
.R  	tau n
.TP
.I float  
.B o
.B =0.
.R  	tau o
.TP
.I file   
.B tau
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/xuxin/Mpseudodepth.c
.SH VERSION
4.2-git
