.TH sfpsmig 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpsmig \- 2-D Phase-shift modeling and migration. 
.SH SYNOPSIS
.B sfpsmig < inp.rsf > out.rsf vel=vel.rsf adj=n nw= dw= eps=0.1f
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag, 0: modeling, 1: migration
.TP
.I float  
.B dw
.B =
.R  
.TP
.I float  
.B eps
.B =0.1f
.R  	stabilization parameter
.TP
.I int    
.B nw
.B =
.R  
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/chenyk/Mpsmig.c
.SH VERSION
4.2-git
