.TH sfpseudoprim 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpseudoprim \- Generate pseudoprimaries using multiples
.SH SYNOPSIS
.B sfpseudoprim < in.rsf > out.rsf mul=mul.rsf verb=n stack=y both=n jumpo=1 jumps=1
.SH COMMENTS
The axes in the input are {offset,shot,frequency}
The axes in the output are {offset,shot,frequency}
Requirement: offset interval = shot interval

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B both
.B =n
.R  [y/n]	receiver flag, if y, receiver with both sides
.TP
.I int    
.B jumpo
.B =1
.R  	jump in offset dimension, only for stack=n
.TP
.I int    
.B jumps
.B =1
.R  	jump in shot dimension, only for stack=n
.TP
.I string 
.B mul
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B stack
.B =y
.R  [y/n]	stack flag, if y, no common pseudoprimary gather
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/yliu/Mpseudoprim.c
.SH VERSION
4.2-git
