.TH sfpseudolrexp 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpseudolrexp \- Generate rank-1 approximation for lowrank wave propagation: lrexp
.SH SYNOPSIS
.B sfpseudolrexp < fft.rsf > alpha.rsf flag= gpz= nt= dt= t0= nz= dz= z0= nx= dx= x0= seed= eps= npk=
.SH PARAMETERS
.PD 0
.TP
.I        
.B dt
.B =
.R  
.TP
.I        
.B dx
.B =
.R  
.TP
.I        
.B dz
.B =
.R  
.TP
.I        
.B eps
.B =
.R  	tolerance
.TP
.I        
.B flag
.B =
.R  
.TP
.I        
.B gpz
.B =
.R  
.TP
.I        
.B npk
.B =
.R  	maximum sample rows/columns
.TP
.I        
.B nt
.B =
.R  
.TP
.I        
.B nx
.B =
.R  
.TP
.I        
.B nz
.B =
.R  
.TP
.I        
.B seed
.B =
.R  	seed for random number generator
.TP
.I        
.B t0
.B =
.R  
.TP
.I        
.B x0
.B =
.R  	Get lowrank parameters
.TP
.I        
.B z0
.B =
.R  
.SH SOURCE
.I user/jingwei/Mpseudolrexp.cc
.SH VERSION
4.2-git
