.TH sfpspp 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpspp \- Pseudo-spectral wave extrapolation for second-order two-way wave equation using wavefield injection for passive imaging 
.SH SYNOPSIS
.B sfpspp < Fi.rsf > Fo.rsf wave=Fw.rsf dat_v=Fd_v.rsf snaps=snaps.rsf spx= spz= f0= t0= A= snap=0 cmplx=y pad1=1 abc=n nbt= nbb=nbt nbl=nbt nbr=nbt ct= cb=ct cl=ct cr=ct verb=n ps=n vref=1500 nt= dt= gpl=-1 gpl_v=-1 src=0 n_srcs=1 gpx=-1 gpz=-1 gpx_v=-1 gpz_v=-1
.SH PARAMETERS
.PD 0
.TP
.I floats 
.B A
.B =
.R  	wavelet amplitude  [n_srcs]
.TP
.I bool   
.B abc
.B =n
.R  [y/n]	absorbing flag
.TP
.I float  
.B cb
.B =ct
.R  
.TP
.I float  
.B cl
.B =ct
.R  
.TP
.I bool   
.B cmplx
.B =y
.R  [y/n]	use complex fft
.TP
.I float  
.B cr
.B =ct
.R  
.TP
.I float  
.B ct
.B =
.R  
.TP
.I string 
.B dat_v
.B =
.R  	auxiliary output file name
.TP
.I float  
.B dt
.B =
.R  
.TP
.I floats 
.B f0
.B =
.R  	wavelet peak freq  [n_srcs]
.TP
.I int    
.B gpl
.B =-1
.R  	geophone length
.TP
.I int    
.B gpl_v
.B =-1
.R  	geophone height
.TP
.I int    
.B gpx
.B =-1
.R  	geophone position x
.TP
.I int    
.B gpx_v
.B =-1
.R  	geophone position x
.TP
.I int    
.B gpz
.B =-1
.R  	geophone position z
.TP
.I int    
.B gpz_v
.B =-1
.R  	geophone position z
.TP
.I int    
.B n_srcs
.B =1
.R  	source type
.TP
.I int    
.B nbb
.B =nbt
.R  
.TP
.I int    
.B nbl
.B =nbt
.R  
.TP
.I int    
.B nbr
.B =nbt
.R  
.TP
.I int    
.B nbt
.B =
.R  
.TP
.I int    
.B nt
.B =
.R  
.TP
.I int    
.B pad1
.B =1
.R  	padding factor on the first axis
.TP
.I bool   
.B ps
.B =n
.R  [y/n]	use pseudo-spectral
.TP
.I int    
.B snap
.B =0
.R  	interval for snapshots
.TP
.I file   
.B snaps
.B =
.R  	auxiliary output file name
.TP
.I ints   
.B spx
.B =
.R  	shot position x  [n_srcs]
.TP
.I ints   
.B spz
.B =
.R  	shot position z  [n_srcs]
.TP
.I int    
.B src
.B =0
.R  	source type
.TP
.I floats 
.B t0
.B =
.R  	wavelet time lag  [n_srcs]
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.TP
.I float  
.B vref
.B =1500
.R  	reference velocity (default using water)
.TP
.I string 
.B wave
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/jsun/Mpspp.c
.SH VERSION
4.2-git
