.TH sfptaupmo3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfptaupmo3 \- Slope-based tau-p 3D moveout. 
.SH SYNOPSIS
.B sfptaupmo3 < inp.rsf dip1=dip1.rsf dip2=dip2.rsf > nmod.rsf tau0=tau0.rsf eps=0.01
.SH PARAMETERS
.PD 0
.TP
.I string 
.B dip1
.B =
.R  	slope field mesaure along dimension 2(auxiliary input file name)
.TP
.I string 
.B dip2
.B =
.R  	slope field mesaure along dimension 3(auxiliary input file name)
.TP
.I float  
.B eps
.B =0.01
.R  	stretch regularization
.TP
.I string 
.B tau0
.B =
.R  	tau0(tau,p) (auxiliary output file name)
.SH SOURCE
.I system/seismic/Mptaupmo3.c
.SH VERSION
4.2-git
