.TH sfput 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfput \- Input parameters into a header. 
.SH SYNOPSIS
.B sfput < in.rsf > out.rsf [parameter=value list]
.SH USED IN
.TP
.I bei/ft1/ft2d
.TP
.I bei/trimo/all
.TP
.I bei/trimo/subsamp
.TP
.I bei/trimo/veltran
.TP
.I carrot/test/modeling
.TP
.I chen/test/wavmod
.TP
.I cup/rna2d/real
.TP
.I cup/rna2d/shot
.TP
.I cup/rna2d/simple
.TP
.I cup/rna3d/real
.TP
.I cup/rna3d/shot
.TP
.I cup/rna3d/sin
.TP
.I cwp/geo2006TimeShiftImagingCondition/flat
.TP
.I cwp/geo2006TimeShiftImagingCondition/icomp
.TP
.I cwp/geo2006TimeShiftImagingCondition/zicig
.TP
.I cwp/geo2007StereographicImagingCondition/sigsbee2
.TP
.I cwp/geo2008InterferometricImagingCondition/circle
.TP
.I cwp/geo2008InterferometricImagingCondition/sact1
.TP
.I cwp/geo2008InterferometricImagingCondition/sigs2
.TP
.I cwp/geo2008IsotropicAngleDomainElasticRTM/marm2allA
.TP
.I cwp/geo2008IsotropicAngleDomainElasticRTM/marm2oneA
.TP
.I cwp/geo2008NumericWEMVAoperators/flatWEMVA
.TP
.I cwp/geo2008NumericWEMVAoperators/saltWEMVA
.TP
.I cwp/geo2009TTIModeSeparation/fold
.TP
.I cwp/geo2009TTIModeSeparation/marmousi2
.TP
23 more examples listed in:
.TP
/home/mlouboutin3/Research/madagascar//share/doc/madagascar/html/sfput.html
.SH SOURCE
.I system/main/put.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfput
.SH VERSION
4.2-git
