.TH sfpwspray 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpwspray \- Plane-wave spray. 
.SH SYNOPSIS
.B sfpwspray < inp.rsf dip=dip.rsf > out.rsf verb=n eps=0.01 ns= order=1 rect=2 reduce=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I float  
.B eps
.B =0.01
.R  	regularization
.TP
.I int    
.B ns
.B =
.R  	spray radius
.TP
.I int    
.B order
.B =1
.R  	accuracy order
.TP
.I int    
.B rect
.B =2
.R  	radius for predictive coherence (reduce=coherence)
.TP
.I string 
.B reduce
.B =
.R  	reduction method (none,stack,median,triangle,gaussian,predict,coherence)
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.SH SOURCE
.I user/pwd/Mpwspray.c
.SH VERSION
4.2-git
