.TH sfpwdchain1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpwdchain1 \- Chain of PWDs - linear operator 
.SH SYNOPSIS
.B sfpwdchain1 < inp.rsf dip=dip.rsf sig=sig.rsf > out.rsf adj=n drift=n forx=n order=1
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B drift
.B =n
.R  [y/n]	if shift filter
.TP
.I bool   
.B forx
.B =n
.R  [y/n]	for x only
.TP
.I int    
.B order
.B =1
.R  	PWD order
.TP
.I file   
.B sig
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/pwd/Mpwdchain1.c
.SH VERSION
4.2-git
