.TH sfpwdix 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpwdix \- Convert RMS to interval velocity using LS and plane-wave construction. 
.SH SYNOPSIS
.B sfpwdix < vrms.rsf > vint.rsf weight=weight.rsf slope=slope.rsf vrmsout=vout.rsf niter=100 ncycle=10 rect1=1 verb=n eps=0. order=1
.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =0.
.R  	regularization parameter
.TP
.I int    
.B ncycle
.B =10
.R  	number of cycles for anisotropic diffusion
.TP
.I int    
.B niter
.B =100
.R  	maximum number of iterations
.TP
.I int    
.B order
.B =1
.R  	accuracy order
.TP
.I int    
.B rect1
.B =1
.R  	vertical smoothing radius
.TP
.I file   
.B slope
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I string 
.B vrmsout
.B =
.R  	optionally, output predicted vrms (auxiliary output file name)
.TP
.I file   
.B weight
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/pwd/Mpwdix.c
.SH VERSION
4.2-git Mdix.c 803 2004-09-18 12:32:15Z fomels
