.TH sfpwdchain2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpwdchain2 \- Chain of PWDs 
.SH SYNOPSIS
.B sfpwdchain2 < inp.rsf sig=sig.rsf > out.rsf drift=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B drift
.B =n
.R  [y/n]	if shift filter
.TP
.I file   
.B sig
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/pwd/Mpwdchain2.c
.SH VERSION
4.2-git
