.TH sfpwsmooth 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpwsmooth \- 2-D structure-enhancing filtering. 
.SH SYNOPSIS
.B sfpwsmooth < in.rsf dip=dip.rsf > out.rsf verb=n ns=0 adj=n eps=0.01 order=1
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I float  
.B eps
.B =0.01
.R  	regularization
.TP
.I int    
.B ns
.B =0
.R  	smoothing radius
.TP
.I int    
.B order
.B =1
.R  	accuracy order
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/pwd/Mpwsmooth.c
.SH VERSION
4.2-git
