.TH sfpwave3d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpwave3d \- 
.SH SYNOPSIS
.B sfpwave3d > Fdat.rsf verb=n nt= ot= dt= nx= ox= dx= ny= oy= dy= nz= oz= dz= vel=1.0 cx=1.0 cy=1.0 cz=1.0
.SH COMMENTS
generate a plane in t-x-y-z space
cx x + cy y + cz z - vel t = 0
(the plane goes through the origin)

.SH PARAMETERS
.PD 0
.TP
.I float  
.B cx
.B =1.0
.R  
.TP
.I float  
.B cy
.B =1.0
.R  
.TP
.I float  
.B cz
.B =1.0
.R  
.TP
.I float  
.B dt
.B =
.R  
.TP
.I float  
.B dx
.B =
.R  
.TP
.I float  
.B dy
.B =
.R  
.TP
.I float  
.B dz
.B =
.R  
.TP
.I int    
.B nt
.B =
.R  
.TP
.I int    
.B nx
.B =
.R  
.TP
.I int    
.B ny
.B =
.R  
.TP
.I int    
.B nz
.B =
.R  
.TP
.I float  
.B ot
.B =
.R  
.TP
.I float  
.B ox
.B =
.R  
.TP
.I float  
.B oy
.B =
.R  
.TP
.I float  
.B oz
.B =
.R  
.TP
.I float  
.B vel
.B =1.0
.R  
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/psava/Mpwave3d.py
.SH VERSION
4.2-git
