.TH sfpwpaint2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpwpaint2 \- 3-D painting by plane-wave construction. 
.SH SYNOPSIS
.B sfpwpaint2 < dip.rsf > out.rsf cost=cost.rsf seed=seed.rsf data=n verb=n eps=0.01 order=1
.SH PARAMETERS
.PD 0
.TP
.I file   
.B cost
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B data
.B =n
.R  [y/n]	spray input data
.TP
.I float  
.B eps
.B =0.01
.R  	regularization
.TP
.I int    
.B order
.B =1
.R  	accuracy order
.TP
.I string 
.B seed
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]
.SH SOURCE
.I user/pwd/Mpwpaint2.c
.SH VERSION
4.2-git
