.TH sfpwspray2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpwspray2 \- Plane-wave spray in 3-D. 
.SH SYNOPSIS
.B sfpwspray2 < inp.rsf dip=dip.rsf > out.rsf verb=n eps=0.01 order=1 ns2= ns3=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I float  
.B eps
.B =0.01
.R  	regularization
.TP
.I int    
.B ns2
.B =
.R  
.TP
.I int    
.B ns3
.B =
.R  	spray radius
.TP
.I int    
.B order
.B =1
.R  	accuracy order
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.SH SOURCE
.I user/pwd/Mpwspray2.c
.SH VERSION
4.2-git
