.TH sfpwdchain 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpwdchain \- Multiple dip estimation by chain of PWDs 
.SH SYNOPSIS
.B sfpwdchain < inp.rsf dip=dip.rsf > out.rsf dipin=dipin.rsf nc=1 order=1 drift=n vp=n verb=(bool) (1 == nt) niter=0 liter=50 rect1=1 rect2=1 lambda=1.0f
.SH PARAMETERS
.PD 0
.TP
.I file   
.B dip
.B =
.R  	auxiliary output file name
.TP
.I string 
.B dipin
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B drift
.B =n
.R  [y/n]	if shift filter
.TP
.I float  
.B lambda
.B =1.0f
.R  	scaling
.TP
.I int    
.B liter
.B =50
.R  	number of linear iterations
.TP
.I int    
.B nc
.B =1
.R  	number of components
.TP
.I int    
.B niter
.B =0
.R  	number of iterations
.TP
.I int    
.B order
.B =1
.R  	PWD order
.TP
.I int    
.B rect1
.B =1
.R  
.TP
.I int    
.B rect2
.B =1
.R  	smoothing radius
.TP
.I bool   
.B verb
.B =(bool) (1 == nt)
.R  [y/n]	verbosity flag
.TP
.I bool   
.B vp
.B =n
.R  [y/n]	if use variable projection
.SH SOURCE
.I user/pwd/Mpwdchain.c
.SH VERSION
4.2-git
