.TH sfpyran 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfpyran \- Add random noise using python.
.SH SYNOPSIS
.B sfpyran < pi.rsf > po.rsf axis=2 range=1 seed=n2 type=y mean=0 var=1 rep=n
.SH PARAMETERS
.PD 0
.TP
.I int    
.B axis
.B =2
.R  
.TP
.I float  
.B mean
.B =0
.R  	noise mean (default=0)
.TP
.I float  
.B range
.B =1
.R  	noise range (default=1)
.TP
.I bool   
.B rep
.B =n
.R  [y/n]	if y, replace data with noise
.TP
.I int    
.B seed
.B =n2
.R  	random seed (default=n2)
.TP
.I string 
.B type
.B =y
.R  	noise type, y: normal, n: uniform
.TP
.I float  
.B var
.B =1
.R  	noise variance (default=1)
.SH SOURCE
.I user/chenyk/Mpyran.py
.SH VERSION
4.2-git
