.TH sfqdome 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfqdome \- 3-D synthetic image from Jon Claerbout. 
.SH SYNOPSIS
.B sfqdome > mod.rsf trace=trace.rsf ranget=3. n1=400 n2=100 n3=50 large=(int) n1*ranget d1=0.004 d2=0.01 d3=0.02 o1=0. o2=-3.*d2 o3=-3.*d3 gaussvel=2.5 throw=0.01 endtaper=20 slicei=40 impedance=n
.SH PARAMETERS
.PD 0
.TP
.I float  
.B d1
.B =0.004
.R  
.TP
.I float  
.B d2
.B =0.01
.R  
.TP
.I float  
.B d3
.B =0.02
.R  
.TP
.I int    
.B endtaper
.B =20
.R  
.TP
.I float  
.B gaussvel
.B =2.5
.R  
.TP
.I bool   
.B impedance
.B =n
.R  [y/n]
.TP
.I int    
.B large
.B =(int) n1*ranget
.R  
.TP
.I int    
.B n1
.B =400
.R  
.TP
.I int    
.B n2
.B =100
.R  
.TP
.I int    
.B n3
.B =50
.R  
.TP
.I float  
.B o1
.B =0.
.R  
.TP
.I float  
.B o2
.B =-3.*d2
.R  
.TP
.I float  
.B o3
.B =-3.*d3
.R  
.TP
.I float  
.B ranget
.B =3.
.R  
.TP
.I int    
.B slicei
.B =40
.R  
.TP
.I float  
.B throw
.B =0.01
.R  
.TP
.I string 
.B trace
.B =
.R  	file to optionally output the master trace (auxiliary output file name)
.SH SOURCE
.I user/gee/Mqdome.c
.SH VERSION
4.2-git
