.TH sfR2to3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfR2to3 \- None
.SH SYNOPSIS
.B sfR2to3 < two.rsf > three.rsf common=commonoffset.rsf cut= offset=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B common
.B =
.R  	auxiliary output file name
.TP
.I        
.B cut
.B =
.R  	command-line parameter
.TP
.I        
.B offset
.B =
.R  	command-line parameter
.SH SOURCE
.I user/mehdi/MR2to3.f90
.SH VERSION
4.2-git
