.TH sfradon34 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfradon34 \- azimuthally anisotropic 3to4 Radon transform (using 3to3 butterfly)
.SH SYNOPSIS
.B sfradon34 < input.rsf > output.rsf ntau= np= nq= ns= tau0= dtau= p0= dp= q0= dq= s0= ds= N=
.SH PARAMETERS
.PD 0
.TP
.I        
.B N
.B =
.R  	number of partitions
.TP
.I        
.B dp
.B =
.R  
.TP
.I        
.B dq
.B =
.R  
.TP
.I        
.B ds
.B =
.R  
.TP
.I        
.B dtau
.B =
.R  
.TP
.I        
.B np
.B =
.R  
.TP
.I        
.B nq
.B =
.R  
.TP
.I        
.B ns
.B =
.R  
.TP
.I        
.B ntau
.B =
.R  
.TP
.I        
.B p0
.B =
.R  
.TP
.I        
.B q0
.B =
.R  
.TP
.I        
.B s0
.B =
.R  
.TP
.I        
.B tau0
.B =
.R  
.SH SOURCE
.I user/jingwei/Mradon34.cc
.SH VERSION
4.2-git
