.TH sfrandcut 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfrandcut \- cut a random dataset from a 3D cube 
.SH SYNOPSIS
.B sfrandcut < Fi.rsf > Fo.rsf rr=Fr.rsf verb=n axis=2
.SH PARAMETERS
.PD 0
.TP
.I int    
.B axis
.B =2
.R  	stack axis
.TP
.I file   
.B rr
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/psava/Mrandcut.c
.SH VERSION
4.2-git
