.TH sfrandline 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfrandline \- Construct data from random lines 
.SH SYNOPSIS
.B sfrandline > out.rsf n1=10 n2=10 lines=3 seed=2000
.SH PARAMETERS
.PD 0
.TP
.I int    
.B lines
.B =3
.R  	number of lines
.TP
.I int    
.B n1
.B =10
.R  
.TP
.I int    
.B n2
.B =10
.R  	dimensions
.TP
.I int    
.B seed
.B =2000
.R  	random number seed
.SH SOURCE
.I user/gee/Mrandline.c
.SH VERSION
4.2-git
