.TH sfrays3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfrays3 \- Ray tracing by a Runge-Kutta integrator in 3-D.
.SH SYNOPSIS
.B sfrays3 < vel.rsf > rays.rsf shotfile=shots.rsf anglefile=angles.rsf vel=y order=4 nt= dt= sym=y escvar=n zshot=o[0] yshot=o[1] + 0.5*(n[1]-1)*d[1] xshot=o[2] + 0.5*(n[2]-1)*d[2] na= nb= a0=0. amax=360. b0=0. bmax=180. > rays.rsf
.SH COMMENTS
Rays can be plotted with sfplotrays.

.SH PARAMETERS
.PD 0
.TP
.I float  
.B a0
.B =0.
.R  	First azimuth angle in degrees (if anglefile is not specified)
.TP
.I float  
.B amax
.B =360.
.R  	Maximum azimuth angle in degrees (if anglefile is not specified)
.TP
.I string 
.B anglefile
.B =
.R  	file with initial angles (auxiliary input file name)
.TP
.I float  
.B b0
.B =0.
.R  	First inclination angle in degrees (if anglefile is not specified)
.TP
.I float  
.B bmax
.B =180.
.R  	Maximum inclination angle in degrees (if anglefile is not specified)
.TP
.I float  
.B dt
.B =
.R  	Sampling in time
.TP
.I bool   
.B escvar
.B =n
.R  [y/n]	If y - output escape values, n - trajectories
.TP
.I int    
.B na
.B =
.R  	Number of azimuths (if anglefile is not specified)
.TP
.I int    
.B nb
.B =
.R  	Number of inclinations (if anglefile is not specified)
.TP
.I int    
.B nt
.B =
.R  	Number of time steps
.TP
.I int    
.B order
.B =4
.R  	Interpolation order
.TP
.I string 
.B shotfile
.B =
.R  	file with shot locations (auxiliary input file name)
.TP
.I bool   
.B sym
.B =y
.R  [y/n]	if y, use symplectic integrator
.TP
.I bool   
.B vel
.B =y
.R  [y/n]	If y, input is velocity; if n, slowness
.TP
.I float  
.B xshot
.B =o[2] + 0.5*(n[2]-1)*d[2]
.R  	shot location crossline (if shotfile is not specified)
.TP
.I float  
.B yshot
.B =o[1] + 0.5*(n[1]-1)*d[1]
.R  	shot location inline (if shotfile is not specified)
.TP
.I float  
.B zshot
.B =o[0]
.R  	shot location in depth (if shotfile is not specified)
.SH SOURCE
.I system/seismic/Mrays3.c
.SH VERSION
4.2-git
