.TH sfradon2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfradon2 \- 2to2 Radon transform (using 2to2 butterfly)
.SH SYNOPSIS
.B sfradon2 < input.rsf > output.rsf ntau= np= tau0= dtau= p0= dp= N=
.SH PARAMETERS
.PD 0
.TP
.I        
.B N
.B =
.R  	number of partitions
.TP
.I        
.B dp
.B =
.R  
.TP
.I        
.B dtau
.B =
.R  
.TP
.I        
.B np
.B =
.R  
.TP
.I        
.B ntau
.B =
.R  
.TP
.I        
.B p0
.B =
.R  
.TP
.I        
.B tau0
.B =
.R  
.SH SOURCE
.I user/jingwei/Mradon2.cc
.SH VERSION
4.2-git
