.TH sfreadsample 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfreadsample \- Oriented zero-offset migration. 
.SH SYNOPSIS
.B sfreadsample > so1.rsf init=so2.rsf final=so3.rsf N= sample=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B N
.B =
.R  
.TP
.I file   
.B final
.B =
.R  	auxiliary output file name
.TP
.I file   
.B init
.B =
.R  	auxiliary output file name
.TP
.I string 
.B sample
.B =
.R  
.SH SOURCE
.I user/roman/Mreadsample.c
.SH VERSION
4.2-git
