.TH sfrefer 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfrefer \- Subtract a reference from a grid. 
.SH SYNOPSIS
.B sfrefer < in.rsf > out.rsf ref=ref.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B ref
.B =
.R  	auxiliary input file name
.SH SOURCE
.I system/seismic/Mrefer.c
.SH VERSION
4.2-git
