.TH sfresamplextnd 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfresamplextnd \- 2D data resampling with ability to extrapolate. 
.SH SYNOPSIS
.B sfresamplextnd < in.rsf > out.rsf o1=o[0] d1=d[0] o2=o[1] d2=d[1] n1=(d[0]*(n[0]-1)+o[0]-o1)/d1 n2=(d[1]*(n[1]-1)+o[1]-o2)/d2
.SH PARAMETERS
.PD 0
.TP
.I float  
.B d1
.B =d[0]
.R  	sample interval on 1st axis
.TP
.I float  
.B d2
.B =d[1]
.R  	sample interval on 2nd axis
.TP
.I int    
.B n1
.B =(d[0]*(n[0]-1)+o[0]-o1)/d1
.R  	number of samples on first axis
.TP
.I int    
.B n2
.B =(d[1]*(n[1]-1)+o[1]-o2)/d2
.R  	number of samples on second axis
.TP
.I float  
.B o1
.B =o[0]
.R  	first sample sample on 1st axis
.TP
.I float  
.B o2
.B =o[1]
.R  	first sample on 2nd axis
.SH SOURCE
.I user/luke/Mresamplextnd.c
.SH VERSION
4.2-git
