.TH sfregr 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfregr \- Linear regression 
.SH SYNOPSIS
.B sfregr < inp.rsf reg=reg.rsf > out.rsf dim=1 niter=10 method=2 verb=n n1iter=10 perc=90.0 fact=1.5 type=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B dim
.B =1
.R  	number of dimensions
.TP
.I float  
.B fact
.B =1.5
.R  	percentage for sharpening
.TP
.I int    
.B method
.B =2
.R  	method (L1-like or L2)
.TP
.I int    
.B n1iter
.B =10
.R  	number of POCS iterations
.TP
.I int    
.B niter
.B =10
.R  	number of CG iterations
.TP
.I float  
.B perc
.B =90.0
.R  	percentage for sharpening
.TP
.I file   
.B reg
.B =
.R  	auxiliary input file name
.TP
.I string 
.B type
.B =
.R  	thresholding type
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/fomels/Mregr.c
.SH VERSION
4.2-git
