.TH sfrealign 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfrealign \- 
.SH SYNOPSIS
.B sfrealign < logrefa.rsf < log1a.rsf > log1_co.rsf log1=
.SH COMMENTS
Residual well log realignment

Built for log data manipulation - algined axis (o1/d1/n1) with reference well log

.SH PARAMETERS
.PD 0
.TP
.I string 
.B log1
.B =
.R  
.SH SOURCE
.I user/sbader/Mrealign.py
.SH VERSION
4.2-git
