.TH sfreplace 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfreplace \- 
.SH SYNOPSIS
.B sfreplace < loga.rsf > log_eo.rsf loc= num=
.SH COMMENTS
1D dataset padding 

Built for time-depth relationship manipulation. LSIM scan/pick is smooth intoducing non-real updates at top of pick.

.SH PARAMETERS
.PD 0
.TP
.I int    
.B loc
.B =
.R  	Location of value used to replace
.TP
.I int    
.B num
.B =
.R  	Number of values to replace at beginning of dataset
.SH SOURCE
.I user/sbader/Mreplace.py
.SH VERSION
4.2-git
