.TH sfrefl2ai 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfrefl2ai \- Convert reflectivity to acoustic impedance. 
.SH SYNOPSIS
.B sfrefl2ai < ref.rsf > ai.rsf a0=a0.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B a0
.B =
.R  	auxiliary input file name
.SH SOURCE
.I system/seismic/Mrefl2ai.c
.SH VERSION
4.2-git
