.TH sfrec2ps 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfrec2ps \- None
.SH SYNOPSIS
.B sfrec2ps < infile.rsf > outfile.rsf alpha=6.2 beta=3.5 irot=0. adj=y
.SH PARAMETERS
.PD 0
.TP
.I        
.B adj
.B =y
.R  
.TP
.I        
.B alpha
.B =6.2
.R  	P-wave Velocity at surface
.TP
.I        
.B beta
.B =3.5
.R  	S-wave velocity at surface
.TP
.I        
.B irot
.B =0.
.R  	Rotation of array w.r.t. 1st axis
.SH SOURCE
.I user/jeff/Mrec2ps.f90
.SH VERSION
4.2-git
