.TH sfreal 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfreal \- Extract real (sfreal) or imaginary (sfimag) part of a complex dataset. 
.SH SYNOPSIS
.B sfreal < cmplx.rsf > real.rsf
.SH USED IN
.TP
.I bei/ft1/brad
.TP
.I bei/ft1/ft2d
.TP
.I bei/ft1/ft2d
.TP
.I bei/ft1/plane4
.TP
.I cup/rna2d/shot
.TP
.I cup/rna2d/simple
.TP
.I cup/rna3d/real
.TP
.I cup/rna3d/sin
.TP
.I cwp/geo2006TimeShiftImagingCondition/flat
.TP
.I cwp/geo2007StereographicImagingCondition/sigsbee2
.TP
.I cwp/geo2008NumericWEMVAoperators/flatWEMVA
.TP
.I cwp/geo2008NumericWEMVAoperators/saltWEMVA
.TP
.I cwp/geo2009TTIModeSeparation/tti3
.TP
.I cwp/geo2011WideAzimuthAngleDecomposition/seam357
.TP
.I cwp/jse2006RWEImagingOverturningReflections/sigsbee
.TP
.I cwp/pept2011MicroearthquakeMonitoring/saf1
.TP
.I cwp/pept2011MicroearthquakeMonitoring/saf3
.TP
.I data/alaska/line31-81-m8r
.SH SOURCE
.I system/main/real.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfreal
.SH VERSION
4.2-git
