.TH sfreciprocity 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfreciprocity \- Create a dipping layer model for HTI testing purposes.  Has fixed velocity structure, but can change dip of layer and degree of anisotropy.
.SH SYNOPSIS
.B sfreciprocity < Fin.rsf > Fout.rsf
.SH SOURCE
.I user/jeff/Mreciprocity.c
.SH VERSION
4.2-git
