.TH sfrfxrna 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfrfxrna \- Local prediction filter for complex numbers (n-dimensional). 
.SH SYNOPSIS
.B sfrfxrna < dat.rsf > flt.rsf mask=mask.rsf pred=pre.rsf zshift=zshift.rsf zdata=zdata.rsf ns=1 niter=100 verb=y jump=1 ty=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B jump
.B =1
.R  	jump
.TP
.I string 
.B mask
.B =
.R  	auxiliary input file name
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I int    
.B ns
.B =1
.R  	shifts of both sides npef=2*ns+1
.TP
.I string 
.B pred
.B =
.R  	auxiliary output file name
.TP
.I string 
.B ty
.B =
.R  	Prediction type: all=backward+forward
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity flag
.TP
.I string 
.B zdata
.B =
.R  	auxiliary output file name
.TP
.I string 
.B zshift
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/gchliu/Mrfxrna.c
.SH VERSION
4.2-git
