.TH sfrfccp 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfrfccp \- None
.SH SYNOPSIS
.B sfrfccp < infile.rsf vp=vpfile.rsf vs=vsfile.rsf > outfile.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B vp
.B =
.R  	auxiliary input file name
.TP
.I file   
.B vs
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/jeff/Mrfccp.f90
.SH VERSION
4.2-git
