.TH sfrfspecdiv 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfrfspecdiv \- None
.SH SYNOPSIS
.B sfrfspecdiv < infile.rsf file1=file1.rsf > outfile.rsf a=1.25 c=0.01 pd=10.
.SH PARAMETERS
.PD 0
.TP
.I        
.B a
.B =1.25
.R  
.TP
.I        
.B c
.B =0.01
.R  
.TP
.I file   
.B file1
.B =
.R  	auxiliary input file name
.TP
.I        
.B pd
.B =10.
.R  	phase delay
.SH SOURCE
.I user/jeff/Mrfspecdiv.f90
.SH VERSION
4.2-git
