.TH sfrm 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfrm \- Remove RSF files together with their data.
.SH SYNOPSIS
.B sfrm file1.rsf [file2.rsf ...] [-i] [-v] [-f] 
.SH COMMENTS
Mimics the standard Unix rm command.

See also: sfmv, sfcp.

.SH SOURCE
.I system/main/rm.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfrm
.SH VERSION
4.2-git
