.TH sfrmtrace 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfrmtrace \- Remove part of traces (resample) in order to make aliasing 
.SH SYNOPSIS
.B sfrmtrace < in.rsf > out.rsf factor=2
.SH PARAMETERS
.PD 0
.TP
.I int    
.B factor
.B =2
.R  	zero part beginning point
.SH SOURCE
.I user/chenyk/Mrmtrace.c
.SH VERSION
4.2-git
