.TH sfrotater 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfrotater \- Roatation with Interpolation from a regular grid in 2-D. 
.SH SYNOPSIS
.B sfrotater < inp.rsf > out.rsf angle=90. interp=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B angle
.B =90.
.R  	rotation angle
.TP
.I string 
.B interp
.B =
.R  	[n,l,c] interpolation type
.SH SOURCE
.I user/zone/Mrotater.c
.SH VERSION
4.2-git
