.TH sfrotvol 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfrotvol \- 3D volume rotation about a vertical axis 
.SH SYNOPSIS
.B sfrotvol < inFile.rsf > outFile.rsf xf=0.f yf=0.f theta=0.f
.SH PARAMETERS
.PD 0
.TP
.I float  
.B theta
.B =0.f
.R  	rotation angle
.TP
.I float  
.B xf
.B =0.f
.R  	x-coord of the vertical axis
.TP
.I float  
.B yf
.B =0.f
.R  	y-coord of the vertical axis
.SH SOURCE
.I user/aklokov/Mrotvol.c
.SH VERSION
4.2-git
