.TH sfrsf2handvel 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfrsf2handvel \- Convert RSF to velocity picks 
.SH SYNOPSIS
.B sfrsf2handvel < in.rsf > out.rsf skip=4
.SH PARAMETERS
.PD 0
.TP
.I int    
.B skip
.B =4
.R  	number of distance bins
.SH SOURCE
.I user/salah/Mrsf2handvel.c
.SH VERSION
4.2-git
