.TH sfrsf2txt 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfrsf2txt \- RSF file to Text (ASCII) file (as a matrix) 
.SH SYNOPSIS
.B sfrsf2txt < in.rsf format= tfile=
.SH COMMENTS
Example: 
sftxt2rsf tfile=location.txt n1=2 n2=3 >location.rsf
sfrsf2txt <location.rsf format=.4f tfile=location2.txt
more location.txt
more location2.txt

.SH PARAMETERS
.PD 0
.TP
.I string 
.B format
.B =
.R  
.TP
.I string 
.B tfile
.B =
.R  
.SH SOURCE
.I user/chenyk/Mrsf2txt.c
.SH VERSION
4.2-git
