.TH sfrtseislet 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfrtseislet \- Seislet transform using relative time 
.SH SYNOPSIS
.B sfrtseislet < in.rsf > out.rsf rt=rt.rsf inv=n adj=n eps=0.01 unit=n order=1 verb=n type=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	if y, do adjoint transform
.TP
.I float  
.B eps
.B =0.01
.R  	regularization
.TP
.I bool   
.B inv
.B =n
.R  [y/n]	if y, do inverse transform
.TP
.I int    
.B order
.B =1
.R  	accuracy order
.TP
.I file   
.B rt
.B =
.R  	auxiliary input file name
.TP
.I string 
.B type
.B =
.R  	[haar,linear,biorthogonal] wavelet type, the default is linear
.TP
.I bool   
.B unit
.B =n
.R  [y/n]	if y, use unitary scaling
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/zgeng/Mrtseislet.c
.SH VERSION
4.2-git
