.TH sfsamptest 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsamptest \- Test sample function prop1, prop2, prop3, prop4
.SH SYNOPSIS
.B sfsamptest < fft.rsf flag= reg= zx0= kzx0= nz= dz= z0= nx= dx= x0=
.SH PARAMETERS
.PD 0
.TP
.I        
.B dx
.B =
.R  
.TP
.I        
.B dz
.B =
.R  
.TP
.I        
.B flag
.B =
.R  
.TP
.I        
.B kzx0
.B =
.R  
.TP
.I        
.B nx
.B =
.R  
.TP
.I        
.B nz
.B =
.R  
.TP
.I        
.B reg
.B =
.R  
.TP
.I        
.B x0
.B =
.R  
.TP
.I        
.B z0
.B =
.R  
.TP
.I        
.B zx0
.B =
.R  
.SH SOURCE
.I user/jingwei/Msamptest.cc
.SH VERSION
4.2-git
