.TH sfsamplowmat 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsamplowmat \- Sample the lowrank propagation matrix 
.SH SYNOPSIS
.B sfsamplowmat < velocity.rsf > mat.rsf dt= nz= dz= z0= nx= dx= x0=
.SH PARAMETERS
.PD 0
.TP
.I        
.B dt
.B =
.R  
.TP
.I        
.B dx
.B =
.R  
.TP
.I        
.B dz
.B =
.R  
.TP
.I        
.B nx
.B =
.R  
.TP
.I        
.B nz
.B =
.R  
.TP
.I        
.B x0
.B =
.R  
.TP
.I        
.B z0
.B =
.R  
.SH SOURCE
.I user/jingwei/Msamplowmat.cc
.SH VERSION
4.2-git
