.TH sfsamptestlrexp 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsamptestlrexp \- Test sample function lrexp
.SH SYNOPSIS
.B sfsamptestlrexp < fft.rsf flag= gpz= zx0= kzx0= nt= dt= t0= nz= dz= z0= nx= dx= x0=
.SH PARAMETERS
.PD 0
.TP
.I        
.B dt
.B =
.R  
.TP
.I        
.B dx
.B =
.R  
.TP
.I        
.B dz
.B =
.R  
.TP
.I        
.B flag
.B =
.R  
.TP
.I        
.B gpz
.B =
.R  
.TP
.I        
.B kzx0
.B =
.R  
.TP
.I        
.B nt
.B =
.R  
.TP
.I        
.B nx
.B =
.R  
.TP
.I        
.B nz
.B =
.R  
.TP
.I        
.B t0
.B =
.R  
.TP
.I        
.B x0
.B =
.R  
.TP
.I        
.B z0
.B =
.R  
.TP
.I        
.B zx0
.B =
.R  
.SH SOURCE
.I user/jingwei/Msamptestlrexp.cc
.SH VERSION
4.2-git
