.TH sfsbslice 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsbslice \- 
.SH SYNOPSIS
.B sfsbslice < logrefa.rsf < deptha.rsf < log1a.rsf < log2a.rsf < log3a.rsf < log4a.rsf < log5a.rsf < log6a.rsf > logref_co.rsf depth_c=depth_co.rsf log1_c=log1_co.rsf log2_c=log2_co.rsf log3_c=log3_co.rsf log4_c=log4_co.rsf log5_c=log5_co.rsf log6_c=log6_co.rsf depth= log1= log2= log3= log4= log5= log6=
.SH COMMENTS
Multiple 1D inputs clipped to length of reference input

Built for log data manipulation - clips six input logs to the length of the reference well log

.SH PARAMETERS
.PD 0
.TP
.I string 
.B depth
.B =
.R  
.TP
.I file   
.B depth_c
.B =
.R  	auxiliary output file name
.TP
.I string 
.B log1
.B =
.R  
.TP
.I file   
.B log1_c
.B =
.R  	auxiliary output file name
.TP
.I string 
.B log2
.B =
.R  
.TP
.I file   
.B log2_c
.B =
.R  	auxiliary output file name
.TP
.I string 
.B log3
.B =
.R  
.TP
.I file   
.B log3_c
.B =
.R  	auxiliary output file name
.TP
.I string 
.B log4
.B =
.R  
.TP
.I file   
.B log4_c
.B =
.R  	auxiliary output file name
.TP
.I string 
.B log5
.B =
.R  
.TP
.I file   
.B log5_c
.B =
.R  	auxiliary output file name
.TP
.I string 
.B log6
.B =
.R  
.TP
.I file   
.B log6_c
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/sbader/Msbslice.py
.SH VERSION
4.2-git
