.TH sfsbclip1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsbclip1 \- 
.SH SYNOPSIS
.B sfsbclip1 < logrefa.rsf > logref_co.rsf value= clip=
.SH COMMENTS
One-sided data clipping

Built for log data manipulation - remove extraneous values introduced from LSIM shifting

.SH PARAMETERS
.PD 0
.TP
.I float  
.B clip
.B =
.R  	Clipping value
.TP
.I float  
.B value
.B =
.R  	Output if log is less than clip
.SH SOURCE
.I user/sbader/Msbclip1.py
.SH VERSION
4.2-git
