.TH sfseisxwell 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfseisxwell \- Select seismic data cross well position. 
.SH SYNOPSIS
.B sfseisxwell < in.rsf > out.rsf path=spath.rsf well=well.rsf wx= wy= nw=0
.SH PARAMETERS
.PD 0
.TP
.I int    
.B nw
.B =0
.R  	number of well points
.TP
.I string 
.B path
.B =
.R  	auxiliary output file name
.TP
.I string 
.B well
.B =
.R  	auxiliary input file name
.TP
.I floats 
.B wx
.B =
.R  	well x coordinates  [nw]
.TP
.I floats 
.B wy
.B =
.R  	well y coordinates  [nw]
.SH SOURCE
.I user/yliu/Mseisxwell.c
.SH VERSION
4.2-git
