.TH sfseisreg2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfseisreg2 \- Data regularization in 2-D using seislet transform. 
.SH SYNOPSIS
.B sfseisreg2 < in.rsf > out.rsf dip=dip.rsf eps=0.01 interp=2 niter=50 order=1 order=1 verb=n head= type=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I float  
.B eps
.B =0.01
.R  	regularization parameter
.TP
.I string 
.B head
.B =
.R  
.TP
.I int    
.B interp
.B =2
.R  	interpolation length
.TP
.I int    
.B niter
.B =50
.R  	number of iterations
.TP
.I int    
.B order
.B =1
.R  	accuracy order
.TP
.I string 
.B type
.B =
.R  	[haar,linear,biorthogonal] wavelet type, the default is linear
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/yliu/Mseisreg2.c
.SH VERSION
4.2-git
