.TH sfsemblancew 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsemblancew \- Semblance over the specified axis. 
.SH SYNOPSIS
.B sfsemblancew < in.rsf > out.rsf weighted=n axis=2 nb=2
.SH PARAMETERS
.PD 0
.TP
.I int    
.B axis
.B =2
.R  	which axis to stack
.TP
.I int    
.B nb
.B =2
.R  	smoothing along the first axis
.TP
.I bool   
.B weighted
.B =n
.R  [y/n]	if use weighted semblance
.SH SOURCE
.I user/fomels/Msemblancew.c
.SH VERSION
4.2-git
