.TH sfseisthr 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfseisthr \- Seislet Transform Denoising using Thresholding
.SH SYNOPSIS
.B sfseisthr < in.rsf > out.rsf dip=dip.rsf slet=slet.rsf sletthr=sletthr.rsf eps=0.01 pclip=99. order1=1 eps=0.01 type= thrtype=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I float  
.B eps
.B =0.01
.R  	regularization
.TP
.I int    
.B order1
.B =1
.R  	accuracy order for seislet transform
.TP
.I float  
.B pclip
.B =99.
.R  	data clip percentile (default is 99)
.TP
.I string 
.B slet
.B =
.R  	seismic domain (auxiliary output file name)
.TP
.I string 
.B sletthr
.B =
.R  	thresholded seislet domain (auxiliary output file name)
.TP
.I string 
.B thrtype
.B =
.R  	[soft,hard] thresholding type, the default is soft
.TP
.I string 
.B type
.B =
.R  	[haar,linear,biorthogonal] wavelet type, the default is linear
.SH SOURCE
.I user/chenyk/Mseisthr.c
.SH VERSION
4.2-git
