.TH sfseisbreg2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfseisbreg2 \- Missing data interpolation in 2D using seislet and Bregman shaping iteration. 
.SH SYNOPSIS
.B sfseisbreg2 < in.rsf > out.rsf dip=dip.rsf mask=mask.rsf niter=20 order=1 verb=n eps=0.01 perc=99. order=1 type= oper=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I float  
.B eps
.B =0.01
.R  	regularization parameter
.TP
.I string 
.B mask
.B =
.R  	auxiliary input file name
.TP
.I int    
.B niter
.B =20
.R  	number of iterations
.TP
.I string 
.B oper
.B =
.R  	[bregman,thresholding] method, the default is bregman
.TP
.I int    
.B order
.B =1
.R  	accuracy order
.TP
.I float  
.B perc
.B =99.
.R  	percentage for soft thresholding
.TP
.I string 
.B type
.B =
.R  	[haar,linear,biorthogonal] wavelet type, the default is biorthogonal
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/yliu/Mseisbreg2.c
.SH VERSION
4.2-git
