.TH sfseispocs 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfseispocs \- Missing data interpolation using POCS added 2-D seislet transform. 
.SH SYNOPSIS
.B sfseispocs < in.rsf > out.rsf dip=dip.rsf mask=mask.rsf convex=convex.rsf niter=20 order=1 verb=n eps=0.01 order=1 perc=90. fact=0.5 type=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B convex
.B =
.R  	auxiliary input file name
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I float  
.B eps
.B =0.01
.R  	regularization parameter
.TP
.I float  
.B fact
.B =0.5
.R  	percentage for smooth
.TP
.I string 
.B mask
.B =
.R  	auxiliary input file name
.TP
.I int    
.B niter
.B =20
.R  	number of iterations
.TP
.I int    
.B order
.B =1
.R  	accuracy order
.TP
.I float  
.B perc
.B =90.
.R  	percentage for smooth
.TP
.I string 
.B type
.B =
.R  	[haar,linear,biorthogonal] wavelet type, the default is biorthogonal
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/yliu/Mseispocs.c
.SH VERSION
4.2-git
