.TH sfsemblance 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsemblance \- Semblance over the specified axis. 
.SH SYNOPSIS
.B sfsemblance < in.rsf > out.rsf weighted=n axis=2
.SH PARAMETERS
.PD 0
.TP
.I int    
.B axis
.B =2
.R  	which axis to stack
.TP
.I bool   
.B weighted
.B =n
.R  [y/n]	if use weighted semblance
.SH SOURCE
.I user/fomels/Msemblance.c
.SH VERSION
4.2-git
