.TH sfseishrink 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfseishrink \- 2-D Seislet shrinkage denoising. 
.SH SYNOPSIS
.B sfseishrink < in.rsf > out.rsf dip=dip.rsf lcurve=lcurve.rsf hcurve=hcurve.rsf norm=norm.rsf order=1 verb=n dwt=n eps=0.01 perc=90. nperc=1 type=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B dwt
.B =n
.R  [y/n]	if y, dwt in vertical axis
.TP
.I float  
.B eps
.B =0.01
.R  	regularization parameter
.TP
.I string 
.B hcurve
.B =
.R  	auxiliary output file name
.TP
.I string 
.B lcurve
.B =
.R  	auxiliary output file name
.TP
.I string 
.B norm
.B =
.R  	auxiliary output file name
.TP
.I int    
.B nperc
.B =1
.R  	number of percentage dimension
.TP
.I int    
.B order
.B =1
.R  [1,2,3]	accuracy order
.TP
.I float  
.B perc
.B =90.
.R  	percentage for shrinkage
.TP
.I string 
.B type
.B =
.R  	[haar,linear,biorthogonal] wavelet type, the default is biorthogonal
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/yliu/Mseishrink.c
.SH VERSION
4.2-git
