.TH sfseisavf 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfseisavf \- 1-D amplitude versus frequency (AVF) analysis with 1-D seislet frames 
.SH SYNOPSIS
.B sfseisavf < in.rsf > out.rsf freq=w.rsf thr=t.rsf verb=y ncycle=0 niter=1 type=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B freq
.B =
.R  	auxiliary input file name
.TP
.I int    
.B ncycle
.B =0
.R  	number of iterations
.TP
.I int    
.B niter
.B =1
.R  	number of Bregman iterations
.TP
.I file   
.B thr
.B =
.R  	auxiliary input file name
.TP
.I string 
.B type
.B =
.R  	[haar,linear,biorthogonal] wavelet type, the default is linear
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/yliu/Mseisavf.c
.SH VERSION
4.2-git
