.TH sfsglfdrtm2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsglfdrtm2 \- None
.SH SYNOPSIS
.B sfsglfdrtm2 < Fsrc.rsf fvel=Ffvel.rsf fden=Ffden.rsf bvel=Fbvel.rsf bden=Fbden.rsf rec=Frcd.rsf > Fimg1.rsf img2=Fimg2.rsf tmpwf=Ftmpwf.rsf tmpbwf=Ftmpbwf.rsf Gx=FGx.rsf Gz=FGz.rsf sxx=Fsxx.rsf sxz=Fsxz.rsf szx=Fszx.rsf szz=Fszz.rsf verb=n wantwf=n wantrecord=y srcdecay=SRCDECAY srcrange=SRCRANGE srctrunc=SRCTRUNC pmlsize=PMLOUT pmld0=PMLD0 decay=DECAY_FLAG decaybegin=DECAY_BEGIN freesurface=n slx=-1.0 spx=-1 gdep=-1.0 gp=0 ginter=1 snapinter=10
.SH PARAMETERS
.PD 0
.TP
.I file   
.B Gx
.B =
.R  	auxiliary input file name
.TP
.I file   
.B Gz
.B =
.R  	auxiliary input file name
.TP
.I file   
.B bden
.B =
.R  	auxiliary input file name
.TP
.I file   
.B bvel
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B decay
.B =DECAY_FLAG
.R  [y/n]	Flag of decay boundary condtion: 1 = use ; 0 = not use
.TP
.I int    
.B decaybegin
.B =DECAY_BEGIN
.R  	Begin time of using decay boundary condition
.TP
.I file   
.B fden
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B freesurface
.B =n
.R  [y/n]	free surface
.TP
.I file   
.B fvel
.B =
.R  	auxiliary input file name
.TP
.I float  
.B gdep
.B =-1.0
.R  	recorder depth on grid
.TP
.I int    
.B ginter
.B =1
.R  	geophone interval
.TP
.I int    
.B gp
.B =0
.R  	recorder depth on index
.TP
.I file   
.B img2
.B =
.R  	auxiliary output file name
.TP
.I int    
.B pmld0
.B =PMLD0
.R  	PML parameter
.TP
.I int    
.B pmlsize
.B =PMLOUT
.R  	size of PML layer
.TP
.I file   
.B rec
.B =
.R  	auxiliary input file name
.TP
.I float  
.B slx
.B =-1.0
.R  	source location x
.TP
.I int    
.B snapinter
.B =10
.R  	snap interval
.TP
.I int    
.B spx
.B =-1
.R  	source location x (index)
.TP
.I bool   
.B srcdecay
.B =SRCDECAY
.R  [y/n]	source decay
.TP
.I int    
.B srcrange
.B =SRCRANGE
.R  	source decay range
.TP
.I float  
.B srctrunc
.B =SRCTRUNC
.R  	trunc source after srctrunc time (s)
.TP
.I file   
.B sxx
.B =
.R  	auxiliary input file name
.TP
.I file   
.B sxz
.B =
.R  	auxiliary input file name
.TP
.I file   
.B szx
.B =
.R  	auxiliary input file name
.TP
.I file   
.B szz
.B =
.R  	auxiliary input file name
.TP
.I file   
.B tmpbwf
.B =
.R  	auxiliary output file name
.TP
.I file   
.B tmpwf
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.TP
.I bool   
.B wantrecord
.B =y
.R  [y/n]	if n, using record data generated by this program
.TP
.I bool   
.B wantwf
.B =n
.R  [y/n]	output forward and backward wavefield
.SH SOURCE
.I user/fangg/Msglfdrtm2.c
.SH VERSION
4.2-git
