.TH sfsglfdcz2_7 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsglfdcz2_7 \- 2D Lowrank FD coefficient of d/dx on staggered grid
.SH SYNOPSIS
.B sfsglfdcz2_7 < velf.rsf > outm.rsf sx=fsx.rsf sz=fsz.rsf seed=time(NULL eps=1.e-6 npk=50 dt= size=6 wavnumcut=1.0
.SH PARAMETERS
.PD 0
.TP
.I        
.B dt
.B =
.R  	time step
.TP
.I        
.B eps
.B =1.e-6
.R  	tolerance
.TP
.I        
.B npk
.B =50
.R  	maximum rank
.TP
.I        
.B seed
.B =time(NULL
.R  
.TP
.I        
.B size
.B =6
.R  	stencil length
.TP
.I file   
.B sx
.B =
.R  	auxiliary output file name
.TP
.I file   
.B sz
.B =
.R  	auxiliary output file name
.TP
.I        
.B wavnumcut
.B =1.0
.R  	wavenumber cut percentile
.SH SOURCE
.I user/fangg/Msglfdcz2_7.cc
.SH VERSION
4.2-git
