.TH sfsgfdewe2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsgfdewe2d \- 2-D staggered-grid elastic time-domain FD modeling 
.SH SYNOPSIS
.B sfsgfdewe2d datax=dataxf.rsf dataz=datazf.rsf vp=vpf.rsf vs=vsf.rsf rho=rhof.rsf nshot=1 dshot=1 nx=nvx nabs=50 sx_ini= sz_ini=5 hsz=5 tmax= dt= peak=20
.SH COMMENTS

10th order in space, 2th order in time. 

.SH PARAMETERS
.PD 0
.TP
.I file   
.B datax
.B =
.R  	auxiliary output file name
.TP
.I file   
.B dataz
.B =
.R  	auxiliary output file name
.TP
.I int    
.B dshot
.B =1
.R  	shot interval, multiple of receiver intervals
.TP
.I float  
.B dt
.B =
.R  	time interval
.TP
.I int    
.B hsz
.B =5
.R  	vertical position of recerivers
.TP
.I int    
.B nabs
.B =50
.R  	width of padded boundary
.TP
.I int    
.B nshot
.B =1
.R  	number of shots
.TP
.I int    
.B nx
.B =nvx
.R  	coverage area for each shot
.TP
.I float  
.B peak
.B =20
.R  	peak frequency for Ricker wavelet (in Hz)
.TP
.I file   
.B rho
.B =
.R  	auxiliary input file name
.TP
.I int    
.B sx_ini
.B =
.R  	horizontal position of shot point
.TP
.I int    
.B sz_ini
.B =5
.R  	vertical position of shot point
.TP
.I float  
.B tmax
.B =
.R  	record length
.TP
.I file   
.B vp
.B =
.R  	auxiliary input file name
.TP
.I file   
.B vs
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/zhiguang/Msgfdewe2d.c
.SH VERSION
4.2-git
