.TH sfsglfdcp1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsglfdcp1 \- Relative error of phase velocity of 16-th order 1D SG Lowrank FD and 1D FD coefficient 
.SH SYNOPSIS
.B sfsglfdcp1 < velf.rsf > outm.rsf Mfd=Mfdfile.rsf Mlr=Mlrfile.rsf seed=time(NULL eps=1.e-4 npk=20 dt= size=16
.SH PARAMETERS
.PD 0
.TP
.I file   
.B Mfd
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Mlr
.B =
.R  	auxiliary output file name
.TP
.I        
.B dt
.B =
.R  	time step
.TP
.I        
.B eps
.B =1.e-4
.R  	tolerance
.TP
.I        
.B npk
.B =20
.R  	maximum rank
.TP
.I        
.B seed
.B =time(NULL
.R  
.TP
.I        
.B size
.B =16
.R  	stencil length
.SH SOURCE
.I user/fangg/Msglfdcp1.cc
.SH VERSION
4.2-git
