.TH sfshapeagc 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfshapeagc \- Automatic gain control by shaping regularization. 
.SH SYNOPSIS
.B sfshapeagc < in.rsf > out.rsf gain=fgain.rsf niter=100 eps=0.0f verb=n rect#=(125,1,1,...)
.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =0.0f
.R  	regularization
.TP
.I string 
.B gain
.B =
.R  	output gain file (optional) (auxiliary output file name)
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I int    
.B rect#
.B =(125,1,1,...)
.R  	smoothing radius on #-th axis
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.SH USED IN
.TP
.I bei/dpmv/krchdmo
.TP
.I data/alaska/line31-81-m8r
.SH SOURCE
.I user/fomels/Mshapeagc.c
.SH VERSION
4.2-git
