.TH sfshapebin 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfshapebin \- Data binning in 2-D slices by inverse interpolation. 
.SH SYNOPSIS
.B sfshapebin < in.rsf > out.rsf pattern=pattern.rsf pin=pin.rsf pout=pout.rsf xkey= ykey= nx= ny= xmin= xmax= ymin= ymax= x0=xmin y0=ymin dx= dy= interp=2 niter=nm nliter=1 eps=1./nd gauss=n shape=y verb=y filt1=3. filt2=filt1 head=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dx
.B =
.R  	bin size in x
.TP
.I float  
.B dy
.B =
.R  	bin size in y
.TP
.I float  
.B eps
.B =1./nd
.R  	regularization parameter
.TP
.I float  
.B filt1
.B =3.
.R  
.TP
.I float  
.B filt2
.B =filt1
.R  	smoothing length for shaping
.TP
.I bool   
.B gauss
.B =n
.R  [y/n]	if y, use gaussian shaping (estimated from the data)
.TP
.I string 
.B head
.B =
.R  
.TP
.I int    
.B interp
.B =2
.R  	interpolation length
.TP
.I int    
.B niter
.B =nm
.R  	number of iterations
.TP
.I int    
.B nliter
.B =1
.R  	number of reweighting iterations
.TP
.I int    
.B nx
.B =
.R  	Number of bins in x
.TP
.I int    
.B ny
.B =
.R  	Number of bins in y
.TP
.I string 
.B pattern
.B =
.R  	auxiliary input file name
.TP
.I string 
.B pin
.B =
.R  	auxiliary input file name
.TP
.I string 
.B pout
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B shape
.B =y
.R  [y/n]	if y, use shaping regularization
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity flag
.TP
.I float  
.B x0
.B =xmin
.R  
.TP
.I int    
.B xkey
.B =
.R  	x key number
.TP
.I float  
.B xmax
.B =
.R  
.TP
.I float  
.B xmin
.B =
.R  
.TP
.I float  
.B y0
.B =ymin
.R  	grid origin
.TP
.I int    
.B ykey
.B =
.R  	y key number
.TP
.I float  
.B ymax
.B =
.R  
.TP
.I float  
.B ymin
.B =
.R  	Grid dimensions
.SH SOURCE
.I system/generic/Mshapebin.c
.SH VERSION
4.2-git
