.TH sfshiftd2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfshiftd2 \- Generate shifts for 1-D regularized autoregression double sides (include the trace self for 3D shifts). 
.SH SYNOPSIS
.B sfshiftd2 < in.rsf > shift.rsf ns=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B ns
.B =
.R  	number of shifts
.SH USED IN
.TP
.I cup/rna3d/real
.SH SOURCE
.I user/gchliu/Mshiftd2.c
.SH VERSION
4.2-git
