.TH sfshifts2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfshifts2 \- Apply linear time shifts on multiple traces. 
.SH SYNOPSIS
.B sfshifts2 < in.rsf > shift.rsf s0= ds=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B ds
.B =
.R  	shift sampling
.TP
.I int    
.B s0
.B =
.R  	first shift (in number of samples along 1st axis)
.SH SOURCE
.I user/zgeng/Mshifts2.c
.SH VERSION
4.2-git
