.TH sfshotconstkirch 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfshotconstkirch \- Prestack shot-profile Kirchhoff migration in constant velocity. 
.SH SYNOPSIS
.B sfshotconstkirch < inp.rsf > out.rsf aal=y nx=ns dx=ds x0=s0 offset=n vel=
.SH COMMENTS

Requires the input to be in (time,offset,shot)

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B aal
.B =y
.R  [y/n]	if y, apply antialiasing
.TP
.I float  
.B dx
.B =ds
.R  
.TP
.I int    
.B nx
.B =ns
.R  
.TP
.I bool   
.B offset
.B =n
.R  [y/n]	if y, the output is in offset
.TP
.I float  
.B vel
.B =
.R  	velocity
.TP
.I float  
.B x0
.B =s0
.R  
.SH SOURCE
.I system/seismic/Mshotconstkirch.c
.SH VERSION
4.2-git
