.TH sfshoot2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfshoot2 \- 2-D ray shooting. 
.SH SYNOPSIS
.B sfshoot2 < vel.rsf > out.rsf shotfile=shots.rsf vel=y order=4 lsint=n nt=nx*nz nr=1 r0=x0 dr=dx tol=0.01
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dr
.B =dx
.R  	receiver increment
.TP
.I bool   
.B lsint
.B =n
.R  [y/n]	if use least-squares interpolation
.TP
.I int    
.B nr
.B =1
.R  	number of recievers
.TP
.I int    
.B nt
.B =nx*nz
.R  	Maximum number of time steps
.TP
.I int    
.B order
.B =4
.R  	Interpolation order
.TP
.I float  
.B r0
.B =x0
.R  	first receiver
.TP
.I string 
.B shotfile
.B =
.R  	file with shot locations (auxiliary input file name)
.TP
.I float  
.B tol
.B =0.01
.R  	Shooting tolerance (in degrees)
.TP
.I bool   
.B vel
.B =y
.R  [y/n]	If y, the input is velocity; if n, slowness
.SH SOURCE
.I system/seismic/Mshoot2.c
.SH VERSION
4.2-git
