.TH sfshiftd1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfshiftd1 \- Generate shifts for 1-D regularized autoregression double sides (not include the trace self). 
.SH SYNOPSIS
.B sfshiftd1 < in.rsf > shift.rsf ns=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B ns
.B =
.R  	number of shifts
.SH USED IN
.TP
.I cup/rna3d/shot
.TP
.I cup/rna3d/sin
.SH SOURCE
.I user/gchliu/Mshiftd1.c
.SH VERSION
4.2-git
