.TH sfshearer 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfshearer \- Preconditioning for traveltime picking. 
.SH SYNOPSIS
.B sfshearer < in.rsf > out.rsf niter=100 order=10 ref=1. short=1 long=10 rect1=1 rect2=1 ... 
.SH COMMENTS
rectN defines the size of the smoothing stencil in N-th dimension.

.SH PARAMETERS
.PD 0
.TP
.I int    
.B long
.B =10
.R  	long smoothing radius
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I int    
.B order
.B =10
.R  	Hilbert transformer order
.TP
.I float  
.B ref
.B =1.
.R  	Hilbert transformer reference (0.5 < ref <= 1)
.TP
.I int    
.B short
.B =1
.R  	short smoothing radius
.SH USED IN
.TP
.I bei/vela/vscan
.SH SOURCE
.I user/fomels/Mshearer.c
.SH VERSION
4.2-git Menvelope.c 696 2004-07-06 23:17:31Z fomels
