.TH sfshstack 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfshstack \- Shaping stack. 
.SH SYNOPSIS
.B sfshstack < cmp.rsf velocity=velocity.rsf > stack.rsf offset=offset.rsf half=y slowness=n h0=0. eps=0.01 jump=1 niter=10 restart=niter tol=1e-5 flo= fhi= nplo=6 nphi=6
.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =0.01
.R  	stretch regularization
.TP
.I float  
.B fhi
.B =
.R  	High frequency in band, default is Nyquist
.TP
.I float  
.B flo
.B =
.R  	Low frequency in band, default is 0
.TP
.I float  
.B h0
.B =0.
.R  	reference offset
.TP
.I bool   
.B half
.B =y
.R  [y/n]	if y, the second axis is half-offset instead of full offset
.TP
.I int    
.B jump
.B =1
.R  	subsampling
.TP
.I int    
.B niter
.B =10
.R  	number of iterations
.TP
.I int    
.B nphi
.B =6
.R  	number of poles for high cutoff
.TP
.I int    
.B nplo
.B =6
.R  	number of poles for low cutoff
.TP
.I string 
.B offset
.B =
.R  	auxiliary input file name
.TP
.I int    
.B restart
.B =niter
.R  	GMRES memory
.TP
.I bool   
.B slowness
.B =n
.R  [y/n]	if y, use slowness instead of velocity
.TP
.I float  
.B tol
.B =1e-5
.R  	GMRES tolerance
.TP
.I file   
.B velocity
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/kregimbal/Mshstack.c
.SH VERSION
4.2-git
