.TH sfsharadwav 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsharadwav \- 
.SH SYNOPSIS
.B sfsharadwav > Fou.rsf verb=n window= delay=
.SH COMMENTS
Create the time domain range compressed waveform for SHARAD
Created by: Dylan Hickson, Colorado School of Mines
Created on: Mar 9, 2022

.SH PARAMETERS
.PD 0
.TP
.I float  
.B delay
.B =
.R  	latency delay in transmitted signal in microseconds
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I bool   
.B window
.B =
.R  [y/n]	spectral Hann window flag
.SH SOURCE
.I user/cwp/Msharadwav.py
.SH VERSION
4.2-git
