.TH sfshuffle2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfshuffle2 \- Shuffling an array 
.SH SYNOPSIS
.B sfshuffle2 < bshuffle.rsf > ashuffle.rsf iteration=1 seed=2012
.SH PARAMETERS
.PD 0
.TP
.I int    
.B iteration
.B =1
.R  
.TP
.I int    
.B seed
.B =2012
.R  
.SH SOURCE
.I user/parvaneh/Mshuffle2.c
.SH VERSION
4.2-git
