.TH sfshapefill 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfshapefill \- Missing data interpolation in 2-D by Laplacian regularization. 
.SH SYNOPSIS
.B sfshapefill < in.rsf > out.rsf mask=mask.rsf niter=200 verb=n dim=dim rect#=(1,1,...)
.SH PARAMETERS
.PD 0
.TP
.I int    
.B dim
.B =dim
.R  	dimensionality
.TP
.I string 
.B mask
.B =
.R  	optional mask file with zeroes for missing data locations (auxiliary input file name)
.TP
.I int    
.B niter
.B =200
.R  	number of iterations
.TP
.I int    
.B rect#
.B =(1,1,...)
.R  	smoothing radius on #-th axis
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/fomels/Mshapefill.c
.SH VERSION
4.2-git
