.TH sfshifts 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfshifts \- Multiple shifts. 
.SH SYNOPSIS
.B sfshifts < inp.rsf > out.rsf np= dp= p0=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dp
.B =
.R  	slope sampling
.TP
.I int    
.B np
.B =
.R  	number of slopes
.TP
.I float  
.B p0
.B =
.R  	first slope
.SH SOURCE
.I system/seismic/Mshifts.c
.SH VERSION
4.2-git
