.TH sfshapesigk 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfshapesigk \- Signal component separation using plane-wave shaping. 
.SH SYNOPSIS
.B sfshapesigk < in.rsf dips=dips.rsf > out.rsf niter=50 eps=1. verb=n rect1=1 rect2=1
.SH COMMENTS

The program works with 2-D data.

.SH PARAMETERS
.PD 0
.TP
.I file   
.B dips
.B =
.R  	auxiliary input file name
.TP
.I float  
.B eps
.B =1.
.R  	regularization parameter
.TP
.I int    
.B niter
.B =50
.R  	maximum number of iterations
.TP
.I int    
.B rect1
.B =1
.R  	vertical smoothing radius
.TP
.I int    
.B rect2
.B =1
.R  	lateral smoothing radius
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/pwd/Mshapesigk.c
.SH VERSION
4.2-git
