.TH sfshuffle 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfshuffle \- shuffle the data
.SH SYNOPSIS
.B sfshuffle < pi.rsf > po.rsf axis=2 seed=n2 inv=n
.SH PARAMETERS
.PD 0
.TP
.I int    
.B axis
.B =2
.R  
.TP
.I bool   
.B inv
.B =n
.R  [y/n]
.TP
.I int    
.B seed
.B =n2
.R  
.SH USED IN
.TP
.I chen/test/fpca
.SH SOURCE
.I user/chen/Mshuffle.py
.SH VERSION
4.2-git
