.TH sfshift 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfshift \- Fourier-domain shift in 1,2 and 3 dimensions 
.SH SYNOPSIS
.B sfshift < Fi.rsf > Fo.rsf ompchunk=1 verb=n del1=0. del2=0. del3=0.
.SH PARAMETERS
.PD 0
.TP
.I float  
.B del1
.B =0.
.R  	delay on axis 1
.TP
.I float  
.B del2
.B =0.
.R  	delay on axis 2
.TP
.I float  
.B del3
.B =0.
.R  	delay on axis 3
.TP
.I int    
.B ompchunk
.B =1
.R  	OpenMP data chunk size
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/psava/Mshift.c
.SH VERSION
4.2-git
