.TH sfsint2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsint2 \- Interpolation for sparse data in 2D, e.g., well logs 
.SH SYNOPSIS
.B sfsint2 < in.rsf > out.rsf dip=dip.rsf mask=mask.rsf niter=100 order=1 ns=1 eps=0.01
.SH PARAMETERS
.PD 0
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I float  
.B eps
.B =0.01
.R  	regularization
.TP
.I string 
.B mask
.B =
.R  	auxiliary input file name
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I int    
.B ns
.B =1
.R  	smoothing radius
.TP
.I int    
.B order
.B =1
.R  	accuracy order
.SH SOURCE
.I user/chenyk/Msint2.c
.SH VERSION
4.2-git
