.TH sfsin 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsin \- Simple operations with complex sinusoids 
.SH SYNOPSIS
.B sfsin < in.rsf > out.rsf root=root.rsf mask=mask.rsf adj=n verb=n niter=0 rect=1 perc=50. fact=0.5 eps=1./n1 oper= type=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag
.TP
.I float  
.B eps
.B =1./n1
.R  	scaling for shaping inversion
.TP
.I float  
.B fact
.B =0.5
.R  	factor for thresholding (used when oper=t and niter > 0)
.TP
.I string 
.B mask
.B =
.R  	missing data interpolation (auxiliary input file name)
.TP
.I int    
.B niter
.B =0
.R  	number of iterations
.TP
.I string 
.B oper
.B =
.R  	operation to perform
.TP
.I float  
.B perc
.B =50.
.R  	percentage for thresholding (used when oper=t and niter > 0)
.TP
.I int    
.B rect
.B =1
.R  	smoothing radius (for oper=s)
.TP
.I file   
.B root
.B =
.R  	auxiliary input file name
.TP
.I string 
.B type
.B =
.R  	[haar,linear,biortho] type of the seislet transform
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I system/seismic/Msin.c
.SH VERSION
4.2-git
