.TH sfsint3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsint3 \- Interpolation for sparse data in 3D, e.g., well logs 
.SH SYNOPSIS
.B sfsint3 < in.rsf > out.rsf dip=dip.rsf mask=mask.rsf niter=100 order1=1 order2=1 ns1=1 ns2=1 eps=0.01
.SH PARAMETERS
.PD 0
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I float  
.B eps
.B =0.01
.R  	regularization
.TP
.I string 
.B mask
.B =
.R  	auxiliary input file name
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I int    
.B ns1
.B =1
.R  
.TP
.I int    
.B ns2
.B =1
.R  	smoothing radius
.TP
.I int    
.B order1
.B =1
.R  
.TP
.I int    
.B order2
.B =1
.R  	accuracy order
.SH SOURCE
.I user/chenyk/Msint3.c
.SH VERSION
4.2-git
