.TH sfsimidenoise 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsimidenoise \- Random noise attenuation using local similarity 
.SH SYNOPSIS
.B sfsimidenoise < in.rsf > out.rsf similarity=simi.rsf thr=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B similarity
.B =
.R  	auxiliary input file name
.TP
.I float  
.B thr
.B =
.R  	thresholding level
.SH SOURCE
.I user/chenyk/Msimidenoise.c
.SH VERSION
4.2-git
