.TH sfsimilarity 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsimilarity \- Local similarity measure between two datasets. 
.SH SYNOPSIS
.B sfsimilarity < in.rsf > out.rsf other=other.rsf verb=y niter=20 eps=0.0f rect#=(1,1,...)
.SH COMMENTS

September 2015 program of the month:
http://ahay.org/blog/2015/09/14/program-of-the-month-sfsimilarity/

.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =0.0f
.R  	regularization
.TP
.I int    
.B niter
.B =20
.R  	maximum number of iterations
.TP
.I file   
.B other
.B =
.R  	auxiliary input file name
.TP
.I int    
.B rect#
.B =(1,1,...)
.R  	smoothing radius on #-th axis
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity
.SH SOURCE
.I user/fomels/Msimilarity.c
.SH VERSION
4.2-git
