.TH sfsic3d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsic3d \- Local slant stacks I.C. 
.SH SYNOPSIS
.B sfsic3d < Fs.rsf ur=Fr.rsf > Fi.rsf ompchunk=1 verb=n stack=n sig=1.0 nanga=1 oanga=0.0 danga=1.0 nangb=1 oangb=0.0 dangb=1.0 nl=1 dl=1. ol=0.
.SH PARAMETERS
.PD 0
.TP
.I float  
.B danga
.B =1.0
.R  
.TP
.I float  
.B dangb
.B =1.0
.R  
.TP
.I float  
.B dl
.B =1.
.R  
.TP
.I int    
.B nanga
.B =1
.R  
.TP
.I int    
.B nangb
.B =1
.R  
.TP
.I int    
.B nl
.B =1
.R  
.TP
.I float  
.B oanga
.B =0.0
.R  
.TP
.I float  
.B oangb
.B =0.0
.R  
.TP
.I float  
.B ol
.B =0.
.R  
.TP
.I int    
.B ompchunk
.B =1
.R  	OpenMP data chunk size
.TP
.I float  
.B sig
.B =1.0
.R  
.TP
.I bool   
.B stack
.B =n
.R  [y/n]
.TP
.I file   
.B ur
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH USED IN
.TP
.I cwp/geo2007StereographicImagingCondition/flat4
.TP
.I cwp/geo2007StereographicImagingCondition/gaus1
.TP
.I cwp/geo2007StereographicImagingCondition/sigsbee2
.SH SOURCE
.I user/psava/Msic3d.c
.SH VERSION
4.2-git
