.TH sfsimidenoise1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsimidenoise1 \- Random noise attenuation using local similarity (different weighting approach) 
.SH SYNOPSIS
.B sfsimidenoise1 < in.rsf > out.rsf similarity=simi.rsf s1= s2=
.SH COMMENTS
The weighting function is defined as
W(s) = 1				if s>s2
	 = (s-s1)/(s2-s1)	if s1<=s<=s2
	 = 0				if s<s1

.SH PARAMETERS
.PD 0
.TP
.I float  
.B s1
.B =
.R  	thresholding level 1
.TP
.I float  
.B s2
.B =
.R  	thresholding level 2
.TP
.I file   
.B similarity
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/chenyk/Msimidenoise1.c
.SH VERSION
4.2-git
