.TH sfsimenv 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsimenv \- Rotate phase and compute similarity with enevelope. 
.SH SYNOPSIS
.B sfsimenv < inp.rsf > sim.rsf na=360 da=1.0 a0=-180. order=100 ref=1. verb=y inv=y niter=20 rect=3
.SH PARAMETERS
.PD 0
.TP
.I float  
.B a0
.B =-180.
.R  	first angle
.TP
.I float  
.B da
.B =1.0
.R  	angle increment
.TP
.I bool   
.B inv
.B =y
.R  [y/n]	inverse similarity
.TP
.I int    
.B na
.B =360
.R  	number of angles
.TP
.I int    
.B niter
.B =20
.R  	maximum number of iterations
.TP
.I int    
.B order
.B =100
.R  	Hilbert transformer order
.TP
.I int    
.B rect
.B =3
.R  	smoothing radius
.TP
.I float  
.B ref
.B =1.
.R  	Hilbert transformer reference (0.5 < ref <= 1)
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity
.SH SOURCE
.I user/fomels/Msimenv.c
.SH VERSION
4.2-git
