.TH sfsignal 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsignal \- Generate signal series 
.SH SYNOPSIS
.B sfsignal > out.rsf para= n=100 o=0.0 d=0.004 waveform=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B d
.B =0.004
.R  	interval
.TP
.I int    
.B n
.B =100
.R  	length
.TP
.I float  
.B o
.B =0.0
.R  	original
.TP
.I floats 
.B para
.B =
.R  	 [4]
.TP
.I string 
.B waveform
.B =
.R  	waveform: ricker,sinc,harmonic,randn,rand
.SH USED IN
.TP
.I chen/test/wavmod
.SH SOURCE
.I user/chen/Msignal.c
.SH VERSION
4.2-git
