.TH sfsigmoid 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsigmoid \- 2-D synthetic model from J.F.Claerbout. 
.SH SYNOPSIS
.B sfsigmoid > mod.rsf n1=400 n2=100 large=5*n1 o1=0. o2=0. d1=0.004 d2=0.032 reflectivity=y taper=y
.SH COMMENTS

October 2014 program of the month:
http://ahay.org/blog/2014/10/08/program-of-the-month-sfsigmoid/

.SH PARAMETERS
.PD 0
.TP
.I float  
.B d1
.B =0.004
.R  
.TP
.I float  
.B d2
.B =0.032
.R  	sampling
.TP
.I int    
.B large
.B =5*n1
.R  	reflectivity series
.TP
.I int    
.B n1
.B =400
.R  	vertical axis
.TP
.I int    
.B n2
.B =100
.R  	horizontal axis
.TP
.I float  
.B o1
.B =0.
.R  
.TP
.I float  
.B o2
.B =0.
.R  	origin
.TP
.I bool   
.B reflectivity
.B =y
.R  [y/n]	if output reflectivity (otherwise output impedance model)
.TP
.I bool   
.B taper
.B =y
.R  [y/n]	if taper the edges
.SH USED IN
.TP
.I bei/dwnc/sigmoid
.TP
.I bei/krch/sep73
.SH SOURCE
.I user/gee/Msigmoid.c
.SH VERSION
4.2-git
