.TH sfsmoothcur 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsmoothcur \- Convert input slope and time derivative
.SH SYNOPSIS
.B sfsmoothcur < DATA.rsf dipt=DIPT.rsf > MODEL.rsf dataout=DATA_OUT.rsf eps=1.0 niter=100 rect#=(1,1,...)
.SH COMMENTS
* to its curvature field using LS and shaping regularization
* applied to causint_lop d = L m

Takes: rect1= rect2= ...

rectN defines the size of the smoothing stencil in N-th dimension.

.SH PARAMETERS
.PD 0
.TP
.I string 
.B dataout
.B =
.R  	optionally, output predicted data (auxiliary output file name)
.TP
.I file   
.B dipt
.B =
.R  	auxiliary input file name
.TP
.I float  
.B eps
.B =1.0
.R  	dumping factor
.TP
.I int    
.B niter
.B =100
.R  	maximum number of iterations
.TP
.I int    
.B rect#
.B =(1,1,...)
.R  	smoothing radius on #-th axis
.SH SOURCE
.I user/lcasasan/Msmoothcur.c
.SH VERSION
4.2-git Mdix.c 5595 2010-03-21 16:54:14Z sfomel
