.TH sfsmstack 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsmstack \- Stack a dataset over the second dimensions by smart stacking. 
.SH SYNOPSIS
.B sfsmstack < in.rsf > out.rsf s=1 l=0 ifwt=y esp=1e-10
.SH PARAMETERS
.PD 0
.TP
.I float  
.B esp
.B =1e-10
.R  
.TP
.I bool   
.B ifwt
.B =y
.R  [y/n]
.TP
.I int    
.B l
.B =0
.R  	parameter for alpha-trimmed mean
.TP
.I int    
.B s
.B =1
.R  	exponent
.SH SOURCE
.I user/gchliu/Msmstack.c
.SH VERSION
4.2-git
