.TH sfsmopick 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsmopick \- 
.SH SYNOPSIS
.B sfsmopick < Fin.rsf > Fou.rsf verb=n wpo=1.0 ne=1 oe=0.0 de=+0.1
.SH COMMENTS
smooth picker on the first dimension

.SH PARAMETERS
.PD 0
.TP
.I float  
.B de
.B =+0.1
.R  
.TP
.I int    
.B ne
.B =1
.R  
.TP
.I float  
.B oe
.B =0.0
.R  
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I float  
.B wpo
.B =1.0
.R  	weight exponent
.SH SOURCE
.I user/psava/Msmopick.py
.SH VERSION
4.2-git
