.TH sfsmoothn 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsmoothn \- N-D non-stationary smoothing (fixed version of sfnsmooth.) 
.SH SYNOPSIS
.B sfsmoothn < in.rsf > out.rsf repeat=1 rect#= shift#=
.SH COMMENTS
Note Fomel's Mnsmooth.c may contain bugs in user/fomel/ntriangle.c
t[i] -> t[o+i*d]; s[i]->s[o+i*d] in triple 
Example: chenyk/ortho_non/nsmooth

.SH PARAMETERS
.PD 0
.TP
.I string 
.B rect#
.B =
.R  	size of the smoothing stencil in #-th dimension /auxiliary input file/
.TP
.I int    
.B repeat
.B =1
.R  	repeat filtering several times
.TP
.I string 
.B shift#
.B =
.R  	shifting of the smoothing stencil in #-th dimension /auxiliary input file/
.SH SOURCE
.I user/chenyk/Msmoothn.c
.SH VERSION
4.2-git
