.TH sfsmooth 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsmooth \- Multi-dimensional triangle smoothing. 
.SH SYNOPSIS
.B sfsmooth < in.rsf > out.rsf repeat=1 adj=n rect#=(1,1,...) diff#=(n,n,...)
.SH COMMENTS

January 2012 program of the month:
http://ahay.org/blog/2012/01/01/program-of-the-month-sfsmooth/

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	run in the adjoint mode
.TP
.I bool   
.B diff#
.B =(n,n,...)
.R  [y/n]	differentiation on #-th axis
.TP
.I int    
.B rect#
.B =(1,1,...)
.R  	smoothing radius on #-th axis
.TP
.I int    
.B repeat
.B =1
.R  	repeat filtering several times
.SH USED IN
.TP
.I bei/dpmv/matt
.TP
.I bei/dpmv/yalei
.TP
.I bei/dwnc/sigmoid
.TP
.I bei/dwnc/vofz
.TP
.I bei/fdm/kjartjac
.TP
.I bei/fld/synmarine
.TP
.I bei/ft1/autocor
.TP
.I bei/ft1/ft2d
.TP
.I bei/ft1/plane4
.TP
.I bei/krch/sep73
.TP
.I bei/sg/denmark
.TP
.I cup/rna3d/real
.TP
.I cup/rna3d/sin
.TP
.I cwp/geo2006TimeShiftImagingCondition/flat
.TP
.I cwp/geo2006TimeShiftImagingCondition/zicig
.TP
.I cwp/geo2007StereographicImagingCondition/flat4
.TP
.I cwp/geo2007StereographicImagingCondition/gaus1
.TP
.I cwp/geo2007StereographicImagingCondition/sigsbee2
.TP
.I cwp/geo2008InterferometricImagingCondition/sact1
.TP
.I cwp/geo2008InterferometricImagingCondition/sigs2
.TP
.I cwp/geo2008IsotropicAngleDomainElasticRTM/marm2allA
.TP
.I cwp/geo2008IsotropicAngleDomainElasticRTM/marm2oneA
.TP
.I cwp/geo2008NumericWEMVAoperators/flatWEMVA
.TP
.I cwp/geo2008NumericWEMVAoperators/saltWEMVA
.TP
.I cwp/geo2009VTIModeSeparation/separate3
.TP
3 more examples listed in:
.TP
/home/mlouboutin3/Research/madagascar//share/doc/madagascar/html/sfsmooth.html
.SH SOURCE
.I system/generic/Msmooth.c
.SH VERSION
4.2-git
