.TH sfsnrcyk 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsnrcyk \- Compute signal-noise-ratio.
.SH SYNOPSIS
.B sfsnrcyk < signal.rsf noisy=noise.rsf > snrf.rsf
.SH COMMENTS
SNR=10 log10(sum(clean)/sum(noise))
.SH PARAMETERS
.PD 0
.TP
.I file   
.B noisy
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/chenyk/Msnrcyk.c
.SH VERSION
4.2-git
