.TH sfsnr2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsnr2 \- Compute signal-noise-ratio.
.SH SYNOPSIS
.B sfsnr2 < signal.rsf noise=noise.rsf > snrf.rsf
.SH COMMENTS

SNR=10 log10(sum(clean)/sum(noise))

August 2019 program of the month:
http://ahay.org/blog/2019/08/10/program-of-the-month-sfsnr2/

.SH PARAMETERS
.PD 0
.TP
.I file   
.B noise
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/chenyk/Msnr2.c
.SH VERSION
4.2-git
