.TH sfsortdensity 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsortdensity \- sort density
.SH SYNOPSIS
.B sfsortdensity < Fin.rsf > Fout.rsf verb=n thrsh=0.05
.SH PARAMETERS
.PD 0
.TP
.I float  
.B thrsh
.B =0.05
.R  	verbosity flag
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/jyan/Msortdensity.c
.SH VERSION
4.2-git
