.TH sfspefcstep 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfspefcstep \- Streaming prediction-error filter with constant step. 
.SH SYNOPSIS
.B sfspefcstep < inp.rsf > out.rsf infil=infil.rsf verb=n na= ngp=0 lambda1= lambda2=0.0f
.SH PARAMETERS
.PD 0
.TP
.I string 
.B infil
.B =
.R  	initial filter (auxiliary input file name)
.TP
.I float  
.B lambda1
.B =
.R  	constant scale parameter in time axis
.TP
.I float  
.B lambda2
.B =0.0f
.R  	constant scale parameter in space axis
.TP
.I int    
.B na
.B =
.R  	filter size
.TP
.I int    
.B ngp
.B =0
.R  	constant step
.TP
.I bool   
.B verb
.B =n
.R  [y/n]
.SH SOURCE
.I user/yliu/Mspefcstep.c
.SH VERSION
4.2-git
