.TH sfspitzbl 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfspitzbl \- Missing data interpolation in 2-D using F-X Prediction Error Filters
.SH SYNOPSIS
.B sfspitzbl < in.rsf > out.rsf order=3 ntraces=1 f1=0.0 f2=1.0 verb=n norm=y
.SH COMMENTS
based on Seismic trace interpolation in the F-X domain
S.Spitz Geophysics 56, 785(1991). 
This implementation is for bandlimited [f1 f2] signals


.SH PARAMETERS
.PD 0
.TP
.I float  
.B f1
.B =0.0
.R  	lower  frequency in band limited signal >= 0.0
.TP
.I float  
.B f2
.B =1.0
.R  	higher frequency in band limited signal <= 1.0  (normalized nyquist)
.TP
.I bool   
.B norm
.B =y
.R  [y/n]	normalization flag
.TP
.I int    
.B ntraces
.B =1
.R  	number of traces to be interpolated
.TP
.I int    
.B order
.B =3
.R  	linear PEF order
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/lcasasan/Mspitzbl.c
.SH VERSION
4.2-git
