.TH sfspline 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfspline \- 1-D cubic spline interpolation.
.SH SYNOPSIS
.B sfspline < in.rsf > out.rsf pattern=pattern.rsf fp= sort=n
.SH COMMENTS

Specify either n1= o1= d1= or pattern=

.SH PARAMETERS
.PD 0
.TP
.I floats 
.B fp
.B =
.R  	end-point derivatives  [2]
.TP
.I string 
.B pattern
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B sort
.B =n
.R  [y/n]	if y, the coordinates need sorting
.SH USED IN
.TP
.I cwp/geo2008IsotropicAngleDomainElasticRTM/marm2allA
.TP
.I cwp/geo2008IsotropicAngleDomainElasticRTM/marm2oneA
.TP
.I cwp/geo2009TTIModeSeparation/fold
.SH SOURCE
.I system/generic/Mspline.c
.SH VERSION
4.2-git
