.TH sfsplineplane 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsplineplane \- B-spline plane-wave filter 
.SH SYNOPSIS
.B sfsplineplane > out.rsf lag=lag.rsf nw=2 p=0. niter=20 eps=SF_EPS
.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =SF_EPS
.R  
.TP
.I string 
.B lag
.B =
.R  	auxiliary output file name
.TP
.I int    
.B niter
.B =20
.R  	number of spectral decomposition iterations
.TP
.I int    
.B nw
.B =2
.R  	filter size
.TP
.I float  
.B p
.B =0.
.R  	plane-wave slope
.SH SOURCE
.I user/gee/Msplineplane.c
.SH VERSION
4.2-git
