.TH sfsplinefilter 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsplinefilter \- Convert data to B-spline coefficients. 
.SH SYNOPSIS
.B sfsplinefilter < in.rsf > out.rsf nw=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B nw
.B =
.R  	filter size
.SH SOURCE
.I system/generic/Msplinefilter.c
.SH VERSION
4.2-git
