.TH sfspray 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfspray \- Extend a dataset by duplicating in the specified axis dimension.
.SH SYNOPSIS
.B sfspray < in.rsf > out.rsf axis=2 n= d= o= label= unit=
.SH COMMENTS
This operation is adjoint to sfstack.

.SH PARAMETERS
.PD 0
.TP
.I int    
.B axis
.B =2
.R  	which axis to spray
.TP
.I float  
.B d
.B =
.R  	Sampling of the newly created dimension
.TP
.I string 
.B label
.B =
.R  	Label of the newly created dimension
.TP
.I int    
.B n
.B =
.R  	Size of the newly created dimension
.TP
.I float  
.B o
.B =
.R  	Origin of the newly created dimension
.TP
.I string 
.B unit
.B =
.R  	Units of the newly created dimension
.SH USED IN
.TP
.I bei/ft1/ft2d
.TP
.I bei/trimo/mod
.TP
.I bei/vela/strat
.TP
.I cup/rna3d/shot
.TP
.I cwp/geo2006TimeShiftImagingCondition/flat
.TP
.I cwp/geo2006TimeShiftImagingCondition/zicig
.TP
.I cwp/geo2007StereographicImagingCondition/flat4
.TP
.I cwp/geo2007StereographicImagingCondition/gaus1
.TP
.I cwp/geo2008IsotropicAngleDomainElasticRTM/marm2allA
.TP
.I cwp/geo2008IsotropicAngleDomainElasticRTM/marm2oneA
.TP
.I cwp/geo2008NumericWEMVAoperators/flatWEMVA
.TP
.I cwp/geo2008NumericWEMVAoperators/saltWEMVA
.TP
.I cwp/geo2009TTIModeSeparation/fold
.TP
.I cwp/geo2009TTIModeSeparation/marmousi2
.TP
.I cwp/geo2011WideAzimuthAngleDecomposition/flatEICangle
.TP
.I cwp/jse2006RWEImagingOverturningReflections/sigsbee
.TP
.I cwp/pept2011MicroearthquakeMonitoring/saf1
.TP
.I cwp/pept2011MicroearthquakeMonitoring/saf2
.TP
.I cwp/pept2011MicroearthquakeMonitoring/saf3
.TP
.I data/alaska/line31-81-m8r
.SH SOURCE
.I system/main/spray.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfspray
.SH VERSION
4.2-git
