.TH sfsqsanaly 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsqsanaly \- Analytic escape solutions in phase space for constant gradient of slowness squared 
.SH SYNOPSIS
.B sfsqsanaly < in.rsf > out.rsf iq= gx= gz= sc= xc= zc=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B gx
.B =
.R  	x-gradient of slowness^2
.TP
.I float  
.B gz
.B =
.R  	z-gradient of slowness^2
.TP
.I int    
.B iq
.B =
.R  	switch for escape variable 0=x, 1=a, 2=t, 3=z
.TP
.I float  
.B sc
.B =
.R  	slowness constant
.TP
.I float  
.B xc
.B =
.R  	x reference
.TP
.I float  
.B zc
.B =
.R  	z reference
.SH SOURCE
.I user/browaeys/Msqsanaly.c
.SH VERSION
4.2-git
