.TH sfsrmod3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsrmod3 \- 3-D S/R modeling with extended split-step 
.SH SYNOPSIS
.B sfsrmod3 slo=Fs_s.rsf sls=Fs_r.rsf < Fw_s.rsf > Fw_r.rsf ref=Fr.rsf ompchunk=1 ompnth=0 verb=y eps=0.01 nrmax=1 dtmax=0.004 pmx=0 pmy=0 tmx=0 tmy=0 twoway=n
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dtmax
.B =0.004
.R  	time error
.TP
.I float  
.B eps
.B =0.01
.R  	stability parameter
.TP
.I int    
.B nrmax
.B =1
.R  	maximum number of refs
.TP
.I int    
.B ompchunk
.B =1
.R  	OpenMP data chunk size
.TP
.I int    
.B ompnth
.B =0
.R  	OpenMP available threads
.TP
.I int    
.B pmx
.B =0
.R  	padding on x
.TP
.I int    
.B pmy
.B =0
.R  	padding on y
.TP
.I file   
.B ref
.B =
.R  	auxiliary input file name
.TP
.I file   
.B slo
.B =
.R  	auxiliary input file name
.TP
.I string 
.B sls
.B =
.R  	auxiliary input file name
.TP
.I int    
.B tmx
.B =0
.R  	taper on x
.TP
.I int    
.B tmy
.B =0
.R  	taper on y
.TP
.I bool   
.B twoway
.B =n
.R  [y/n]	two-way traveltime
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity flag
.SH USED IN
.TP
.I cwp/geo2006TimeShiftImagingCondition/flat
.TP
.I cwp/geo2007StereographicImagingCondition/sigsbee2
.TP
.I cwp/geo2008NumericWEMVAoperators/flatWEMVA
.TP
.I cwp/geo2008NumericWEMVAoperators/saltWEMVA
.SH SOURCE
.I user/psava/Msrmod3.c
.SH VERSION
4.2-git
