.TH sfsscrg 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsscrg \- Extract common reciever gathers from simultaneous data 
.SH SYNOPSIS
.B sfsscrg < in.rsf delay=delay.rsf > out.rsf jt=1 nt=n1
.SH PARAMETERS
.PD 0
.TP
.I file   
.B delay
.B =
.R  	auxiliary input file name
.TP
.I int    
.B jt
.B =1
.R  	subsampling [nps] in observation
.TP
.I int    
.B nt
.B =n1
.R  
.SH SOURCE
.I user/chen/Msscrg.c
.SH VERSION
4.2-git
