.TH sfss 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfss \- generate simultaneous sources grid from delay file 
.SH SYNOPSIS
.B sfss < in.rsf > out.rsf n1=1000 o1=0.0 d1=0.004 l1= u1=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B d1
.B =0.004
.R  	original
.TP
.I string 
.B l1
.B =
.R  	label "Time"
.TP
.I int    
.B n1
.B =1000
.R  	samples
.TP
.I float  
.B o1
.B =0.0
.R  	sampling interval
.TP
.I string 
.B u1
.B =
.R  	unit "s"
.SH SOURCE
.I user/chen/Mss.c
.SH VERSION
4.2-git
