.TH sfssblend 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfssblend \- blend reciever gathers (T-S-R) to generate simultaneous data 
.SH SYNOPSIS
.B sfssblend < in.rsf delay=delay.rsf > out.rsf jt=1
.SH PARAMETERS
.PD 0
.TP
.I file   
.B delay
.B =
.R  	auxiliary input file name
.TP
.I int    
.B jt
.B =1
.R  	subsampling nps
.SH SOURCE
.I user/chen/Mssblend.c
.SH VERSION
4.2-git
