.TH sfstiff3d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfstiff3d \- stiffness tensor for 3D TTI models
.SH SYNOPSIS
.B sfstiff3d vp=Fvp.rsf vs=Fvs.rsf ro=Fro.rsf epsilon=Fepsilon.rsf delta=Fdelta.rsf gamma=Fgamma.rsf nu=Fnu.rsf alpha=Falpha.rsf > Fcc.rsf verb=n dim=2
.SH PARAMETERS
.PD 0
.TP
.I file   
.B alpha
.B =
.R  	auxiliary input file name
.TP
.I file   
.B delta
.B =
.R  	auxiliary input file name
.TP
.I int    
.B dim
.B =2
.R  	verbosity flag
.TP
.I file   
.B epsilon
.B =
.R  	auxiliary input file name
.TP
.I file   
.B gamma
.B =
.R  	auxiliary input file name
.TP
.I file   
.B nu
.B =
.R  	auxiliary input file name
.TP
.I file   
.B ro
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I file   
.B vp
.B =
.R  	auxiliary input file name
.TP
.I file   
.B vs
.B =
.R  	auxiliary input file name
.SH USED IN
.TP
.I cwp/geo2009TTIModeSeparation/tti3
.SH SOURCE
.I user/jyan/Mstiff3d.c
.SH VERSION
4.2-git
