.TH sfstack3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfstack3 \- OpenMP stack on axis 1,2 or 3 
.SH SYNOPSIS
.B sfstack3 < Fi.rsf > Fo.rsf verb=n axis=2 verb=y nbuf=1
.SH PARAMETERS
.PD 0
.TP
.I int    
.B axis
.B =2
.R  	stack axis
.TP
.I int    
.B nbuf
.B =1
.R  	buffer size
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/psava/Mstack3.c
.SH VERSION
4.2-git
