.TH sfstackn 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfstackn \- Stack prespecified values. 
.SH SYNOPSIS
.B sfstackn < in.rsf > out.rsf min=minin.rsf max=maxin.rsf mean=y thres=0.
.SH PARAMETERS
.PD 0
.TP
.I string 
.B max
.B =
.R  	file determining up to which value to stack (auxiliary input file name)
.TP
.I bool   
.B mean
.B =y
.R  [y/n]	if n, sum; if y, average
.TP
.I string 
.B min
.B =
.R  	file determining from which value to stack (auxiliary input file name)
.TP
.I float  
.B thres
.B =0.
.R  	threshold (percentage of maxabs)
.SH SOURCE
.I user/saragiotis/Mstackn.c
.SH VERSION
4.2-git
