.TH sfstltft 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfstltft \- Streaming time-frequency transform (LTFT). 
.SH SYNOPSIS
.B sfstltft < in.rsf > out.rsf basis=basis.rsf mask=mask.rsf weight=weight.rsf inv=n verb=n nw= dw= w0=0. lambda=1.0f
.SH PARAMETERS
.PD 0
.TP
.I string 
.B basis
.B =
.R  	auxiliary output file name
.TP
.I float  
.B dw
.B =
.R  	frequency step
.TP
.I bool   
.B inv
.B =n
.R  [y/n]	if y, do inverse transform
.TP
.I float  
.B lambda
.B =1.0f
.R  	smoothing parameter
.TP
.I string 
.B mask
.B =
.R  	data weight (auxiliary input file name)
.TP
.I int    
.B nw
.B =
.R  	number of frequencies
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I float  
.B w0
.B =0.
.R  	first frequency
.TP
.I string 
.B weight
.B =
.R  	model weight (auxiliary input file name)
.SH SOURCE
.I user/fomels/Mstltft.c
.SH VERSION
4.2-git
