.TH sfstf2telewfld 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfstf2telewfld \- None
.SH SYNOPSIS
.B sfstf2telewfld < infile.rsf stf=stffile.rsf > outfile.rsf old=oldfile.rsf p1=0. z0=40. v0=8.0 dt=0.001
.SH PARAMETERS
.PD 0
.TP
.I        
.B dt
.B =0.001
.R  
.TP
.I file   
.B old
.B =
.R  	auxiliary output file name
.TP
.I        
.B p1
.B =0.
.R  
.TP
.I file   
.B stf
.B =
.R  	auxiliary input file name
.TP
.I        
.B v0
.B =8.0
.R  
.TP
.I        
.B z0
.B =40.
.R  
.SH SOURCE
.I user/jeff/Mstf2telewfld.f90
.SH VERSION
4.2-git
