.TH sfstcurvature 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfstcurvature \- Curvature in stratigraphic coordinates 
.SH SYNOPSIS
.B sfstcurvature < xhor.rsf yh=yhor.rsf zh=zhor.rsf > cur.rsf scale=1.0 what=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B scale
.B =1.0
.R  	scaling (from time to depth)
.TP
.I string 
.B what
.B =
.R  	what to compute
.TP
.I file   
.B yh
.B =
.R  	auxiliary input file name
.TP
.I file   
.B zh
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/parvaneh/Mstcurvature.c
.SH VERSION
4.2-git
