.TH sfstreamissh 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfstreamissh \- Missing data interpolating using streaming PEF on a helix 
.SH SYNOPSIS
.B sfstreamissh < inp.rsf > out.rsf lag=lag.rsf known=known.rsf a= n= na=0 eps= var=0.0f seed=time(NULL)
.SH PARAMETERS
.PD 0
.TP
.I ints   
.B a
.B =
.R  	filter shape  [dim]
.TP
.I float  
.B eps
.B =
.R  	regularization
.TP
.I file   
.B known
.B =
.R  	auxiliary input file name
.TP
.I string 
.B lag
.B =
.R  	auxiliary input file name
.TP
.I ints   
.B n
.B =
.R  	 [dim]
.TP
.I int    
.B na
.B =0
.R  	PEF filter size (not including leading one)
.TP
.I int    
.B seed
.B =time(NULL)
.R  	random seed
.TP
.I float  
.B var
.B =0.0f
.R  	noise variance
.SH SOURCE
.I user/gee/Mstreamissh.c
.SH VERSION
4.2-git
