.TH sfstphase 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfstphase \- Streaming estimate of instantaneous frequency. 
.SH SYNOPSIS
.B sfstphase < in.rsf > out.rsf lambda= window_size=1 verb=n complex=n order=100 ref=1. hertz=n band=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B band
.B =n
.R  [y/n]	if y, compute instantaneous bandwidth
.TP
.I bool   
.B complex
.B =n
.R  [y/n]	if y, use complex-valued computations
.TP
.I bool   
.B hertz
.B =n
.R  [y/n]	if y, convert output to Hertz
.TP
.I float  
.B lambda
.B =
.R  
.TP
.I int    
.B order
.B =100
.R  	Hilbert transformer order
.TP
.I float  
.B ref
.B =1.
.R  	Hilbert transformer reference (0.5 < ref <= 1)
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.TP
.I int    
.B window_size
.B =1
.R  	window_size
.SH SOURCE
.I user/fomels/Mstphase.c
.SH VERSION
4.2-git
