.TH sfstream 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfstream \- Streaming PEF 
.SH SYNOPSIS
.B sfstream < inp.rsf > out.rsf pattern=pat.rsf pef=pef.rsf known=known.rsf inv=n adj=n na= eps=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag (for linear operator)
.TP
.I float  
.B eps
.B =
.R  	regularization
.TP
.I bool   
.B inv
.B =n
.R  [y/n]	inversion flag
.TP
.I string 
.B known
.B =
.R  	known data locations (optional) (auxiliary input file name)
.TP
.I int    
.B na
.B =
.R  	PEF filter size (not including leading one)
.TP
.I string 
.B pattern
.B =
.R  	pattern data (for linear operator) (auxiliary input file name)
.TP
.I string 
.B pef
.B =
.R  	output PEF (optional) (auxiliary output file name)
.SH SOURCE
.I user/fomels/Mstream.c
.SH VERSION
4.2-git
