.TH sfstfchain2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfstfchain2 \- Find a symmetric chain of 1-D Fourier weighting and scaling with movies
.SH SYNOPSIS
.B sfstfchain2 < src.rsf > wht.rsf target=tgt.rsf init_w=w0.rsf init_wf=wf0.rsf fweight=fwht.rsf match=mch.rsf wsnap=snap_w.rsf wfsnap=snap_wf.rsf lsmigsnap=snap_lsmig.rsf rect1=1 rect2=1 frect1=1 frect2=1 niter=0 liter=50 snap=0
.SH PARAMETERS
.PD 0
.TP
.I int    
.B frect1
.B =1
.R  
.TP
.I int    
.B frect2
.B =1
.R  	smoothing in frequency
.TP
.I file   
.B fweight
.B =
.R  	auxiliary output file name
.TP
.I file   
.B init_w
.B =
.R  	auxiliary input file name
.TP
.I file   
.B init_wf
.B =
.R  	auxiliary input file name
.TP
.I int    
.B liter
.B =50
.R  	number of linear iterations
.TP
.I file   
.B lsmigsnap
.B =
.R  	auxiliary output file name
.TP
.I file   
.B match
.B =
.R  	auxiliary output file name
.TP
.I int    
.B niter
.B =0
.R  	number of iterations
.TP
.I int    
.B rect1
.B =1
.R  
.TP
.I int    
.B rect2
.B =1
.R  	smoothing in time
.TP
.I int    
.B snap
.B =0
.R  	interval for snapshots
.TP
.I file   
.B target
.B =
.R  	auxiliary input file name
.TP
.I file   
.B wfsnap
.B =
.R  	auxiliary output file name
.TP
.I file   
.B wsnap
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/fomels/Mstfchain2.c
.SH VERSION
4.2-git
