.TH sfstaticcorr 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfstaticcorr \- 
.SH SYNOPSIS
.B sfstaticcorr < Fin.rsf > Fou.rsf verb=n
.SH COMMENTS
Static Corrections for Redatuming SHARAD data to MOLA surface
Input: 2D correlation between SHARAD data and clutter simulation
Output: Smoothed maximum correlation picks representing residual ionosphere time delay
Created on: Mar 9, 2021

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/cwp/Mstaticcorr.py
.SH VERSION
4.2-git
