.TH sfsum3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsum3 \- adjoint test
.SH SYNOPSIS
.B sfsum3 < input1.rsf input2=input2.rsf input3=input3.rsf input4=input4.rsf > output.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B input2
.B =
.R  	auxiliary input file name
.TP
.I file   
.B input3
.B =
.R  	auxiliary input file name
.TP
.I file   
.B input4
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/jingwei/Msum3.cc
.SH VERSION
4.2-git
