.TH sfsuplane 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsuplane \- Create common offset data file with up to 3 planes 
.SH SYNOPSIS
.B sfsuplane > out.rsf nt=NT ntr=NTR dt=DT offset=OFF npl=NPL taper=0 dip1=0 len1=3*ntr/4 ct1=nt/2-1 cx1=ntr/2-1 dip2=4 len2=3*ntr/4 ct2=nt/2-1 cx2=ntr/2-1 dip3=8 len3=3*ntr/4 ct3=nt/2-1 cx3=ntr/2-1 liner=0
.SH COMMENTS
Command line should be: sfsuplane in=NULL >file.rsf 
(There should be at least one parameter in command line because of sf_init(argc,argv))

.SH PARAMETERS
.PD 0
.TP
.I int    
.B ct1
.B =nt/2-1
.R  
.TP
.I int    
.B ct2
.B =nt/2-1
.R  
.TP
.I int    
.B ct3
.B =nt/2-1
.R  
.TP
.I int    
.B cx1
.B =ntr/2-1
.R  	set defaults and/or get parameters for plane 2
.TP
.I int    
.B cx2
.B =ntr/2-1
.R  	set defaults and/or get parameters for plane 3
.TP
.I int    
.B cx3
.B =ntr/2-1
.R  	check if user wants the special output specified
.TP
.I float  
.B dip1
.B =0
.R  
.TP
.I float  
.B dip2
.B =4
.R  
.TP
.I float  
.B dip3
.B =8
.R  
.TP
.I float  
.B dt
.B =DT
.R  
.TP
.I int    
.B len1
.B =3*ntr/4
.R  
.TP
.I int    
.B len2
.B =3*ntr/4
.R  
.TP
.I int    
.B len3
.B =3*ntr/4
.R  
.TP
.I int    
.B liner
.B =0
.R  
.TP
.I int    
.B npl
.B =NPL
.R  
.TP
.I int    
.B nt
.B =NT
.R  
.TP
.I int    
.B ntr
.B =NTR
.R  
.TP
.I float  
.B offset
.B =OFF
.R  
.TP
.I int    
.B taper
.B =0
.R  	set defaults and/or get parameters for plane 1
.SH SOURCE
.I user/chenyk/Msuplane.c
.SH VERSION
4.2-git
