.TH sfsumamp 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsumamp \- Stack energy between two input horizons 
.SH SYNOPSIS
.B sfsumamp < dataFile.rsf top=hTopFile.rsf bot=hBotFile.rsf > stackFile.rsf badSample=99999.f
.SH PARAMETERS
.PD 0
.TP
.I float  
.B badSample
.B =99999.f
.R  	non-interpreted sample in the horizons
.TP
.I string 
.B bot
.B =
.R  	bottom horizon (auxiliary input file name)
.TP
.I string 
.B top
.B =
.R  	top horizon (auxiliary input file name)
.SH SOURCE
.I user/aklokov/Msumamp.c
.SH VERSION
4.2-git
