.TH sfsvddenoise 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsvddenoise \- SVD denoising 
.SH SYNOPSIS
.B sfsvddenoise < in.rsf > out.rsf pclip=99.
.SH PARAMETERS
.PD 0
.TP
.I float  
.B pclip
.B =99.
.R  	data clip percentile (default is 99)
.SH SOURCE
.I user/yliu/Msvddenoise.c
.SH VERSION
4.2-git
