.TH sfsvmf 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsvmf \- Space varying median filtering. 
.SH SYNOPSIS
.B sfsvmf < in.rsf > out.rsf similarity=similarity.rsf L=lengthout.rsf boundary=n ns=0 ne=n2-1 nfw= l1=4 l2=2 l3=2 l4=4 lambda1=0.15 lambda2=0.25 lambda3=0.75 lambda4=0.85
.SH COMMENTS
Using local similarity as a reference.

.SH PARAMETERS
.PD 0
.TP
.I string 
.B L
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B boundary
.B =n
.R  [y/n]	if y, boundary is data, whereas zero
.TP
.I int    
.B l1
.B =4
.R  	space-varying window parameter "l1" (default=4)
.TP
.I int    
.B l2
.B =2
.R  	space-varying window parameter "l2" (default=2)
.TP
.I int    
.B l3
.B =2
.R  	space-varying window parameter "l3" (default=2)
.TP
.I int    
.B l4
.B =4
.R  	space-varying window parameter "l4" (default=4)
.TP
.I float  
.B lambda1
.B =0.15
.R  	space-varying window parameter "lambda1" (default=0.15)
.TP
.I float  
.B lambda2
.B =0.25
.R  	space-varying window parameter "lambda2" (default=0.25)
.TP
.I float  
.B lambda3
.B =0.75
.R  	space-varying window parameter "lambda3" (default=0.75)
.TP
.I float  
.B lambda4
.B =0.85
.R  	space-varying window parameter "lambda4" (default=0.85)
.TP
.I int    
.B ne
.B =n2-1
.R  	processing window ending point, corresponding to the temporal axis, n2 means transposed first-axis dimension.
.TP
.I int    
.B nfw
.B =
.R  	reference filter-window length (>l4, positive and odd integer)
.TP
.I int    
.B ns
.B =0
.R  	processing window starting point, corresponding to the temporal axis
.TP
.I file   
.B similarity
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/chenyk/Msvmf.c
.SH VERSION
4.2-git
