.TH sfsvdtest 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsvdtest \- Singular value decomposition to select rank-1 approximation
.SH SYNOPSIS
.B sfsvdtest < matrix.rsf > alpha.rsf nz= nx= nkz= nkx=
.SH PARAMETERS
.PD 0
.TP
.I        
.B nkx
.B =
.R  
.TP
.I        
.B nkz
.B =
.R  
.TP
.I        
.B nx
.B =
.R  
.TP
.I        
.B nz
.B =
.R  
.SH SOURCE
.I user/jingwei/Msvdtest.cc
.SH VERSION
4.2-git
