.TH sfswtdenoise 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfswtdenoise \- Denoising using stationary wavelet transform. 
.SH SYNOPSIS
.B sfswtdenoise < in.rsf > out.rsf ratio=1. len_filter=2 n_layer=2
.SH PARAMETERS
.PD 0
.TP
.I int    
.B len_filter
.B =2
.R  	filter length
.TP
.I int    
.B n_layer
.B =2
.R  	number of wavelet transform layers
.TP
.I float  
.B ratio
.B =1.
.R  	ratio for denoising
.SH SOURCE
.I system/generic/Mswtdenoise.c
.SH VERSION
4.2-git
