.TH sfswvarimax 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfswvarimax \- Sliding window varimax 
.SH SYNOPSIS
.B sfswvarimax < in.rsf > out.rsf sw=n size=0 thres=0. term=100. f1=0 f2=0 n1=nz0-fz n2=nx0-fx
.SH PARAMETERS
.PD 0
.TP
.I int    
.B f1
.B =0
.R  	sliding window radius
.TP
.I int    
.B f2
.B =0
.R  	sliding window radius
.TP
.I int    
.B n1
.B =nz0-fz
.R  	sliding window radius
.TP
.I int    
.B n2
.B =nx0-fx
.R  	sliding window radius
.TP
.I int    
.B size
.B =0
.R  	sliding window radius
.TP
.I bool   
.B sw
.B =n
.R  [y/n]	sliding window
.TP
.I float  
.B term
.B =100.
.R  	variance threshold (normalized)
.TP
.I float  
.B thres
.B =0.
.R  	variance threshold (normalized)
.SH SOURCE
.I user/jsun/Mswvarimax.c
.SH VERSION
4.2-git
