.TH sfswell 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfswell \- Add swell noise to the data.
.SH SYNOPSIS
.B sfswell < in.rsf > out.rsf den=10. inten=0.1 slope=0.1 width=4 length=30 num=5 rep=n noise=n
.SH PARAMETERS
.PD 0
.TP
.I float  
.B den
.B =10.
.R  	noise density (percent, default=10, Min=0, Max=100)
.TP
.I float  
.B inten
.B =0.1
.R  	noise intensity (multiple peak value of data, default=0.1)
.TP
.I int    
.B length
.B =30
.R  	max noise length (default=30)
.TP
.I bool   
.B noise
.B =n
.R  [y/n]	if y, output noise only
.TP
.I int    
.B num
.B =5
.R  	noise number (default=5)
.TP
.I bool   
.B rep
.B =n
.R  [y/n]	if y, replace data with noise
.TP
.I float  
.B slope
.B =0.1
.R  	noise slope (default=0.1)
.TP
.I int    
.B width
.B =4
.R  	max noise width (default=4)
.SH SOURCE
.I user/yliu/Mswell.c
.SH VERSION
4.2-git
