.TH sfswnorm 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfswnorm \- Sliding window normalization 
.SH SYNOPSIS
.B sfswnorm < in.rsf > out.rsf size=0 sw=n log=n var_thres=0. perc=5
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B log
.B =n
.R  [y/n]	log scaling
.TP
.I float  
.B perc
.B =5
.R  	threshold percentage of the maximum value
.TP
.I int    
.B size
.B =0
.R  	sliding window radius
.TP
.I bool   
.B sw
.B =n
.R  [y/n]	sliding window
.TP
.I float  
.B var_thres
.B =0.
.R  	variance threshold (normalized)
.SH SOURCE
.I user/jsun/Mswnorm.c
.SH VERSION
4.2-git
