.TH sfsynmarine 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfsynmarine \- Simple synthetic marine data example. 
.SH SYNOPSIS
.B sfsynmarine > out.rsf nt=250 nh=48 ny=10 nz=25
.SH PARAMETERS
.PD 0
.TP
.I int    
.B nh
.B =48
.R  	offset samples
.TP
.I int    
.B nt
.B =250
.R  	time samples
.TP
.I int    
.B ny
.B =10
.R  	midpoint samples
.TP
.I int    
.B nz
.B =25
.R  	depth samples
.SH USED IN
.TP
.I bei/fld/synmarine
.SH SOURCE
.I user/gee/Msynmarine.c
.SH VERSION
4.2-git
