.TH sft2diter 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sft2diter \- Time-to-depth conversion (linear operator) 
.SH SYNOPSIS
.B sft2diter < in.rsf > out.rsf s0=is0.rsf t0=it0.rsf x0=ix0.rsf f0=if0.rsf mask=mask.rsf prec=prec.rsf dix=dix.rsf velocity=y adj=n shape=n eps=0.1 verb=n tol=1.e-6 cgiter=200 rect#=(1,1,...) what=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag
.TP
.I int    
.B cgiter
.B =200
.R  	number of CG iterations
.TP
.I string 
.B dix
.B =
.R  	auxiliary input file name
.TP
.I float  
.B eps
.B =0.1
.R  	regularization parameter
.TP
.I string 
.B f0
.B =
.R  	auxiliary input file name
.TP
.I string 
.B mask
.B =
.R  	auxiliary input file name
.TP
.I string 
.B prec
.B =
.R  	auxiliary input file name
.TP
.I int    
.B rect#
.B =(1,1,...)
.R  	smoothing radius on #-th axis
.TP
.I string 
.B s0
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B shape
.B =n
.R  [y/n]	regularization (default Tikhnov)
.TP
.I string 
.B t0
.B =
.R  	auxiliary input file name
.TP
.I float  
.B tol
.B =1.e-6
.R  	tolerance for shaping regularization
.TP
.I bool   
.B velocity
.B =y
.R  [y/n]	y, inputs are velocity / n, slowness-squared
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I string 
.B what
.B =
.R  	what to compute (default inversion)
.TP
.I string 
.B x0
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/llisiw/Mt2diter.c
.SH VERSION
4.2-git
