.TH sftaperedge 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftaperedge \- Taper based on data parameters
.SH SYNOPSIS
.B sftaperedge < dataFile.rsf > maskFile.rsf len=11
.SH COMMENTS
Input - "inline/xline" plane

.SH PARAMETERS
.PD 0
.TP
.I int    
.B len
.B =11
.R  	length of the taper function
.SH SOURCE
.I user/aklokov/Mtaperedge.c
.SH VERSION
4.2-git
