.TH sftclip 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftclip \- Clip to threshold. 
.SH SYNOPSIS
.B sftclip < inp.rsf > out.rsf lowercut=0.2 uppercut=0.8
.SH PARAMETERS
.PD 0
.TP
.I float  
.B lowercut
.B =0.2
.R  
.TP
.I float  
.B uppercut
.B =0.8
.R  
.SH SOURCE
.I system/generic/Mtclip.c
.SH VERSION
4.2-git
