.TH sftdconvert 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftdconvert \- Iterative time-to-depth velocity conversion 
.SH SYNOPSIS
.B sftdconvert < in.rsf > out.rsf dix=dix.rsf t0=t_0.rsf x0=x_0.rsf f0=f_0.rsf grad=grad.rsf cost=cost.rsf mask=mini.rsf prec=prec.rsf velocity=y order=1 thres=10. niter=1 cgiter=200 shape=n eps=0.1 nline=0 verb=n tol=1.e-6 rect#=(1,1,...) mval=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B cgiter
.B =200
.R  	number of CG iterations
.TP
.I string 
.B cost
.B =
.R  	auxiliary output file name
.TP
.I string 
.B dix
.B =
.R  	auxiliary input file name
.TP
.I float  
.B eps
.B =0.1
.R  	regularization parameter
.TP
.I string 
.B f0
.B =
.R  	auxiliary output file name
.TP
.I string 
.B grad
.B =
.R  	auxiliary output file name
.TP
.I string 
.B mask
.B =
.R  	auxiliary input file name
.TP
.I string 
.B mval
.B =
.R  
.TP
.I int    
.B niter
.B =1
.R  	number of nonlinear updates
.TP
.I int    
.B nline
.B =0
.R  	maximum number of line search (default turned-off)
.TP
.I int    
.B order
.B =1
.R  	fastmarch accuracy order
.TP
.I string 
.B prec
.B =
.R  	auxiliary input file name
.TP
.I int    
.B rect#
.B =(1,1,...)
.R  	smoothing radius on #-th axis
.TP
.I bool   
.B shape
.B =n
.R  [y/n]	regularization (default Tikhnov)
.TP
.I string 
.B t0
.B =
.R  	auxiliary output file name
.TP
.I float  
.B thres
.B =10.
.R  	thresholding for caustics
.TP
.I float  
.B tol
.B =1.e-6
.R  	tolerance for shaping regularization
.TP
.I bool   
.B velocity
.B =y
.R  [y/n]	y, input is velocity / n, slowness-squared
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I string 
.B x0
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/llisiw/Mtdconvert.c
.SH VERSION
4.2-git
