.TH sfTestsolver 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfTestsolver \- Test for conjugate gradient, steepest descent, jacobi iteration, gauss-seidel iteration, successive over relaxation (SOR) iteration 
.SH SYNOPSIS
.B sfTestsolver
.SH SOURCE
.I user/chenyk/MTestsolver.c
.SH VERSION
4.2-git
