.TH sftelemig2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftelemig2d \- None
.SH SYNOPSIS
.B sftelemig2d < infile.rsf Svel=Svelfile.rsf rwf=rwffile.rsf swf=swffile.rsf > outfile.rsf cig=cigfile.rsf nh=0 source_norm=n verbose=n forward=n ntaper=40 eps=0.01
.SH PARAMETERS
.PD 0
.TP
.I file   
.B Svel
.B =
.R  	auxiliary input file name
.TP
.I file   
.B cig
.B =
.R  	auxiliary output file name
.TP
.I        
.B eps
.B =0.01
.R  	Taper on the side boundaries (npts)
.TP
.I        
.B forward
.B =n
.R  	Forward scattering (T/F)
.TP
.I        
.B nh
.B =0
.R  	Number of subsurface offsets (between 1 and 128)
.TP
.I        
.B ntaper
.B =40
.R  	Taper on the side boundaries (npts)
.TP
.I file   
.B rwf
.B =
.R  	auxiliary input file name
.TP
.I        
.B source_norm
.B =n
.R  	Normalize the image by the power of the SWF (T/F)
.TP
.I file   
.B swf
.B =
.R  	auxiliary input file name
.TP
.I        
.B verbose
.B =n
.R  	Verbose (T/F)
.SH SOURCE
.I user/jeff/Mtelemig2d.f90
.SH VERSION
4.2-git
