.TH sftestcasoper 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftestcasoper \- Test linear cascading matching-Radon operator. 
.SH SYNOPSIS
.B sftestcasoper < in.rsf > out.rsf filt=fil.rsf adj=n inv=n verb=n np= dp= p0= niter=100 freq=y parab=n x0=1. rho=y anti=1. p1=0.
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	if y, perform adjoint operation
.TP
.I float  
.B anti
.B =1.
.R  	antialiasing, only when freq=n
.TP
.I float  
.B dp
.B =
.R  	p sampling
.TP
.I file   
.B filt
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B freq
.B =y
.R  [y/n]	if y, parabolic Radon transform
.TP
.I bool   
.B inv
.B =n
.R  [y/n]	if y, perform inverse operation
.TP
.I int    
.B niter
.B =100
.R  
.TP
.I int    
.B np
.B =
.R  	number of p values
.TP
.I float  
.B p0
.B =
.R  	p origin
.TP
.I float  
.B p1
.B =0.
.R  	reference slope, only when freq=n
.TP
.I bool   
.B parab
.B =n
.R  [y/n]	if y, parabolic Radon transform, only when freq=y
.TP
.I bool   
.B rho
.B =y
.R  [y/n]	rho filtering, only when freq=n
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I float  
.B x0
.B =1.
.R  	reference offset
.SH SOURCE
.I user/yliu/Mtestcasoper.c
.SH VERSION
4.2-git Mtestcasoper.c 5959 2010-05-14 04:11:09Z yang_liu
