.TH sftestlist 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftestlist \- Inventory test results of Madagascar example book directories.
.SH SYNOPSIS
.B sftestlist levels=3 outfile= untested=n
.SH COMMENTS
Scan a directory tree (or list of directory trees) to a given depth,
and inventory the contents and test results.

The inventory occurs only at the specified depth (default 3), not the
intervening depths.  Directories named .svn are skipped.  Only
directories containing an SConstruct file are listed.

Examples (from within $RSFSRC):

sftestlist book                         # inventory of book
sftestlist levels=2 book/geostats       # inventory of book/geostats

.SH PARAMETERS
.PD 0
.TP
.I int    
.B levels
.B =3
.R  	directory search depth
.TP
.I string 
.B outfile
.B =
.R  	file name for detailed inventory table, default none
.TP
.I bool   
.B untested
.B =n
.R  [y/n]	list untested examples?
.SH SOURCE
.I user/jennings/Mtestlist.py
.SH VERSION
4.2-git
