.TH sftest1_matchl1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftest1_matchl1 \- L1 1D matched filter 
.SH SYNOPSIS
.B sftest1_matchl1 < inp.rsf filt=filt.rsf > out.rsf mult=mult.rsf nb=3 verb=n niter=100 perc=90.0
.SH PARAMETERS
.PD 0
.TP
.I file   
.B filt
.B =
.R  	auxiliary output file name
.TP
.I string 
.B mult
.B =
.R  	auxiliary input file name
.TP
.I int    
.B nb
.B =3
.R  	matched-filter order
.TP
.I int    
.B niter
.B =100
.R  	number of POCS iterations
.TP
.I float  
.B perc
.B =90.0
.R  	percentage for sharpening
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/lcasasan/Mtest1_matchl1.c
.SH VERSION
4.2-git
