.TH sfTestfd2d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfTestfd2d \- A demo of 2D FD test
.SH SYNOPSIS
.B sfTestfd2d < Fv.rsf > Fw.rsf nb=30 nt= dt= fm=20.0 ft=0 jt=1
.SH COMMENTS
Sponage absorbing boundary condition

.SH PARAMETERS
.PD 0
.TP
.I float  
.B dt
.B =
.R  	time sampling interval
.TP
.I float  
.B fm
.B =20.0
.R  	dominant freq of Ricker wavelet
.TP
.I int    
.B ft
.B =0
.R  	first recorded time
.TP
.I int    
.B jt
.B =1
.R  	time interval
.TP
.I int    
.B nb
.B =30
.R  	thickness of sponge ABC
.TP
.I int    
.B nt
.B =
.R  	number of time steps
.SH SOURCE
.I user/pyang/MTestfd2d.c
.SH VERSION
4.2-git
