.TH sfthreshold1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfthreshold1 \- Soft or hard thresholding using exact-value or percentile thresholding.
.SH SYNOPSIS
.B sfthreshold1 < in.rsf > out.rsf other=other.rsf ifperc=1 ifverb=0 thr= type=
.SH COMMENTS
When type=soft and ifperc=1, sfthreshold1 is equal to sfthreshold.

.SH PARAMETERS
.PD 0
.TP
.I int    
.B ifperc
.B =1
.R  	0, exact-value thresholding; 1, percentile thresholding.
.TP
.I int    
.B ifverb
.B =0
.R  	0, not print threshold value; 1, print threshold value.
.TP
.I string 
.B other
.B =
.R  	If output the difference between the thresholded part and the original one (auxiliary output file name)
.TP
.I float  
.B thr
.B =
.R  	thresholding level
.TP
.I string 
.B type
.B =
.R  	[soft,hard] thresholding type, the default is soft
.SH SOURCE
.I user/chenyk/Mthreshold1.c
.SH VERSION
4.2-git
