.TH sfthickat 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfthickat \- None
.SH SYNOPSIS
.B sfthickat < reflectors.rsf refseis=reference.rsf > thickness.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B refseis
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/mehdi/Mthickat.f90
.SH VERSION
4.2-git
