.TH sfthreshold2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfthreshold2 \- 2-D Soft thresholding. 
.SH SYNOPSIS
.B sfthreshold2 < in.rsf > out.rsf thr=thr.rsf verb=n pclip=99.
.SH PARAMETERS
.PD 0
.TP
.I float  
.B pclip
.B =99.
.R  
.TP
.I string 
.B thr
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/yliu/Mthreshold2.c
.SH VERSION
4.2-git
