.TH sfthreads 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfthreads \- Testing Posix threads 
.SH SYNOPSIS
.B sfthreads kernels= times=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B kernels
.B =
.R  	Number of kernel threads to create
.TP
.I int    
.B times
.B =
.R  	Number of SQRT loops to execute
.SH SOURCE
.I user/mccowan/Mthreads.c
.SH VERSION
4.2-git
