.TH sfthreshold3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfthreshold3 \- Automatic soft or hard thresholding. 
.SH SYNOPSIS
.B sfthreshold3 < in.rsf > out.rsf type= dist=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B dist
.B =
.R  	[gaussian,rayleigh] distribution type, the default is gaussian
.TP
.I string 
.B type
.B =
.R  	[soft,hard] thresholding type, the default is soft
.SH SOURCE
.I user/yliu/Mthreshold3.c
.SH VERSION
4.2-git
