.TH sfthin 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfthin \- Sparse deconvolution. 
.SH SYNOPSIS
.B sfthin < seis.rsf > refl.rsf wave=wave.rsf conv=conv.rsf niter=100 eps=0.0001 pclip=4
.SH PARAMETERS
.PD 0
.TP
.I string 
.B conv
.B =
.R  	auxiliary output file name
.TP
.I float  
.B eps
.B =0.0001
.R  	regularization for Wiener deconvolution
.TP
.I int    
.B niter
.B =100
.R  	maximum number of iterations
.TP
.I float  
.B pclip
.B =4
.R  	percentage to threshold
.TP
.I file   
.B wave
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/fomels/Mthin.c
.SH VERSION
4.2-git
