.TH sfthreedcube 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfthreedcube \- Interactively displays a 3D cube of RSF data using Python + MayaVi2 + VTK.
.SH SYNOPSIS
.B sfthreedcube < fin.rsf
.SH COMMENTS

REQUIRES NUMPY, SCIPY, and MAyaVi2

.SH SOURCE
.I user/godwinj/Mthreedcube.py
.SH VERSION
4.2-git
