.TH sftime2depthweak 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftime2depthweak \- Time-to-depth conversion in media with weak lateral variations 2D (Sripanich and Fomel, 2017). 
.SH SYNOPSIS
.B sftime2depthweak < in.rsf dvdx0=dveldx0.rsf dvdt0=dveldt0.rsf refvelocity=refvelocity.rsf outdt0=outdeltime.rsf outdx0=outdeldist.rsf outdv=outdelv.rsf zsubsample=100 nderiv=10 refderiv=1. smoothlen=nx/20 nsmooth=10
.SH PARAMETERS
.PD 0
.TP
.I file   
.B dvdt0
.B =
.R  	auxiliary input file name
.TP
.I file   
.B dvdx0
.B =
.R  	auxiliary input file name
.TP
.I int    
.B nderiv
.B =10
.R  	Derivative filter order
.TP
.I int    
.B nsmooth
.B =10
.R  	Smoothing repeat
.TP
.I file   
.B outdt0
.B =
.R  	auxiliary output file name
.TP
.I file   
.B outdv
.B =
.R  	auxiliary output file name
.TP
.I file   
.B outdx0
.B =
.R  	auxiliary output file name
.TP
.I float  
.B refderiv
.B =1.
.R  	Deriveative filter reference (0.5 < ref <= 1)
.TP
.I file   
.B refvelocity
.B =
.R  	auxiliary input file name
.TP
.I int    
.B smoothlen
.B =nx/20
.R  	Smoothing filter length
.TP
.I int    
.B zsubsample
.B =100
.R  	Additional subsampling in depth for stability
.SH SOURCE
.I user/zone/Mtime2depthweak.c
.SH VERSION
4.2-git
