.TH sftimecont 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftimecont \- Forward or reverse time continuation using fast marching. 
.SH SYNOPSIS
.B sftimecont < vel.rsf > time.rsf surf=time0.rsf forwd=n vel=y order=2
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B forwd
.B =n
.R  [y/n]	continue forward or backward
.TP
.I int    
.B order
.B =2
.R  [1,2]	Accuracy order
.TP
.I file   
.B surf
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B vel
.B =y
.R  [y/n]	if y, the input is velocity; n, slowness squared
.SH SOURCE
.I user/fomels/Mtimecont.c
.SH VERSION
4.2-git
