.TH sftimeshift 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftimeshift \- Apply variable time shifts using plane-wave construction. 
.SH SYNOPSIS
.B sftimeshift < inp.rsf > out.rsf dip=dip.rsf eps=0.01 order=1
.SH PARAMETERS
.PD 0
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I float  
.B eps
.B =0.01
.R  	regularization
.TP
.I int    
.B order
.B =1
.R  	accuracy order
.SH SOURCE
.I user/pwd/Mtimeshift.c
.SH VERSION
4.2-git
