.TH sftinterp 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftinterp \- Traveltime interpolation by cubic Hermite spline 
.SH SYNOPSIS
.B sftinterp < in.rsf > out.rsf deriv=deriv.rsf pattern=pattern.rsf type=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B deriv
.B =
.R  	auxiliary input file name
.TP
.I string 
.B pattern
.B =
.R  	auxiliary input file name
.TP
.I string 
.B type
.B =
.R  	type of interpolation (default Hermit)
.SH SOURCE
.I user/llisiw/Mtinterp.c
.SH VERSION
4.2-git
