.TH sftkirmig 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftkirmig \- 2-D Kirchhoff pre-stack time migration/demigration. 
.SH SYNOPSIS
.B sftkirmig < in.rsf vel=vel.rsf > out.rsf offset=offset.rsf ompchunk=1 ompnth=0 adj=y verb=n half=y amp=y ncdp=ncmp dcdp=dcmp cdp0=cmp0 ncmp=ncdp dcmp=dcdp cmp0=cdp0 antialias=1.0 apt=ncmp rho=1.-1./nt
.SH COMMENTS
The axes in the data are {time,cmp,offset}
The axes in the offset are {1,cmp,offset}
The axes in the image are {time,cdp,offset}

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =y
.R  [y/n]	yes: migration, no: modeling
.TP
.I bool   
.B amp
.B =y
.R  [y/n]	if y, use amplitue factor
.TP
.I float  
.B antialias
.B =1.0
.R  	antialiasing
.TP
.I float  
.B apt
.B =ncmp
.R  	migration aperture
.TP
.I float  
.B cdp0
.B =cmp0
.R  
.TP
.I float  
.B cmp0
.B =cdp0
.R  
.TP
.I float  
.B dcdp
.B =dcmp
.R  
.TP
.I float  
.B dcmp
.B =dcdp
.R  
.TP
.I bool   
.B half
.B =y
.R  [y/n]	if y, the third axis is half-offset instead of full offset
.TP
.I int    
.B ncdp
.B =ncmp
.R  
.TP
.I int    
.B ncmp
.B =ncdp
.R  
.TP
.I string 
.B offset
.B =
.R  	auxiliary input file name
.TP
.I int    
.B ompchunk
.B =1
.R  	OpenMP data chunk size
.TP
.I int    
.B ompnth
.B =0
.R  	OpenMP available threads
.TP
.I float  
.B rho
.B =1.-1./nt
.R  	Leaky integration constant
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/seisinv/Mtkirmig.c
.SH VERSION
4.2-git
