.TH sftmigda 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftmigda \- 3D time scattering-angle Kirchhoff migration  
.SH SYNOPSIS
.B sftmigda < dataFile.rsf vel=velFile.rsf > imageFile.rsf semb=sembFile.rsf dag=dagFile.rsf cig=cigFile.rsf is3d=n axis2label=0 isAA=y isDipAz=y hmign=dp.hNum sembWindow=11 edgeTaper=5.f itn=dp.zNum ixn=dp.xNum iyn=rp.is3D ? vp.yNum : 1 ito=dp.zStart ixo=dp.xStart iyo=dp.yStart itd=dp.zStep ixd=dp.xStep iyd=dp.yStep dipn=1 sdipn=1 dipo=0.f sdipo=90.f dipd=1.f sdipd=1.f
.SH PARAMETERS
.PD 0
.TP
.I int    
.B axis2label
.B =0
.R  	0 - shot; 1 - cmp; 2 - receiver
.TP
.I string 
.B cig
.B =
.R  	output file containing CIGs in the surface-offset domain (auxiliary output file name)
.TP
.I string 
.B dag
.B =
.R  	output file containing CIGs in the dip-angle domain (auxiliary output file name)
.TP
.I float  
.B dipd
.B =1.f
.R  	step in dip-angle
.TP
.I int    
.B dipn
.B =1
.R  	number of dip-angles
.TP
.I float  
.B dipo
.B =0.f
.R  	first dip-angle
.TP
.I float  
.B edgeTaper
.B =5.f
.R  	edge taper for dip-angle gathers (in degree)
.TP
.I int    
.B hmign
.B =dp.hNum
.R  	number of migrated offsets
.TP
.I bool   
.B is3d
.B =n
.R  [y/n]	if y, apply 3D migration
.TP
.I bool   
.B isAA
.B =y
.R  [y/n]	if y, apply anti-aliasing
.TP
.I bool   
.B isDipAz
.B =y
.R  [y/n]	if y, apply dip/azimuth mode; if n, apply inline/crossline angle mode
.TP
.I float  
.B itd
.B =dp.zStep
.R  	step in imaged times  (in ms)
.TP
.I int    
.B itn
.B =dp.zNum
.R  	number of imaged times
.TP
.I float  
.B ito
.B =dp.zStart
.R  	first imaged time (in ms)
.TP
.I float  
.B ixd
.B =dp.xStep
.R  	step in imaged inlines
.TP
.I int    
.B ixn
.B =dp.xNum
.R  	number of imaged inlines
.TP
.I float  
.B ixo
.B =dp.xStart
.R  	first imaged inline
.TP
.I float  
.B iyd
.B =dp.yStep
.R  	step in imaged crosslines
.TP
.I int    
.B iyn
.B =rp.is3D ? vp.yNum : 1
.R  	number of imaged crosslines
.TP
.I float  
.B iyo
.B =dp.yStart
.R  	first imaged crossline
.TP
.I float  
.B sdipd
.B =1.f
.R  	step in secondary (azimuth or crossline) angle
.TP
.I int    
.B sdipn
.B =1
.R  	number of secondary (azimuth or crossline) angles
.TP
.I float  
.B sdipo
.B =90.f
.R  	first secondary (azimuth or crossline) angle
.TP
.I string 
.B semb
.B =
.R  	output file containing semblance measure of CIGs stacking (auxiliary output file name)
.TP
.I int    
.B sembWindow
.B =11
.R  	vertical window for semblance calculation (in samples)
.TP
.I string 
.B vel
.B =
.R  	velocity model file (velocity in m/s) (auxiliary input file name)
.SH SOURCE
.I user/aklokov/Mtmigda.cc
.SH VERSION
4.2-git
