.TH sftouch 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftouch \- Applies the Unix command touch to binaries of RSF datasets in a directory.
.SH SYNOPSIS
.B sftouch verb=n dir=. rec=n chk4nan=n
.SH COMMENTS
Will go down recursively in subdirectories. Current date and time is used.
Useful for determining disk leaks: Orphan binaries (those without headers) will
not be touched. You can remove them with commands such as:
find $DATAPATH -type f -mmin +15 -exec rm -f {} \;
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B chk4nan
.B =n
.R  [y/n]	Check for NaN values. Expensive!!
.TP
.I string 
.B dir
.B =.
.R  	Directory with files
.TP
.I bool   
.B rec
.B =n
.R  [y/n]	Whether to go down recursively
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	Display what is wrong with the dataset
.SH SOURCE
.I user/ivlad/Mtouch.py
.SH VERSION
4.2-git
