.TH sftransp12 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftransp12 \- Transpose 1-2 
.SH SYNOPSIS
.B sftransp12 < Fin.rsf > Fou.rsf verb=n memsize=1000.0
.SH PARAMETERS
.PD 0
.TP
.I float  
.B memsize
.B =1000.0
.R  
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/psava/Mtransp12.c
.SH VERSION
4.2-git
