.TH sftristack 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftristack \- Resampling with triangle weights. 
.SH SYNOPSIS
.B sftristack < in.rsf > out.rsf adj=y rect=1 gauss=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =y
.R  [y/n]	adjoint flag
.TP
.I bool   
.B gauss
.B =n
.R  [y/n]	use pseudo-gaussian
.TP
.I int    
.B rect
.B =1
.R  	smoothing radius
.SH SOURCE
.I user/fomels/Mtristack.c
.SH VERSION
4.2-git
