.TH sftricascade 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftricascade \- Triangle filter cascade 
.SH SYNOPSIS
.B sftricascade < inp.rsf > out.rsf rect=1 inter=n
.SH PARAMETERS
.PD 0
.TP
.I int    
.B inter
.B =n
.R  	interrupt
.TP
.I int    
.B rect
.B =1
.R  	smoothing radius
.SH SOURCE
.I user/fomels/Mtricascade.c
.SH VERSION
4.2-git
