.TH sftraveltimelen 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftraveltimelen \- Oriented zero-offset migration. 
.SH SYNOPSIS
.B sftraveltimelen < dist.rsf time=time.rsf dept=dept.rsf len=lent.rsf > imagt.rsf xsrc= tolz= tolx= interpolate= timez0=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B dept
.B =
.R  	auxiliary input file name
.TP
.I int    
.B interpolate
.B =
.R  
.TP
.I file   
.B len
.B =
.R  	auxiliary input file name
.TP
.I file   
.B time
.B =
.R  	auxiliary input file name
.TP
.I string 
.B timez0
.B =
.R  
.TP
.I float  
.B tolx
.B =
.R  
.TP
.I float  
.B tolz
.B =
.R  
.TP
.I float  
.B xsrc
.B =
.R  
.SH SOURCE
.I user/roman/Mtraveltimelen.c
.SH VERSION
4.2-git
