.TH sftrapez 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftrapez \- Convolution with a trapezoidal filter. 
.SH SYNOPSIS
.B sftrapez < in.rsf > out.rsf frequency=
.SH PARAMETERS
.PD 0
.TP
.I floats 
.B frequency
.B =
.R  	frequencies (in Hz), default: (0.1,0.15,0.45,0.5)*Nyquist  [4]
.SH SOURCE
.I system/generic/Mtrapez.c
.SH VERSION
4.2-git
