.TH sftrapepass 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftrapepass \- Trapezoid bandpass filter in the frequency domain. 
.SH SYNOPSIS
.B sftrapepass < in.rsf > out.rsf
.SH COMMENTS
f1, f2, f3, f4 correspond to four key points of the trapezoid bandpass filter.
.SH SOURCE
.I user/chenyk/Mtrapepass.c
.SH VERSION
4.2-git
