.TH sftrace2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftrace2 \- 2-D multiple arrivals by cell ray tracing. 
.SH SYNOPSIS
.B sftrace2 < vel.rsf > outp.rsf size=size.rsf grid=grid.rsf na=60 da=3.1 a0=-90. maxsplit=10 minx=0.5*dx maxx=2.*dx mina=0.5*da maxa=2.*da vel=y order=3 lsint=n
.SH PARAMETERS
.PD 0
.TP
.I float  
.B a0
.B =-90.
.R  	initial angle (in degrees)
.TP
.I float  
.B da
.B =3.1
.R  	angle increment (in degrees)
.TP
.I file   
.B grid
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B lsint
.B =n
.R  [y/n]	if use least-squares interpolation
.TP
.I float  
.B maxa
.B =2.*da
.R  
.TP
.I int    
.B maxsplit
.B =10
.R  	maximum splitting for adaptive grid
.TP
.I float  
.B maxx
.B =2.*dx
.R  
.TP
.I float  
.B mina
.B =0.5*da
.R  
.TP
.I float  
.B minx
.B =0.5*dx
.R  	parameters for adaptive grid
.TP
.I int    
.B na
.B =60
.R  	number of angles
.TP
.I int    
.B order
.B =3
.R  	velocity interpolation order
.TP
.I file   
.B size
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B vel
.B =y
.R  [y/n]	y: velocity, n: slowness
.SH SOURCE
.I user/fomels/Mtrace2.c
.SH VERSION
4.2-git Mtrace2.c 853 2004-11-05 12:54:22Z fomels
