.TH sftraveltimelen3d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftraveltimelen3d \- Oriented zero-offset migration. 
.SH SYNOPSIS
.B sftraveltimelen3d < dist.rsf disty=distY.rsf time=time.rsf dept=dept.rsf len=lent.rsf > imagt.rsf xsrc= ysrc=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B dept
.B =
.R  	auxiliary input file name
.TP
.I file   
.B disty
.B =
.R  	auxiliary input file name
.TP
.I file   
.B len
.B =
.R  	auxiliary input file name
.TP
.I file   
.B time
.B =
.R  	auxiliary input file name
.TP
.I float  
.B xsrc
.B =
.R  
.TP
.I float  
.B ysrc
.B =
.R  
.SH SOURCE
.I user/roman/Mtraveltimelen3d.c
.SH VERSION
4.2-git
