.TH sftti2de 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftti2de \- 2-D two-components wavefield modeling using original elastic displacement wave equation in TTI media.
.SH SYNOPSIS
.B sftti2de < Fvp0.rsf vs0=Fvs0.rsf epsi=Feps.rsf del=Fdel.rsf the=Fthe.rsf > Fo1.rsf Elasticz=Fo2.rsf ns=301 dt=0.001
.SH COMMENTS

Copyright (C) 2012 Tongji University, Shanghai, China 
Authors: Jiubing Cheng, Wei Kang and Tengfei Wang

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

.SH PARAMETERS
.PD 0
.TP
.I file   
.B Elasticz
.B =
.R  	auxiliary output file name
.TP
.I file   
.B del
.B =
.R  	auxiliary input file name
.TP
.I float  
.B dt
.B =0.001
.R  
.TP
.I file   
.B epsi
.B =
.R  	auxiliary input file name
.TP
.I int    
.B ns
.B =301
.R  
.TP
.I file   
.B the
.B =
.R  	auxiliary input file name
.TP
.I file   
.B vs0
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/chengjb/Mtti2de.c
.SH VERSION
4.2-git
