.TH sftti2dpseudosvlrsep 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftti2dpseudosvlrsep \- None
.SH SYNOPSIS
.B sftti2dpseudosvlrsep < vp0.rsf > PseudoPureSVx.rsf PseudoPureSepSVx=PseudoPureSepSVx.rsf PseudoPureSepSVz=PseudoPureSepSVz.rsf PseudoPureSV=PseudoPureSV.rsf seed=time(NULL eps=1.e-6 npk=20 ns= dt=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B PseudoPureSV
.B =
.R  	auxiliary output file name
.TP
.I file   
.B PseudoPureSepSVx
.B =
.R  	auxiliary output file name
.TP
.I file   
.B PseudoPureSepSVz
.B =
.R  	auxiliary output file name
.TP
.I        
.B dt
.B =
.R  
.TP
.I        
.B eps
.B =1.e-6
.R  	tolerance
.TP
.I        
.B npk
.B =20
.R  	maximum rank
.TP
.I        
.B ns
.B =
.R  
.TP
.I        
.B seed
.B =time(NULL
.R  
.SH SOURCE
.I user/chengjb/Mtti2dpseudosvlrsep.cc
.SH VERSION
4.2-git
