.TH sftti2delrdecomp 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftti2delrdecomp \- None
.SH SYNOPSIS
.B sftti2delrdecomp < vp0.rsf > Elasticx.rsf ElasticPx=ElasticPx.rsf ElasticPz=ElasticPz.rsf ElasticSVx=ElasticSVx.rsf ElasticSVz=ElasticSVz.rsf seed=time(NULL eps=1.e-6 npk=20 ns= dt=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B ElasticPx
.B =
.R  	auxiliary output file name
.TP
.I file   
.B ElasticPz
.B =
.R  	auxiliary output file name
.TP
.I file   
.B ElasticSVx
.B =
.R  	auxiliary output file name
.TP
.I file   
.B ElasticSVz
.B =
.R  	auxiliary output file name
.TP
.I        
.B dt
.B =
.R  
.TP
.I        
.B eps
.B =1.e-6
.R  	tolerance
.TP
.I        
.B npk
.B =20
.R  	maximum rank
.TP
.I        
.B ns
.B =
.R  
.TP
.I        
.B seed
.B =time(NULL
.R  
.SH SOURCE
.I user/chengjb/Mtti2delrdecomp.cc
.SH VERSION
4.2-git
