.TH sftti2delrdec 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftti2delrdec \- None
.SH SYNOPSIS
.B sftti2delrdec < vp0.rsf ElasticPx=ElasticPx.rsf ElasticPz=ElasticPz.rsf ElasticSx=ElasticSx.rsf ElasticSz=ElasticSz.rsf Orthog=Orthog.rsf seed=time(NULL eps=1.e-6 npk=20
.SH PARAMETERS
.PD 0
.TP
.I file   
.B ElasticPx
.B =
.R  	auxiliary output file name
.TP
.I file   
.B ElasticPz
.B =
.R  	auxiliary output file name
.TP
.I file   
.B ElasticSx
.B =
.R  	auxiliary output file name
.TP
.I file   
.B ElasticSz
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Orthog
.B =
.R  	auxiliary output file name
.TP
.I        
.B eps
.B =1.e-6
.R  	tolerance
.TP
.I        
.B npk
.B =20
.R  	maximum rank
.TP
.I        
.B seed
.B =time(NULL
.R  
.SH SOURCE
.I user/chengjb/Mtti2delrdec.cc
.SH VERSION
4.2-git
