.TH sfTTinv 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfTTinv \- None
.SH SYNOPSIS
.B sfTTinv CCorrect=Ccor.rsf Cpredicted=Cpred.rsf common=commonoffset.rsf azimuth= offset=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B CCorrect
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Cpredicted
.B =
.R  	auxiliary output file name
.TP
.I        
.B azimuth
.B =
.R  	command-line parameter
.TP
.I file   
.B common
.B =
.R  	auxiliary output file name
.TP
.I        
.B offset
.B =
.R  	command-line parameter
.SH SOURCE
.I user/mehdi/MTTinv.f90
.SH VERSION
4.2-git
