.TH sftti2delrsep2p 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftti2delrsep2p \- None
.SH SYNOPSIS
.B sftti2delrsep2p < vp0.rsf Errpolxp1=Errpolxp1.rsf Errpolxp2=Errpolxp2.rsf Polxp1=Polxp1.rsf Polxp2=Polxp2.rsf Errpolzp1=Errpolzp1.rsf Errpolzp2=Errpolzp2.rsf Polzp1=Polzp1.rsf Polzp2=Polzp2.rsf > Elasticx.rsf ElasticSepP=ElasticSepP.rsf ElasticSepSV=ElasticSepSV.rsf seed=time(NULL eps=1.e-6 npk=20 ns= dt= ireconstruct= xrec1= zrec1= xrec2= zrec2=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B ElasticSepP
.B =
.R  	auxiliary output file name
.TP
.I file   
.B ElasticSepSV
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Errpolxp1
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Errpolxp2
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Errpolzp1
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Errpolzp2
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Polxp1
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Polxp2
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Polzp1
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Polzp2
.B =
.R  	auxiliary output file name
.TP
.I        
.B dt
.B =
.R  
.TP
.I        
.B eps
.B =1.e-6
.R  	tolerance
.TP
.I        
.B ireconstruct
.B =
.R  
.TP
.I        
.B npk
.B =20
.R  	maximum rank
.TP
.I        
.B ns
.B =
.R  
.TP
.I        
.B seed
.B =time(NULL
.R  
.TP
.I        
.B xrec1
.B =
.R  
.TP
.I        
.B xrec2
.B =
.R  
.TP
.I        
.B zrec1
.B =
.R  
.TP
.I        
.B zrec2
.B =
.R  
.SH SOURCE
.I user/chengjb/Mtti2delrsep2p.cc
.SH VERSION
4.2-git
