.TH sftti3delrsepSV 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftti3delrsepSV \- None
.SH SYNOPSIS
.B sftti3delrsepSV < vp0.rsf seed=time(NULL eps=1.e-6 npk=20 iflagvti=
.SH PARAMETERS
.PD 0
.TP
.I        
.B eps
.B =1.e-6
.R  	tolerance
.TP
.I        
.B iflagvti
.B =
.R  
.TP
.I        
.B npk
.B =20
.R  	maximum rank
.TP
.I        
.B seed
.B =time(NULL
.R  
.SH SOURCE
.I user/chengjb/Mtti3delrsepSV.cc
.SH VERSION
4.2-git
