.TH sftti2dekspacelr 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftti2dekspacelr \- None
.SH SYNOPSIS
.B sftti2dekspacelr < vp0.rsf > Elasticx.rsf Elasticz=Elasticz.rsf seed=time(NULL eps=1.e-6 npk=20 ns= dt=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B Elasticz
.B =
.R  	auxiliary output file name
.TP
.I        
.B dt
.B =
.R  
.TP
.I        
.B eps
.B =1.e-6
.R  	tolerance
.TP
.I        
.B npk
.B =20
.R  	maximum rank
.TP
.I        
.B ns
.B =
.R  
.TP
.I        
.B seed
.B =time(NULL
.R  
.SH SOURCE
.I user/chengjb/Mtti2dekspacelr.cc
.SH VERSION
4.2-git
