.TH sftti2delrdecomp2p 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftti2delrdecomp2p \- None
.SH SYNOPSIS
.B sftti2delrdecomp2p < vp0.rsf Errdecxp1=Errdecxp1.rsf Errdecxp2=Errdecxp2.rsf Decompxp1=Decompxp1.rsf Decompxp2=Decompxp2.rsf Errdecxzp1=Errdecxzp1.rsf Errdecxzp2=Errdecxzp2.rsf Decompxzp1=Decompxzp1.rsf Decompxzp2=Decompxzp2.rsf Errdeczp1=Errdeczp1.rsf Errdeczp2=Errdeczp2.rsf Decompzp1=Decompzp1.rsf Decompzp2=Decompzp2.rsf > ElasticX.rsf ElasticPx=ElasticPx.rsf ElasticPz=ElasticPz.rsf ElasticSVx=ElasticSVx.rsf ElasticSVz=ElasticSVz.rsf seed=time(NULL eps=1.e-6 npk=20 ns= dt= ireconstruct= xrec1= zrec1= xrec2= zrec2=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B Decompxp1
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Decompxp2
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Decompxzp1
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Decompxzp2
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Decompzp1
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Decompzp2
.B =
.R  	auxiliary output file name
.TP
.I file   
.B ElasticPx
.B =
.R  	auxiliary output file name
.TP
.I file   
.B ElasticPz
.B =
.R  	auxiliary output file name
.TP
.I file   
.B ElasticSVx
.B =
.R  	auxiliary output file name
.TP
.I file   
.B ElasticSVz
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Errdecxp1
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Errdecxp2
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Errdecxzp1
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Errdecxzp2
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Errdeczp1
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Errdeczp2
.B =
.R  	auxiliary output file name
.TP
.I        
.B dt
.B =
.R  
.TP
.I        
.B eps
.B =1.e-6
.R  	tolerance
.TP
.I        
.B ireconstruct
.B =
.R  
.TP
.I        
.B npk
.B =20
.R  	maximum rank
.TP
.I        
.B ns
.B =
.R  
.TP
.I        
.B seed
.B =time(NULL
.R  
.TP
.I        
.B xrec1
.B =
.R  
.TP
.I        
.B xrec2
.B =
.R  
.TP
.I        
.B zrec1
.B =
.R  
.TP
.I        
.B zrec2
.B =
.R  
.SH SOURCE
.I user/chengjb/Mtti2delrdecomp2p.cc
.SH VERSION
4.2-git
