.TH sftwolayer3dti 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftwolayer3dti \- 2-D two-components wavefield modeling using pseudo-pure mode P-wave equation in VTI media.
.SH SYNOPSIS
.B sftwolayer3dti > Fo1.rsf vs0=Fo2.rsf epsi=Fo3.rsf del=Fo4.rsf gam=Fo5.rsf the=Fo6.rsf phi=Fo7.rsf ny=201 nx=201 nz=201 dy=0.008 dx=0.008 dz=0.008 vp0_1=3000.0 vs0_1=1200.0 eps_1=0.2 del_1=0.1 gam_1=0.0 the_1=0.0 phi_1=0.0 vp0_2=3000.0 vs0_2=1200.0 eps_2=0.2 del_2=0.1 gam_2=0.0 the_2=30.0 phi_2=0.0
.SH COMMENTS
Copyright (C) 2012 Tongji University, Shanghai, China 
Authors: Jiubing Cheng and Wei Kang

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

.SH PARAMETERS
.PD 0
.TP
.I file   
.B del
.B =
.R  	auxiliary output file name
.TP
.I float  
.B del_1
.B =0.1
.R  
.TP
.I float  
.B del_2
.B =0.1
.R  
.TP
.I float  
.B dx
.B =0.008
.R  
.TP
.I float  
.B dy
.B =0.008
.R  
.TP
.I float  
.B dz
.B =0.008
.R  
.TP
.I float  
.B eps_1
.B =0.2
.R  
.TP
.I float  
.B eps_2
.B =0.2
.R  
.TP
.I file   
.B epsi
.B =
.R  	auxiliary output file name
.TP
.I file   
.B gam
.B =
.R  	auxiliary output file name
.TP
.I float  
.B gam_1
.B =0.0
.R  
.TP
.I float  
.B gam_2
.B =0.0
.R  
.TP
.I int    
.B nx
.B =201
.R  
.TP
.I int    
.B ny
.B =201
.R  
.TP
.I int    
.B nz
.B =201
.R  
.TP
.I file   
.B phi
.B =
.R  	auxiliary output file name
.TP
.I float  
.B phi_1
.B =0.0
.R  
.TP
.I float  
.B phi_2
.B =0.0
.R  
.TP
.I file   
.B the
.B =
.R  	auxiliary output file name
.TP
.I float  
.B the_1
.B =0.0
.R  
.TP
.I float  
.B the_2
.B =30.0
.R  	Unit: degree
.TP
.I float  
.B vp0_1
.B =3000.0
.R  
.TP
.I float  
.B vp0_2
.B =3000.0
.R  
.TP
.I file   
.B vs0
.B =
.R  	auxiliary output file name
.TP
.I float  
.B vs0_1
.B =1200.0
.R  
.TP
.I float  
.B vs0_2
.B =1200.0
.R  
.SH SOURCE
.I user/chengjb/Mtwolayer3dti.c
.SH VERSION
4.2-git
