.TH sftwolayer 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftwolayer \- Two layer NN training
.SH SYNOPSIS
.B sftwolayer < dat.rsf label=lbl.rsf valdata=valdat.rsf vallabel=vallbl.rsf weight1=wt1.rsf weight2=wt2.rsf bias1=bs1.rsf bias2=bs2.rsf > loss.rsf weight1out=wt1out.rsf weight2out=wt2out.rsf bias1out=bs1out.rsf bias2out=bs2out.rsf valloss=valloss.rsf lr= niter= act= opt= seed= stop= lossfunc= reg= alpha=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B act
.B =
.R  	Activation function - 0:sigmoid 1:tanh 2:relu 3:identity
.TP
.I float  
.B alpha
.B =
.R  	Regularization coeff. If not, set alpha=0
.TP
.I file   
.B bias1
.B =
.R  	auxiliary input file name
.TP
.I file   
.B bias1out
.B =
.R  	auxiliary output file name
.TP
.I file   
.B bias2
.B =
.R  	auxiliary input file name
.TP
.I file   
.B bias2out
.B =
.R  	auxiliary output file name
.TP
.I file   
.B label
.B =
.R  	auxiliary input file name
.TP
.I float  
.B lossfunc
.B =
.R  	Loss function - 0:MSE 1:L1
.TP
.I float  
.B lr
.B =
.R  
.TP
.I float  
.B niter
.B =
.R  
.TP
.I float  
.B opt
.B =
.R  	Optimization method - 0:SGD 1:momentum 2:Adam
.TP
.I float  
.B reg
.B =
.R  	Regularization - 0:L2 1:L1
.TP
.I float  
.B seed
.B =
.R  
.TP
.I float  
.B stop
.B =
.R  
.TP
.I file   
.B valdata
.B =
.R  	auxiliary input file name
.TP
.I file   
.B vallabel
.B =
.R  	auxiliary input file name
.TP
.I file   
.B valloss
.B =
.R  	auxiliary output file name
.TP
.I file   
.B weight1
.B =
.R  	auxiliary input file name
.TP
.I file   
.B weight1out
.B =
.R  	auxiliary output file name
.TP
.I file   
.B weight2
.B =
.R  	auxiliary input file name
.TP
.I file   
.B weight2out
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/fomels/Mtwolayer.py
.SH VERSION
4.2-git
