.TH sftwodip2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftwodip2 \- 2-D two dip estimation by plane wave destruction.
.SH SYNOPSIS
.B sftwodip2 < in.rsf > out.rsf dip1=dip1.rsf dip2=dip2.rsf mask=mask.rsf niter=5 eps=1 lam=1 order=1 nj1=1 nj2=1 drift=n verb=n sign=n gauss=n both=y p0=1. q0=0. < data.rsf > dip.rsf
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B both
.B =y
.R  [y/n]	if y, estimate both dips
.TP
.I string 
.B dip1
.B =
.R  	auxiliary input file name
.TP
.I string 
.B dip2
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B drift
.B =n
.R  [y/n]	if shift filter
.TP
.I float  
.B eps
.B =1
.R  	vertical smoothness
.TP
.I bool   
.B gauss
.B =n
.R  [y/n]	if y, use exact Gaussian for smoothing
.TP
.I float  
.B lam
.B =1
.R  	horizontal smoothness
.TP
.I string 
.B mask
.B =
.R  	auxiliary input file name
.TP
.I int    
.B niter
.B =5
.R  	number of iterations
.TP
.I int    
.B nj1
.B =1
.R  	antialiasing for first dip
.TP
.I int    
.B nj2
.B =1
.R  	antialiasing for second dip
.TP
.I int    
.B order
.B =1
.R  	accuracy order
.TP
.I float  
.B p0
.B =1.
.R  	initial first dip
.TP
.I float  
.B q0
.B =0.
.R  	initial second dip
.TP
.I bool   
.B sign
.B =n
.R  [y/n]	if y, keep dip sign constant
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH USED IN
.TP
.I cwp/geo2006TimeShiftImagingCondition/zicig
.SH SOURCE
.I user/pwd/Mtwodip2.c
.SH VERSION
4.2-git
