.TH sftxsorth 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftxsorth \- Streaming orthogonalize signal and noise in t-x domain. 
.SH SYNOPSIS
.B sftxsorth < in.rsf noise=noise.rsf > fnoi2.rsf sig2=fsig2.rsf gamma1= gamma2=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B gamma1
.B =
.R  	Regularization in t direction, gamma_t in equations 18 and 20
.TP
.I float  
.B gamma2
.B =
.R  	Regularization in x direction, gamma_x in equations 18 and 20
.TP
.I file   
.B noise
.B =
.R  	auxiliary input file name
.TP
.I file   
.B sig2
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/yliu/Mtxsorth.c
.SH VERSION
4.2-git
