.TH sftxspfvsint2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftxspfvsint2 \- Missing data interpolation using t-x streaming prediction filter with varying smoothness and noncausal structure. 
.SH SYNOPSIS
.B sftxspfvsint2 < in.rsf > out.rsf known=known.rsf a= verb=n smooth=n epst=0 epsx=0 lambda1= lambda2= var=0.0f seed=time(NULL)
.SH PARAMETERS
.PD 0
.TP
.I ints   
.B a
.B =
.R  	 [dim]
.TP
.I float  
.B epst
.B =0
.R  	Smoothness in t direction
.TP
.I float  
.B epsx
.B =0
.R  	Smoothness in x direction
.TP
.I file   
.B known
.B =
.R  	auxiliary input file name
.TP
.I float  
.B lambda1
.B =
.R  	Regularization in t direction
.TP
.I float  
.B lambda2
.B =
.R  	Regularization in x direction
.TP
.I int    
.B seed
.B =time(NULL)
.R  
.TP
.I bool   
.B smooth
.B =n
.R  [y/n]	If yes, use varying smoothness
.TP
.I float  
.B var
.B =0.0f
.R  
.TP
.I bool   
.B verb
.B =n
.R  [y/n]
.SH SOURCE
.I user/yliu/Mtxspfvsint2.c
.SH VERSION
4.2-git
