.TH sftxrna3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sftxrna3 \- 3D space-noncausal t-x-y nonstationary regularized autoregression. 
.SH SYNOPSIS
.B sftxrna3 < mat.rsf > pre.rsf a= niter=20 verb=n
.SH PARAMETERS
.PD 0
.TP
.I ints   
.B a
.B =
.R  	 [mdim]
.TP
.I int    
.B niter
.B =20
.R  	number of iterations
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/yliu/Mtxrna3.c
.SH VERSION
4.2-git
