.TH sfunfault 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfunfault \- Unfault image 
.SH SYNOPSIS
.B sfunfault < in.rsf slip=slip.rsf > out.rsf shift=shift.rsf dip=dip.rsf mask=mask.rsf inv=n mode=y niter=100 off=2 lam=1
.SH PARAMETERS
.PD 0
.TP
.I file   
.B dip
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B inv
.B =n
.R  [y/n]
.TP
.I float  
.B lam
.B =1
.R  	regularization
.TP
.I file   
.B mask
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B mode
.B =y
.R  [y/n]
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I int    
.B off
.B =2
.R  	offset to fault
.TP
.I file   
.B shift
.B =
.R  	auxiliary input file name
.TP
.I file   
.B slip
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/zhiguang/Munfault.c
.SH VERSION
4.2-git
