.TH sfupgrad 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfupgrad \- Causal gradient operator 
.SH SYNOPSIS
.B sfupgrad < inp.rsf ref=ref.rsf > out.rsf adj=n grad=y dim=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag
.TP
.I int    
.B dim
.B =
.R  
.TP
.I bool   
.B grad
.B =y
.R  [y/n]	if y, gradient; if n, Laplacian
.TP
.I file   
.B ref
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/fomels/Mupgrad.c
.SH VERSION
4.2-git
