.TH sfvaricost 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfvaricost \- 
.SH SYNOPSIS
.B sfvaricost lambda= epsilon=
.SH COMMENTS
Determines costs associated with velocity models from varipick.
Input is velocity model, needs semb= semblance volume


.SH PARAMETERS
.PD 0
.TP
.I float  
.B epsilon
.B =
.R  
.TP
.I float  
.B lambda
.B =
.R  
.SH SOURCE
.I user/luke/Mvaricost.py
.SH VERSION
4.2-git
