.TH sfvariminim 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfvariminim \- 
.SH SYNOPSIS
.B sfvariminim lambda= epsilon= costs= worst=
.SH COMMENTS
outputs the minimum and maximum cost velocity models
input is series of models
semb= semblance volume
costs= output for cost
worst= worst model output
primary output is lowest cost model


.SH PARAMETERS
.PD 0
.TP
.I string 
.B costs
.B =
.R  
.TP
.I float  
.B epsilon
.B =
.R  
.TP
.I float  
.B lambda
.B =
.R  
.TP
.I string 
.B worst
.B =
.R  
.SH SOURCE
.I user/luke/Mvariminim.py
.SH VERSION
4.2-git
