.TH sfvariogram 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfvariogram \- Compute a variogram of data values. 
.SH SYNOPSIS
.B sfvariogram < in.rsf > out.rsf dh=1 oh=0 nh=n1/dh-oh semi=y
.SH PARAMETERS
.PD 0
.TP
.I int    
.B dh
.B =1
.R  	interval (number) of variogram lag
.TP
.I int    
.B nh
.B =n1/dh-oh
.R  	number of variogram lag
.TP
.I int    
.B oh
.B =0
.R  	origin (number) of variogram lag
.TP
.I bool   
.B semi
.B =y
.R  [y/n]	if y, output semivariogram
.SH SOURCE
.I user/yliu/Mvariogram.c
.SH VERSION
4.2-git
