.TH sfvam 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfvam \- Create a layered model. 
.SH SYNOPSIS
.B sfvam > vfile.rsf nz= nx= dz= dx=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dx
.B =
.R  	distance sampling
.TP
.I float  
.B dz
.B =
.R  	depth sampling
.TP
.I int    
.B nx
.B =
.R  	distance grid
.TP
.I int    
.B nz
.B =
.R  	depth grid
.SH SOURCE
.I user/hpcss/Mvam.c
.SH VERSION
4.2-git
