.TH sfvar2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfvar2 \- Variogram from irregular 2-D data. 
.SH SYNOPSIS
.B sfvar2 < in.rsf > out.rsf nx= dx=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dx
.B =
.R  	distance sampling
.TP
.I int    
.B nx
.B =
.R  	number of distance bins
.SH SOURCE
.I user/fomels/Mvar2.c
.SH VERSION
4.2-git
