.TH sfvconvert 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfvconvert \- 2-D velocity mapping from manual picking to rsf RMS format. 
.SH SYNOPSIS
.B sfvconvert < in.rsf > out.rsf pattern=pattern.rsf shift=0
.SH COMMENTS
Covert from
--------------------------------------
Time_i(ms) RMS_i(m/s) Lateral_j(trace)
...        ...        ...
-1         0          Lateral_j
...        ...        ...
--------------------------------------
to
regular RSF_RMS velocity grid

Specify either n1= o1= d1= n2= o2= d2= or pattern=

.SH PARAMETERS
.PD 0
.TP
.I string 
.B pattern
.B =
.R  	auxiliary input file name
.TP
.I int    
.B shift
.B =0
.R  	Lateral shift
.SH SOURCE
.I user/yliu/Mvconvert.c
.SH VERSION
4.2-git
