.TH sfvelsteer 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfvelsteer \- Velocity steering for 2D receivers array. 
.SH SYNOPSIS
.B sfvelsteer < in.rsf > out.rsf nvx= dvx= ovx= nvy= dvy= ovy= iypi=0 iyps=ny-1 xp=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dvx
.B =
.R  	vx sampling
.TP
.I float  
.B dvy
.B =
.R  	vy sampling
.TP
.I int    
.B iypi
.B =0
.R  	first depth position where velocity steering is computed
.TP
.I int    
.B iyps
.B =ny-1
.R  	last depth position where velocity steering is computed
.TP
.I int    
.B nvx
.B =
.R  	number of vx values
.TP
.I int    
.B nvy
.B =
.R  	number of vy values
.TP
.I float  
.B ovx
.B =
.R  	vx origin
.TP
.I float  
.B ovy
.B =
.R  	vy origin
.TP
.I float  
.B xp
.B =
.R  	lateral position where velocity steering is computed
.SH SOURCE
.I user/browaeys/Mvelsteer.c
.SH VERSION
4.2-git
