.TH sfvelinv 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfvelinv \- Velocity transform for generating velocity spectra and its corresponding hyperbolic modeling. 
.SH SYNOPSIS
.B sfvelinv < cmp.rsf > vtr.rsf adj=n niter=0 ns=nx ds=0.001 os=0.00000001 nx=ns dx=10. ox=0. robust=n perc=90. fact=1.5 nliter=10 eps=1. type=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adj = 0: from velocity-domain(t,s) to cmp-gather(t,x)
       adj = 1: from cmp-gather(t,x) to velocity-domain(t,s)
.TP
.I float  
.B ds
.B =0.001
.R  	slowness sampling
.TP
.I float  
.B dx
.B =10.
.R  	offset sampling
.TP
.I float  
.B eps
.B =1.
.R  	regularization parameter for robust inversion
.TP
.I float  
.B fact
.B =1.5
.R  	threshold factor for robust inversion
.TP
.I int    
.B niter
.B =0
.R  	number of iterations (invoked if adj=y)
.TP
.I int    
.B nliter
.B =10
.R  	number of POCS iterations for robust inversion
.TP
.I int    
.B ns
.B =nx
.R  	number of slowness values
.TP
.I int    
.B nx
.B =ns
.R  	number of offset values
.TP
.I float  
.B os
.B =0.00000001
.R  	slowness origin
.TP
.I float  
.B ox
.B =0.
.R  	offset origin
.TP
.I float  
.B perc
.B =90.
.R  	threshold percentage for robust inversion
.TP
.I bool   
.B robust
.B =n
.R  [y/n]	robust inversion
.TP
.I string 
.B type
.B =
.R  	thresholding type
.SH SOURCE
.I user/fomels/Mvelinv.c
.SH VERSION
4.2-git
