.TH sfvelcon3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfvelcon3 \- 3-D finite-difference velocity continuation on a helix 
.SH SYNOPSIS
.B sfvelcon3 < inp.rsf > out.rsf adj=y inv=1 nv=nt vel=1.
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =y
.R  [y/n]	forward or backward continuation
.TP
.I int    
.B inv
.B =1
.R  	inversion type
.TP
.I int    
.B nv
.B =nt
.R  	velocity steps
.TP
.I float  
.B vel
.B =1.
.R  	initial velocity
.SH SOURCE
.I user/gee/Mvelcon3.c
.SH VERSION
4.2-git
