.TH sfvelmap 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfvelmap \- 2-D mapping from moving-object velocity to plane-wave slowness 
.SH SYNOPSIS
.B sfvelmap < in.rsf > out.rsf osx=-0.5/dvx osy=-0.5/dvy nt=360 dt=0.5 ot=0.
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dt
.B =0.5
.R  	line parameter increment
.TP
.I int    
.B nt
.B =360
.R  	number of line parameter for integration in [0,180].
.TP
.I float  
.B osx
.B =-0.5/dvx
.R  
.TP
.I float  
.B osy
.B =-0.5/dvy
.R  
.TP
.I float  
.B ot
.B =0.
.R  	line parameter origin
.SH SOURCE
.I user/browaeys/Mvelmap.c
.SH VERSION
4.2-git
