.TH sfvelinvnew 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfvelinvnew \- None
.SH SYNOPSIS
.B sfvelinvnew < infile.rsf res=fres.rsf vel0=fm.rsf mres=fmres.rsf > outfile.rsf velout=vtr.rsf nv=nhx dv=0.01 ov=1.5 niter=20 savevel=0 flag=0 mflag=0 huber=0 irls=0 nstep=1 rwt=0. mwt=0. srate=0.01 eps=0.01 lamda=1000. delta=0.0001 step=0.000005 alpha=790.635 alpha= lip= reset=
.SH PARAMETERS
.PD 0
.TP
.I        
.B alpha
.B =
.R  	smoothing parameter, typical value: 1 to 10 times estimated norm(x,inf)
.TP
.I        
.B delta
.B =0.0001
.R  	delta controls update step and convergent, small delta ensure convergence but with small decrease in data fit error
.TP
.I        
.B dv
.B =0.01
.R  
.TP
.I        
.B eps
.B =0.01
.R  
.TP
.I        
.B flag
.B =0
.R  
.TP
.I        
.B huber
.B =0
.R  
.TP
.I        
.B irls
.B =0
.R  
.TP
.I        
.B lamda
.B =1000.
.R  	lamda controls sparsity, bigger lamda, more sparsity
.TP
.I        
.B lip
.B =
.R  	the estimated Lipschitz constrant of the dual objective, default: alpha*normest(A*A',1e-2)
.TP
.I        
.B mflag
.B =0
.R  
.TP
.I file   
.B mres
.B =
.R  	auxiliary output file name
.TP
.I        
.B mwt
.B =0.
.R  
.TP
.I        
.B niter
.B =20
.R  
.TP
.I        
.B nstep
.B =1
.R  
.TP
.I        
.B nv
.B =nhx
.R  
.TP
.I        
.B ov
.B =1.5
.R  
.TP
.I file   
.B res
.B =
.R  	auxiliary output file name
.TP
.I        
.B reset
.B =
.R  	Nesterov's acceleration restart (theta is reset) or skip (theta is not reset)
.TP
.I        
.B rwt
.B =0.
.R  
.TP
.I        
.B savevel
.B =0
.R  	Flag to choose the algorithm
.TP
.I        
.B srate
.B =0.01
.R  
.TP
.I        
.B step
.B =0.000005
.R  	step is very important in convergence and sparsity
.TP
.I file   
.B vel0
.B =
.R  	auxiliary input file name
.TP
.I file   
.B velout
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/seisinv/Mvelinvnew.f90
.SH VERSION
4.2-git
