.TH sfvelcon 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfvelcon \- Post-stack velocity continuation by implicit finite differences 
.SH SYNOPSIS
.B sfvelcon < in.rsf > out.rsf vel=0.75 v0=0. nv=n1 adj=n add=n inv=0
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B add
.B =n
.R  [y/n]	addition flag
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag
.TP
.I int    
.B inv
.B =0
.R  	amplitude type
.TP
.I int    
.B nv
.B =n1
.R  	number of steps
.TP
.I float  
.B v0
.B =0.
.R  	starting velocity
.TP
.I float  
.B vel
.B =0.75
.R  	final velocity
.SH SOURCE
.I user/fomels/Mvelcon.c
.SH VERSION
4.2-git
