.TH sfvelxf 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfvelxf \- None
.SH SYNOPSIS
.B sfvelxf < vtr.rsf < cmp.rsf adj=0 nx=ns dx=10. ox=0. ns=nx ds=0.001 os=0.00000001
.SH PARAMETERS
.PD 0
.TP
.I        
.B adj
.B =0
.R  	adj = 0  : from velocity-domain(t,s) to cmp-gather(t,x)
.TP
.I        
.B ds
.B =0.001
.R  
.TP
.I        
.B dx
.B =10.
.R  
.TP
.I        
.B ns
.B =nx
.R  
.TP
.I        
.B nx
.B =ns
.R  
.TP
.I        
.B os
.B =0.00000001
.R  
.TP
.I        
.B ox
.B =0.
.R  
.SH SOURCE
.I user/jun/Mvelxf.f90
.SH VERSION
4.2-git
