.TH sfvelinvww 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfvelinvww \- None
.SH SYNOPSIS
.B sfvelinvww < infile.rsf > outfile.rsf velout=vtr.rsf ns=nh ds=0.001 os=0.00000001 huber=0 irls=0 nstep=1 niter=20 rwt=0. mwt=0. srate=0.01 epw=0.01 savevel=0
.SH PARAMETERS
.PD 0
.TP
.I        
.B ds
.B =0.001
.R  
.TP
.I        
.B epw
.B =0.01
.R  
.TP
.I        
.B huber
.B =0
.R  
.TP
.I        
.B irls
.B =0
.R  
.TP
.I        
.B mwt
.B =0.
.R  
.TP
.I        
.B niter
.B =20
.R  
.TP
.I        
.B ns
.B =nh
.R  
.TP
.I        
.B nstep
.B =1
.R  
.TP
.I        
.B os
.B =0.00000001
.R  
.TP
.I        
.B rwt
.B =0.
.R  
.TP
.I        
.B savevel
.B =0
.R  
.TP
.I        
.B srate
.B =0.01
.R  
.TP
.I file   
.B velout
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/jun/Mvelinvww.f90
.SH VERSION
4.2-git
