.TH sfvelxf3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfvelxf3 \- None
.SH SYNOPSIS
.B sfvelxf3 < vtr.rsf < cmp.rsf adj=0 nx=nv ny=1 dx=0.01 dy=0.01 ox=0. oy=0. nv=nx dv=0.01 ov=1.5
.SH PARAMETERS
.PD 0
.TP
.I        
.B adj
.B =0
.R  	adj = 0  : from velocity-domain(t,s) to cmp-gather(t,x)
.TP
.I        
.B dv
.B =0.01
.R  
.TP
.I        
.B dx
.B =0.01
.R  
.TP
.I        
.B dy
.B =0.01
.R  
.TP
.I        
.B nv
.B =nx
.R  
.TP
.I        
.B nx
.B =nv
.R  
.TP
.I        
.B ny
.B =1
.R  
.TP
.I        
.B ov
.B =1.5
.R  
.TP
.I        
.B ox
.B =0.
.R  
.TP
.I        
.B oy
.B =0.
.R  
.SH SOURCE
.I user/seisinv/Mvelxf3.f90
.SH VERSION
4.2-git
