.TH sfvfsacrsnh 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfvfsacrsnh \- Version 2.0 - Zero offset CRS parameters inversion (RN, RNIP, BETA) with Very Fast Simulated Aneeling (VFSA) Global Optimization
.SH SYNOPSIS
.B sfvfsacrsnh < in.rsf > out.rsf om0=0.0 dm0=0.1 nm0=1 v0=1.5 ot0=0.0 dt0=0.1 nt0=1 c0=0.5 temp0=10 repeat=1 verb=0
.SH COMMENTS

This program uses the Non-Hyperbolic CRS approximation to fit data cube and get the zero-offset CRS parameters (Fomel, 2013).

Programmer: Rodolfo A. C. Neves (Dirack) 13/08/2021

Email:  rodolfo_profissional@hotmail.com

License: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.


.SH PARAMETERS
.PD 0
.TP
.I float  
.B c0
.B =0.5
.R  	damping factor of VFSA
.TP
.I float  
.B dm0
.B =0.1
.R  	central CMP's sampling (Km)
.TP
.I float  
.B dt0
.B =0.1
.R  	t0's sampling (s)
.TP
.I int    
.B nm0
.B =1
.R  	central CMP's number of samples (Km)
.TP
.I int    
.B nt0
.B =1
.R  	Number of t0's sampling (s)
.TP
.I float  
.B om0
.B =0.0
.R  	central CMP's origin  (Km)
.TP
.I float  
.B ot0
.B =0.0
.R  	t0's origin (s)
.TP
.I int    
.B repeat
.B =1
.R  	How many times to perform VFSA global optimization
.TP
.I float  
.B temp0
.B =10
.R  	initial VFSA temperature
.TP
.I float  
.B v0
.B =1.5
.R  	Near surface velocity (Km/s)
.TP
.I bool   
.B verb
.B =0
.R  [y/n]	1: active mode; 0: quiet mode
.SH SOURCE
.I user/dirack/Mvfsacrsnh.c
.SH VERSION
4.2-git
