.TH sfvipmig0 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfvipmig0 \- Velocity-independent phase-space zero-offset migration. 
.SH SYNOPSIS
.B sfvipmig0 < inp.rsf > mig.rsf vmin= vmax=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B vmax
.B =
.R  	convert to slowness
.TP
.I float  
.B vmin
.B =
.R  
.SH SOURCE
.I user/fomels/Mvipmig0.c
.SH VERSION
4.2-git
