.TH sfvofzperm 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfvofzperm \- V(z) prestack exploditing reflector. 
.SH SYNOPSIS
.B sfvofzperm < data.rsf > image.rsf size=size.rsf left=left.rsf middle=middle.rsf right=right.rsf mig=n nz= dz= nt= dt= nh= dh=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dh
.B =
.R  	offset sampling (if modeling)
.TP
.I float  
.B dt
.B =
.R  	time sampling (if modeling)
.TP
.I float  
.B dz
.B =
.R  	time sampling (if migration)
.TP
.I file   
.B left
.B =
.R  	auxiliary input file name
.TP
.I file   
.B middle
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B mig
.B =n
.R  [y/n]	if n, modeling; if y, migration
.TP
.I int    
.B nh
.B =
.R  	offset samples (if modeling)
.TP
.I int    
.B nt
.B =
.R  	time samples (if modeling)
.TP
.I int    
.B nz
.B =
.R  	time samples (if migration)
.TP
.I file   
.B right
.B =
.R  	auxiliary input file name
.TP
.I file   
.B size
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/fomels/Mvofzperm.c
.SH VERSION
4.2-git
