.TH sfvti2dpseudosv 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfvti2dpseudosv \- 2-D two-components wavefield modeling using pseudo-pure mode qSV-wave equation in VTI media.
.SH SYNOPSIS
.B sfvti2dpseudosv < Fvp0.rsf vs0=Fvs0.rsf epsi=Feps.rsf del=Fdel.rsf > Fo1.rsf PseudoPureSVz=Fo2.rsf PseudoPureSV=Fo3.rsf acx=Fo4.rsf acz=Fo5.rsf asx=Fo6.rsf asz=Fo7.rsf asvx=Fo8.rsf asvz=Fo9.rsf acxx=Fo10.rsf aczz=Fo11.rsf asxx=Fo12.rsf aszz=Fo13.rsf asvxx=Fo14.rsf asvzz=Fo15.rsf PseudoPureSepSV=Fo16.rsf ns=301 dt=0.001 isep=0 ihomo=0 itaper=0 nstep=2 tapertype=
.SH COMMENTS

Copyright (C) 2012 Tongji University, Shanghai, China 
Authors: Jiubing Cheng, Wei Kang and Tengfei Wang

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

.SH PARAMETERS
.PD 0
.TP
.I file   
.B PseudoPureSV
.B =
.R  	auxiliary output file name
.TP
.I file   
.B PseudoPureSVz
.B =
.R  	auxiliary output file name
.TP
.I file   
.B PseudoPureSepSV
.B =
.R  	auxiliary output file name
.TP
.I file   
.B acx
.B =
.R  	auxiliary output file name
.TP
.I file   
.B acxx
.B =
.R  	auxiliary output file name
.TP
.I file   
.B acz
.B =
.R  	auxiliary output file name
.TP
.I file   
.B aczz
.B =
.R  	auxiliary output file name
.TP
.I file   
.B asvx
.B =
.R  	auxiliary output file name
.TP
.I file   
.B asvxx
.B =
.R  	auxiliary output file name
.TP
.I file   
.B asvz
.B =
.R  	auxiliary output file name
.TP
.I file   
.B asvzz
.B =
.R  	auxiliary output file name
.TP
.I file   
.B asx
.B =
.R  	auxiliary output file name
.TP
.I file   
.B asxx
.B =
.R  	auxiliary output file name
.TP
.I file   
.B asz
.B =
.R  	auxiliary output file name
.TP
.I file   
.B aszz
.B =
.R  	auxiliary output file name
.TP
.I file   
.B del
.B =
.R  	auxiliary input file name
.TP
.I float  
.B dt
.B =0.001
.R  
.TP
.I file   
.B epsi
.B =
.R  	auxiliary input file name
.TP
.I int    
.B ihomo
.B =0
.R  	if ihomo=1, homogeneous medium
.TP
.I int    
.B isep
.B =0
.R  	if isep=1, separate wave-modes
.TP
.I int    
.B itaper
.B =0
.R  	if itaper=1, taper the wavenumber domain p=operators
.TP
.I int    
.B ns
.B =301
.R  
.TP
.I int    
.B nstep
.B =2
.R  
.TP
.I string 
.B tapertype
.B =
.R  	taper type
.TP
.I file   
.B vs0
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/chengjb/Mvti2dpseudosv.c
.SH VERSION
4.2-git
