.TH sfvtihti2ort 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfvtihti2ort \- Combining VTI and HTI parameters to orthorhombic according to Schoenberg & Sayer (1995)
.SH SYNOPSIS
.B sfvtihti2ort > c11o.rsf c22o=c22o.rsf c33o=c33o.rsf c44o=c44o.rsf c55o=c55o.rsf c66o=c66o.rsf c12o=c12o.rsf c13o=c13o.rsf c23o=c23o.rsf < c33.rsf c55=c55.rsf c11v=c11v.rsf c66v=c66v.rsf c12v=c12v.rsf c13v=c13v.rsf c11h=c11h.rsf c55h=c55h.rsf c12h=c12h.rsf c13h=c13h.rsf phi=phi.rsf c16o=c16o.rsf c26o=c26o.rsf c36o=c36o.rsf c45o=c45o.rsf rotate=n
.SH COMMENTS
NOTE: HTI is defined in VTI grid with respect to the vertical (Ruger(1997)) 
Refer to SEAM 2 notes for detailed description


.SH PARAMETERS
.PD 0
.TP
.I file   
.B c11h
.B =
.R  	auxiliary input file name
.TP
.I file   
.B c11v
.B =
.R  	auxiliary input file name
.TP
.I file   
.B c12h
.B =
.R  	auxiliary input file name
.TP
.I file   
.B c12o
.B =
.R  	auxiliary output file name
.TP
.I file   
.B c12v
.B =
.R  	auxiliary input file name
.TP
.I file   
.B c13h
.B =
.R  	auxiliary input file name
.TP
.I file   
.B c13o
.B =
.R  	auxiliary output file name
.TP
.I file   
.B c13v
.B =
.R  	auxiliary input file name
.TP
.I file   
.B c16o
.B =
.R  	auxiliary output file name
.TP
.I file   
.B c22o
.B =
.R  	auxiliary output file name
.TP
.I file   
.B c23o
.B =
.R  	auxiliary output file name
.TP
.I file   
.B c26o
.B =
.R  	auxiliary output file name
.TP
.I file   
.B c33o
.B =
.R  	auxiliary output file name
.TP
.I file   
.B c36o
.B =
.R  	auxiliary output file name
.TP
.I file   
.B c44o
.B =
.R  	auxiliary output file name
.TP
.I file   
.B c45o
.B =
.R  	auxiliary output file name
.TP
.I file   
.B c55
.B =
.R  	auxiliary input file name
.TP
.I file   
.B c55h
.B =
.R  	auxiliary input file name
.TP
.I file   
.B c55o
.B =
.R  	auxiliary output file name
.TP
.I file   
.B c66o
.B =
.R  	auxiliary output file name
.TP
.I file   
.B c66v
.B =
.R  	auxiliary input file name
.TP
.I file   
.B phi
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B rotate
.B =n
.R  [y/n]	Doing azimuthal rotation (y-> mono, n-> ortho)
.SH SOURCE
.I user/zone/Mvtihti2ort.c
.SH VERSION
4.2-git
