.TH sfwave4 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfwave4 \- 1-D finite-difference wave extrapolation 
.SH SYNOPSIS
.B sfwave4 < inp.rsf > out.rsf vel=vel.rsf grad=grad.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B grad
.B =
.R  	auxiliary input file name
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/songxl/Mwave4.c
.SH VERSION
4.2-git
