.TH sfwavemixop 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfwavemixop \- Complex 2-D wave propagation (with kiss-fft)
.SH SYNOPSIS
.B sfwavemixop < Fw.rsf > Fo.rsf ref=Fr.rsf snaps=Fs.rsf left=left.rsf right=right.rsf alpha=Fa.rsf beta=Fb.rsf verb=n snap=0 correct=n type=0 pad1=1 mode=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B alpha
.B =
.R  	auxiliary input file name
.TP
.I file   
.B beta
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B correct
.B =n
.R  [y/n]	jingwei's correction
.TP
.I file   
.B left
.B =
.R  	auxiliary input file name
.TP
.I string 
.B mode
.B =
.R  	default mode is pspi
.TP
.I int    
.B pad1
.B =1
.R  	padding factor on the first axis
.TP
.I file   
.B ref
.B =
.R  	auxiliary input file name
.TP
.I file   
.B right
.B =
.R  	auxiliary input file name
.TP
.I int    
.B snap
.B =0
.R  	interval for snapshots
.TP
.I file   
.B snaps
.B =
.R  	auxiliary output file name
.TP
.I int    
.B type
.B =0
.R  	type of propagation; 0 means no correction applied, and mode takes effect, 9 enables jjsf
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.SH SOURCE
.I user/jsun/Mwavemixop.c
.SH VERSION
4.2-git
