.TH sfwarpscanw 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfwarpscanw \- Multicomponent data registration analysis. 
.SH SYNOPSIS
.B sfwarpscanw < in.rsf > warped.rsf other=other.rsf renergy=renergy.rsf denergy=denergy.rsf verb=y cheb=n sign=n ren=n den=n ng=1 g0= dg=g0 rect1=1 rect2=1 rect3=1 rect4=1 niter=10 shift=n accuracy=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B accuracy
.B =
.R  [1-4]	interpolation accuracy
.TP
.I bool   
.B cheb
.B =n
.R  [y/n]	use Chebyshev scan
.TP
.I bool   
.B den
.B =n
.R  [y/n]	use data energy
.TP
.I file   
.B denergy
.B =
.R  	auxiliary input file name
.TP
.I float  
.B dg
.B =g0
.R  	gamma sampling
.TP
.I float  
.B g0
.B =
.R  	gamma origin
.TP
.I int    
.B ng
.B =1
.R  	number of gamma values
.TP
.I int    
.B niter
.B =10
.R  	number of iterations
.TP
.I file   
.B other
.B =
.R  	auxiliary input file name
.TP
.I int    
.B rect1
.B =1
.R  	vertical smoothing
.TP
.I int    
.B rect2
.B =1
.R  	gamma smoothing
.TP
.I int    
.B rect3
.B =1
.R  	in-line smoothing
.TP
.I int    
.B rect4
.B =1
.R  	cross-line smoothing
.TP
.I bool   
.B ren
.B =n
.R  [y/n]	use reference energy
.TP
.I file   
.B renergy
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B shift
.B =n
.R  [y/n]	use shift instead of stretch
.TP
.I bool   
.B sign
.B =n
.R  [y/n]	use signed similarity
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/sbader/Mwarpscanw.c
.SH VERSION
4.2-git Mwarpscan.c 744 2004-08-17 18:46:07Z fomels
