.TH sfwavmod 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfwavmod \- 1-2-3D finite difference modeling 
.SH SYNOPSIS
.B sfwavmod < in.rsf vel=vel.rsf sgrid=sgrid.rsf ggrid=ggrid.rsf > dat.rsf wfl=wfl.rsf jt=1 jtm=100 ot=0.0 verb=n
.SH PARAMETERS
.PD 0
.TP
.I file   
.B ggrid
.B =
.R  	auxiliary input file name
.TP
.I int    
.B jt
.B =1
.R  	time interval in observation system
.TP
.I int    
.B jtm
.B =100
.R  	time interval of wave movie
.TP
.I float  
.B ot
.B =0.0
.R  	time delay
.TP
.I file   
.B sgrid
.B =
.R  	auxiliary input file name
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity
.TP
.I string 
.B wfl
.B =
.R  	wavefield movie file (auxiliary output file name)
.SH USED IN
.TP
.I chen/test/wavmod
.SH SOURCE
.I user/chen/Mwavmod.c
.SH VERSION
4.2-git
