.TH sfweiajw 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfweiajw \- 3-D wave-equation wavefield continuation with adjoint-source 
.SH SYNOPSIS
.B sfweiajw slo=Fslo.rsf < Fsou.rsf > Fwfl.rsf verb=n down=y causal=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B causal
.B =
.R  [y/n]	causality flag
.TP
.I bool   
.B down
.B =y
.R  [y/n]	up/down   flag
.TP
.I file   
.B slo
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/psava/Mweiajw.c
.SH VERSION
4.2-git
