.TH sfwexzomva 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfwexzomva \- 3-D S/R WEMVA with extended split-step 
.SH SYNOPSIS
.B sfwexzomva slo=Bs.rsf < Pi.rsf < Ps.rsf wfl=Bwr.rsf verb=y adj= eps=0.01 nrmax=1 dtmax=0.004 pmx=0 pmy=0 tmx=0 tmy=0
.SH PARAMETERS
.PD 0
.TP
.I int    
.B adj
.B =
.R  	y=ADJ Back-projection; n=FWD Forward Scattering
.TP
.I float  
.B dtmax
.B =0.004
.R  	max time error
.TP
.I float  
.B eps
.B =0.01
.R  	stability parameter
.TP
.I int    
.B nrmax
.B =1
.R  	max number of refs
.TP
.I int    
.B pmx
.B =0
.R  	padding on x
.TP
.I int    
.B pmy
.B =0
.R  	padding on y
.TP
.I file   
.B slo
.B =
.R  	auxiliary input file name
.TP
.I int    
.B tmx
.B =0
.R  	taper on x
.TP
.I int    
.B tmy
.B =0
.R  	taper on y
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity flag
.TP
.I file   
.B wfl
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/cwp/Mwexzomva.c
.SH VERSION
4.2-git
