.TH sfwem3d_gpu 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfwem3d_gpu \- 3D ISOTROPIC wave-equation finite-difference migration on GPU 
.SH SYNOPSIS
.B sfwem3d_gpu vel=Fvel.rsf swf=Fswf.rsf rwf=Frwf.rsf swfout=Fswfo.rsf rwfout=Frwfo.rsf kxmap=Fkxmap.rsf > Fxigo.rsf gpu=0 nxtap=40 nytap=40 verbose=n wantwf=n
.SH PARAMETERS
.PD 0
.TP
.I int    
.B gpu
.B =0
.R  	ID of the GPU to be used
.TP
.I file   
.B kxmap
.B =
.R  	auxiliary output file name
.TP
.I int    
.B nxtap
.B =40
.R  	TAPER size
.TP
.I int    
.B nytap
.B =40
.R  	TAPER size
.TP
.I file   
.B rwf
.B =
.R  	auxiliary input file name
.TP
.I file   
.B rwfout
.B =
.R  	auxiliary output file name
.TP
.I file   
.B swf
.B =
.R  	auxiliary input file name
.TP
.I file   
.B swfout
.B =
.R  	auxiliary output file name
.TP
.I file   
.B vel
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verbose
.B =n
.R  [y/n]	VERBOSITY flag
.TP
.I bool   
.B wantwf
.B =n
.R  [y/n]	Want output wavefields
.SH SOURCE
.I user/rweiss/Mwem3d_gpu.cu
.SH VERSION
4.2-git
