.TH sfweximg 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfweximg \- 3-D modeling/migration with extended SSF 
.SH SYNOPSIS
.B sfweximg slo=Fs.rsf swfl=Fws.rsf < Fm.rsf cc=Fc.rsf > Fd.rsf rwfl=Fwr.rsf adj= save=0 feic=0 verb=n eps=0.01 nrmax=1 dtmax=0.004 pmx=0 pmy=0 tmx=0 tmy=0 nhx=0 nhy=0 nhz=0 nht=0 dht=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B adj
.B =
.R  	y=ADJ migration; n=FWD modeling
.TP
.I file   
.B cc
.B =
.R  	auxiliary input file name
.TP
.I float  
.B dht
.B =
.R  
.TP
.I float  
.B dtmax
.B =0.004
.R  	max time error
.TP
.I float  
.B eps
.B =0.01
.R  	stability parameter
.TP
.I int    
.B feic
.B =0
.R  	extended I.C. flag
.TP
.I int    
.B nht
.B =0
.R  	number of lags on the t axis
.TP
.I int    
.B nhx
.B =0
.R  	number of lags on the x axis
.TP
.I int    
.B nhy
.B =0
.R  	number of lags on the y axis
.TP
.I int    
.B nhz
.B =0
.R  	number of lags on the z axis
.TP
.I int    
.B nrmax
.B =1
.R  	maximum references
.TP
.I int    
.B pmx
.B =0
.R  	padding on x
.TP
.I int    
.B pmy
.B =0
.R  	padding on y
.TP
.I string 
.B rwfl
.B =
.R  	auxiliary output file name
.TP
.I int    
.B save
.B =0
.R  	save wfld flag
.TP
.I file   
.B slo
.B =
.R  	auxiliary input file name
.TP
.I file   
.B swfl
.B =
.R  	auxiliary input file name
.TP
.I int    
.B tmx
.B =0
.R  	taper on x
.TP
.I int    
.B tmy
.B =0
.R  	taper on y
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/cwp/Mweximg.c
.SH VERSION
4.2-git
