.TH sfwei 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfwei \- 3-D modeling/migration with extended SSF 
.SH SYNOPSIS
.B sfwei slo=Fslo.rsf < Fsou.rsf dat=Frec.rsf > Fcic.rsf coo=Fcoo.rsf cip=Feic.rsf > Fwfl.rsf verb=n causal=n causal=n irun=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B causal
.B =n
.R  [y/n]	causality
.TP
.I file   
.B cip
.B =
.R  	auxiliary output file name
.TP
.I file   
.B coo
.B =
.R  	auxiliary input file name
.TP
.I file   
.B dat
.B =
.R  	auxiliary input file name
.TP
.I string 
.B irun
.B =
.R  
.TP
.I file   
.B slo
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH USED IN
.TP
.I cwp/geo2011WideAzimuthAngleDecomposition/flatEICangle
.SH SOURCE
.I user/psava/Mwei.c
.SH VERSION
4.2-git
