.TH sfweas1 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfweas1 \- 1-D analytic solution for acoustic wave equation 
.SH SYNOPSIS
.B sfweas1 < Fin.rsf > Fout.rsf vel= nx= dx= spx= kt= ox=0.0 rule=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dx
.B =
.R  
.TP
.I int    
.B kt
.B =
.R  	selected time
.TP
.I int    
.B nx
.B =
.R  
.TP
.I float  
.B ox
.B =0.0
.R  
.TP
.I string 
.B rule
.B =
.R  	t, s : quadrature rules
.TP
.I int    
.B spx
.B =
.R  	source point in x
.TP
.I float  
.B vel
.B =
.R  
.SH SOURCE
.I user/fangg/Mweas1.c
.SH VERSION
4.2-git
