.TH sfweiajs 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfweiajs \- Adjoint source construction for image-domain waveform tomography 
.SH SYNOPSIS
.B sfweiajs bwf=Fbwf.rsf < Feic.rsf coo=Fcoo.rsf > Faso.rsf verb=n conj= irun=
.SH PARAMETERS
.PD 0
.TP
.I file   
.B bwf
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B conj
.B =
.R  [y/n]	flag
.TP
.I file   
.B coo
.B =
.R  	auxiliary input file name
.TP
.I string 
.B irun
.B =
.R  
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/psava/Mweiajs.c
.SH VERSION
4.2-git
