.TH sfwinscan 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfwinscan \- Picking scanned data window trace by trace with fixed t0
.SH SYNOPSIS
.B sfwinscan < cmp.rsf > outf.rsf winsz=200 v0=1000 deltav=20 t0=0.5 n=100
.SH PARAMETERS
.PD 0
.TP
.I float  
.B deltav
.B =20
.R  	step lenth for velocity scan
.TP
.I int    
.B n
.B =100
.R  	numbers of velscan
.TP
.I float  
.B t0
.B =0.5
.R  	t0 fixed
.TP
.I float  
.B v0
.B =1000
.R  	init Vel for velocity scan
.TP
.I int    
.B winsz
.B =200
.R  	for each trace,the width of window. unit:sample point
.SH SOURCE
.I user/yliu/Mwinscan.c
.SH VERSION
4.2-git
