.TH sfwindow 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfwindow \- Window a portion of a dataset. 
.SH SYNOPSIS
.B sfwindow < in.rsf > out.rsf verb=n squeeze=y j#=(1,...) d#=(d1,d2,...) f#=(0,...) min#=(o1,o2,,...) n#=(0,...) max#=(o1+(n1-1)*d1,o2+(n1-1)*d2,,...)
.SH COMMENTS

Other parameters from the command line are passed to the output (similar to sfput).

.SH PARAMETERS
.PD 0
.TP
.I float  
.B d#
.B =(d1,d2,...)
.R  	sampling in #-th dimension
.TP
.I largeint
.B f#
.B =(0,...)
.R  	window start in #-th dimension
.TP
.I int    
.B j#
.B =(1,...)
.R  	jump in #-th dimension
.TP
.I float  
.B max#
.B =(o1+(n1-1)*d1,o2+(n1-1)*d2,,...)
.R  	maximum in #-th dimension
.TP
.I float  
.B min#
.B =(o1,o2,,...)
.R  	minimum in #-th dimension
.TP
.I largeint
.B n#
.B =(0,...)
.R  	window size in #-th dimension
.TP
.I bool   
.B squeeze
.B =y
.R  [y/n]	if y, squeeze dimensions equal to 1 to the end
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	Verbosity flag
.SH USED IN
.TP
.I bei/dpmv/krchdmo
.TP
.I bei/dpmv/matt
.TP
.I bei/dwnc/sigmoid
.TP
.I bei/fdm/kjartjac
.TP
.I bei/fld/cube
.TP
.I bei/fld/shotmovie
.TP
.I bei/fld/synmarine
.TP
.I bei/fld/yc
.TP
.I bei/ft1/autocor
.TP
.I bei/ft1/brad
.TP
.I bei/ft1/ft2d
.TP
.I bei/krch/sep73
.TP
.I bei/sg/denmark
.TP
.I bei/sg/toldi
.TP
.I bei/trimo/mod
.TP
.I bei/trimo/subsamp
.TP
.I bei/vela/stretch
.TP
.I bei/vela/vscan
.TP
.I bei/wvs/head
.TP
.I bei/wvs/vscan
.TP
.I cup/rna2d/real
.TP
.I cup/rna2d/shot
.TP
.I cup/rna2d/simple
.TP
.I cup/rna3d/real
.TP
.I cup/rna3d/shot
.TP
39 more examples listed in:
.TP
/home/mlouboutin3/Research/madagascar//share/doc/madagascar/html/sfwindow.html
.SH SOURCE
.I system/main/window.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfwindow
.SH VERSION
4.2-git
