.TH sfwigner 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfwigner \- Assymptotic Wigner distribution in space-time 
.SH SYNOPSIS
.B sfwigner < Fu.rsf > Fw.rsf ompchunk=1 verb=n nh1=0 nh2=0 nh3=0 wk=0.0
.SH PARAMETERS
.PD 0
.TP
.I int    
.B nh1
.B =0
.R  
.TP
.I int    
.B nh2
.B =0
.R  
.TP
.I int    
.B nh3
.B =0
.R  
.TP
.I int    
.B ompchunk
.B =1
.R  	OpenMP data chunk size
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I float  
.B wk
.B =0.0
.R  
.SH USED IN
.TP
.I cwp/pept2011MicroearthquakeMonitoring/saf1
.TP
.I cwp/pept2011MicroearthquakeMonitoring/saf2
.TP
.I cwp/pept2011MicroearthquakeMonitoring/saf3
.SH SOURCE
.I user/psava/Mwigner.c
.SH VERSION
4.2-git
