.TH sfwilson 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfwilson \- Wilson-Burg spectral factorization. 
.SH SYNOPSIS
.B sfwilson < in.rsf > out.rsf lag=lag0.rsf lagout=lag.rsf maxlag= niter=20 eps=1.e-6 n1=maxlag a0=1. verb=y stable=n lagin= filtin=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B a0
.B =1.
.R  
.TP
.I float  
.B eps
.B =1.e-6
.R  	truncation tolerance
.TP
.I string 
.B filtin
.B =
.R  
.TP
.I string 
.B lag
.B =
.R  	optional input file with filter lags (auxiliary input file name)
.TP
.I string 
.B lagin
.B =
.R  	optional input file with output filter lags
.TP
.I string 
.B lagout
.B =
.R  	auxiliary output file name
.TP
.I int    
.B maxlag
.B =
.R  	maximum lag
.TP
.I int    
.B n1
.B =maxlag
.R  	output filter length
.TP
.I int    
.B niter
.B =20
.R  	number of iterations
.TP
.I bool   
.B stable
.B =n
.R  [y/n]	stability flag
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/gee/Mwilson.c
.SH VERSION
4.2-git
