.TH sfwkbjTI 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfwkbjTI \- VTI eikonal solver (3-D). 
.SH SYNOPSIS
.B sfwkbjTI < bv.rsf > time.rsf shotfile=shots.rsf br1=d1 br2=d2 br3=d3 plane1=n plane2=n plane3=n b1=plane[2]? n1: (int) (br1/d1+0.5) b2=plane[1]? n2: (int) (br2/d2+0.5) b3=plane[0]? n3: (int) (br3/d3+0.5) zshot=0. yshot=o2 + 0.5*(n2-1)*d2 xshot=o3 + 0.5*(n3-1)*d3 vv= eta=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B b1
.B =plane[2]? n1: (int) (br1/d1+0.5)
.R  
.TP
.I int    
.B b2
.B =plane[1]? n2: (int) (br2/d2+0.5)
.R  
.TP
.I int    
.B b3
.B =plane[0]? n3: (int) (br3/d3+0.5)
.R  	Constant-velocity box around the source (in samples)
.TP
.I float  
.B br1
.B =d1
.R  
.TP
.I float  
.B br2
.B =d2
.R  
.TP
.I float  
.B br3
.B =d3
.R  	Constant-velocity box around the source (in physical dimensions)
.TP
.I string 
.B eta
.B =
.R  
.TP
.I bool   
.B plane1
.B =n
.R  [y/n]
.TP
.I bool   
.B plane2
.B =n
.R  [y/n]
.TP
.I bool   
.B plane3
.B =n
.R  [y/n]	plane-wave source
.TP
.I string 
.B shotfile
.B =
.R  	File with shot locations (n2=number of shots, n1=3) (auxiliary input file name)
.TP
.I string 
.B vv
.B =
.R  
.TP
.I float  
.B xshot
.B =o3 + 0.5*(n3-1)*d3
.R  
.TP
.I float  
.B yshot
.B =o2 + 0.5*(n2-1)*d2
.R  
.TP
.I float  
.B zshot
.B =0.
.R  	Shot location (used if no shotfile)
.SH SOURCE
.I user/tariq/MwkbjTI.c
.SH VERSION
4.2-git MwkbjTI.c 4136 2009-02-07 17:20:32Z sfomel
