.TH sfwlslfdc1ww 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfwlslfdc1ww \- None
.SH SYNOPSIS
.B sfwlslfdc1ww < velf.rsf > outm.rsf sx=fsx.rsf Mexact=Mexactfile.rsf wfun=Mwfun.rsf Mapp=Mappfile.rsf wtfull=Mwtfull.rsf seed=time(NULL f0=15 a0=0.0001 taper=0.0 eps=1.e-4 npk=20 dt= wavnumcut=1.0 size=6
.SH PARAMETERS
.PD 0
.TP
.I file   
.B Mapp
.B =
.R  	auxiliary output file name
.TP
.I file   
.B Mexact
.B =
.R  	auxiliary output file name
.TP
.I        
.B a0
.B =0.0001
.R  	weight parameters
.TP
.I        
.B dt
.B =
.R  	time step
.TP
.I        
.B eps
.B =1.e-4
.R  	tolerance
.TP
.I        
.B f0
.B =15
.R  	dominant frequency
.TP
.I        
.B npk
.B =20
.R  	maximum rank
.TP
.I        
.B seed
.B =time(NULL
.R  
.TP
.I        
.B size
.B =6
.R  	stencil length
.TP
.I file   
.B sx
.B =
.R  	auxiliary output file name
.TP
.I        
.B taper
.B =0.0
.R  	taper for stability
.TP
.I        
.B wavnumcut
.B =1.0
.R  	wavenumber cut percentile
.TP
.I file   
.B wfun
.B =
.R  	auxiliary output file name
.TP
.I file   
.B wtfull
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/fangg/Mwlslfdc1ww.cc
.SH VERSION
4.2-git
