.TH sfwmf 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfwmf \- 1D weighted median filtering. 
.SH SYNOPSIS
.B sfwmf < in.rsf > out.rsf weights=weights.rsf verb=n nfw= boundary=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B boundary
.B =n
.R  [y/n]	if y, boundary is data, whereas zero
.TP
.I int    
.B nfw
.B =
.R  	filter-window length (positive and odd integer)
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.TP
.I string 
.B weights
.B =
.R  	auxiliary input file name
.SH SOURCE
.I user/yliu/Mwmf.c
.SH VERSION
4.2-git
