.TH sfwuab 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfwuab \- Wrapper for Utilities Acting on Binaries
.SH SYNOPSIS
.B sfwuab prog= inp= tpar= ipar= verb=n
.SH PARAMETERS
.PD 0
.TP
.I string 
.B inp
.B =
.R  	Input file
.TP
.I string 
.B ipar
.B =
.R  	Independent params, i.e. "perc=100 cmap=rgb"
.TP
.I string 
.B prog
.B =
.R  	Non-madagascar utility
.TP
.I string 
.B tpar
.B =
.R  	Translated params, i.e.: "ni1=n1 ni2=n2"
.TP
.I bool   
.B verb
.B =n
.R  [y/n]
.SH SOURCE
.I user/ivlad/Mwuab.py
.SH VERSION
4.2-git
