.TH sfxcor3d 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfxcor3d \- OpenMP time- or freq-domain reversed cross-correlation on the fourth axes, read entire cube into memory 
.SH SYNOPSIS
.B sfxcor3d < Fs.rsf uu=Fr.rsf > Fi.rsf verb=n rev=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B rev
.B =n
.R  [y/n]	reverse the fourth axis of uu
.TP
.I file   
.B uu
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/jsun/Mxcor3d.c
.SH VERSION
4.2-git
