.TH sfximage 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfximage \- Displays a 2-D RSF file with Seismic Unix's ximage
.SH SYNOPSIS
.B sfximage inp= par= verb=n
.SH COMMENTS
Test with:
sfspike n1=5 n2=3 nsp=3 k1=1,3,4 k2=1,2,3 > junk.rsf;
sfximage inp=junk.rsf par="perc=100 cmap=rgb1 legend=1";
You should see a picture with blue background and red blobs.
See also sfimage.
.SH PARAMETERS
.PD 0
.TP
.I string 
.B inp
.B =
.R  	Input file
.TP
.I string 
.B par
.B =
.R  	ximage params that can't be found in RSF headr
.TP
.I bool   
.B verb
.B =n
.R  [y/n]
.SH SOURCE
.I user/ivlad/Mximage.py
.SH VERSION
4.2-git
