.TH sfzero 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfzero \- Zero crossings with sub-pixel resolution. 
.SH SYNOPSIS
.B sfzero < inp.rsf > out.rsf nzero=nzero.rsf nw=4 down=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B down
.B =n
.R  [y/n]	only zeros on the way down
.TP
.I int    
.B nw
.B =4
.R  	Interpolation accuracy
.TP
.I file   
.B nzero
.B =
.R  	auxiliary output file name
.SH SOURCE
.I user/fomels/Mzero.c
.SH VERSION
4.2-git
