.TH sfzowei 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfzowei \- 3-D zero-offset modeling/migration 
.SH SYNOPSIS
.B sfzowei slo=Fslo.rsf < Fdat.rsf > Fcic.rsf sou=Fsou.rsf verb=n adj=y
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =y
.R  [y/n]	adjoint flag, true for migration, false for modeling
.TP
.I file   
.B slo
.B =
.R  	auxiliary input file name
.TP
.I file   
.B sou
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B verb
.B =n
.R  [y/n]	verbosity flag
.SH SOURCE
.I user/psava/Mzowei.c
.SH VERSION
4.2-git
