.TH sfzortholr3 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfzortholr3 \- Lowrank decomposition for 3-D orthorhombic wave propagation. 
.SH SYNOPSIS
.B sfzortholr3 < c11.rsf seta1=seta1.rsf fft=fft.rsf left=left.rsf > right.rsf seed=time(NULL eps=1.e-4 npk=20 dt= mode=0 tilt=false
.SH PARAMETERS
.PD 0
.TP
.I        
.B dt
.B =
.R  	time step
.TP
.I        
.B eps
.B =1.e-4
.R  	tolerance
.TP
.I file   
.B fft
.B =
.R  	auxiliary input file name
.TP
.I file   
.B left
.B =
.R  	auxiliary output file name
.TP
.I        
.B mode
.B =0
.R  	'0' means quasi-P (default),'1' means quasi-S, '2' means quasi-S2
.TP
.I        
.B npk
.B =20
.R  	maximum rank
.TP
.I        
.B seed
.B =time(NULL
.R  
.TP
.I file   
.B seta1
.B =
.R  	auxiliary input file name
.TP
.I        
.B tilt
.B =false
.R  
.SH SOURCE
.I user/jsun/Mzortholr3.cc
.SH VERSION
4.2-git
