.TH sfzolsrtm2 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfzolsrtm2 \- 2-D FFT-based zero-offset exploding reflector modeling/migration linear operator 
.SH SYNOPSIS
.B sfzolsrtm2 < data.rsf > image.rsf snaps=snaps.rsf left=left.rsf right=right.rsf adj=n timer=n verb=n snap=0 pad1=1 gpz=0 taper=0 thresh=0.92 oz=0. nz= dz= nt= dt=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	if n, modeling; if y, migration
.TP
.I float  
.B dt
.B =
.R  	time sampling
.TP
.I float  
.B dz
.B =
.R  	depth sampling
.TP
.I int    
.B gpz
.B =0
.R  	geophone surface
.TP
.I file   
.B left
.B =
.R  	auxiliary input file name
.TP
.I int    
.B nt
.B =
.R  	time samples
.TP
.I int    
.B nz
.B =
.R  	depth samples
.TP
.I float  
.B oz
.B =0.
.R  
.TP
.I int    
.B pad1
.B =1
.R  	padding factor on the first axis
.TP
.I file   
.B right
.B =
.R  	auxiliary input file name
.TP
.I int    
.B snap
.B =0
.R  	interval for snapshots
.TP
.I file   
.B snaps
.B =
.R  	auxiliary output file name
.TP
.I int    
.B taper
.B =0
.R  	tapering in the frequency domain
.TP
.I float  
.B thresh
.B =0.92
.R  	tapering threshold
.TP
.I bool   
.B timer
.B =n
.R  [y/n]
.TP
.I bool   
.B verb
.B =n
.R  [y/n]
.SH SOURCE
.I user/jsun/Mzolsrtm2.c
.SH VERSION
4.2-git
