.TH sfztrace 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
sfztrace \- Multiple arrivals by depth marching. 
.SH SYNOPSIS
.B sfztrace < in.rsf nt=nx*nz na=362 da=0.5 a0=-90. vel=y order=3 iorder=4
.SH PARAMETERS
.PD 0
.TP
.I float  
.B a0
.B =-90.
.R  	starting angle (in degrees)
.TP
.I float  
.B da
.B =0.5
.R  	angle increment (in degrees)
.TP
.I int    
.B iorder
.B =4
.R  	interpolation accuracy for grid
.TP
.I int    
.B na
.B =362
.R  	number of angles
.TP
.I int    
.B nt
.B =nx*nz
.R  	ray length bound
.TP
.I int    
.B order
.B =3
.R  	interpolation accuracy for velocity
.TP
.I bool   
.B vel
.B =y
.R  [y/n]	y, input is velocity; n, slowness
.SH SOURCE
.I user/fomels/Mztrace.c
.SH VERSION
4.2-git
