.TH vpvr 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
vpvr \- Plot impulse responses in 2 dimensions 
.SH SYNOPSIS
.B vpvr > plot.vpl color=7 fat=5 dash=0.0 edash=0.1 vrscale=1. groupscale=1. phasescale=.5 norm=0. inc=0.5 line=n info=y disp=y group=y particle=n ellipse=y c11=0. c13=0. c33=0. c55=0. c66=0. log= only= title=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B c11
.B =0.
.R  
.TP
.I float  
.B c13
.B =0.
.R  
.TP
.I float  
.B c33
.B =0.
.R  
.TP
.I float  
.B c55
.B =0.
.R  
.TP
.I float  
.B c66
.B =0.
.R  
.TP
.I int    
.B color
.B =7
.R  
.TP
.I float  
.B dash
.B =0.0
.R  
.TP
.I bool   
.B disp
.B =y
.R  [y/n]	if n, give phase velocity instead of dispersion relation
.TP
.I float  
.B edash
.B =0.1
.R  	elliptical approximation dash
.TP
.I bool   
.B ellipse
.B =y
.R  [y/n]	if use elliptic approximation
.TP
.I int    
.B fat
.B =5
.R  
.TP
.I bool   
.B group
.B =y
.R  [y/n]	if n, give group slowness instead of group velocity
.TP
.I float  
.B groupscale
.B =1.
.R  	scales only the group stuff
.TP
.I float  
.B inc
.B =0.5
.R  	increment of phi sub w in degrees
.TP
.I bool   
.B info
.B =y
.R  [y/n]	if print in small letters the elastic constants across the top
.TP
.I bool   
.B line
.B =n
.R  [y/n]	if draw lines to indicate some important angles. (Angles at
     which triplication "first" occurs, and angles at which pure P
     and Sv modes exist)
.TP
.I string 
.B log
.B =
.R  
.TP
.I float  
.B norm
.B =0.
.R  
.TP
.I string 
.B only
.B =
.R  	(Pdisp, SVdisp, SHdisp, P, SV, SH)
.TP
.I bool   
.B particle
.B =n
.R  [y/n]	if show particle motion directions
.TP
.I float  
.B phasescale
.B =.5
.R  	scales only the phase stuff
.TP
.I string 
.B title
.B =
.R  
.TP
.I float  
.B vrscale
.B =1.
.R  	scales everything by a factor
.SH SOURCE
.I user/dellinger/Mvr.c
.SH VERSION
4.2-git
