.TH vpvrtest 1  "APRIL 2023" Madagascar "Madagascar Manuals"
.SH NAME
vpvrtest \- Plot impulse responses in 2 dimensions 
.SH SYNOPSIS
.B vpvrtest > plot.vpl dash=0.0 francis=n invert=n groupscale=1. phasescale=1. norm=1. inc=0.5 c11=1. c13=.5 c33=1. c55=.25 m=-1 which=n flip=n
.SH PARAMETERS
.PD 0
.TP
.I float  
.B c11
.B =1.
.R  
.TP
.I float  
.B c13
.B =.5
.R  
.TP
.I float  
.B c33
.B =1.
.R  
.TP
.I float  
.B c55
.B =.25
.R  
.TP
.I float  
.B dash
.B =0.0
.R  
.TP
.I bool   
.B flip
.B =n
.R  [y/n]	reciprocal of W's used in Francis' approximation
.TP
.I bool   
.B francis
.B =n
.R  [y/n]
.TP
.I float  
.B groupscale
.B =1.
.R  	scales only the group stuff
.TP
.I float  
.B inc
.B =0.5
.R  	increment of phi sub w in degrees
.TP
.I bool   
.B invert
.B =n
.R  [y/n]	reciprocal of plotting radius
.TP
.I int    
.B m
.B =-1
.R  
.TP
.I float  
.B norm
.B =1.
.R  
.TP
.I float  
.B phasescale
.B =1.
.R  	scales only the phase stuff
.TP
.I bool   
.B which
.B =n
.R  [y/n]	transform from phase to group domain or vice versa
.SH SOURCE
.I user/dellinger/Mvrtest.c
.SH VERSION
4.2-git
