name: CI-Madagascar

on:
  # Trigger the workflow on push to master or pull request
  # to be merged in master
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - version: '1.8'
            os: ubuntu-latest
            arch: x64
          - version: '1.8'
            os: macos-latest
            arch: arm64

    steps:
      - name: Checkout Madagascar
        uses: actions/checkout@v3

      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Build Madagascar
        run: |
          mkdir -p mad_src
          cd mad_src
          mad_url="https://github.com/ahay/src.git"
          # branch_name=$(git ls-remote $mad_url | grep -E "madagascar-[0-9]+\.[0-9]+" | tail -n 1 | awk '{print $2}')
          # branch_name=$(echo $branch_name | sed 's|refs/heads/||')
          branch_name="master"
          git clone --single-branch --branch $branch_name $mad_url
          cd src
          ./configure --prefix=$HOME/madagascar 
          make -j$(nproc)
          make install
          source $HOME/madagascar/share/madagascar/etc/env.sh

      - name: Check RSFROOT
        run: | 
          echo "RSFROOT=$RSFROOT"
          source $HOME/madagascar/share/madagascar/etc/env.sh
          echo "RSFROOT=$RSFROOT"

      - name: Run tests
        uses: julia-actions/julia-runtest@latest
