name: CI-Madagascar

on:
  # Trigger the workflow on push to master or pull request
  # to be merged in master
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - version: '1.8'
            os: ubuntu-latest
            arch: x64
          - version: '1.8'
            os: macos-latest
            arch: arm64

    steps:
      - name: Checkout Madagascar
        uses: actions/checkout@v3

      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Build Madagascar
        run: ./.github/workflows/helpers/ci/build_madagascar.sh

      - name: Run tests
        run: ./.github/workflows/helpers/ci/run_tests.sh

      - name: Generate docs
        if: matrix.os == 'ubuntu-latest'
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.github/workflows/helpers/ci/generate_docs.sh
